// WP-8.3 volumetric clouds on Vulkan: see include/fuse/renderer/clouds/volumetric_clouds.hpp.
#include <fuse/renderer/clouds/volumetric_clouds.hpp>

#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/device.hpp>

#include <algorithm>
#include <cstring>
#include <initializer_list>

#if defined(FUSE_VULKAN_BACKEND)
#include <vulkan/vulkan.h>

// Generated by cmake/rp_wp83.cmake from shaders/clouds/*: kCl<Kernel><Slang|Glsl>Spv and
// FUSE_CLOUDS_GPU_{SLANG,GLSL} when every kernel of a language exists.
#include "clouds_gpu_spv.h"
#endif

namespace fuse::renderer::clouds {

namespace {
constexpr u32 kPushBytes = sizeof(CloudPush);
constexpr u32 kFrameStride = 512u; ///< ring slot size (>= sizeof(CloudParams), 256-aligned)
static_assert(sizeof(CloudParams) <= kFrameStride, "frame ring slot");
constexpr u64 kTexel = sizeof(ClTexel);

BufferUsage bufferUsage(std::initializer_list<BufferUsage> bits) {
    u32 u = 0;
    for (const BufferUsage b : bits) {
        u |= static_cast<u32>(b);
    }
    return static_cast<BufferUsage>(u);
}

u64 align256(u64 v) { return (v + 255u) & ~u64{255u}; }

u32 groups(u32 items, u32 size) { return items == 0u ? 1u : (items + size - 1u) / size; }

bool sameLayout(const CloudBufferLayout& a, const CloudBufferLayout& b, u32 first, u32 last) {
    for (u32 i = first; i <= last; ++i) {
        if (a.offset[i] != b.offset[i] || a.bytes[i] != b.bytes[i]) {
            return false;
        }
    }
    return true;
}

#if defined(FUSE_VULKAN_BACKEND)
struct Code {
    const u32* words = nullptr;
    usize bytes = 0;
};
template <usize N>
Code code(const u32 (&spv)[N]) {
    return Code{spv, sizeof(spv)};
}
#endif
} // namespace

CloudBufferLayout CloudBufferLayout::compute(const CloudParams& p) {
    CloudBufferLayout l{};
    const u64 texels[kCloudSectionCount] = {
        static_cast<u64>(p.shapeSize) * p.shapeSize * p.shapeSize,
        static_cast<u64>(p.detailSize) * p.detailSize * p.detailSize,
        static_cast<u64>(p.weatherSize) * p.weatherSize,
        static_cast<u64>(p.freshWidth) * p.freshHeight * 2u,
        static_cast<u64>(p.width) * p.height * 2u,
        static_cast<u64>(p.width) * p.height * 2u,
        static_cast<u64>(p.outWidth) * p.outHeight,
    };
    u64 cursor = 0;
    for (u32 i = 0; i < kCloudSectionCount; ++i) {
        if (i == static_cast<u32>(CloudSection::Fresh)) {
            l.noiseBytes = cursor;
            cursor = 0;
        }
        l.offset[i] = cursor;
        l.bytes[i] = texels[i] * kTexel;
        cursor = align256(cursor + std::max<u64>(l.bytes[i], 16u));
    }
    l.frameBytes = cursor;
    return l;
}

CloudCapabilities queryCloudCapabilities(const VulkanDevice* device) {
    CloudCapabilities c{};
#if defined(FUSE_VULKAN_BACKEND)
    if (device == nullptr || !device->isValid()) {
        return c;
    }
    const RendererCaps& caps = device->info().caps;
    if (!caps.bufferDeviceAddress || !caps.shaderInt64) {
        c.reason = "bufferDeviceAddress / shaderInt64 missing";
        return c;
    }
    c.clouds = true;
    c.reason = "ok";
#else
    (void)device;
    c.reason = "stub backend";
#endif
    return c;
}

VolumetricClouds::~VolumetricClouds() { destroy(); }

bool VolumetricClouds::init(const CloudGpuDesc& desc) {
    destroy();
    m_desc = desc;
#if defined(FUSE_VULKAN_BACKEND)
    if (desc.allocator == nullptr || desc.bindless == nullptr || desc.framesInFlight == 0u) {
        return false;
    }
    if (!queryCloudCapabilities(desc.device).clouds) {
        return false;
    }
    m_retired.reserve(8);
    m_initialized = true; // destroy() releases partial state from here on
    BufferDesc ring{};
    ring.size = static_cast<usize>(desc.framesInFlight) * kFrameStride;
    ring.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress});
    ring.memoryUsage = MemoryUsage::CpuToGpu;
    ring.name = "clouds.params";
    if (!m_desc.allocator->createBuffer(ring, m_frameRing) || m_frameRing.mapped == nullptr ||
        m_frameRing.deviceAddress == 0u || !createPipelines()) {
        destroy();
        return false;
    }
    return true;
#else
    return false;
#endif
}

void VolumetricClouds::destroy() {
    if (!m_initialized) {
        return;
    }
#if defined(FUSE_VULKAN_BACKEND)
    collectRetired(~0ull);
    for (Buffer* b : {&m_noise, &m_frame, &m_frameRing}) {
        if (b->handle != nullptr) {
            m_desc.allocator->destroyBuffer(*b);
        }
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    for (void*& pipeline : m_pipelines) {
        if (pipeline != nullptr) {
            vkDestroyPipeline(device, static_cast<VkPipeline>(pipeline), nullptr);
            pipeline = nullptr;
        }
    }
    if (m_layoutHandle != nullptr) {
        vkDestroyPipelineLayout(device, static_cast<VkPipelineLayout>(m_layoutHandle), nullptr);
    }
#endif
    m_layoutHandle = nullptr;
    m_noise = Buffer{};
    m_frame = Buffer{};
    m_frameRing = Buffer{};
    m_noiseQueue = rg::kNoQueue;
    m_frameQueue = rg::kNoQueue;
    m_frameAddress = 0;
    m_retired.clear();
    m_layout = CloudBufferLayout{};
    m_params = CloudParams{};
    m_noiseParams = CloudParams{};
    m_noiseDirty = true;
    m_history = CloudHistoryState{};
    m_nextHistory = CloudHistoryState{};
    m_historyOut = CloudSection::History0;
    m_recordCount = 0;
    m_language = "none";
    m_stats = CloudStats{};
    m_initialized = false;
}

bool VolumetricClouds::createPipelines() {
#if defined(FUSE_VULKAN_BACKEND)
    Code k[kKernelCount]{};
    bool found = false;
#if defined(FUSE_CLOUDS_GPU_SLANG)
    if (m_desc.language == CloudKernelLanguage::Auto || m_desc.language == CloudKernelLanguage::Slang) {
        k[kShape] = code(kClNoiseShapeSlangSpv);
        k[kDetail] = code(kClNoiseDetailSlangSpv);
        k[kWeather] = code(kClWeatherSlangSpv);
        k[kMarch] = code(kClMarchSlangSpv);
        k[kReconstruct] = code(kClReconstructSlangSpv);
        k[kComposite] = code(kClCompositeSlangSpv);
        k[kProbe] = code(kClProbeSlangSpv);
        m_language = "slang";
        found = true;
    }
#endif
#if defined(FUSE_CLOUDS_GPU_GLSL)
    if (!found && (m_desc.language == CloudKernelLanguage::Auto || m_desc.language == CloudKernelLanguage::Glsl)) {
        k[kShape] = code(kClNoiseShapeGlslSpv);
        k[kDetail] = code(kClNoiseDetailGlslSpv);
        k[kWeather] = code(kClWeatherGlslSpv);
        k[kMarch] = code(kClMarchGlslSpv);
        k[kReconstruct] = code(kClReconstructGlslSpv);
        k[kComposite] = code(kClCompositeGlslSpv);
        k[kProbe] = code(kClProbeGlslSpv);
        m_language = "glsl";
        found = true;
    }
#endif
    if (!found) {
        return false;
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    VkDescriptorSetLayout setLayout = static_cast<VkDescriptorSetLayout>(m_desc.bindless->layoutHandle());
    VkPushConstantRange range{VK_SHADER_STAGE_COMPUTE_BIT, 0, kPushBytes};
    VkPipelineLayoutCreateInfo layoutInfo{};
    layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutInfo.setLayoutCount = setLayout != VK_NULL_HANDLE ? 1u : 0u;
    layoutInfo.pSetLayouts = &setLayout;
    layoutInfo.pushConstantRangeCount = 1;
    layoutInfo.pPushConstantRanges = &range;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    if (vkCreatePipelineLayout(device, &layoutInfo, nullptr, &layout) != VK_SUCCESS) {
        return false;
    }
    m_layoutHandle = layout;
    const VkPipelineCreateFlags createFlags = static_cast<VkPipelineCreateFlags>(m_desc.bindless->pipelineCreateFlags());
    for (u32 i = 0; i < kKernelCount; ++i) {
        VkShaderModuleCreateInfo moduleInfo{};
        moduleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        moduleInfo.codeSize = k[i].bytes;
        moduleInfo.pCode = k[i].words;
        VkShaderModule module = VK_NULL_HANDLE;
        if (vkCreateShaderModule(device, &moduleInfo, nullptr, &module) != VK_SUCCESS) {
            return false;
        }
        VkComputePipelineCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
        info.flags = createFlags;
        info.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        info.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
        info.stage.module = module;
        info.stage.pName = "main";
        info.layout = layout;
        VkPipeline pipeline = VK_NULL_HANDLE;
        const VkResult result = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
        vkDestroyShaderModule(device, module, nullptr);
        m_pipelines[i] = pipeline;
        if (result != VK_SUCCESS) {
            return false;
        }
    }
    return true;
#else
    return false;
#endif
}

void VolumetricClouds::retire(Buffer& buffer) {
    if (buffer.handle != nullptr) {
        Retired old{};
        old.buffer = buffer;
        old.serial = m_frameSerial;
        m_retired.push_back(old);
        ++m_stats.retired;
    }
    buffer = Buffer{};
}

bool VolumetricClouds::createBuffer(u64 bytes, const char* name, Buffer& target, u8& queue) {
    BufferDesc d{};
    d.size = static_cast<usize>(bytes);
    d.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress, BufferUsage::TransferSrc});
    d.memoryUsage = MemoryUsage::GpuOnly;
    d.name = name;
    Buffer fresh{};
    if (!m_desc.allocator->createBuffer(d, fresh) || fresh.deviceAddress == 0u) {
        if (fresh.handle != nullptr) {
            m_desc.allocator->destroyBuffer(fresh);
        }
        return false;
    }
    retire(target);
    target = fresh;
    queue = rg::kNoQueue;
    return true;
}

u32 VolumetricClouds::collectRetired(u64 completedSerial) {
    u32 collected = 0;
    usize keep = 0;
    for (usize i = 0; i < m_retired.size(); ++i) {
        if (m_retired[i].serial > completedSerial) {
            m_retired[keep++] = m_retired[i];
            continue;
        }
        if (m_retired[i].buffer.handle != nullptr) {
            m_desc.allocator->destroyBuffer(m_retired[i].buffer);
        }
        ++collected;
    }
    m_retired.resize(keep);
    m_stats.retired = m_stats.retired >= collected ? m_stats.retired - collected : 0u;
    return collected;
}

bool VolumetricClouds::beginFrame(u64 frameSerial, const CloudSettings& settings, const CloudFrame& frame) {
    if (!m_initialized) {
        return false;
    }
    CloudParams p{};
    if (!resolve_cloud_params(settings, frame, m_history, p)) {
        return false;
    }
    m_frameSerial = frameSerial;
    m_recordCount = 0;
    m_stats.passes = 0;
    m_stats.noiseRan = false;
    m_stats.marchedPixels = 0;
    const CloudBufferLayout layout = CloudBufferLayout::compute(p);
    const u32 fresh = static_cast<u32>(CloudSection::Fresh);
    if (m_noise.handle == nullptr || layout.noiseBytes != m_layout.noiseBytes || !sameLayout(layout, m_layout, 0u, fresh - 1u)) {
        if (!createBuffer(layout.noiseBytes, "clouds.noise", m_noise, m_noiseQueue)) {
            return false;
        }
        m_noiseDirty = true;
        ++m_stats.noiseRebuilds;
    }
    const bool resized = p.width != m_params.width || p.height != m_params.height || p.block != m_params.block ||
                         p.outWidth != m_params.outWidth || p.outHeight != m_params.outHeight;
    if (m_frame.handle == nullptr || layout.frameBytes != m_layout.frameBytes ||
        !sameLayout(layout, m_layout, fresh, kCloudSectionCount - 1u)) {
        if (!createBuffer(layout.frameBytes, "clouds.frame", m_frame, m_frameQueue)) {
            return false;
        }
        ++m_stats.frameRebuilds;
    }
    if (resized) { // new extent: the history is meaningless
        p.flags &= ~static_cast<u32>(kClFlagHistory);
    }
    m_layout = layout;
    if (!cloud_noise_equal(p, m_noiseParams)) {
        m_noiseDirty = true;
    }
    const u64 n = m_noise.deviceAddress;
    const u64 f = m_frame.deviceAddress;
    p.shapeNoise = n + layout.offset[static_cast<u32>(CloudSection::Shape)];
    p.detailNoise = n + layout.offset[static_cast<u32>(CloudSection::Detail)];
    p.weather = n + layout.offset[static_cast<u32>(CloudSection::Weather)];
    p.fresh = f + layout.offset[fresh];
    m_historyOut = (m_history.frameIndex & 1u) == 0u ? CloudSection::History0 : CloudSection::History1;
    const CloudSection historyIn = m_historyOut == CloudSection::History0 ? CloudSection::History1 : CloudSection::History0;
    p.historyOut = f + layout.offset[static_cast<u32>(m_historyOut)];
    p.historyIn = f + layout.offset[static_cast<u32>(historyIn)];
    p.result = f + layout.offset[static_cast<u32>(CloudSection::Result)];
    m_params = p;
    const u32 slot = static_cast<u32>(frameSerial % m_desc.framesInFlight);
    const u64 offset = static_cast<u64>(slot) * kFrameStride;
    std::memcpy(static_cast<u8*>(m_frameRing.mapped) + offset, &p, sizeof(p));
    m_frameAddress = m_frameRing.deviceAddress + offset;
    m_nextHistory.previousCamera = frame.camera;
    m_nextHistory.previousWind = frame.windOffset;
    m_nextHistory.frameIndex = m_history.frameIndex + 1u;
    m_nextHistory.historyValid = true;
    return true;
}

CloudGraphRefs VolumetricClouds::importInto(rg::Graph& graph) {
    CloudGraphRefs refs{};
    if (!m_initialized || m_noise.handle == nullptr || m_frame.handle == nullptr) {
        return refs;
    }
    refs.noise = graph.importBuffer(rg::ImportedBuffer{m_noise.handle, m_noise.desc.size, m_noiseQueue, &m_noiseQueue,
                                                       "clouds.noise"});
    refs.frame = graph.importBuffer(rg::ImportedBuffer{m_frame.handle, m_frame.desc.size, m_frameQueue, &m_frameQueue,
                                                       "clouds.frame"});
    return refs;
}

VolumetricClouds::PassRecord* VolumetricClouds::nextRecord(u32 kernel) {
    if (m_recordCount >= kMaxPasses) {
        return nullptr;
    }
    PassRecord* r = &m_records[m_recordCount++];
    *r = PassRecord{};
    r->self = this;
    r->kernel = kernel;
    r->push.params = m_frameAddress;
    return r;
}

rg::BufferRange VolumetricClouds::range(CloudSection which) const {
    const u32 i = static_cast<u32>(which);
    return rg::BufferRange{m_layout.offset[i], std::max<u64>(m_layout.bytes[i], 16u)};
}

void VolumetricClouds::addPasses(rg::Graph& graph, const CloudGraphRefs& refs, const CloudInputs& inputs) {
    if (!m_initialized || !refs.noise.valid() || !refs.frame.valid()) {
        return;
    }
    const CloudParams& p = m_params;
    const u8 cs = rg::kStageCompute;
    const bool atm = (p.flags & kClFlagAtmosphere) != 0u && inputs.atmosphereLuts.valid();
    if (m_noiseDirty) {
        PassRecord* s = nextRecord(kShape);
        PassRecord* d = nextRecord(kDetail);
        PassRecord* w = nextRecord(kWeather);
        if (s != nullptr && d != nullptr && w != nullptr) {
            s->groups[0] = s->groups[1] = s->groups[2] = groups(p.shapeSize, kClTile3);
            graph.addPass("clouds.noise.shape", &VolumetricClouds::recordDispatch, s)
                .use(refs.noise, rg::Access::StorageWrite, range(CloudSection::Shape), cs);
            d->groups[0] = d->groups[1] = d->groups[2] = groups(p.detailSize, kClTile3);
            graph.addPass("clouds.noise.detail", &VolumetricClouds::recordDispatch, d)
                .use(refs.noise, rg::Access::StorageWrite, range(CloudSection::Detail), cs);
            w->groups[0] = w->groups[1] = groups(p.weatherSize, kClTile);
            graph.addPass("clouds.weather", &VolumetricClouds::recordDispatch, w)
                .use(refs.noise, rg::Access::StorageWrite, range(CloudSection::Weather), cs);
            m_stats.passes += 3u;
            m_stats.noiseRan = true;
            ++m_stats.noiseBakes;
            m_noiseDirty = false;
            m_noiseParams = p;
        }
    }
    const CloudSection historyIn = m_historyOut == CloudSection::History0 ? CloudSection::History1 : CloudSection::History0;
    if (PassRecord* m = nextRecord(kMarch)) {
        m->groups[0] = groups(p.freshWidth, kClTile);
        m->groups[1] = groups(p.freshHeight, kClTile);
        rg::PassBuilder b = graph.addPass("clouds.march", &VolumetricClouds::recordDispatch, m);
        b.use(refs.noise, rg::Access::StorageRead, {}, cs).use(refs.frame, rg::Access::StorageWrite, range(CloudSection::Fresh), cs);
        if (atm) {
            b.use(inputs.atmosphereLuts, rg::Access::StorageRead, {}, cs);
        }
        ++m_stats.passes;
        m_stats.marchedPixels = p.freshWidth * p.freshHeight;
    }
    if (PassRecord* r = nextRecord(kReconstruct)) {
        r->groups[0] = groups(p.width, kClTile);
        r->groups[1] = groups(p.height, kClTile);
        graph.addPass("clouds.reconstruct", &VolumetricClouds::recordDispatch, r)
            .use(refs.frame, rg::Access::StorageRead, range(CloudSection::Fresh), cs)
            .use(refs.frame, rg::Access::StorageRead, range(historyIn), cs)
            .use(refs.frame, rg::Access::StorageWrite, range(m_historyOut), cs);
        ++m_stats.passes;
    }
    if (PassRecord* c = nextRecord(kComposite)) {
        c->groups[0] = groups(p.outWidth, kClTile);
        c->groups[1] = groups(p.outHeight, kClTile);
        rg::PassBuilder b = graph.addPass("clouds.composite", &VolumetricClouds::recordDispatch, c);
        b.use(refs.frame, rg::Access::StorageRead, range(m_historyOut), cs)
            .use(refs.frame, rg::Access::StorageWrite, range(CloudSection::Result), cs);
        if (atm) {
            b.use(inputs.atmosphereLuts, rg::Access::StorageRead, {}, cs);
        }
        if ((p.flags & kClFlagBackground) != 0u && inputs.background.valid()) {
            b.use(inputs.background, rg::Access::StorageRead, {}, cs);
        }
        if ((p.flags & kClFlagSceneDepth) != 0u && inputs.depth.valid()) {
            b.use(inputs.depth, rg::Access::StorageRead, {}, cs);
        }
        ++m_stats.passes;
    }
    m_history = m_nextHistory;
}

void VolumetricClouds::addCopy(rg::Graph& graph, const CloudGraphRefs& refs, CloudSection which, rg::BufferRef dst,
                               u64 dstOffset) {
    if (!m_initialized || !dst.valid() || !refs.noise.valid() || !refs.frame.valid()) {
        return;
    }
    PassRecord* r = nextRecord(kKernelCount);
    if (r == nullptr) {
        return;
    }
    const u32 i = static_cast<u32>(which);
    const rg::BufferRef from = i < static_cast<u32>(CloudSection::Fresh) ? refs.noise : refs.frame;
    r->copySrc = m_layout.offset[i];
    r->copyBytes = m_layout.bytes[i];
    r->copyDst = dstOffset;
    r->copyFrom = from;
    r->copyTo = dst;
    ++m_stats.passes;
    graph.addPass("clouds.copy", &VolumetricClouds::recordCopy, r)
        .use(from, rg::Access::TransferSrc, rg::BufferRange{r->copySrc, r->copyBytes})
        .use(dst, rg::Access::TransferDst, rg::BufferRange{dstOffset, r->copyBytes});
}

void VolumetricClouds::addProbe(rg::Graph& graph, const CloudGraphRefs& refs, const CloudInputs& inputs,
                                rg::BufferRef srcBuffer, u64 srcAddress, rg::BufferRef dstBuffer, u64 dstAddress,
                                u32 count) {
    if (!m_initialized || !refs.noise.valid() || !srcBuffer.valid() || !dstBuffer.valid() || count == 0u) {
        return;
    }
    PassRecord* r = nextRecord(kProbe);
    if (r == nullptr) {
        return;
    }
    r->push.src = srcAddress;
    r->push.dst = dstAddress;
    r->push.mode = count;
    r->groups[0] = groups(count, 64u);
    ++m_stats.passes;
    const u8 cs = rg::kStageCompute;
    rg::PassBuilder b = graph.addPass("clouds.probe", &VolumetricClouds::recordDispatch, r);
    b.use(refs.noise, rg::Access::StorageRead, {}, cs)
        .use(srcBuffer, rg::Access::StorageRead, rg::BufferRange{0, static_cast<u64>(count) * kClProbeInputs * kTexel}, cs)
        .use(dstBuffer, rg::Access::StorageWrite, rg::BufferRange{0, static_cast<u64>(count) * kClProbeOutputs * kTexel},
             cs);
    if ((m_params.flags & kClFlagAtmosphere) != 0u && inputs.atmosphereLuts.valid()) {
        b.use(inputs.atmosphereLuts, rg::Access::StorageRead, {}, cs);
    }
}

void VolumetricClouds::recordDispatch(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const VolumetricClouds& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, static_cast<VkPipeline>(self.m_pipelines[r.kernel]));
    self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, self.m_layoutHandle, 0);
    vkCmdPushConstants(cmd, static_cast<VkPipelineLayout>(self.m_layoutHandle), VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       kPushBytes, &r.push);
    vkCmdDispatch(cmd, r.groups[0], r.groups[1], r.groups[2]);
#else
    (void)context;
    (void)user;
#endif
}

void VolumetricClouds::recordCopy(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    const VkBufferCopy region{r.copySrc, r.copyDst, r.copyBytes};
    vkCmdCopyBuffer(cmd, static_cast<VkBuffer>(context.buffer(r.copyFrom)),
                    static_cast<VkBuffer>(context.buffer(r.copyTo)), 1, &region);
#else
    (void)context;
    (void)user;
#endif
}

} // namespace fuse::renderer::clouds
