#!/usr/bin/env python3
"""FUSE Relight RL-3.4: fixture mods applied to an RL-0.4 app change the captured scene as expected.

One case = Tests/relight/fixtures/replace/golden/<case>.json:
  {"app": "ff_textured",
   "mods": [{"fixture": "textured_a", "root": "remix"}, {"fixture": "textured_b", "root": "fuse", "name": "..."}],
   "env": {"FUSE_RELIGHT_MOD_ORDER": "..."},                              (optional)
   "hot_reload": {"frame": 10, "fixture": "multi_v2", "name": "multi"},    (optional)
   "expected": "<other case>"}                                             (optional: share an expected summary)

1. Stages the fixture mods (Tests/relight/fixtures/replace/mods/<fixture>, textures generated by
   fuse_relight_replace_tests --stage) into the run directory's search roots: rtx-remix/mods/<name> (Remix) and
   fuse-relight/mods/<name> (FUSE-native), the defaults of relight.replace.modPaths.
2. Runs the app through the Relight d3d9.dll / d3d8.dll under Wine + Xvfb (tests/tap/rl_tap_run.py's runner) with
   relight.tap.mode = capture: the replacement engine (replace/replace_live.hpp) writes the replaced scene into the
   capture record ("replacement" on each committed draw, one "replace_frame" line per frame).
   Hot reload cases set relight.replace.debugReloadWaitFrame: at that frame the engine writes the marker file
   relight_replace_wait and waits for a file notification; the driver then writes the new version of the mod
   (atomically renamed over mod.usda). The reload must be applied at most one frame after its notification, and
   the frames before / after must show the old / new content.
3. Summarises the record (mods and their stack order and option layers; runs of identical per-frame stats; every
   reload; the last frame's lights, deleted lights, residency and per-draw replacements) and compares it with
   <case>.expected.json (--update writes it).

  rl_replace_golden.py --case CASE.json --fixtures DIR --exe app.exe --d3d9 d3d9.dll --d3d8 d3d8.dll
      --runner run.sh --prefix-root DIR --stager fuse_relight_replace_tests.exe [--emulator 'runner|prefix']
      --out DIR [--keep] [--update]
The run directory is removed on a pass unless --keep. Exit codes: 0 pass, 1 fail, 77 skip (no Wine / Xvfb).
"""
import argparse
import json
import os
import shutil
import subprocess
import sys
import threading
import time

sys.dont_write_bytecode = True
SKIP = 77
ROOTS = {"remix": os.path.join("rtx-remix", "mods"), "fuse": os.path.join("fuse-relight", "mods")}


def emulator(args):
    return [p for p in args.emulator.split("|") if p] if args.emulator else []


def stage(args, fixture, dest):
    src = os.path.join(args.fixtures, "mods", fixture)
    if not os.path.isdir(src):
        raise RuntimeError("no fixture mod %s" % src)
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    proc = subprocess.run(emulator(args) + [args.stager, "--stage", src, dest], stdout=subprocess.PIPE,
                          stderr=subprocess.STDOUT)
    if proc.returncode != 0 or not os.path.isdir(dest):
        raise RuntimeError("staging %s failed (%d): %s" % (fixture, proc.returncode, proc.stdout.decode(errors="replace")[-2000:]))


def link_or_copy(src, dst):
    try:
        os.link(src, dst)
    except OSError:
        shutil.copy2(src, dst)


def run_app(args, case, run_dir):
    if os.path.isdir(run_dir):
        shutil.rmtree(run_dir)
    os.makedirs(run_dir)
    for src in (args.exe, args.d3d9, args.d3d8):
        link_or_copy(src, os.path.join(run_dir, os.path.basename(src)))
    for m in case["mods"]:
        stage(args, m["fixture"], os.path.join(run_dir, ROOTS[m.get("root", "remix")], m.get("name", m["fixture"])))
    hot = case.get("hot_reload")
    hot_src = None
    if hot:
        hot_src = os.path.join(run_dir, "hot_reload_stage")
        stage(args, hot["fixture"], hot_src)
    env = dict(os.environ)
    env.setdefault("DXVK_LOG_LEVEL", "warn")
    env["DXVK_LOG_PATH"] = "none"
    env.update({"FUSE_RELIGHT": "1", "FUSE_RELIGHT_TAP_MODE": "capture",
                "FUSE_RELIGHT_TAP_CAPTURE_PATH": "relight_capture.jsonl"})
    env.update(case.get("env", {}))
    marker = os.path.join(run_dir, "relight_replace_wait")
    if hot:
        env["FUSE_RELIGHT_REPLACE_DEBUG_RELOAD_WAIT_FRAME"] = str(hot["frame"])
        env["FUSE_RELIGHT_REPLACE_DEBUG_RELOAD_MARKER"] = "relight_replace_wait"
    cmd = ["bash", args.runner, "--native-d3d", args.prefix_root, os.path.join(run_dir, os.path.basename(args.exe)),
           "--out", ".", "--quiet"]
    proc = subprocess.Popen(cmd, cwd=run_dir, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output = []
    reader = threading.Thread(target=lambda: output.append(proc.stdout.read()))
    reader.start()
    edited = None
    if hot:
        # The engine blocks at the marker frame until it sees a notification: edit the mod then.
        deadline = time.time() + 600
        while time.time() < deadline and proc.poll() is None and not os.path.exists(marker):
            time.sleep(0.005)
        if os.path.exists(marker):
            dest_dir = os.path.join(run_dir, ROOTS[hot.get("root", "remix")], hot["name"])
            for name in sorted(os.listdir(hot_src)):
                tmp = os.path.join(dest_dir, "." + name + ".tmp")
                shutil.copyfile(os.path.join(hot_src, name), tmp)
                os.replace(tmp, os.path.join(dest_dir, name))
            edited = True
        else:
            edited = False
    rc = proc.wait()
    reader.join()
    text = (output[0] if output else b"").decode(errors="replace")
    with open(os.path.join(run_dir, "run.log"), "w") as f:
        f.write(text)
    return rc, text, edited


def summarize(capture_path):
    lines = []
    with open(capture_path) as f:
        for l in f:
            if l.strip():
                lines.append(json.loads(l))
    frames = [l for l in lines if l["ev"] == "replace_frame"]
    if not frames:
        return None
    last = frames[-1]
    runs = []
    for fr in frames:
        if runs and runs[-1]["stats"] == fr["stats"] and runs[-1]["last"] + 1 == fr["frame"]:
            runs[-1]["last"] = fr["frame"]
        else:
            runs.append({"first": fr["frame"], "last": fr["frame"], "stats": fr["stats"]})
    reloads = [fr["reload"] for fr in frames if fr.get("reload")]
    draws = []
    for d in lines:
        if d["ev"] == "draw" and d["frame"] == last["frame"] and "replacement" in d:
            draws.append({"di": d["di"], "key": (d.get("geometry") or {}).get("key"),
                          "color_texture": d["classification"]["color_texture"], "replacement": d["replacement"]})
    return {
        "frames": len(frames),
        "watch": last["watch"],
        "generation": last["generation"],
        "mods": last["mods"],
        "stats_runs": runs,
        "reloads": reloads,
        "last_frame": {"frame": last["frame"], "lights": last["lights"], "deleted_lights": last["deleted_lights"],
                       "residency": last["residency"], "draws": draws},
    }


def diff(a, b, path="", out=None):
    out = [] if out is None else out
    if isinstance(a, dict) and isinstance(b, dict):
        for k in sorted(set(a) | set(b)):
            if k not in a or k not in b:
                out.append("%s.%s: %s" % (path, k, "missing from the run" if k not in a else "not expected"))
            else:
                diff(a[k], b[k], path + "." + k, out)
    elif isinstance(a, list) and isinstance(b, list) and len(a) == len(b):
        for i, (x, y) in enumerate(zip(a, b)):
            diff(x, y, "%s[%d]" % (path, i), out)
    elif a != b:
        out.append("%s: run %s, expected %s" % (path, json.dumps(a)[:300], json.dumps(b)[:300]))
    return out


def main():
    ap = argparse.ArgumentParser()
    for opt in ("case", "fixtures", "exe", "d3d9", "d3d8", "runner", "prefix_root", "stager", "out"):
        ap.add_argument("--" + opt.replace("_", "-"), required=True)
    ap.add_argument("--emulator", default="")
    ap.add_argument("--keep", action="store_true")
    ap.add_argument("--update", action="store_true")
    args = ap.parse_args()
    with open(args.case) as f:
        case = json.load(f)
    name = os.path.splitext(os.path.basename(args.case))[0]
    run_dir = os.path.join(args.out, "run")
    try:
        rc, text, edited = run_app(args, case, run_dir)
    except RuntimeError as e:
        print("FAIL: %s: %s" % (name, e))
        return 1
    if rc == SKIP:
        print(text.strip())
        return SKIP
    if rc != 0:
        print(text.strip()[-4000:])
        print("FAIL: %s: the app exited with %d" % (name, rc))
        return 1
    capture = os.path.join(run_dir, "relight_capture.jsonl")
    if not os.path.isfile(capture):
        print("FAIL: %s: no capture record" % name)
        return 1
    summary = summarize(capture)
    if summary is None:
        print(text.strip()[-2000:])
        print("FAIL: %s: the capture record has no replace_frame line (no replacement engine?)" % name)
        return 1
    errors = []
    hot = case.get("hot_reload")
    if hot:
        if not edited:
            errors.append("the engine never reached the hot reload frame %d (no marker file)" % hot["frame"])
        later = summary["reloads"][1:]
        if not later:
            errors.append("no reload after the edit")
        for r in later:
            if r["applied_frame"] - r["notified_frame"] > 1:
                errors.append("reload generation %d: applied at frame %d, notified at %d (> 1 frame)"
                              % (r["generation"], r["applied_frame"], r["notified_frame"]))
            if r["notified_frame"] != hot["frame"]:
                errors.append("reload generation %d notified at frame %d, the edit was made at frame %d"
                              % (r["generation"], r["notified_frame"], hot["frame"]))
    for m in summary["mods"]:
        if m["errors"]:
            errors.append("mod %s reports %d error(s) (see run.log)" % (m["name"], m["errors"]))
    expected_path = os.path.join(os.path.dirname(args.case), case.get("expected", name) + ".expected.json")
    if args.update:
        with open(expected_path, "w") as f:
            json.dump(summary, f, indent=2, sort_keys=True)
            f.write("\n")
        print("updated %s" % expected_path)
    elif not os.path.isfile(expected_path):
        errors.append("no %s (run with --update to write it)" % expected_path)
    else:
        with open(expected_path) as f:
            expected = json.load(f)
        errors += diff(summary, expected)
    if errors:
        print("FAIL: %s (%s): %d difference(s):" % (name, case["app"], len(errors)))
        for e in errors[:60]:
            print("  " + e)
        return 1
    stats = summary["stats_runs"][-1]["stats"]
    print("PASS: %s (%s): %d frame(s), %d mod(s), last frame: %d mesh replaced (%d hidden), %d material(s), "
          "%d light(s) replaced, %d deleted, %d attached; %d reload(s)"
          % (name, case["app"], summary["frames"], len(summary["mods"]), stats["mesh_replaced"], stats["hidden"],
             stats["material_replaced"], stats["lights_replaced"], stats["lights_deleted"], stats["lights_attached"],
             len(summary["reloads"])))
    if not args.keep:
        shutil.rmtree(args.out, ignore_errors=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
