#!/usr/bin/env python3
"""FUSE app icon generator (Appendix A rename checklist: icons).

The icon is defined once, geometrically, in a 256x256 design space: a dark rounded tile with two
overlapping discs (2D and 3D) whose lens-shaped overlap is the white "fusion" core. This script
emits the scalable SVG and rasterises the same geometry (4x4 supersampling, no third-party
dependencies) into PNGs at 16/32/48/256 px plus a PNG-compressed Windows .ico.

    gen_fuse_icons.py [--out DIR]     write fuse.svg, fuse_<N>.png, fuse.ico (default: this dir)
    gen_fuse_icons.py --check [DIR]   regenerate in memory; exit 1 if the committed files differ
                                      (SVG text, PNG pixels, ICO directory + embedded PNG pixels)
"""

import os
import struct
import sys
import zlib

SIZES = (16, 32, 48, 256)
DESIGN = 256.0

TILE = (8.0, 8.0, 248.0, 248.0, 52.0)  # x0, y0, x1, y1, corner radius
TILE_RGB = (0x14, 0x1A, 0x26)
DISC_2D = (100.0, 128.0, 66.0)  # cx, cy, r
DISC_2D_RGB = (0xFF, 0x7A, 0x1A)
DISC_3D = (156.0, 128.0, 66.0)
DISC_3D_RGB = (0x1F, 0xC8, 0xE8)
CORE_RGB = (0xFF, 0xFF, 0xFF)


def _hex(rgb):
    return "#%02x%02x%02x" % rgb


def svg_text():
    x0, y0, x1, y1, r = TILE
    ax, ay, ar = DISC_2D
    bx, by, br = DISC_3D
    # Lens = intersection of the two equal discs: two arcs between the circle intersection points.
    dx = (bx - ax) / 2.0
    hy = (ar * ar - dx * dx) ** 0.5
    mx = ax + dx
    top = (mx, ay - hy)
    bot = (mx, ay + hy)
    def f(v):
        return ("%.3f" % v).rstrip("0").rstrip(".")
    lens = "M%s %s A%s %s 0 0 1 %s %s A%s %s 0 0 1 %s %s Z" % (
        f(top[0]), f(top[1]), f(ar), f(ar), f(bot[0]), f(bot[1]),
        f(br), f(br), f(top[0]), f(top[1]))
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- FUSE application icon. Generated by gen_fuse_icons.py; do not edit by hand. -->\n'
        '<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256" viewBox="0 0 256 256">\n'
        '  <title>FUSE</title>\n'
        '  <rect x="%s" y="%s" width="%s" height="%s" rx="%s" ry="%s" fill="%s"/>\n'
        '  <circle cx="%s" cy="%s" r="%s" fill="%s"/>\n'
        '  <circle cx="%s" cy="%s" r="%s" fill="%s"/>\n'
        '  <path d="%s" fill="%s"/>\n'
        '</svg>\n'
    ) % (f(x0), f(y0), f(x1 - x0), f(y1 - y0), f(r), f(r), _hex(TILE_RGB),
         f(ax), f(ay), f(ar), _hex(DISC_2D_RGB),
         f(bx), f(by), f(br), _hex(DISC_3D_RGB),
         lens, _hex(CORE_RGB))


def _in_tile(x, y):
    x0, y0, x1, y1, r = TILE
    if x < x0 or x > x1 or y < y0 or y > y1:
        return False
    cx = min(max(x, x0 + r), x1 - r)
    cy = min(max(y, y0 + r), y1 - r)
    return (x - cx) ** 2 + (y - cy) ** 2 <= r * r


def _in_disc(d, x, y):
    return (x - d[0]) ** 2 + (y - d[1]) ** 2 <= d[2] * d[2]


def sample(x, y):
    """RGBA (0..255, alpha 0 or 255) of the design at design-space point (x, y)."""
    if not _in_tile(x, y):
        return None
    a = _in_disc(DISC_2D, x, y)
    b = _in_disc(DISC_3D, x, y)
    if a and b:
        return CORE_RGB
    if a:
        return DISC_2D_RGB
    if b:
        return DISC_3D_RGB
    return TILE_RGB


def rasterise(size, ss=4):
    """Returns raw RGBA rows (bytes) for a size x size render, ss x ss supersampled."""
    scale = DESIGN / size
    rows = []
    for py in range(size):
        row = bytearray()
        for px in range(size):
            r = g = b = cov = 0
            for sy in range(ss):
                for sx in range(ss):
                    c = sample((px + (sx + 0.5) / ss) * scale, (py + (sy + 0.5) / ss) * scale)
                    if c is not None:
                        r += c[0]
                        g += c[1]
                        b += c[2]
                        cov += 1
            if cov == 0:
                row += b"\x00\x00\x00\x00"
            else:
                row += bytes((r // cov, g // cov, b // cov, (cov * 255 + ss * ss // 2) // (ss * ss)))
        rows.append(bytes(row))
    return rows


def _chunk(tag, data):
    return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)


def png_bytes(size, rows):
    raw = b"".join(b"\x00" + r for r in rows)
    return (b"\x89PNG\r\n\x1a\n" + _chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)) +
            _chunk(b"IDAT", zlib.compress(raw, 9)) + _chunk(b"IEND", b""))


def png_decode(data):
    """Minimal decoder for the PNGs this script writes (8-bit RGBA, filter 0). -> (w, h, rows)."""
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    pos, idat, w, h = 8, b"", 0, 0
    while pos < len(data):
        n = struct.unpack(">I", data[pos:pos + 4])[0]
        tag = data[pos + 4:pos + 8]
        body = data[pos + 8:pos + 8 + n]
        if tag == b"IHDR":
            w, h, depth, ctype = struct.unpack(">IIBB", body[:10])
            if depth != 8 or ctype != 6:
                raise ValueError("not 8-bit RGBA")
        elif tag == b"IDAT":
            idat += body
        pos += 12 + n
    raw = zlib.decompress(idat)
    stride = w * 4 + 1
    rows = []
    for y in range(h):
        line = raw[y * stride:(y + 1) * stride]
        if line[0] != 0:
            raise ValueError("unsupported PNG filter %d" % line[0])
        rows.append(bytes(line[1:]))
    return w, h, rows


def ico_bytes(pngs):
    """Windows .ico with PNG-compressed entries (Vista+), one per size."""
    head = struct.pack("<HHH", 0, 1, len(pngs))
    offset = 6 + 16 * len(pngs)
    dirs, blobs = b"", b""
    for size, data in pngs:
        dim = 0 if size >= 256 else size
        dirs += struct.pack("<BBBBHHII", dim, dim, 0, 0, 1, 32, len(data), offset)
        blobs += data
        offset += len(data)
    return head + dirs + blobs


def ico_decode(data):
    """-> list of (size, png bytes)."""
    _, kind, count = struct.unpack("<HHH", data[:6])
    if kind != 1:
        raise ValueError("not an icon")
    out = []
    for i in range(count):
        w, _, _, _, _, _, n, off = struct.unpack("<BBBBHHII", data[6 + 16 * i:22 + 16 * i])
        out.append((w or 256, data[off:off + n]))
    return out


def generate():
    files = {"fuse.svg": svg_text().encode("utf-8")}
    rasters = {}
    pngs = []
    for s in SIZES:
        rows = rasterise(s)
        rasters[s] = rows
        data = png_bytes(s, rows)
        files["fuse_%d.png" % s] = data
        pngs.append((s, data))
    files["fuse.ico"] = ico_bytes(pngs)
    return files, rasters


def check(directory):
    files, rasters = generate()
    bad = []
    def read(name):
        p = os.path.join(directory, name)
        if not os.path.isfile(p):
            bad.append("%s: missing" % name)
            return None
        with open(p, "rb") as fh:
            return fh.read()
    svg = read("fuse.svg")
    if svg is not None and svg.replace(b"\r\n", b"\n") != files["fuse.svg"]:
        bad.append("fuse.svg: differs from generator output")
    for s in SIZES:
        name = "fuse_%d.png" % s
        data = read(name)
        if data is None:
            continue
        try:
            w, h, rows = png_decode(data)
        except Exception as e:  # noqa: BLE001 - report any decode failure as a gate failure
            bad.append("%s: %s" % (name, e))
            continue
        if (w, h) != (s, s) or rows != rasters[s]:
            bad.append("%s: pixels differ from generator output" % name)
    ico = read("fuse.ico")
    if ico is not None:
        try:
            entries = ico_decode(ico)
            if [e[0] for e in entries] != list(SIZES):
                bad.append("fuse.ico: sizes %s != %s" % ([e[0] for e in entries], list(SIZES)))
            for s, data in entries:
                if s in rasters and png_decode(data)[2] != rasters[s]:
                    bad.append("fuse.ico: %dpx entry pixels differ" % s)
        except Exception as e:  # noqa: BLE001
            bad.append("fuse.ico: %s" % e)
    for b in bad:
        print("  " + b, file=sys.stderr)
    print("gen_fuse_icons --check %s: %d difference(s)" % (directory, len(bad)))
    return 1 if bad else 0


def main(argv):
    here = os.path.dirname(os.path.abspath(__file__))
    if len(argv) >= 1 and argv[0] == "--check":
        return check(argv[1] if len(argv) > 1 else here)
    out = argv[1] if len(argv) > 1 and argv[0] == "--out" else here
    os.makedirs(out, exist_ok=True)
    files, _ = generate()
    for name, data in sorted(files.items()):
        with open(os.path.join(out, name), "wb") as fh:
            fh.write(data)
        print("wrote %s (%d bytes)" % (os.path.join(out, name), len(data)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
