// Screen-space radiance cascades on Vulkan: see include/fuse/renderer/ssrc/ssrc_gpu.hpp.
#include <fuse/renderer/ssrc/ssrc_gpu.hpp>

#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/device.hpp>

#include <algorithm>
#include <cstring>
#include <initializer_list>

#if defined(FUSE_VULKAN_BACKEND)
#include <vulkan/vulkan.h>

// Generated by cmake/rp_ssrc.cmake from shaders/ssrc/*: kSrc<Kernel><Slang|Glsl>Spv and FUSE_SSRC_GPU_{SLANG,GLSL}
// when every kernel of a language exists.
#include "ssrc_gpu_spv.h"
#endif

namespace fuse::renderer::ssrc {

namespace {
constexpr u32 kPushBytes = sizeof(SsrcPush);
constexpr u32 kFrameStride = 768u; ///< ring slot size (>= sizeof(SsrcFrameConstants), 256-aligned)
static_assert(sizeof(SsrcFrameConstants) <= kFrameStride, "frame ring slot");
constexpr u32 kOutputFormat = static_cast<u32>(GpuFormat::R16G16B16A16Sfloat);
constexpr u64 kTexel = 16u;  ///< f32x4
constexpr u64 kRecord = 8u;  ///< u32x2 (4 x f16)

BufferUsage bufferUsage(std::initializer_list<BufferUsage> bits) {
    u32 u = 0;
    for (const BufferUsage b : bits) {
        u |= static_cast<u32>(b);
    }
    return static_cast<BufferUsage>(u);
}

ImageUsage imageUsage(std::initializer_list<ImageUsage> bits) {
    u32 u = 0;
    for (const ImageUsage b : bits) {
        u |= static_cast<u32>(b);
    }
    return static_cast<ImageUsage>(u);
}

u64 align256(u64 v) { return (v + 255u) & ~u64{255u}; }

u32 groups(u32 items, u32 size) { return items == 0u ? 1u : (items + size - 1u) / size; }

/// Same work buffer / direction table: extent and every cascade's grid and direction resolution.
bool sameLayout(const SsrcFrameConstants& a, const SsrcFrameConstants& b) {
    if (a.width != b.width || a.height != b.height || a.cascades != b.cascades) {
        return false;
    }
    for (u32 i = 0; i < a.cascades; ++i) {
        if (a.probesX[i] != b.probesX[i] || a.probesY[i] != b.probesY[i] || a.dirRes[i] != b.dirRes[i]) {
            return false;
        }
    }
    return true;
}

#if defined(FUSE_VULKAN_BACKEND)
struct Code {
    const u32* words = nullptr;
    usize bytes = 0;
};
template <usize N>
Code code(const u32 (&spv)[N]) {
    return Code{spv, sizeof(spv)};
}
#endif
} // namespace

SsrcBufferLayout SsrcBufferLayout::compute(const SsrcLayoutInfo& info, u32 width, u32 height) {
    SsrcBufferLayout l{};
    u64 cursor = 0;
    auto take = [&](u64 bytes) {
        const u64 at = cursor;
        cursor = align256(cursor + std::max<u64>(bytes, 16u));
        return at;
    };
    const u64 n = static_cast<u64>(width) * height;
    l.geo = take(n * kTexel);
    l.lit = take(n * kTexel);
    l.diffuse = take(n * kTexel);
    l.albedo = take(n * kTexel);
    l.indirect = take(n * kTexel);
    l.records[0] = take(info.maxRecords * kRecord);
    l.records[1] = take(info.maxRecords * kRecord);
    l.maxRecords = info.maxRecords;
    l.workBytes = cursor;
    return l;
}

SsrcCapabilities querySsrcCapabilities(const VulkanDevice* device) {
    SsrcCapabilities c{};
#if defined(FUSE_VULKAN_BACKEND)
    if (device == nullptr || !device->isValid()) {
        return c;
    }
    const RendererCaps& caps = device->info().caps;
    if (!caps.bufferDeviceAddress || !caps.shaderInt64) {
        c.reason = "bufferDeviceAddress / shaderInt64 missing";
        return c;
    }
    VkFormatProperties props{};
    vkGetPhysicalDeviceFormatProperties(static_cast<VkPhysicalDevice>(device->nativePhysicalDevice()),
                                        static_cast<VkFormat>(kOutputFormat), &props);
    if ((props.optimalTilingFeatures & VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT) == 0u) {
        c.reason = "RGBA16F storage images unsupported";
        return c;
    }
    c.ssrc = true;
    c.reason = "ok";
#else
    (void)device;
    c.reason = "stub backend";
#endif
    return c;
}

SsrcGpu::~SsrcGpu() { destroy(); }

bool SsrcGpu::init(const SsrcGpuDesc& desc) {
    destroy();
    m_desc = desc;
#if defined(FUSE_VULKAN_BACKEND)
    if (desc.allocator == nullptr || desc.bindless == nullptr || desc.framesInFlight == 0u) {
        return false;
    }
    if (!querySsrcCapabilities(desc.device).ssrc) {
        return false;
    }
    m_retired.reserve(8);
    m_initialized = true; // destroy() releases partial state from here on
    BufferDesc ring{};
    ring.size = static_cast<usize>(desc.framesInFlight) * kFrameStride;
    ring.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress});
    ring.memoryUsage = MemoryUsage::CpuToGpu;
    ring.name = "ssrc.frame";
    if (!m_desc.allocator->createBuffer(ring, m_frameRing) || m_frameRing.mapped == nullptr ||
        m_frameRing.deviceAddress == 0u || !createPipelines()) {
        destroy();
        return false;
    }
    return true;
#else
    return false;
#endif
}

void SsrcGpu::destroy() {
    if (!m_initialized) {
        return;
    }
#if defined(FUSE_VULKAN_BACKEND)
    collectRetired(~0ull);
    Retired current{};
    current.buffers[0] = m_work;
    current.buffers[1] = m_dirs;
    current.image = m_output.image;
    current.slots[0] = m_output.slot;
    for (u32 i = 0; i < kInputCount; ++i) {
        current.slots[1u + i] = m_inputSlots[i];
    }
    destroyRetired(current);
    if (m_frameRing.handle != nullptr) {
        m_desc.allocator->destroyBuffer(m_frameRing);
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    for (void*& pipeline : m_pipelines) {
        if (pipeline != nullptr) {
            vkDestroyPipeline(device, static_cast<VkPipeline>(pipeline), nullptr);
            pipeline = nullptr;
        }
    }
    if (m_layoutHandle != nullptr) {
        vkDestroyPipelineLayout(device, static_cast<VkPipelineLayout>(m_layoutHandle), nullptr);
    }
#endif
    m_layoutHandle = nullptr;
    m_work = Buffer{};
    m_dirs = Buffer{};
    m_workQueue = rg::kNoQueue;
    m_output = Output{};
    m_frameRing = Buffer{};
    m_frameAddress = 0;
    m_retired.clear();
    for (u32 i = 0; i < kInputCount; ++i) {
        m_inputImages[i] = nullptr;
        m_inputSlots[i] = BindlessSlotHandle{};
        m_inputHandles[i] = 0u;
    }
    m_width = m_height = 0;
    m_layout = SsrcBufferLayout{};
    m_info = SsrcLayoutInfo{};
    m_layoutKey = SsrcFrameConstants{};
    m_recordCount = 0;
    m_language = "none";
    m_stats = SsrcGpuStats{};
    m_constants = SsrcFrameConstants{};
    m_hasDump = false;
    m_initialized = false;
}

bool SsrcGpu::createPipelines() {
#if defined(FUSE_VULKAN_BACKEND)
    Code k[kKernelCount]{};
    bool found = false;
#if defined(FUSE_SSRC_GPU_SLANG)
    if (m_desc.language == SsrcKernelLanguage::Auto || m_desc.language == SsrcKernelLanguage::Slang) {
        k[kPrepare] = code(kSrcPrepareSlangSpv);
        k[kCascade] = code(kSrcCascadeSlangSpv);
        k[kGather] = code(kSrcGatherSlangSpv);
        m_language = "slang";
        found = true;
    }
#endif
#if defined(FUSE_SSRC_GPU_GLSL)
    if (!found && (m_desc.language == SsrcKernelLanguage::Auto || m_desc.language == SsrcKernelLanguage::Glsl)) {
        k[kPrepare] = code(kSrcPrepareGlslSpv);
        k[kCascade] = code(kSrcCascadeGlslSpv);
        k[kGather] = code(kSrcGatherGlslSpv);
        m_language = "glsl";
        found = true;
    }
#endif
    if (!found) {
        return false;
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    VkDescriptorSetLayout setLayout = static_cast<VkDescriptorSetLayout>(m_desc.bindless->layoutHandle());
    VkPushConstantRange range{VK_SHADER_STAGE_COMPUTE_BIT, 0, kPushBytes};
    VkPipelineLayoutCreateInfo layoutInfo{};
    layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutInfo.setLayoutCount = setLayout != VK_NULL_HANDLE ? 1u : 0u;
    layoutInfo.pSetLayouts = &setLayout;
    layoutInfo.pushConstantRangeCount = 1;
    layoutInfo.pPushConstantRanges = &range;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    if (vkCreatePipelineLayout(device, &layoutInfo, nullptr, &layout) != VK_SUCCESS) {
        return false;
    }
    m_layoutHandle = layout;
    const VkPipelineCreateFlags createFlags = static_cast<VkPipelineCreateFlags>(m_desc.bindless->pipelineCreateFlags());
    for (u32 i = 0; i < kKernelCount; ++i) {
        VkShaderModuleCreateInfo moduleInfo{};
        moduleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        moduleInfo.codeSize = k[i].bytes;
        moduleInfo.pCode = k[i].words;
        VkShaderModule module = VK_NULL_HANDLE;
        if (vkCreateShaderModule(device, &moduleInfo, nullptr, &module) != VK_SUCCESS) {
            return false;
        }
        VkComputePipelineCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
        info.flags = createFlags;
        info.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        info.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
        info.stage.module = module;
        info.stage.pName = "main";
        info.layout = layout;
        VkPipeline pipeline = VK_NULL_HANDLE;
        const VkResult result = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
        vkDestroyShaderModule(device, module, nullptr);
        m_pipelines[i] = pipeline;
        if (result != VK_SUCCESS) {
            return false;
        }
    }
    return true;
#else
    return false;
#endif
}

bool SsrcGpu::rebuildWork(const SsrcFrameConstants& c, const SsrcLayoutInfo& info, u32 width, u32 height) {
    const SsrcBufferLayout layout = SsrcBufferLayout::compute(info, width, height);
    BufferDesc work{};
    work.size = static_cast<usize>(layout.workBytes);
    work.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress, BufferUsage::TransferSrc});
    work.memoryUsage = MemoryUsage::GpuOnly;
    work.name = "ssrc.work";
    buildDirectionTable(c, m_dirScratch);
    BufferDesc dirs{};
    dirs.size = m_dirScratch.size() * sizeof(f32);
    dirs.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress});
    dirs.memoryUsage = MemoryUsage::CpuToGpu;
    dirs.name = "ssrc.dirs";
    Buffer freshWork{};
    Buffer freshDirs{};
    const bool ok = m_desc.allocator->createBuffer(work, freshWork) && freshWork.deviceAddress != 0u &&
                    m_desc.allocator->createBuffer(dirs, freshDirs) && freshDirs.deviceAddress != 0u &&
                    freshDirs.mapped != nullptr;
    if (!ok) {
        Retired r{};
        r.buffers[0] = freshWork;
        r.buffers[1] = freshDirs;
        destroyRetired(r);
        return false;
    }
    std::memcpy(freshDirs.mapped, m_dirScratch.data(), dirs.size);
    if (m_work.handle != nullptr || m_dirs.handle != nullptr) {
        Retired old{};
        old.buffers[0] = m_work;
        old.buffers[1] = m_dirs;
        retire(old);
    }
    m_work = freshWork;
    m_dirs = freshDirs;
    m_workQueue = rg::kNoQueue;
    m_layout = layout;
    m_info = info;
    m_layoutKey = c;
    ++m_stats.workRebuilds;
    return true;
}

bool SsrcGpu::createOutput(u32 width, u32 height) {
    Output o{};
    TextureDesc d{};
    d.width = width;
    d.height = height;
    d.format = static_cast<GpuFormat>(kOutputFormat);
    d.usage = imageUsage({ImageUsage::Storage, ImageUsage::Sampled, ImageUsage::TransferSrc});
    d.name = "ssrc.output";
    if (!m_desc.allocator->createImage(d, o.image)) {
        return false;
    }
    o.slot = m_desc.bindless->registerTextureSlot(o.image, true);
    if (!o.slot.isValid()) {
        m_desc.allocator->destroyImage(o.image);
        return false;
    }
    if (m_output.image.image != nullptr) {
        Retired old{};
        old.image = m_output.image;
        old.slots[0] = m_output.slot;
        retire(old);
    }
    m_output = o;
    ++m_stats.outputRebuilds;
    return true;
}

bool SsrcGpu::bindInput(u32 index, const Texture* image) {
    void* handle = image != nullptr ? image->image : nullptr;
    if (handle == m_inputImages[index] && (handle == nullptr || m_inputSlots[index].isValid())) {
        return true;
    }
    if (m_inputSlots[index].isValid()) {
        Retired old{};
        old.slots[1u + index] = m_inputSlots[index];
        retire(old);
    }
    m_inputSlots[index] = BindlessSlotHandle{};
    m_inputImages[index] = nullptr;
    m_inputHandles[index] = 0u;
    if (handle == nullptr) {
        return true;
    }
    m_inputSlots[index] = m_desc.bindless->registerTextureSlot(*image, false);
    if (!m_inputSlots[index].isValid()) {
        return false;
    }
    m_inputImages[index] = handle;
    m_inputHandles[index] = m_desc.bindless->shaderHandle(m_inputSlots[index]);
    ++m_stats.inputBinds;
    return true;
}

void SsrcGpu::retire(Retired r) {
    r.serial = m_frameSerial;
    m_retired.push_back(r);
    ++m_stats.retired;
}

void SsrcGpu::destroyRetired(Retired& r) {
    for (BindlessSlotHandle& slot : r.slots) {
        if (slot.isValid()) {
            m_desc.bindless->unregisterSlot(slot);
        }
    }
    for (Buffer& b : r.buffers) {
        if (b.handle != nullptr) {
            m_desc.allocator->destroyBuffer(b);
        }
    }
    if (r.image.image != nullptr) {
        m_desc.allocator->destroyImage(r.image);
    }
    r = Retired{};
}

u32 SsrcGpu::collectRetired(u64 completedSerial) {
    u32 collected = 0;
    usize keep = 0;
    for (usize i = 0; i < m_retired.size(); ++i) {
        if (m_retired[i].serial > completedSerial) {
            m_retired[keep++] = m_retired[i];
            continue;
        }
        destroyRetired(m_retired[i]);
        ++collected;
    }
    m_retired.resize(keep);
    m_stats.retired = m_stats.retired >= collected ? m_stats.retired - collected : 0u;
    return collected;
}

bool SsrcGpu::beginFrame(u64 frameSerial, const SsrcSettings& settings, const ssfx_gpu::SsfxCameraDesc& camera,
                         const f32 (&ambient)[3], const SsrcFrameImages& images) {
    if (!m_initialized) {
        return false;
    }
    const Texture* inputs[kInputCount] = {images.depth, images.normalAo, images.albedo, images.roughMetal, images.lit};
    for (const Texture* t : inputs) {
        if (t == nullptr || t->image == nullptr) {
            return false;
        }
    }
    const u32 w = images.depth->desc.width;
    const u32 h = images.depth->desc.height;
    if (w == 0u || h == 0u) {
        return false;
    }
    for (const Texture* t : inputs) {
        if (t->desc.width != w || t->desc.height != h) {
            return false;
        }
    }
    if (settings.ddgi && images.ddgiVolume == 0u) {
        return false;
    }
    SsrcFrameConstants c{};
    SsrcLayoutInfo info{};
    if (!resolve_constants(settings, camera, ambient, w, h, c, &info)) {
        return false;
    }
    m_frameSerial = frameSerial;
    m_recordCount = 0;
    m_stats.passes = 0;
    m_stats.cascades = 0;
    if (m_work.handle == nullptr || !sameLayout(c, m_layoutKey)) {
        if (!rebuildWork(c, info, w, h)) {
            return false;
        }
    }
    if (w != m_width || h != m_height || m_output.image.image == nullptr) {
        if (!createOutput(w, h)) {
            return false;
        }
        m_width = w;
        m_height = h;
    }
    for (u32 i = 0; i < kInputCount; ++i) {
        if (!bindInput(i, inputs[i])) {
            return false;
        }
    }
    const u64 work = m_work.deviceAddress;
    c.geo = work + m_layout.geo;
    c.lit = work + m_layout.lit;
    c.diffuse = work + m_layout.diffuse;
    c.albedo = work + m_layout.albedo;
    c.indirect = work + m_layout.indirect;
    c.records0 = work + m_layout.records[0];
    c.records1 = work + m_layout.records[1];
    c.dirs = m_dirs.deviceAddress;
    c.ddgiVolume = settings.ddgi ? images.ddgiVolume : 0u;
    c.dump = images.dumpAddress;
    c.inputDepth = m_inputHandles[0];
    c.inputNormal = m_inputHandles[1];
    c.inputAlbedo = m_inputHandles[2];
    c.inputRoughMetal = m_inputHandles[3];
    c.inputLit = m_inputHandles[4];
    c.output = m_desc.bindless->shaderHandle(m_output.slot);
    m_hasDump = images.dumpAddress != 0u;
    m_constants = c;
    const u32 slot = static_cast<u32>(frameSerial % m_desc.framesInFlight);
    const u64 offset = static_cast<u64>(slot) * kFrameStride;
    std::memcpy(static_cast<u8*>(m_frameRing.mapped) + offset, &c, sizeof(c));
    m_frameAddress = m_frameRing.deviceAddress + offset;
    return true;
}

SsrcGraphRefs SsrcGpu::importInto(rg::Graph& graph) {
    SsrcGraphRefs refs{};
    if (!m_initialized || m_work.handle == nullptr) {
        return refs;
    }
    refs.work =
        graph.importBuffer(rg::ImportedBuffer{m_work.handle, m_work.desc.size, m_workQueue, &m_workQueue, "ssrc.work"});
    rg::ImportedImage i{};
    i.image = m_output.image.image;
    i.view = m_output.image.view;
    i.format = kOutputFormat;
    i.width = m_width;
    i.height = m_height;
    i.initialLayout = m_output.layout;
    i.initialQueue = m_output.queue;
    i.layoutTracker = &m_output.layout;
    i.queueTracker = &m_output.queue;
    i.name = "ssrc.output";
    refs.output = graph.importImage(i);
    return refs;
}

SsrcGpu::PassRecord* SsrcGpu::nextRecord(u32 kernel) {
    if (m_recordCount >= kMaxPasses) {
        return nullptr;
    }
    PassRecord* r = &m_records[m_recordCount++];
    *r = PassRecord{};
    r->self = this;
    r->kernel = kernel;
    r->push.frame = m_frameAddress;
    r->groups[0] = groups(m_width, kSsrcTile);
    r->groups[1] = groups(m_height, kSsrcTile);
    return r;
}

void SsrcGpu::addPasses(rg::Graph& graph, const SsrcGraphRefs& refs, const SsrcGraphInputs& inputs) {
    if (!m_initialized || !refs.work.valid() || !refs.output.valid() || !inputs.normalAo.valid() ||
        !inputs.albedo.valid() || !inputs.roughMetal.valid() || !inputs.depth.valid() || !inputs.lit.valid()) {
        return;
    }
    const SsrcFrameConstants& c = m_constants;
    if (PassRecord* r = nextRecord(kPrepare)) {
        ++m_stats.passes;
        graph.addPass("ssrc.prepare", &SsrcGpu::recordDispatch, r)
            .use(inputs.depth, rg::Access::SampledRead, {}, rg::kStageCompute)
            .use(inputs.normalAo, rg::Access::SampledRead, {}, rg::kStageCompute)
            .use(inputs.albedo, rg::Access::SampledRead, {}, rg::kStageCompute)
            .use(inputs.roughMetal, rg::Access::SampledRead, {}, rg::kStageCompute)
            .use(inputs.lit, rg::Access::SampledRead, {}, rg::kStageCompute)
            .use(refs.work, rg::Access::StorageReadWrite, {}, rg::kStageCompute);
    }
    const u64 work = m_work.deviceAddress;
    u64 upper = 0;
    for (u32 ci = c.cascades; ci-- > 0u;) {
        PassRecord* r = nextRecord(kCascade);
        if (r == nullptr) {
            return;
        }
        const u32 count = c.probesX[ci] * c.probesY[ci] * c.dirRes[ci] * c.dirRes[ci];
        const u32 total = groups(count, kSsrcGroupSize);
        r->push.cascade = ci;
        r->push.count = count;
        r->push.upper = upper;
        r->push.dst = work + m_layout.records[ci & 1u];
        r->groups[0] = std::min(total, kSsrcMaxGroupsX);
        r->groups[1] = groups(total, r->groups[0]);
        r->push.groupsX = r->groups[0];
        upper = r->push.dst;
        ++m_stats.passes;
        ++m_stats.cascades;
        rg::PassBuilder pass = graph.addPass("ssrc.cascade", &SsrcGpu::recordDispatch, r);
        pass.use(refs.work, rg::Access::StorageReadWrite, {}, rg::kStageCompute);
        if (c.ddgiVolume != 0u) {
            for (const rg::BufferRef& b : inputs.ddgi) {
                if (b.valid()) {
                    pass.use(b, rg::Access::StorageRead, {}, rg::kStageCompute);
                }
            }
        }
    }
    if (PassRecord* r = nextRecord(kGather)) {
        r->push.upper = upper;
        ++m_stats.passes;
        rg::PassBuilder gather = graph.addPass("ssrc.gather", &SsrcGpu::recordDispatch, r);
        gather.use(refs.work, rg::Access::StorageReadWrite, {}, rg::kStageCompute);
        gather.use(refs.output, rg::Access::StorageWrite, {}, rg::kStageCompute);
        if (m_hasDump && inputs.dump.valid()) {
            gather.use(inputs.dump, rg::Access::StorageWrite,
                       rg::BufferRange{0, static_cast<u64>(m_width) * m_height * kTexel}, rg::kStageCompute);
        }
    }
}

u64 SsrcGpu::copyBytes(SsrcCopySource what) const {
    const u64 n = static_cast<u64>(m_width) * m_height;
    if (what == SsrcCopySource::Records0 || what == SsrcCopySource::Records1) {
        return m_layout.maxRecords * kRecord;
    }
    return n * kTexel;
}

void SsrcGpu::addCopy(rg::Graph& graph, const SsrcGraphRefs& refs, SsrcCopySource what, rg::BufferRef dst,
                      u64 dstOffset) {
    if (!m_initialized || !dst.valid() || !refs.work.valid()) {
        return;
    }
    PassRecord* r = nextRecord(kKernelCount);
    if (r == nullptr) {
        return;
    }
    u64 src = 0;
    switch (what) {
    case SsrcCopySource::Geo: src = m_layout.geo; break;
    case SsrcCopySource::Lit: src = m_layout.lit; break;
    case SsrcCopySource::Diffuse: src = m_layout.diffuse; break;
    case SsrcCopySource::Albedo: src = m_layout.albedo; break;
    case SsrcCopySource::Indirect: src = m_layout.indirect; break;
    case SsrcCopySource::Records0: src = m_layout.records[0]; break;
    case SsrcCopySource::Records1: src = m_layout.records[1]; break;
    }
    r->copySrc = src;
    r->copyBytes = copyBytes(what);
    r->copyDst = dstOffset;
    r->copyFrom = refs.work;
    r->copyTo = dst;
    ++m_stats.passes;
    graph.addPass("ssrc.copy", &SsrcGpu::recordCopy, r)
        .use(refs.work, rg::Access::TransferSrc, rg::BufferRange{r->copySrc, r->copyBytes})
        .use(dst, rg::Access::TransferDst, rg::BufferRange{dstOffset, r->copyBytes});
}

void SsrcGpu::recordDispatch(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const SsrcGpu& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, static_cast<VkPipeline>(self.m_pipelines[r.kernel]));
    self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, self.m_layoutHandle, 0);
    vkCmdPushConstants(cmd, static_cast<VkPipelineLayout>(self.m_layoutHandle), VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       kPushBytes, &r.push);
    vkCmdDispatch(cmd, r.groups[0], r.groups[1], r.groups[2]);
#else
    (void)context;
    (void)user;
#endif
}

void SsrcGpu::recordCopy(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    const VkBufferCopy region{r.copySrc, r.copyDst, r.copyBytes};
    vkCmdCopyBuffer(cmd, static_cast<VkBuffer>(context.buffer(r.copyFrom)), static_cast<VkBuffer>(context.buffer(r.copyTo)),
                    1, &region);
#else
    (void)context;
    (void)user;
#endif
}

} // namespace fuse::renderer::ssrc
