# FUSE Relight RL-2.1: bridge command-schema generator (run with cmake -P at build time).
# RL-2.2 adds the optional "-> Reply_X" row suffix (schema::replyOf).
# Copyright (c) 2026 FUSE contributors (AGPL-3.0). New code: upstream hand-wrote the 370 command cases
# (util_commands.h ids + per-call serialization in the client and server).
#
#   cmake -DTABLE=<commands.table> -DOUT_DIR=<dir> -P gen_commands.cmake
#
# Writes
#   <OUT_DIR>/fuse/relight/bridge/schema/commands.gen.hpp         ids, structs, codec declarations,
#                                                                  dispatch<Visitor>, kSchemaHash
#   <OUT_DIR>/fuse/relight/bridge/schema/commands_random.gen.hpp  fuzz randomizers (tests only)
#   <OUT_DIR>/commands.gen.cpp                                     names, sizes, encoders, decoders, ==
# Pure CMake so neither the MinGW nor the native build needs Python or a host compiler.
cmake_minimum_required(VERSION 3.20)

if(NOT TABLE OR NOT OUT_DIR)
    message(FATAL_ERROR "gen_commands.cmake: pass -DTABLE=... -DOUT_DIR=...")
endif()

function(_rl_ctype tok out)
    if(tok STREQUAL "u8")
        set(_t uint8_t)
    elseif(tok STREQUAL "u16")
        set(_t uint16_t)
    elseif(tok STREQUAL "u32" OR tok STREQUAL "handle")
        set(_t uint32_t)
    elseif(tok STREQUAL "u64")
        set(_t uint64_t)
    elseif(tok STREQUAL "i8")
        set(_t int8_t)
    elseif(tok STREQUAL "i16")
        set(_t int16_t)
    elseif(tok STREQUAL "i32")
        set(_t int32_t)
    elseif(tok STREQUAL "i64")
        set(_t int64_t)
    elseif(tok STREQUAL "f32")
        set(_t float)
    elseif(tok STREQUAL "f64")
        set(_t double)
    else()
        message(FATAL_ERROR "commands.table: unknown scalar type '${tok}'")
    endif()
    set(${out} "${_t}" PARENT_SCOPE)
endfunction()

file(STRINGS "${TABLE}" _lines ENCODING UTF-8)
set(_major "")
set(_minor "")
set(_names "")
set(_norm "")
set(_count 0)
set(_lineno 0)
foreach(_raw IN LISTS _lines)
    math(EXPR _lineno "${_lineno} + 1")
    string(REGEX REPLACE "#.*$" "" _line "${_raw}")
    string(STRIP "${_line}" _line)
    if(_line STREQUAL "")
        continue()
    endif()
    if(_line MATCHES "^protocol[ \t]+([0-9]+)[ \t]+([0-9]+)$")
        set(_major "${CMAKE_MATCH_1}")
        set(_minor "${CMAKE_MATCH_2}")
        string(APPEND _norm "protocol ${_major} ${_minor}\n")
        continue()
    endif()
    if(NOT _line MATCHES "^([A-Za-z_][A-Za-z0-9_]*)[ \t]*:(.*)$")
        message(FATAL_ERROR "commands.table:${_lineno}: cannot parse '${_raw}'")
    endif()
    set(_name "${CMAKE_MATCH_1}")
    string(STRIP "${CMAKE_MATCH_2}" _args)
    # RL-2.2: optional "-> Reply_X" suffix names the typed reply the host always sends.
    set(_reply "")
    if(_args MATCHES "^(.*)->[ \t]*([A-Za-z_][A-Za-z0-9_]*)$")
        string(STRIP "${CMAKE_MATCH_1}" _args)
        set(_reply "${CMAKE_MATCH_2}")
    endif()
    if(_name IN_LIST _names OR _name STREQUAL "Invalid")
        message(FATAL_ERROR "commands.table:${_lineno}: duplicate or reserved command '${_name}'")
    endif()
    list(APPEND _names "${_name}")
    math(EXPR _count "${_count} + 1")
    set(_cmd_${_count}_name "${_name}")
    set(_cmd_${_count}_reply "${_reply}")
    set(_fields "")
    set(_nsig "")
    if(NOT _args STREQUAL "")
        # Brackets are replaced before the list split so CMake's bracket rules cannot join elements.
        string(REPLACE "[" "<" _args "${_args}")
        string(REPLACE "]" ">" _args "${_args}")
        string(REPLACE "," ";" _arglist "${_args}")
        set(_fi 0)
        foreach(_a IN LISTS _arglist)
            string(STRIP "${_a}" _a)
            if(NOT _a MATCHES "^([a-z0-9]+)(<([0-9]*)>)?[ \t]+([A-Za-z_][A-Za-z0-9_]*)$")
                message(FATAL_ERROR "commands.table:${_lineno}: cannot parse field '${_a}' of ${_name}")
            endif()
            set(_tok "${CMAKE_MATCH_1}")
            set(_has_dim "${CMAKE_MATCH_2}")
            set(_dim "${CMAKE_MATCH_3}")
            set(_fname "${CMAKE_MATCH_4}")
            if("${_fname}" IN_LIST _fields)
                message(FATAL_ERROR "commands.table:${_lineno}: duplicate field '${_fname}' in ${_name}")
            endif()
            list(APPEND _fields "${_fname}")
            if(_tok STREQUAL "bytes" AND NOT _has_dim)
                set(_ct "std::vector<uint8_t>")
                set(_sig "bytes")
            elseif(_tok STREQUAL "str" AND NOT _has_dim)
                set(_ct "std::string")
                set(_sig "str")
            else()
                _rl_ctype("${_tok}" _base)
                if(_has_dim AND _dim STREQUAL "")
                    set(_ct "std::vector<${_base}>")
                    set(_sig "${_tok}[]")
                elseif(_has_dim)
                    if(_dim LESS_EQUAL 0)
                        message(FATAL_ERROR "commands.table:${_lineno}: array size must be positive")
                    endif()
                    set(_ct "std::array<${_base}, ${_dim}>")
                    set(_sig "${_tok}[${_dim}]")
                else()
                    set(_ct "${_base}")
                    set(_sig "${_tok}")
                endif()
            endif()
            set(_cmd_${_count}_f${_fi}_name "${_fname}")
            set(_cmd_${_count}_f${_fi}_type "${_ct}")
            list(APPEND _nsig "${_sig} ${_fname}")
            math(EXPR _fi "${_fi} + 1")
        endforeach()
        set(_cmd_${_count}_nfields ${_fi})
    else()
        set(_cmd_${_count}_nfields 0)
    endif()
    list(JOIN _nsig "," _nsig_s)
    if(_reply STREQUAL "")
        string(APPEND _norm "${_name}:${_nsig_s}\n")
    else()
        string(APPEND _norm "${_name}:${_nsig_s}->${_reply}\n")
    endif()
endforeach()

foreach(_i RANGE 1 ${_count})
    set(_r "${_cmd_${_i}_reply}")
    if(NOT _r STREQUAL "" AND (NOT _r IN_LIST _names OR NOT _r MATCHES "^Reply_"))
        message(FATAL_ERROR "commands.table: ${_cmd_${_i}_name} -> ${_r}: not a Reply_* row of the table")
    endif()
endforeach()

if(_major STREQUAL "")
    message(FATAL_ERROR "commands.table: missing 'protocol <major> <minor>' line")
endif()
if(_count GREATER 65534)
    message(FATAL_ERROR "commands.table: too many commands for 16-bit ids")
endif()
string(SHA256 _sha "${_norm}")
string(SUBSTRING "${_sha}" 0 16 _hash)

set(_banner "// Generated by Source/FUSE/Relight/bridge/schema/gen_commands.cmake from commands.table.\n// Do not edit: change the table. Copyright (c) 2026 FUSE contributors (AGPL-3.0).\n")

# ---- commands.gen.hpp ----------------------------------------------------------------------------
set(H "${_banner}#pragma once\n\n#include <fuse/relight/bridge/ipc/wire.hpp>\n\n")
string(APPEND H "#include <array>\n#include <cstddef>\n#include <cstdint>\n#include <string>\n#include <utility>\n#include <vector>\n\n")
string(APPEND H "namespace fuse::relight::bridge::schema {\n\n")
string(APPEND H "inline constexpr uint32_t kProtocolMajor = ${_major};\n")
string(APPEND H "inline constexpr uint32_t kProtocolMinor = ${_minor};\n")
string(APPEND H "// SHA-256 (first 64 bits) of the normalized command table: the handshake compares it.\n")
string(APPEND H "inline constexpr uint64_t kSchemaHash = 0x${_hash}ull;\n")
string(APPEND H "inline constexpr uint16_t kCommandCount = ${_count};\n\n")
string(APPEND H "enum class CommandId : uint16_t {\n    Invalid = 0,\n")
foreach(_i RANGE 1 ${_count})
    string(APPEND H "    ${_cmd_${_i}_name} = ${_i},\n")
endforeach()
string(APPEND H "};\n\n")
string(APPEND H "const char* commandName(uint16_t id) noexcept;\n")
string(APPEND H "inline const char* commandName(CommandId id) noexcept { return commandName(static_cast<uint16_t>(id)); }\n")
string(APPEND H "inline constexpr bool isKnownCommand(uint16_t id) noexcept { return id >= 1 && id <= kCommandCount; }\n")
string(APPEND H "// The typed reply the host always sends for command `id` (the table's \"-> Reply_X\"), 0 if none.\n")
string(APPEND H "uint16_t replyOf(uint16_t id) noexcept;\n")
string(APPEND H "inline CommandId replyOf(CommandId id) noexcept { return static_cast<CommandId>(replyOf(static_cast<uint16_t>(id))); }\n\n")
string(APPEND H "enum class DecodeStatus { Ok, UnknownCommand, Malformed };\n\n")
string(APPEND H "namespace cmd {\n\n")
foreach(_i RANGE 1 ${_count})
    set(_n "${_cmd_${_i}_name}")
    string(APPEND H "struct ${_n} {\n    static constexpr CommandId kId = CommandId::${_n};\n")
    math(EXPR _last "${_cmd_${_i}_nfields} - 1")
    if(_cmd_${_i}_nfields GREATER 0)
        foreach(_f RANGE 0 ${_last})
            string(APPEND H "    ${_cmd_${_i}_f${_f}_type} ${_cmd_${_i}_f${_f}_name}{};\n")
        endforeach()
    endif()
    string(APPEND H "};\n")
    string(APPEND H "size_t encodedSize(const ${_n}& c) noexcept;\n")
    string(APPEND H "void encode(ipc::WireWriter& w, const ${_n}& c) noexcept;\n")
    string(APPEND H "bool decode(ipc::WireReader& r, ${_n}& c);\n")
    string(APPEND H "bool operator==(const ${_n}& a, const ${_n}& b);\n")
    string(APPEND H "inline bool operator!=(const ${_n}& a, const ${_n}& b) { return !(a == b); }\n\n")
endforeach()
string(APPEND H "}  // namespace cmd\n\n")
string(APPEND H "// Host-side decoder: decodes the payload of command `id` into its struct and calls\n")
string(APPEND H "// visitor(const cmd::X&, ctx...). Trailing bytes count as malformed.\n")
string(APPEND H "template <class Visitor, class... Ctx>\n")
string(APPEND H "DecodeStatus dispatch(uint16_t id, const void* data, size_t size, Visitor&& visitor, Ctx&&... ctx) {\n")
string(APPEND H "    ipc::WireReader r(data, size);\n    switch (id) {\n")
foreach(_i RANGE 1 ${_count})
    set(_n "${_cmd_${_i}_name}")
    string(APPEND H "    case ${_i}: {\n        cmd::${_n} c;\n        if (!cmd::decode(r, c) || !r.atEnd()) {\n            return DecodeStatus::Malformed;\n        }\n        visitor(static_cast<const cmd::${_n}&>(c), std::forward<Ctx>(ctx)...);\n        return DecodeStatus::Ok;\n    }\n")
endforeach()
string(APPEND H "    default:\n        return DecodeStatus::UnknownCommand;\n    }\n}\n\n")
string(APPEND H "}  // namespace fuse::relight::bridge::schema\n")

# ---- commands.gen.cpp ----------------------------------------------------------------------------
set(C "${_banner}#include <fuse/relight/bridge/schema/commands.gen.hpp>\n\n")
string(APPEND C "namespace fuse::relight::bridge::schema {\n\nnamespace {\nconst char* const kNames[] = {\n    \"Invalid\",\n")
foreach(_i RANGE 1 ${_count})
    string(APPEND C "    \"${_cmd_${_i}_name}\",\n")
endforeach()
string(APPEND C "};\n}  // namespace\n\n")
string(APPEND C "const char* commandName(uint16_t id) noexcept { return id <= kCommandCount ? kNames[id] : \"Unknown\"; }\n\n")
string(APPEND C "namespace {\nconst uint16_t kReplies[] = {\n    0,\n")
foreach(_i RANGE 1 ${_count})
    set(_r "${_cmd_${_i}_reply}")
    if(_r STREQUAL "")
        string(APPEND C "    0,\n")
    else()
        string(APPEND C "    static_cast<uint16_t>(CommandId::${_r}),\n")
    endif()
endforeach()
string(APPEND C "};\n}  // namespace\n\n")
string(APPEND C "uint16_t replyOf(uint16_t id) noexcept { return id <= kCommandCount ? kReplies[id] : 0; }\n\n")
string(APPEND C "namespace cmd {\n\n")
foreach(_i RANGE 1 ${_count})
    set(_n "${_cmd_${_i}_name}")
    set(_nf ${_cmd_${_i}_nfields})
    if(_nf EQUAL 0)
        string(APPEND C "size_t encodedSize(const ${_n}&) noexcept { return 0; }\n")
        string(APPEND C "void encode(ipc::WireWriter&, const ${_n}&) noexcept {}\n")
        string(APPEND C "bool decode(ipc::WireReader&, ${_n}&) { return true; }\n")
        string(APPEND C "bool operator==(const ${_n}&, const ${_n}&) { return true; }\n\n")
        continue()
    endif()
    math(EXPR _last "${_nf} - 1")
    set(_size "")
    set(_enc "")
    set(_dec "")
    set(_eq "")
    foreach(_f RANGE 0 ${_last})
        set(_fn "${_cmd_${_i}_f${_f}_name}")
        list(APPEND _size "ipc::wireSize(c.${_fn})")
        string(APPEND _enc "    w.put(c.${_fn});\n")
        list(APPEND _dec "r.get(c.${_fn})")
        list(APPEND _eq "ipc::wireEqual(a.${_fn}, b.${_fn})")
    endforeach()
    list(JOIN _size " + " _size_s)
    list(JOIN _dec " && " _dec_s)
    list(JOIN _eq " && " _eq_s)
    string(APPEND C "size_t encodedSize(const ${_n}& c) noexcept { return ${_size_s}; }\n")
    string(APPEND C "void encode(ipc::WireWriter& w, const ${_n}& c) noexcept {\n${_enc}}\n")
    string(APPEND C "bool decode(ipc::WireReader& r, ${_n}& c) { return ${_dec_s}; }\n")
    string(APPEND C "bool operator==(const ${_n}& a, const ${_n}& b) { return ${_eq_s}; }\n\n")
endforeach()
string(APPEND C "}  // namespace cmd\n\n}  // namespace fuse::relight::bridge::schema\n")

# ---- commands_random.gen.hpp ---------------------------------------------------------------------
set(R "${_banner}// Fuzz support: randomize(rng, cmd) per command and withRandomCommand(index, rng, f). Rng needs\n")
string(APPEND R "// `uint64_t next()` and `uint32_t length()` (element count for counted fields).\n#pragma once\n\n")
string(APPEND R "#include <fuse/relight/bridge/schema/commands.gen.hpp>\n#include <fuse/relight/bridge/schema/random_fill.hpp>\n\n")
string(APPEND R "namespace fuse::relight::bridge::schema {\n\nnamespace cmd {\n\n")
foreach(_i RANGE 1 ${_count})
    set(_n "${_cmd_${_i}_name}")
    set(_nf ${_cmd_${_i}_nfields})
    if(_nf EQUAL 0)
        string(APPEND R "template <class Rng>\nvoid randomize(Rng&, ${_n}&) {}\n")
        continue()
    endif()
    string(APPEND R "template <class Rng>\nvoid randomize(Rng& rng, ${_n}& c) {\n")
    math(EXPR _last "${_nf} - 1")
    foreach(_f RANGE 0 ${_last})
        string(APPEND R "    randomFill(rng, c.${_cmd_${_i}_f${_f}_name});\n")
    endforeach()
    string(APPEND R "}\n")
endforeach()
string(APPEND R "\n}  // namespace cmd\n\n")
string(APPEND R "// Builds a random instance of the command with table index `index` (0-based, id = index + 1)\n// and calls f(const cmd::X&).\n")
string(APPEND R "template <class Rng, class F>\nvoid withRandomCommand(uint32_t index, Rng& rng, F&& f) {\n    switch (index) {\n")
foreach(_i RANGE 1 ${_count})
    math(EXPR _idx "${_i} - 1")
    set(_n "${_cmd_${_i}_name}")
    string(APPEND R "    case ${_idx}: {\n        cmd::${_n} c;\n        cmd::randomize(rng, c);\n        f(static_cast<const cmd::${_n}&>(c));\n        break;\n    }\n")
endforeach()
string(APPEND R "    default:\n        break;\n    }\n}\n\n}  // namespace fuse::relight::bridge::schema\n")

set(_inc "${OUT_DIR}/fuse/relight/bridge/schema")
file(MAKE_DIRECTORY "${_inc}")
file(WRITE "${_inc}/commands.gen.hpp" "${H}")
file(WRITE "${_inc}/commands_random.gen.hpp" "${R}")
file(WRITE "${OUT_DIR}/commands.gen.cpp" "${C}")
message(STATUS "FUSE Relight bridge schema: ${_count} commands, protocol ${_major}.${_minor}, hash 0x${_hash}")
