// FUSE Relight RL-5.6: the terrain bake on the GPU (see terrain_baker_gpu.hpp).
#include <fuse/relight/terrain/terrain_baker_gpu.hpp>

#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/device.hpp>

#include <algorithm>
#include <cstring>

#if defined(FUSE_VULKAN_BACKEND)
#include <vulkan/vulkan.h>

// Generated by terrain/embed_spirv.cmake: kRlTerrain{Slang,Glsl}Spv, FUSE_RL_TERRAIN_{SLANG,GLSL}.
#include "rl_terrain_spv.h"
#endif

namespace fuse::relight::terrain {

namespace rr = fuse::renderer;
namespace rg = fuse::renderer::rg;

namespace {
constexpr u32 kTile = 8u;
u64 align256(u64 v) { return (v + 255u) & ~u64{255u}; }
u32 storageUsage() {
    return static_cast<u32>(rr::BufferUsage::Storage) | static_cast<u32>(rr::BufferUsage::ShaderDeviceAddress) |
           static_cast<u32>(rr::BufferUsage::TransferSrc);
}
} // namespace

TerrainBakerGpu::TerrainBakerGpu() = default;
TerrainBakerGpu::~TerrainBakerGpu() { destroy(); }

bool TerrainBakerGpu::init(const TerrainBakerGpuDesc& desc) {
    destroy();
    m_desc = desc;
#if defined(FUSE_VULKAN_BACKEND)
    if (desc.device == nullptr || desc.allocator == nullptr || desc.bindless == nullptr || desc.maxLayers == 0u) {
        m_reason = "incomplete TerrainBakerGpuDesc";
        return false;
    }
    m_records.resize(desc.maxLayers + 1u);
    m_retired.reserve(8);
    m_initialized = true;
    if (!createPipeline()) {
        m_reason = "no terrain kernel of the requested language / pipeline creation failed";
        destroy();
        return false;
    }
    m_reason = "ok";
    return true;
#else
    m_reason = "stub backend";
    return false;
#endif
}

void TerrainBakerGpu::destroy() {
    if (!m_initialized) {
        return;
    }
#if defined(FUSE_VULKAN_BACKEND)
    collectRetired();
    if (m_input.handle != nullptr) {
        m_desc.allocator->destroyBuffer(m_input);
    }
    if (m_output.handle != nullptr) {
        m_desc.allocator->destroyBuffer(m_output);
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    if (m_pipeline != nullptr) {
        vkDestroyPipeline(device, static_cast<VkPipeline>(m_pipeline), nullptr);
    }
    if (m_layoutHandle != nullptr) {
        vkDestroyPipelineLayout(device, static_cast<VkPipelineLayout>(m_layoutHandle), nullptr);
    }
#endif
    m_input = rr::Buffer{};
    m_output = rr::Buffer{};
    m_pipeline = nullptr;
    m_layoutHandle = nullptr;
    m_prepared = false;
    m_hash = 0;
    m_language = "none";
    m_stats = TerrainBakerGpuStats{};
    m_initialized = false;
}

bool TerrainBakerGpu::createPipeline() {
#if defined(FUSE_VULKAN_BACKEND)
    const u32* words = nullptr;
    usize bytes = 0;
#if defined(FUSE_RL_TERRAIN_SLANG)
    if (m_desc.language == TerrainKernelLanguage::Auto || m_desc.language == TerrainKernelLanguage::Slang) {
        words = kRlTerrainSlangSpv;
        bytes = sizeof(kRlTerrainSlangSpv);
        m_language = "slang";
    }
#endif
#if defined(FUSE_RL_TERRAIN_GLSL)
    if (words == nullptr &&
        (m_desc.language == TerrainKernelLanguage::Auto || m_desc.language == TerrainKernelLanguage::Glsl)) {
        words = kRlTerrainGlslSpv;
        bytes = sizeof(kRlTerrainGlslSpv);
        m_language = "glsl";
    }
#endif
    if (words == nullptr) {
        return false;
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    VkDescriptorSetLayout setLayout = static_cast<VkDescriptorSetLayout>(m_desc.bindless->layoutHandle());
    VkPushConstantRange range{VK_SHADER_STAGE_COMPUTE_BIT, 0, static_cast<u32>(sizeof(Push))};
    VkPipelineLayoutCreateInfo layoutInfo{};
    layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutInfo.setLayoutCount = 1u;
    layoutInfo.pSetLayouts = &setLayout;
    layoutInfo.pushConstantRangeCount = 1;
    layoutInfo.pPushConstantRanges = &range;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    if (vkCreatePipelineLayout(device, &layoutInfo, nullptr, &layout) != VK_SUCCESS) {
        return false;
    }
    m_layoutHandle = layout;
    VkShaderModuleCreateInfo moduleInfo{};
    moduleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    moduleInfo.codeSize = bytes;
    moduleInfo.pCode = words;
    VkShaderModule module = VK_NULL_HANDLE;
    if (vkCreateShaderModule(device, &moduleInfo, nullptr, &module) != VK_SUCCESS) {
        return false;
    }
    VkComputePipelineCreateInfo info{};
    info.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    info.flags = static_cast<VkPipelineCreateFlags>(m_desc.bindless->pipelineCreateFlags());
    info.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    info.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    info.stage.module = module;
    info.stage.pName = "main";
    info.layout = layout;
    VkPipeline pipeline = VK_NULL_HANDLE;
    const VkResult result = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
    vkDestroyShaderModule(device, module, nullptr);
    m_pipeline = pipeline;
    return result == VK_SUCCESS;
#else
    return false;
#endif
}

bool TerrainBakerGpu::ensure(rr::Buffer& buffer, u64 bytes, u32 memory, const char* name, u8* queue) {
    if (buffer.handle != nullptr && bytes <= buffer.desc.size) {
        return true;
    }
    rr::BufferDesc d{};
    d.size = static_cast<usize>(align256(std::max<u64>(bytes + bytes / 2u, 4096u)));
    d.usage = static_cast<rr::BufferUsage>(storageUsage());
    d.memoryUsage = static_cast<rr::MemoryUsage>(memory);
    d.name = name;
    rr::Buffer fresh{};
    if (!m_desc.allocator->createBuffer(d, fresh) || fresh.mapped == nullptr || fresh.deviceAddress == 0u) {
        if (fresh.handle != nullptr) {
            m_desc.allocator->destroyBuffer(fresh);
        }
        return false;
    }
    if (buffer.handle != nullptr) {
        m_retired.push_back(buffer);
        ++m_stats.reallocations;
    }
    buffer = fresh;
    *queue = rg::kNoQueue;
    return true;
}

bool TerrainBakerGpu::prepare(const TerrainBakeDesc& desc, std::span<const TerrainLayer> layers, bool* rebake) {
    if (rebake != nullptr) {
        *rebake = false;
    }
    if (!m_initialized || desc.width == 0u || desc.height == 0u || !(desc.maxX > desc.minX) ||
        !(desc.maxZ > desc.minZ) || layers.size() > m_desc.maxLayers) {
        m_reason = "invalid bake / too many layers";
        return false;
    }
    const u64 hash = TerrainBaker::contentHash(desc, layers);
    if (m_prepared && hash == m_hash) {
        return true;
    }
    // Layout: layer records (4 words each), vertices (3 words: position, uv, colour), indices (u32), texels (float4).
    u64 vertices = 0, indices = 0, texels = 0;
    for (const TerrainLayer& L : layers) {
        vertices += L.vertexCount;
        indices += L.indexCount;
        if (L.texture != nullptr && L.texture->rgba != nullptr) {
            texels += u64(L.texture->width) * L.texture->height;
        }
    }
    m_offsets[0] = 0;
    m_offsets[1] = align256(u64(layers.size()) * 64u);
    m_offsets[2] = m_offsets[1] + align256(vertices * 48u);
    m_offsets[3] = m_offsets[2] + align256(indices * 4u);
    m_inputBytes = m_offsets[3] + align256(std::max<u64>(texels, 1u) * 16u);
    const u64 outBytes = u64(desc.width) * desc.height * 16u;
    if (!ensure(m_input, m_inputBytes, static_cast<u32>(rr::MemoryUsage::CpuToGpu), "relight.terrain.input",
                &m_inputQueue) ||
        !ensure(m_output, outBytes, static_cast<u32>(rr::MemoryUsage::GpuToCpu), "relight.terrain.output",
                &m_outputQueue)) {
        m_reason = "terrain buffers";
        return false;
    }
    u8* base = static_cast<u8*>(m_input.mapped);
    u32 vbase = 0, ibase = 0, tbase = 0;
    for (usize l = 0; l < layers.size(); ++l) {
        const TerrainLayer& L = layers[l];
        const bool hasTex = L.texture != nullptr && L.texture->rgba != nullptr && L.texture->width > 0u &&
                            L.texture->height > 0u;
        const u32 flags = (L.alphaTest ? 1u : 0u) | (L.uvs != nullptr ? 2u : 0u) | (L.colors != nullptr ? 4u : 0u) |
                          (hasTex ? 8u : 0u);
        const bool usable = L.positions != nullptr && L.indices != nullptr;
        const u32 w0[4] = {vbase, ibase, usable ? L.indexCount : 0u, L.vertexCount};
        const u32 w1[4] = {tbase, hasTex ? L.texture->width : 0u, hasTex ? L.texture->height : 0u,
                           flags | (static_cast<u32>(L.blend) << 8u)};
        const float w2[4] = {L.uvTransform[0], L.uvTransform[1], L.uvTransform[2], L.uvTransform[3]};
        const float w3[4] = {L.uvTransform[4], L.uvTransform[5], L.alphaReference, 0.f};
        u8* rec = base + m_offsets[0] + l * 64u;
        std::memcpy(rec, w0, 16u);
        std::memcpy(rec + 16u, w1, 16u);
        std::memcpy(rec + 32u, w2, 16u);
        std::memcpy(rec + 48u, w3, 16u);
        float* vtx = reinterpret_cast<float*>(base + m_offsets[1]) + usize(vbase) * 12u;
        for (u32 v = 0; usable && v < L.vertexCount; ++v) {
            float* o = vtx + usize(v) * 12u;
            o[0] = L.positions[v * 3u];
            o[1] = L.positions[v * 3u + 1u];
            o[2] = L.positions[v * 3u + 2u];
            o[3] = 0.f;
            o[4] = L.uvs != nullptr ? L.uvs[v * 2u] : 0.f;
            o[5] = L.uvs != nullptr ? L.uvs[v * 2u + 1u] : 0.f;
            o[6] = 0.f;
            o[7] = 0.f;
            for (u32 k = 0; k < 4u; ++k) {
                o[8u + k] = L.colors != nullptr ? L.colors[v * 4u + k] : 1.f;
            }
        }
        if (usable && L.indexCount > 0u) {
            std::memcpy(base + m_offsets[2] + u64(ibase) * 4u, L.indices, usize(L.indexCount) * 4u);
        }
        if (hasTex) {
            const u64 n = u64(L.texture->width) * L.texture->height;
            std::memcpy(base + m_offsets[3] + u64(tbase) * 16u, L.texture->rgba, usize(n) * 16u);
            tbase += static_cast<u32>(n);
        }
        vbase += L.vertexCount;
        ibase += L.indexCount;
    }
    m_bake = desc;
    m_layerCount = static_cast<u32>(layers.size());
    m_hash = hash;
    m_prepared = true;
    ++m_stats.uploads;
    if (rebake != nullptr) {
        *rebake = true;
    }
    return true;
}

bool TerrainBakerGpu::addPasses(rg::Graph& graph, rg::BufferRef* output) {
    if (!m_initialized || !m_prepared) {
        return false;
    }
    const rg::BufferRef in = graph.importBuffer(
        rg::ImportedBuffer{m_input.handle, m_input.desc.size, m_inputQueue, &m_inputQueue, "relight.terrain.input"});
    const rg::BufferRef out = graph.importBuffer(
        rg::ImportedBuffer{m_output.handle, m_output.desc.size, m_outputQueue, &m_outputQueue, "relight.terrain.output"});
    const u64 outBytes = u64(m_bake.width) * m_bake.height * 16u;
    Push base{};
    base.layers = m_input.deviceAddress + m_offsets[0];
    base.vertices = m_input.deviceAddress + m_offsets[1];
    base.indices = m_input.deviceAddress + m_offsets[2];
    base.texels = m_input.deviceAddress + m_offsets[3];
    base.outputs = m_output.deviceAddress;
    base.width = m_bake.width;
    base.height = m_bake.height;
    base.minX = m_bake.minX;
    base.minZ = m_bake.minZ;
    base.sx = float(m_bake.width) / (m_bake.maxX - m_bake.minX);
    base.sz = float(m_bake.height) / (m_bake.maxZ - m_bake.minZ);
    std::memcpy(base.clear, m_bake.clear, sizeof(base.clear));
    for (u32 p = 0; p <= m_layerCount; ++p) {
        PassRecord& r = m_records[p];
        r.self = this;
        r.push = base;
        r.push.stage = p == 0u ? 0u : 1u;
        r.push.layer = p == 0u ? 0u : p - 1u;
        rg::PassBuilder pass =
            graph.addPass(p == 0u ? "relight.terrain.clear" : "relight.terrain.layer", &TerrainBakerGpu::record, &r);
        if (p == 0u) {
            pass.use(out, rg::Access::StorageWrite, rg::BufferRange{0u, outBytes}, rg::kStageCompute);
        } else {
            pass.use(in, rg::Access::StorageRead, rg::BufferRange{0u, m_inputBytes}, rg::kStageCompute)
                .use(out, rg::Access::StorageReadWrite, rg::BufferRange{0u, outBytes}, rg::kStageCompute);
        }
    }
    if (output != nullptr) {
        *output = out;
    }
    ++m_stats.bakes;
    return true;
}

void TerrainBakerGpu::record(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const TerrainBakerGpu& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, static_cast<VkPipeline>(self.m_pipeline));
    self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, self.m_layoutHandle, 0);
    vkCmdPushConstants(cmd, static_cast<VkPipelineLayout>(self.m_layoutHandle), VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       static_cast<u32>(sizeof(Push)), &r.push);
    vkCmdDispatch(cmd, (r.push.width + kTile - 1u) / kTile, (r.push.height + kTile - 1u) / kTile, 1u);
#else
    (void)context;
    (void)user;
#endif
}

u32 TerrainBakerGpu::collectRetired() {
    const u32 n = static_cast<u32>(m_retired.size());
    for (rr::Buffer& b : m_retired) {
        if (b.handle != nullptr) {
            m_desc.allocator->destroyBuffer(b);
        }
    }
    m_retired.clear();
    return n;
}

const float* TerrainBakerGpu::mappedOutput() const { return static_cast<const float*>(m_output.mapped); }
u64 TerrainBakerGpu::outputAddress() const { return m_output.deviceAddress; }

} // namespace fuse::relight::terrain
