// WP-3.2 virtual shadow maps: see include/fuse/renderer/shadow/vsm_raster/vsm_shadows.hpp.
#include <fuse/renderer/shadow/vsm_raster/vsm_shadows.hpp>

#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/device.hpp>

#include <cmath>
#include <cstring>

#if defined(FUSE_VULKAN_BACKEND)
#include <vulkan/vulkan.h>

// Generated by cmake/rp_wp32.cmake from shaders/shadow_vsm/*: kVsmr<Kernel><Slang|Glsl>Spv and
// FUSE_VSMR_{SLANG,GLSL} when every kernel of a language exists.
#include "vsm_raster_spv.h"
#endif

namespace fuse::renderer::vsm {

namespace {
constexpr u32 kFrameStride = 2304u; ///< ring slot (>= sizeof(VsmShadowConstants), 256-aligned)
static_assert(sizeof(VsmShadowConstants) <= kFrameStride, "shadow ring slot");
constexpr u32 kAtlasFormat = 98u;   ///< VK_FORMAT_R32_UINT
constexpr u64 kHeaderBytes = kWordHeaderCount * 4u;
constexpr u64 kArgsBytes = 16u;     ///< words 0..3: the local dispatch args (+ one word of padding)
constexpr u32 kHeaderInit[kWordHeaderCount] = {0u, 1u, 1u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u};
constexpr f32 kMinSpotCos = 0.17364818f; ///< cos(80 degrees): widest spot frustum half angle

u32 groups(u32 items, u32 size) { return items == 0u ? 1u : (items + size - 1u) / size; }

void normalize3(f32 v[3]) {
    const f32 len = std::sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
    const f32 inv = len > 0.f ? 1.f / len : 0.f;
    v[0] *= inv;
    v[1] *= inv;
    v[2] *= inv;
}

void cross3(const f32 a[3], const f32 b[3], f32 out[3]) {
    out[0] = a[1] * b[2] - a[2] * b[1];
    out[1] = a[2] * b[0] - a[0] * b[2];
    out[2] = a[0] * b[1] - a[1] * b[0];
}

/// Fills a VsmLocalLight from its description (pages left alone); false when unusable.
bool buildLocal(const VsmLocalLightDesc& d, VsmLocalLight& e) {
    if (!(d.range > 0.f) || !std::isfinite(d.range) || (d.type != kLocalSpot && d.type != kLocalPoint)) {
        return false;
    }
    for (u32 k = 0; k < 3u; ++k) {
        if (!std::isfinite(d.position[k])) {
            return false;
        }
        e.position[k] = d.position[k];
    }
    e.slot = d.slot;
    e.range = d.range;
    e.invRange = 1.f / d.range;
    e.nearPlane = d.nearPlane > 1e-4f ? (d.nearPlane < d.range * 0.5f ? d.nearPlane : d.range * 0.5f) : 1e-4f;
    e.type = d.type;
    e.faces = d.type == kLocalPoint ? kCubeFaces : 1u;
    e.lightSize = d.lightSize > 0.f ? d.lightSize : 0.f;
    if (d.type == kLocalPoint) {
        e.invTanHalf = 1.f;
        const f32 f[3] = {0.f, 0.f, -1.f};
        const f32 r[3] = {1.f, 0.f, 0.f};
        const f32 u[3] = {0.f, 1.f, 0.f};
        std::memcpy(e.forward, f, sizeof(f));
        std::memcpy(e.right, r, sizeof(r));
        std::memcpy(e.up, u, sizeof(u));
        return true;
    }
    f32 f[3] = {d.direction[0], d.direction[1], d.direction[2]};
    normalize3(f);
    if (!(f[0] * f[0] + f[1] * f[1] + f[2] * f[2] > 0.5f)) {
        return false;
    }
    const f32 upRef[3] = {std::fabs(f[1]) > 0.99f ? 1.f : 0.f, std::fabs(f[1]) > 0.99f ? 0.f : 1.f, 0.f};
    f32 r[3];
    cross3(f, upRef, r);
    normalize3(r);
    f32 u[3];
    cross3(r, f, u);
    std::memcpy(e.forward, f, sizeof(f));
    std::memcpy(e.right, r, sizeof(r));
    std::memcpy(e.up, u, sizeof(u));
    const f32 c = d.cosOuter < kMinSpotCos ? kMinSpotCos : (d.cosOuter > 0.9999f ? 0.9999f : d.cosOuter);
    e.invTanHalf = c / std::sqrt(1.f - c * c);
    return true;
}

#if defined(FUSE_VULKAN_BACKEND)
struct Code {
    const u32* words = nullptr;
    usize bytes = 0;
};
template <usize N>
Code code(const u32 (&spv)[N]) {
    return Code{spv, sizeof(spv)};
}
#endif
} // namespace

bool makeLocalLight(u32 slot, const gpu_scene::GpuLight& light, VsmLocalLightDesc& out) {
    out = VsmLocalLightDesc{};
    if (!(light.range > 0.f)) {
        return false;
    }
    if (light.type == static_cast<u32>(gpu_scene::GpuLightType::Point)) {
        out.type = kLocalPoint;
    } else if (light.type == static_cast<u32>(gpu_scene::GpuLightType::Spot)) {
        out.type = kLocalSpot;
        std::memcpy(out.direction, light.direction, sizeof(out.direction));
        out.cosOuter = light.cosOuter;
    } else {
        return false;
    }
    out.slot = slot;
    std::memcpy(out.position, light.position, sizeof(out.position));
    out.range = light.range;
    return true;
}

VsmShadows::~VsmShadows() { destroy(); }

bool VsmShadows::init(const VsmShadowsDesc& desc) {
    destroy();
    m_desc = desc;
#if defined(FUSE_VULKAN_BACKEND)
    if (desc.allocator == nullptr || desc.bindless == nullptr || desc.framesInFlight == 0u || desc.localPagesX == 0u ||
        desc.localPagesY == 0u || desc.localPagesX > kMaxLocalPagesPerAxis || desc.localPagesY > kMaxLocalPagesPerAxis ||
        !queryVsmCapabilities(desc.device).vsm) {
        return false;
    }
    m_initialized = true; // destroy() releases partial state from here on
    BufferDesc ring{};
    ring.size = static_cast<usize>(desc.framesInFlight) * kFrameStride;
    ring.usage = static_cast<BufferUsage>(static_cast<u32>(BufferUsage::Storage) | static_cast<u32>(BufferUsage::ShaderDeviceAddress));
    ring.memoryUsage = MemoryUsage::CpuToGpu;
    ring.name = "vsm_shadows.frame";
    BufferDesc work{};
    work.size = static_cast<usize>(kRasterWorkWords) * 4u;
    work.usage = static_cast<BufferUsage>(static_cast<u32>(BufferUsage::Storage) | static_cast<u32>(BufferUsage::TransferDst) |
                                          static_cast<u32>(BufferUsage::TransferSrc) | static_cast<u32>(BufferUsage::Indirect) |
                                          static_cast<u32>(BufferUsage::ShaderDeviceAddress));
    work.memoryUsage = MemoryUsage::GpuOnly;
    work.name = "vsm_shadows.work";
    if (!m_desc.allocator->createBuffer(ring, m_frameRing) || m_frameRing.mapped == nullptr || m_frameRing.deviceAddress == 0u ||
        !m_desc.allocator->createBuffer(work, m_work.buffer) || m_work.buffer.deviceAddress == 0u || !createPipelines()) {
        destroy();
        return false;
    }
    m_work.slot = m_desc.bindless->registerBufferSlot(m_work.buffer, false);
    if (!m_work.slot.isValid()) {
        destroy();
        return false;
    }
    m_work.handle = m_desc.bindless->shaderHandle(m_work.slot);
    TextureDesc td{};
    td.width = desc.localPagesX * kLocalPageTexels;
    td.height = desc.localPagesY * kLocalPageTexels;
    td.format = static_cast<GpuFormat>(kAtlasFormat);
    td.usage = static_cast<ImageUsage>(static_cast<u32>(ImageUsage::Storage) | static_cast<u32>(ImageUsage::Sampled) |
                                       static_cast<u32>(ImageUsage::TransferSrc));
    td.name = "vsm_shadows.local";
    if (!m_desc.allocator->createImage(td, m_local.image)) {
        m_local = Image{};
        destroy();
        return false;
    }
    m_local.slot = m_desc.bindless->registerTextureSlot(m_local.image, true);
    if (!m_local.slot.isValid()) {
        destroy();
        return false;
    }
    m_local.handle = m_desc.bindless->shaderHandle(m_local.slot);
    m_hasPrev = false;
    m_prevLocalCount = 0;
    return true;
#else
    return false;
#endif
}

void VsmShadows::destroy() {
    if (!m_initialized) {
        return;
    }
#if defined(FUSE_VULKAN_BACKEND)
    if (m_local.slot.isValid()) {
        m_desc.bindless->unregisterSlot(m_local.slot);
    }
    if (m_local.image.image != nullptr) {
        m_desc.allocator->destroyImage(m_local.image);
    }
    if (m_work.slot.isValid()) {
        m_desc.bindless->unregisterSlot(m_work.slot);
    }
    if (m_work.buffer.handle != nullptr) {
        m_desc.allocator->destroyBuffer(m_work.buffer);
    }
    if (m_frameRing.handle != nullptr) {
        m_desc.allocator->destroyBuffer(m_frameRing);
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    for (void*& pipeline : m_pipelines) {
        if (pipeline != nullptr) {
            vkDestroyPipeline(device, static_cast<VkPipeline>(pipeline), nullptr);
            pipeline = nullptr;
        }
    }
    if (m_layoutHandle != nullptr) {
        vkDestroyPipelineLayout(device, static_cast<VkPipelineLayout>(m_layoutHandle), nullptr);
    }
#endif
    m_layoutHandle = nullptr;
    m_local = Image{};
    m_work = OwnedBuffer{};
    m_frameRing = Buffer{};
    m_frameAddress = 0;
    m_constants = VsmShadowConstants{};
    m_vsm = nullptr;
    m_recordCount = 0;
    m_hasPrev = false;
    m_prevLocalCount = 0;
    m_language = "none";
    m_stats = VsmShadowStats{};
    m_initialized = false;
}

bool VsmShadows::createPipelines() {
#if defined(FUSE_VULKAN_BACKEND)
    Code k[kKernelCount]{};
    bool found = false;
#if defined(FUSE_VSMR_SLANG)
    if (m_desc.language == VsmKernelLanguage::Auto || m_desc.language == VsmKernelLanguage::Slang) {
        k[kRaster] = code(kVsmrRasterSlangSpv);
        k[kLocalDirty] = code(kVsmrLocalDirtySlangSpv);
        k[kLocalList] = code(kVsmrLocalListSlangSpv);
        k[kLocalClear] = code(kVsmrLocalClearSlangSpv);
        k[kLocalRaster] = code(kVsmrLocalRasterSlangSpv);
        k[kProbe] = code(kVsmrProbeSlangSpv);
        m_language = "slang";
        found = true;
    }
#endif
#if defined(FUSE_VSMR_GLSL)
    if (!found && (m_desc.language == VsmKernelLanguage::Auto || m_desc.language == VsmKernelLanguage::Glsl)) {
        k[kRaster] = code(kVsmrRasterGlslSpv);
        k[kLocalDirty] = code(kVsmrLocalDirtyGlslSpv);
        k[kLocalList] = code(kVsmrLocalListGlslSpv);
        k[kLocalClear] = code(kVsmrLocalClearGlslSpv);
        k[kLocalRaster] = code(kVsmrLocalRasterGlslSpv);
        k[kProbe] = code(kVsmrProbeGlslSpv);
        m_language = "glsl";
        found = true;
    }
#endif
    if (!found) {
        return false;
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    VkDescriptorSetLayout setLayout = static_cast<VkDescriptorSetLayout>(m_desc.bindless->layoutHandle());
    VkPushConstantRange range{VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(VsmRasterPush)};
    VkPipelineLayoutCreateInfo layoutInfo{};
    layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutInfo.setLayoutCount = setLayout != VK_NULL_HANDLE ? 1u : 0u;
    layoutInfo.pSetLayouts = &setLayout;
    layoutInfo.pushConstantRangeCount = 1;
    layoutInfo.pPushConstantRanges = &range;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    if (vkCreatePipelineLayout(device, &layoutInfo, nullptr, &layout) != VK_SUCCESS) {
        return false;
    }
    m_layoutHandle = layout;
    const VkPipelineCreateFlags createFlags = static_cast<VkPipelineCreateFlags>(m_desc.bindless->pipelineCreateFlags());
    for (u32 i = 0; i < kKernelCount; ++i) {
        VkShaderModuleCreateInfo moduleInfo{};
        moduleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        moduleInfo.codeSize = k[i].bytes;
        moduleInfo.pCode = k[i].words;
        VkShaderModule module = VK_NULL_HANDLE;
        if (vkCreateShaderModule(device, &moduleInfo, nullptr, &module) != VK_SUCCESS) {
            return false;
        }
        VkComputePipelineCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
        info.flags = createFlags;
        info.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        info.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
        info.stage.module = module;
        info.stage.pName = "main";
        info.layout = layout;
        VkPipeline pipeline = VK_NULL_HANDLE;
        const VkResult result = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
        vkDestroyShaderModule(device, module, nullptr);
        m_pipelines[i] = pipeline;
        if (result != VK_SUCCESS) {
            return false;
        }
    }
    return true;
#else
    return false;
#endif
}

bool VsmShadows::beginFrame(u64 frameSerial, const VsmShadowFrameDesc& frame) {
    if (!m_initialized) {
        return false;
    }
    m_recordCount = 0;
    m_stats = VsmShadowStats{};
    m_vsm = frame.vsm != nullptr && frame.vsm->valid() && frame.vsm->frameConstantsAddress() != 0u ? frame.vsm : nullptr;
    VsmShadowConstants c{};
    c.vsm = m_vsm != nullptr ? m_vsm->frameConstantsAddress() : 0u;
    c.work = m_work.buffer.deviceAddress;
    c.directionalSlot = m_vsm != nullptr ? frame.directionalSlot : kNoSlot;
    c.filterMode = frame.filter.filter <= kFilterPcss ? frame.filter.filter : kFilterPcf;
    c.pcfRadius = frame.filter.pcfRadius < kMaxFilterRadius ? frame.filter.pcfRadius : kMaxFilterRadius;
    c.normalOffset = frame.filter.normalOffset;
    c.depthBias = frame.filter.depthBias;
    c.sunTanAngle = frame.filter.sunTanAngle;
    c.pcssMaxRadius = frame.filter.pcssMaxRadius < kMaxFilterRadius ? frame.filter.pcssMaxRadius : kMaxFilterRadius;
    c.localPool = m_local.handle;
    c.localPagesX = m_desc.localPagesX;
    c.scene = frame.scene;
    c.instanceCount = frame.instanceCount;
    c.workHandle = m_work.handle;
    c.localClear = kDepthClearBits;
    c.frame = static_cast<u32>(frameSerial);
    // Local lights: pages in list order; a light keeps its pages while its list position and
    // parameters stay; the host forces a re-render when anything about it changed.
    const u32 capacity = m_desc.localPagesX * m_desc.localPagesY;
    u32 cursor = 0;
    u32 count = 0;
    const u32 requested = frame.locals != nullptr ? frame.localCount : 0u;
    for (u32 i = 0; i < requested && count < kMaxLocalLights; ++i) {
        VsmLocalLight e{};
        if (!buildLocal(frame.locals[i], e) || cursor + e.faces > capacity) {
            ++m_stats.droppedLights;
            continue;
        }
        for (u32 f = 0; f < e.faces; ++f) {
            e.page[f] = cursor + f;
        }
        cursor += e.faces;
        c.local[count++] = e;
    }
    m_stats.droppedLights += requested > kMaxLocalLights ? requested - kMaxLocalLights : 0u;
    c.localCount = count;
    const bool forceAll = frame.forceLocal || m_vsm == nullptr || !m_hasPrev;
    for (u32 k = 0; k < count; ++k) {
        const bool changed = forceAll || k >= m_prevLocalCount || std::memcmp(&m_prevLocal[k], &c.local[k], sizeof(VsmLocalLight)) != 0;
        if (changed) {
            c.forceMask |= 1u << k;
            ++m_stats.forcedLights;
        }
        m_prevLocal[k] = c.local[k];
    }
    m_prevLocalCount = count;
    m_hasPrev = true;
    m_stats.localLights = count;
    m_stats.localPages = cursor;
    m_constants = c;
    const u64 offset = (frameSerial % m_desc.framesInFlight) * kFrameStride;
    std::memcpy(static_cast<u8*>(m_frameRing.mapped) + offset, &m_constants, sizeof(m_constants));
    m_frameAddress = m_frameRing.deviceAddress + offset;
    return true;
}

VsmShadowGraphRefs VsmShadows::importInto(rg::Graph& graph) {
    VsmShadowGraphRefs refs{};
    if (!m_initialized) {
        return refs;
    }
    refs.work = graph.importBuffer(
        rg::ImportedBuffer{m_work.buffer.handle, m_work.buffer.desc.size, m_work.queue, &m_work.queue, "vsm_shadows.work"});
    rg::ImportedImage i{};
    i.image = m_local.image.image;
    i.view = m_local.image.view;
    i.format = kAtlasFormat;
    i.width = m_desc.localPagesX * kLocalPageTexels;
    i.height = m_desc.localPagesY * kLocalPageTexels;
    i.initialLayout = m_local.layout;
    i.initialQueue = m_local.queue;
    i.layoutTracker = &m_local.layout;
    i.queueTracker = &m_local.queue;
    i.name = "vsm_shadows.local";
    refs.local = graph.importImage(i);
    return refs;
}

VsmShadows::PassRecord* VsmShadows::nextRecord(RecordKind kind, u32 kernel) {
    if (m_recordCount >= kMaxPasses) {
        return nullptr;
    }
    PassRecord* r = &m_records[m_recordCount++];
    *r = PassRecord{};
    r->self = this;
    r->kind = kind;
    r->kernel = kernel;
    r->push.shadow = m_frameAddress;
    ++m_stats.passes;
    return r;
}

void VsmShadows::addRaster(rg::Graph& graph, const VsmShadowGraphRefs& refs, const VsmGraphRefs* vsm,
                           const gpu_scene::GpuSceneGraphRefs& scene) {
    if (!m_initialized || !refs.work.valid() || m_recordCount + 6u > kMaxPasses) {
        return;
    }
    const u64 bytes = m_work.buffer.desc.size;
    {
        PassRecord* r = nextRecord(kReset, 0u);
        graph.addPass("vsm.raster_reset", &VsmShadows::recordPass, r).use(refs.work, rg::Access::TransferDst, rg::BufferRange{0, kHeaderBytes});
    }
    const bool directional = vsm != nullptr && m_vsm != nullptr && vsm->work.valid() && vsm->pool.valid();
    if (directional) {
        PassRecord* r = nextRecord(kDispatchIndirectVsm, kRaster);
        r->indirect = m_vsm->workBuffer().handle;
        r->indirectOffset = m_vsm->renderArgsOffset();
        rg::PassBuilder pass = graph.addPass("vsm.raster", &VsmShadows::recordPass, r);
        gpu_scene::GpuScene::useAll(pass, scene, rg::Access::StorageRead, rg::kStageCompute);
        pass.use(vsm->work, rg::Access::IndirectRead)
            .use(vsm->work, rg::Access::StorageRead, {}, rg::kStageCompute)
            .use(vsm->pool, rg::Access::StorageReadWrite, {}, rg::kStageCompute)
            .use(refs.work, rg::Access::StorageReadWrite, rg::BufferRange{0, kHeaderBytes}, rg::kStageCompute);
    }
    if (m_constants.localCount == 0u || !refs.local.valid()) {
        return;
    }
    if (directional && vsm->bounds.valid()) {
        PassRecord* r = nextRecord(kDispatch, kLocalDirty);
        r->groups[0] = groups(m_vsm->constants().instanceCount, kRasterThreads);
        graph.addPass("vsm.local_dirty", &VsmShadows::recordPass, r)
            .use(vsm->bounds, rg::Access::StorageRead, {}, rg::kStageCompute)
            .use(refs.work, rg::Access::StorageReadWrite, rg::BufferRange{0, kHeaderBytes}, rg::kStageCompute);
    }
    {
        PassRecord* r = nextRecord(kDispatch, kLocalList);
        graph.addPass("vsm.local_list", &VsmShadows::recordPass, r).use(refs.work, rg::Access::StorageReadWrite, {}, rg::kStageCompute);
    }
    {
        PassRecord* r = nextRecord(kDispatchIndirectLocal, kLocalClear);
        graph.addPass("vsm.local_clear", &VsmShadows::recordPass, r)
            .use(refs.work, rg::Access::IndirectRead, rg::BufferRange{0, kArgsBytes})
            .use(refs.work, rg::Access::StorageRead, rg::BufferRange{kHeaderBytes, bytes - kHeaderBytes}, rg::kStageCompute)
            .use(refs.local, rg::Access::StorageWrite, {}, rg::kStageCompute);
    }
    {
        PassRecord* r = nextRecord(kDispatchIndirectLocal, kLocalRaster);
        rg::PassBuilder pass = graph.addPass("vsm.local_raster", &VsmShadows::recordPass, r);
        gpu_scene::GpuScene::useAll(pass, scene, rg::Access::StorageRead, rg::kStageCompute);
        pass.use(refs.work, rg::Access::IndirectRead, rg::BufferRange{0, kArgsBytes})
            .use(refs.work, rg::Access::StorageReadWrite, rg::BufferRange{kArgsBytes, bytes - kArgsBytes}, rg::kStageCompute)
            .use(refs.local, rg::Access::StorageReadWrite, {}, rg::kStageCompute);
    }
}

void VsmShadows::declareSampling(rg::PassBuilder& pass, const VsmShadowGraphRefs& refs, const VsmGraphRefs* vsm, u8 stages) {
    if (vsm != nullptr && vsm->pool.valid()) {
        pass.use(vsm->pool, rg::Access::StorageRead, {}, stages);
    }
    if (vsm != nullptr && vsm->pageTable.valid()) {
        pass.use(vsm->pageTable, rg::Access::StorageRead, {}, stages);
    }
    if (refs.local.valid()) {
        pass.use(refs.local, rg::Access::StorageRead, {}, stages);
    }
}

void VsmShadows::addSamplingUse(rg::Graph& graph, const VsmShadowGraphRefs& refs, const VsmGraphRefs* vsm, u8 stages) {
    if (!m_initialized) {
        return;
    }
    rg::PassBuilder pass = graph.addPass("vsm.shadow_use", nullptr, nullptr);
    pass.neverCull();
    declareSampling(pass, refs, m_vsm != nullptr ? vsm : nullptr, stages);
}

void VsmShadows::addProbe(rg::Graph& graph, const VsmShadowGraphRefs& refs, const VsmGraphRefs* vsm, rg::BufferRef in, u64 inAddress,
                          rg::BufferRef out, u64 outAddress, u32 count) {
    if (!m_initialized || count == 0u || !in.valid() || !out.valid()) {
        return;
    }
    PassRecord* r = nextRecord(kDispatch, kProbe);
    if (r == nullptr) {
        return;
    }
    r->push.in = inAddress;
    r->push.out = outAddress;
    r->push.count = count;
    r->groups[0] = groups(count, kProbeGroup);
    rg::PassBuilder pass = graph.addPass("vsm.probe", &VsmShadows::recordPass, r);
    pass.use(in, rg::Access::StorageRead, rg::BufferRange{0, static_cast<u64>(count) * sizeof(VsmProbeInput)}, rg::kStageCompute)
        .use(out, rg::Access::StorageWrite, rg::BufferRange{0, static_cast<u64>(count) * sizeof(VsmProbeOutput)}, rg::kStageCompute);
    declareSampling(pass, refs, m_vsm != nullptr ? vsm : nullptr, rg::kStageCompute);
}

void VsmShadows::recordPass(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const VsmShadows& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    if (r.kind == kReset) {
        vkCmdUpdateBuffer(cmd, static_cast<VkBuffer>(self.m_work.buffer.handle), 0, sizeof(kHeaderInit), kHeaderInit);
        return;
    }
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, static_cast<VkPipeline>(self.m_pipelines[r.kernel]));
    self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, self.m_layoutHandle, 0);
    vkCmdPushConstants(cmd, static_cast<VkPipelineLayout>(self.m_layoutHandle), VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(VsmRasterPush),
                       &r.push);
    if (r.kind == kDispatchIndirectVsm) {
        vkCmdDispatchIndirect(cmd, static_cast<VkBuffer>(r.indirect), r.indirectOffset);
    } else if (r.kind == kDispatchIndirectLocal) {
        vkCmdDispatchIndirect(cmd, static_cast<VkBuffer>(self.m_work.buffer.handle), 0);
    } else {
        vkCmdDispatch(cmd, r.groups[0], r.groups[1], r.groups[2]);
    }
#else
    (void)context;
    (void)user;
#endif
}

} // namespace fuse::renderer::vsm
