#pragma once

#include <QIcon>
#include <QString>

#include <array>

class QApplication;

namespace fuse::editor::qt {

/// Pixel sizes of the FUSE application icon rasters embedded as Qt resources
/// (Source/FUSE/Branding/fuse_<N>.png, generated by gen_fuse_icons.py).
inline constexpr std::array<int, 4> kAppIconSizes{16, 32, 48, 256};

/// Resource path of one embedded icon raster, e.g. ":/fuse/branding/fuse_32.png".
QString appIconResource(int size);

/// The FUSE application icon (every embedded size).
QIcon applicationIcon();

/// Sets the application-wide window icon and the desktop-entry id ("fuse", matching the installed
/// fuse.desktop) so every editor window, the taskbar and Wayland compositors show the FUSE icon.
void applyApplicationIdentity(QApplication& app);

} // namespace fuse::editor::qt
