// WP-2.3 forward transparency: see include/fuse/renderer/forward/forward_transparency.hpp.
#include <fuse/renderer/forward/forward_transparency.hpp>

#include <fuse/renderer/lighting/gpu/clustered_gpu_types.hpp>
#include <fuse/renderer/visbuffer/vis_format.hpp>
#include <fuse/renderer/visbuffer/visbuffer.hpp>
#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/device.hpp>

#include <algorithm>
#include <cstring>
#include <initializer_list>

#if defined(FUSE_VULKAN_BACKEND)
#include <vulkan/vulkan.h>

// Generated by cmake/rp_wp23.cmake from shaders/forward/*: kFw<Kernel><Slang|Glsl>Spv and
// FUSE_FORWARD_{SLANG,GLSL} when every kernel of a language exists.
#include "forward_spv.h"
#endif

namespace fuse::renderer::forward {

namespace {
[[maybe_unused]] constexpr u32 kPushBytes = sizeof(ForwardPush);

[[maybe_unused]] u64 align256(u64 v) { return (v + 255u) & ~u64{255u}; }

[[maybe_unused]] BufferUsage bufferUsage(std::initializer_list<BufferUsage> bits) {
    u32 u = 0;
    for (const BufferUsage b : bits) {
        u |= static_cast<u32>(b);
    }
    return static_cast<BufferUsage>(u);
}

ImageUsage imageUsage(std::initializer_list<ImageUsage> bits) {
    u32 u = 0;
    for (const ImageUsage b : bits) {
        u |= static_cast<u32>(b);
    }
    return static_cast<ImageUsage>(u);
}

#if defined(FUSE_VULKAN_BACKEND)
struct Code {
    const u32* words = nullptr;
    usize bytes = 0;
};
template <usize N>
Code code(const u32 (&spv)[N]) {
    return Code{spv, sizeof(spv)};
}
#endif
} // namespace

ForwardCapabilities queryForwardCapabilities(const VulkanDevice* device) {
    ForwardCapabilities c{};
#if defined(FUSE_VULKAN_BACKEND)
    const visbuffer::VisCapabilities vis = visbuffer::queryVisCapabilities(device);
    if (!vis.raster) {
        c.reason = vis.rasterReason;
        return c;
    }
    const lighting_gpu::LightingCapabilities lighting = lighting_gpu::queryLightingCapabilities(device);
    if (!lighting.lighting) {
        c.reason = lighting.reason;
        return c;
    }
    VkFormatProperties props{};
    vkGetPhysicalDeviceFormatProperties(static_cast<VkPhysicalDevice>(device->nativePhysicalDevice()),
                                        static_cast<VkFormat>(kForwardColorFormat), &props);
    const VkFormatFeatureFlags need = VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT | VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT |
                                      VK_FORMAT_FEATURE_TRANSFER_DST_BIT;
    if ((props.optimalTilingFeatures & need) != need) {
        c.reason = "RGBA16F blended colour attachments unsupported";
        return c;
    }
    c.forward = true;
    c.reason = "ok";
#else
    (void)device;
    c.reason = "stub backend";
#endif
    return c;
}

ForwardTransparency::~ForwardTransparency() { destroy(); }

bool ForwardTransparency::init(const ForwardTransparencyDesc& desc) {
    destroy();
    m_desc = desc;
#if defined(FUSE_VULKAN_BACKEND)
    if (desc.allocator == nullptr || desc.bindless == nullptr || desc.framesInFlight == 0u || desc.maxDraws == 0u) {
        return false;
    }
    if (!queryForwardCapabilities(desc.device).forward) {
        return false;
    }
    m_initialized = true; // destroy() releases partial state from here on
    m_retired.reserve(4);
    m_opacity.resize(desc.instanceCapacity);
    m_sorted.resize(desc.maxDraws);
    m_cpuDraws.resize(desc.maxDraws);
    m_slotStride = align256(sizeof(ForwardFrameConstants) + static_cast<u64>(desc.maxDraws) * sizeof(ForwardDraw));
    BufferDesc ring{};
    ring.size = static_cast<usize>(desc.framesInFlight * m_slotStride);
    ring.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress});
    ring.memoryUsage = MemoryUsage::CpuToGpu;
    ring.name = "forward_transparency.frame";
    if (!m_desc.allocator->createBuffer(ring, m_frameRing) || m_frameRing.mapped == nullptr ||
        m_frameRing.deviceAddress == 0u || !createPipeline() ||
        (desc.width > 0u && desc.height > 0u && !createTarget(m_color, desc.width, desc.height))) {
        destroy();
        return false;
    }
    if (desc.width > 0u && desc.height > 0u) {
        m_width = desc.width;
        m_height = desc.height;
        m_stats.targetRebuilds = 1u;
    }
    return true;
#else
    return false;
#endif
}

void ForwardTransparency::destroy() {
    if (!m_initialized) {
        return;
    }
#if defined(FUSE_VULKAN_BACKEND)
    collectRetired(~0ull);
    if (m_color.image.image != nullptr) {
        m_desc.allocator->destroyImage(m_color.image);
    }
    if (m_frameRing.handle != nullptr) {
        m_desc.allocator->destroyBuffer(m_frameRing);
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    if (m_pipeline != nullptr) {
        vkDestroyPipeline(device, static_cast<VkPipeline>(m_pipeline), nullptr);
    }
    if (m_layoutHandle != nullptr) {
        vkDestroyPipelineLayout(device, static_cast<VkPipelineLayout>(m_layoutHandle), nullptr);
    }
#endif
    m_pipeline = nullptr;
    m_layoutHandle = nullptr;
    m_color = Target{};
    m_frameRing = Buffer{};
    m_frameAddress = 0;
    m_dumpAddress = 0;
    m_slotStride = 0;
    m_retired.clear();
    m_opacity.clear();
    m_sorted.clear();
    m_cpuDraws.clear();
    m_drawCount = 0;
    m_width = m_height = 0;
    m_recordCount = 0;
    m_language = "none";
    m_stats = ForwardStats{};
    m_initialized = false;
}

bool ForwardTransparency::createPipeline() {
#if defined(FUSE_VULKAN_BACKEND)
    Code vsCode{};
    Code fsCode{};
    bool found = false;
#if defined(FUSE_FORWARD_SLANG)
    if (m_desc.language == ForwardKernelLanguage::Auto || m_desc.language == ForwardKernelLanguage::Slang) {
        vsCode = code(kFwVsSlangSpv);
        fsCode = code(kFwFsSlangSpv);
        m_language = "slang";
        found = true;
    }
#endif
#if defined(FUSE_FORWARD_GLSL)
    if (!found && (m_desc.language == ForwardKernelLanguage::Auto || m_desc.language == ForwardKernelLanguage::Glsl)) {
        vsCode = code(kFwVsGlslSpv);
        fsCode = code(kFwFsGlslSpv);
        m_language = "glsl";
        found = true;
    }
#endif
    if (!found) {
        return false;
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    VkDescriptorSetLayout setLayout = static_cast<VkDescriptorSetLayout>(m_desc.bindless->layoutHandle());
    VkPushConstantRange range{VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0, kPushBytes};
    VkPipelineLayoutCreateInfo layoutInfo{};
    layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutInfo.setLayoutCount = setLayout != VK_NULL_HANDLE ? 1u : 0u;
    layoutInfo.pSetLayouts = &setLayout;
    layoutInfo.pushConstantRangeCount = 1;
    layoutInfo.pPushConstantRanges = &range;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    if (vkCreatePipelineLayout(device, &layoutInfo, nullptr, &layout) != VK_SUCCESS) {
        return false;
    }
    m_layoutHandle = layout;
    auto module = [&](const Code& c) {
        VkShaderModuleCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        info.codeSize = c.bytes;
        info.pCode = c.words;
        VkShaderModule m = VK_NULL_HANDLE;
        vkCreateShaderModule(device, &info, nullptr, &m);
        return m;
    };
    VkShaderModule vs = module(vsCode);
    VkShaderModule fs = module(fsCode);
    if (vs == VK_NULL_HANDLE || fs == VK_NULL_HANDLE) {
        vkDestroyShaderModule(device, vs, nullptr);
        vkDestroyShaderModule(device, fs, nullptr);
        return false;
    }
    VkPipelineShaderStageCreateInfo stages[2]{};
    stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vs;
    stages[0].pName = "main";
    stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = fs;
    stages[1].pName = "main";
    VkPipelineVertexInputStateCreateInfo vertexInput{};
    vertexInput.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
    VkPipelineInputAssemblyStateCreateInfo assembly{};
    assembly.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    assembly.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
    VkPipelineViewportStateCreateInfo viewport{};
    viewport.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    viewport.viewportCount = 1;
    viewport.scissorCount = 1;
    VkPipelineRasterizationStateCreateInfo rasterization{};
    rasterization.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    rasterization.polygonMode = VK_POLYGON_MODE_FILL;
    rasterization.cullMode = m_desc.cull == ForwardCullMode::Back
                                 ? VK_CULL_MODE_BACK_BIT
                                 : (m_desc.cull == ForwardCullMode::Front ? VK_CULL_MODE_FRONT_BIT : VK_CULL_MODE_NONE);
    rasterization.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE; // dynamic (per draw)
    rasterization.lineWidth = 1.f;
    VkPipelineMultisampleStateCreateInfo multisample{};
    multisample.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    multisample.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;
    // Test against the opaque depth (the visibility buffer's LESS convention), never write it.
    VkPipelineDepthStencilStateCreateInfo depth{};
    depth.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
    depth.depthTestEnable = VK_TRUE;
    depth.depthWriteEnable = VK_FALSE;
    depth.depthCompareOp = VK_COMPARE_OP_LESS;
    // Premultiplied over: src = (radiance * a, a); colour and alpha ONE / ONE_MINUS_SRC_ALPHA.
    VkPipelineColorBlendAttachmentState blendAttachment{};
    blendAttachment.blendEnable = VK_TRUE;
    blendAttachment.srcColorBlendFactor = VK_BLEND_FACTOR_ONE;
    blendAttachment.dstColorBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
    blendAttachment.colorBlendOp = VK_BLEND_OP_ADD;
    blendAttachment.srcAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
    blendAttachment.dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
    blendAttachment.alphaBlendOp = VK_BLEND_OP_ADD;
    blendAttachment.colorWriteMask =
        VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
    VkPipelineColorBlendStateCreateInfo blend{};
    blend.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    blend.attachmentCount = 1;
    blend.pAttachments = &blendAttachment;
    const VkDynamicState dynamics[3] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR, VK_DYNAMIC_STATE_FRONT_FACE};
    VkPipelineDynamicStateCreateInfo dynamic{};
    dynamic.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    dynamic.dynamicStateCount = 3;
    dynamic.pDynamicStates = dynamics;
    const VkFormat colorFormat = static_cast<VkFormat>(kForwardColorFormat);
    VkPipelineRenderingCreateInfo rendering{};
    rendering.sType = VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO;
    rendering.colorAttachmentCount = 1;
    rendering.pColorAttachmentFormats = &colorFormat;
    rendering.depthAttachmentFormat = static_cast<VkFormat>(visbuffer::kVisDepthFormat);
    VkGraphicsPipelineCreateInfo info{};
    info.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    info.pNext = &rendering;
    info.flags = static_cast<VkPipelineCreateFlags>(m_desc.bindless->pipelineCreateFlags());
    info.stageCount = 2;
    info.pStages = stages;
    info.pVertexInputState = &vertexInput;
    info.pInputAssemblyState = &assembly;
    info.pViewportState = &viewport;
    info.pRasterizationState = &rasterization;
    info.pMultisampleState = &multisample;
    info.pDepthStencilState = &depth;
    info.pColorBlendState = &blend;
    info.pDynamicState = &dynamic;
    info.layout = layout;
    VkPipeline pipeline = VK_NULL_HANDLE;
    const VkResult result = vkCreateGraphicsPipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
    vkDestroyShaderModule(device, vs, nullptr);
    vkDestroyShaderModule(device, fs, nullptr);
    m_pipeline = pipeline;
    return result == VK_SUCCESS;
#else
    return false;
#endif
}

bool ForwardTransparency::createTarget(Target& t, u32 width, u32 height) {
    t = Target{};
    TextureDesc d{};
    d.width = width;
    d.height = height;
    d.format = static_cast<GpuFormat>(kForwardColorFormat);
    d.usage = imageUsage({ImageUsage::ColorAttachment, ImageUsage::TransferDst, ImageUsage::TransferSrc, ImageUsage::Sampled});
    d.name = "forward_transparency.color";
    if (!m_desc.allocator->createImage(d, t.image)) {
        t = Target{};
        return false;
    }
    return true;
}

u32 ForwardTransparency::collectRetired(u64 completedSerial) {
    u32 collected = 0;
    usize keep = 0;
    for (usize i = 0; i < m_retired.size(); ++i) {
        if (m_retired[i].serial > completedSerial) {
            m_retired[keep++] = m_retired[i];
            continue;
        }
        if (m_retired[i].image.image != nullptr) {
            m_desc.allocator->destroyImage(m_retired[i].image);
        }
        ++collected;
    }
    m_retired.resize(keep);
    m_stats.retired = m_stats.retired >= collected ? m_stats.retired - collected : 0u;
    return collected;
}

bool ForwardTransparency::setOpacity(gpu_scene::InstanceHandle handle, f32 opacity) {
    if (!m_initialized || !handle.valid()) {
        return false;
    }
    if (handle.slot >= m_opacity.size()) {
        m_opacity.resize(std::max<usize>(static_cast<usize>(handle.slot) + 1u, m_opacity.size() * 2u));
    }
    OpacityEntry& e = m_opacity[handle.slot];
    e.generation = handle.generation;
    e.opacity = opacity;
    e.set = true;
    return true;
}

void ForwardTransparency::clearOpacity(gpu_scene::InstanceHandle handle) {
    if (handle.valid() && handle.slot < m_opacity.size() && m_opacity[handle.slot].generation == handle.generation) {
        m_opacity[handle.slot] = OpacityEntry{};
    }
}

bool ForwardTransparency::beginFrame(u64 frameSerial, const ForwardFrameDesc& frame) {
    if (!m_initialized || frame.scene == nullptr || frame.lighting == nullptr || !frame.lighting->valid()) {
        return false;
    }
    m_frameSerial = frameSerial;
    m_recordCount = 0;
    m_stats.passes = 0;
    m_drawCount = 0;
    const u32 w = frame.lighting->width();
    const u32 h = frame.lighting->height();
    if (w == 0u || h == 0u || frame.lighting->frameConstantsAddress() == 0u) {
        return false;
    }
    if (w != m_width || h != m_height || m_color.image.image == nullptr) {
        Target fresh{};
        if (!createTarget(fresh, w, h)) {
            return false;
        }
        if (m_color.image.image != nullptr) {
            m_retired.push_back(Retired{m_color.image, m_frameSerial});
            ++m_stats.retired;
        }
        m_color = fresh;
        m_width = w;
        m_height = h;
        ++m_stats.targetRebuilds;
    }

    // The transparent set, back to front (forward_reference.hpp).
    const gpu_scene::GpuScene& scene = *frame.scene;
    const gpu_scene::TableBytes instances = scene.tableBytes(gpu_scene::GpuSceneTable::Instances);
    const gpu_scene::TableBytes transforms = scene.tableBytes(gpu_scene::GpuSceneTable::Transforms);
    const gpu_scene::TableBytes meshes = scene.tableBytes(gpu_scene::GpuSceneTable::Meshes);
    CollectParams p{};
    p.instances = reinterpret_cast<const gpu_scene::GpuInstance*>(instances.data);
    p.transforms = reinterpret_cast<const gpu_scene::GpuTransform*>(transforms.data);
    p.instanceCount = std::min(instances.count, transforms.count);
    p.meshes = reinterpret_cast<const gpu_scene::GpuMesh*>(meshes.data);
    p.meshCount = meshes.count;
    p.viewProj = frame.viewProj;
    p.opacity = m_opacity.data();
    p.opacityCount = static_cast<u32>(m_opacity.size());
    p.frustumCull = m_desc.frustumCull;
    const CollectResult r = collect_transparent(p, m_sorted.data(), m_desc.maxDraws);
    m_drawCount = r.count;
    m_stats.draws = r.count;
    m_stats.candidates = r.candidates;
    m_stats.culled = r.culled;
    m_stats.dropped = r.dropped;

    const u64 offset = (frameSerial % m_desc.framesInFlight) * m_slotStride;
    u8* slot = static_cast<u8*>(m_frameRing.mapped) + offset;
    ForwardDraw* draws = reinterpret_cast<ForwardDraw*>(slot + sizeof(ForwardFrameConstants));
    for (u32 i = 0; i < m_drawCount; ++i) {
        const SortedDraw& s = m_sorted[i];
        ForwardDraw d{};
        d.slot = s.slot;
        d.opacity = s.opacity;
        std::memcpy(&draws[i], &d, sizeof(d));
        const gpu_scene::GpuMesh& mesh = p.meshes[s.mesh];
        CpuDraw& c = m_cpuDraws[i];
        c.indexCount = mesh.indexCount;
        c.firstIndex = mesh.firstIndex;
        c.vertexOffset = mesh.vertexOffset;
        c.mirrored = s.mirrored;
    }
    ForwardFrameConstants c{};
    std::memcpy(c.viewProj, frame.viewProj, sizeof(c.viewProj));
    c.lighting = frame.lighting->frameConstantsAddress();
    c.draws = m_frameRing.deviceAddress + offset + sizeof(ForwardFrameConstants);
    c.dump = frame.dumpAddress;
    c.scene = scene.headerHandle();
    c.sampler = frame.sampler;
    c.width = m_width;
    c.height = m_height;
    c.drawCount = m_drawCount;
    c.flags = 0u;
    if (frame.atmosphereAddress != 0u) {
        c.flags |= kForwardFlagAerial;
        c.atmosphere = frame.atmosphereAddress;
    }
    if (frame.fogAddress != 0u) {
        c.flags |= kForwardFlagFog;
        c.fog = frame.fogAddress;
    }
    std::memcpy(slot, &c, sizeof(c));
    m_frameAddress = m_frameRing.deviceAddress + offset;
    m_dumpAddress = frame.dumpAddress;
    return true;
}

ForwardGraphRefs ForwardTransparency::importInto(rg::Graph& graph) {
    ForwardGraphRefs refs{};
    if (!m_initialized || m_color.image.image == nullptr) {
        return refs;
    }
    rg::ImportedImage i{};
    i.image = m_color.image.image;
    i.view = m_color.image.view;
    i.format = kForwardColorFormat;
    i.width = m_width;
    i.height = m_height;
    i.initialLayout = m_color.layout;
    i.initialQueue = m_color.queue;
    i.layoutTracker = &m_color.layout;
    i.queueTracker = &m_color.queue;
    i.name = "forward_transparency.color";
    refs.color = graph.importImage(i);
    return refs;
}

void ForwardTransparency::addForward(rg::Graph& graph, const ForwardGraphRefs& refs, const gpu_scene::GpuSceneGraphRefs& scene,
                                     const lighting_gpu::LightingGraphRefs& lightingRefs, rg::TextureRef depth,
                                     rg::BufferRef dump) {
    if (!m_initialized || !refs.color.valid() || !lightingRefs.output.valid() || !lightingRefs.lists.valid() ||
        !depth.valid() || m_recordCount >= kMaxPasses) {
        return;
    }
    CopyRecord& copy = m_copies[m_recordCount];
    copy = CopyRecord{lightingRefs.output, refs.color, m_width, m_height};
    graph.addPass("forward.copy", &ForwardTransparency::recordCopy, &copy)
        .use(lightingRefs.output, rg::Access::TransferSrc)
        .use(refs.color, rg::Access::TransferDst);

    DrawRecord& r = m_records[m_recordCount++];
    r = DrawRecord{};
    r.self = this;
    r.push.frame = m_frameAddress;
    r.color = refs.color;
    r.depth = depth;
    r.indices = scene.indices;
    rg::PassBuilder pass = graph.addPass("forward.draw", &ForwardTransparency::recordDraw, &r);
    gpu_scene::GpuScene::useAll(pass, scene, rg::Access::StorageRead, rg::kStageVertex | rg::kStageFragment);
    if (scene.indices.valid()) {
        pass.use(scene.indices, rg::Access::IndexRead);
    }
    pass.use(lightingRefs.lists, rg::Access::StorageRead, {}, rg::kStageFragment)
        .use(depth, rg::Access::DepthAttachmentRead)
        .use(refs.color, rg::Access::ColorAttachmentWrite);
    if (refs.atmosphere.valid()) {
        pass.use(refs.atmosphere, rg::Access::StorageRead, {}, rg::kStageFragment); // aerial-perspective LUTs
    }
    if (refs.fog.valid()) {
        pass.use(refs.fog, rg::Access::StorageRead, {}, rg::kStageFragment); // the integrated fog volume
    }
    if (dump.valid() && m_dumpAddress != 0u && m_drawCount > 0u) {
        pass.use(dump, rg::Access::StorageWrite,
                 rg::BufferRange{0, static_cast<u64>(m_drawCount) * m_width * m_height * sizeof(ForwardDumpTexel)},
                 rg::kStageFragment);
    }
    ++m_stats.passes;
}

void ForwardTransparency::recordCopy(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const CopyRecord& c = *static_cast<const CopyRecord*>(user);
    VkImageCopy region{};
    region.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    region.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    region.extent = {c.width, c.height, 1};
    vkCmdCopyImage(static_cast<VkCommandBuffer>(context.commandBuffer), static_cast<VkImage>(context.image(c.src)),
                   VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, static_cast<VkImage>(context.image(c.dst)),
                   VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);
#else
    (void)context;
    (void)user;
#endif
}

void ForwardTransparency::recordDraw(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const DrawRecord& r = *static_cast<const DrawRecord*>(user);
    const ForwardTransparency& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    VkRenderingAttachmentInfo color{};
    color.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO;
    color.imageView = static_cast<VkImageView>(context.imageView(r.color));
    color.imageLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    color.loadOp = VK_ATTACHMENT_LOAD_OP_LOAD;
    color.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
    VkRenderingAttachmentInfo depth{};
    depth.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO;
    depth.imageView = static_cast<VkImageView>(context.imageView(r.depth));
    depth.imageLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL;
    depth.loadOp = VK_ATTACHMENT_LOAD_OP_LOAD;
    depth.storeOp = VK_ATTACHMENT_STORE_OP_NONE;
    VkRenderingInfo rendering{};
    rendering.sType = VK_STRUCTURE_TYPE_RENDERING_INFO;
    rendering.renderArea.extent = {self.m_width, self.m_height};
    rendering.layerCount = 1;
    rendering.colorAttachmentCount = 1;
    rendering.pColorAttachments = &color;
    rendering.pDepthAttachment = &depth;
    vkCmdBeginRendering(cmd, &rendering);
    if (r.indices.valid() && self.m_drawCount > 0u) {
        const VkPipelineLayout layout = static_cast<VkPipelineLayout>(self.m_layoutHandle);
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, static_cast<VkPipeline>(self.m_pipeline));
        self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, self.m_layoutHandle, 0);
        const VkViewport viewport{0.f, 0.f, static_cast<f32>(self.m_width), static_cast<f32>(self.m_height), 0.f, 1.f};
        const VkRect2D scissor{{0, 0}, {self.m_width, self.m_height}};
        vkCmdSetViewport(cmd, 0, 1, &viewport);
        vkCmdSetScissor(cmd, 0, 1, &scissor);
        vkCmdBindIndexBuffer(cmd, static_cast<VkBuffer>(context.buffer(r.indices)), 0, VK_INDEX_TYPE_UINT32);
        vkCmdPushConstants(cmd, layout, VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0, kPushBytes, &r.push);
        const VkFrontFace base = self.m_desc.frontFaceCounterClockwise ? VK_FRONT_FACE_COUNTER_CLOCKWISE : VK_FRONT_FACE_CLOCKWISE;
        const VkFrontFace flipped = base == VK_FRONT_FACE_COUNTER_CLOCKWISE ? VK_FRONT_FACE_CLOCKWISE : VK_FRONT_FACE_COUNTER_CLOCKWISE;
        VkFrontFace current = VK_FRONT_FACE_MAX_ENUM;
        for (u32 i = 0; i < self.m_drawCount; ++i) {
            const CpuDraw& d = self.m_cpuDraws[i];
            const VkFrontFace face = d.mirrored ? flipped : base;
            if (face != current) {
                vkCmdSetFrontFace(cmd, face);
                current = face;
            }
            vkCmdDrawIndexed(cmd, d.indexCount, 1, d.firstIndex, d.vertexOffset, i);
        }
    }
    vkCmdEndRendering(cmd);
#else
    (void)context;
    (void)user;
#endif
}

} // namespace fuse::renderer::forward
