// FUSE Relight RL-6.1: the developer overlay's GPU pass (see overlay_gpu.hpp).
#include <fuse/relight/overlay/overlay_gpu.hpp>

#include <fuse/renderer/rg/graph.hpp>

// Last: <vulkan/vulkan.h> (volk shim; brings <windows.h> into PE builds) without the DrawState macro.
#include <fuse/relight/render/frame/vk_dispatch.hpp>

#include "overlay_spv.h" // generated by overlay/CMakeLists.txt

#include <algorithm>
#include <cstring>

namespace fuse::relight::overlay {

namespace rf = fuse::relight::render::frame;
namespace rg = fuse::renderer::rg;
using rf::vkHandle;
using rf::vkValue;

namespace {

constexpr std::uint32_t kLayoutGeneral = VK_IMAGE_LAYOUT_GENERAL;
constexpr std::uint32_t kRegionFormat = VK_FORMAT_R32_UINT;

void passTrampoline(const rg::PassContext& context, void* user) {
    static_cast<OverlayGpu*>(user)->record(context.passIndex,
                                           vkValue(static_cast<VkCommandBuffer>(context.commandBuffer)));
}

} // namespace

struct OverlayGpu::Impl {
    struct Slot {
        VkBuffer buffer = VK_NULL_HANDLE;
        VkDeviceMemory memory = VK_NULL_HANDLE;
        void* mapped = nullptr;
        VkDeviceSize size = 0;
        VkDescriptorSet set = VK_NULL_HANDLE;
        std::uint64_t serial = 0;
    };
    VkDevice device = VK_NULL_HANDLE;
    VkPhysicalDevice physicalDevice = VK_NULL_HANDLE;
    VkShaderModule module = VK_NULL_HANDLE;
    VkDescriptorSetLayout setLayout = VK_NULL_HANDLE;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    VkPipeline pipeline = VK_NULL_HANDLE;
    VkDescriptorPool pool = VK_NULL_HANDLE;
    VkSampler sampler = VK_NULL_HANDLE;
    VkImageView regionView = VK_NULL_HANDLE;
    VkImageView dummyView = VK_NULL_HANDLE;
    Slot slots[kSlots];
    std::uint32_t current = 0;
    // Debug view source.
    bool debugActive = false;
    rf::DebugImage debug;
    VkImageView debugView = VK_NULL_HANDLE;
    std::uint64_t debugViewImage = 0;
    std::uint32_t debugViewFormat = 0, debugViewAspect = 0;
    std::uint64_t debugViewSerial = 0;
    // Graph of the current frame.
    std::uint32_t passCopyIn = UINT32_MAX, passCompose = UINT32_MAX, passCopyOut = UINT32_MAX;
    std::uint32_t resRegion = 0, resDebug = 0, resBuffer = 0;
    std::uint32_t frameW = 0, frameH = 0, frameFormat = 0;

    std::uint32_t memoryType(std::uint32_t bits, VkMemoryPropertyFlags flags) const {
        VkPhysicalDeviceMemoryProperties p{};
        vkGetPhysicalDeviceMemoryProperties(physicalDevice, &p);
        for (std::uint32_t i = 0; i < p.memoryTypeCount; ++i) {
            if ((bits & (1u << i)) && (p.memoryTypes[i].propertyFlags & flags) == flags) {
                return i;
            }
        }
        return UINT32_MAX;
    }
    VkImageView makeView(std::uint64_t image, std::uint32_t format, std::uint32_t aspect) const {
        VkImageViewCreateInfo ci{};
        ci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
        ci.image = vkHandle<VkImage>(image);
        ci.viewType = VK_IMAGE_VIEW_TYPE_2D;
        ci.format = static_cast<VkFormat>(format);
        ci.subresourceRange = {aspect, 0, 1, 0, 1};
        VkImageView view = VK_NULL_HANDLE;
        vkCreateImageView(device, &ci, nullptr, &view);
        return view;
    }
    void destroySlotBuffer(Slot& s) {
        if (s.buffer != VK_NULL_HANDLE) {
            vkDestroyBuffer(device, s.buffer, nullptr);
        }
        if (s.memory != VK_NULL_HANDLE) {
            vkUnmapMemory(device, s.memory);
            vkFreeMemory(device, s.memory, nullptr);
        }
        s.buffer = VK_NULL_HANDLE;
        s.memory = VK_NULL_HANDLE;
        s.mapped = nullptr;
        s.size = 0;
    }
    bool ensureSlotBuffer(Slot& s, VkDeviceSize size) {
        if (s.buffer != VK_NULL_HANDLE && s.size >= size) {
            return true;
        }
        destroySlotBuffer(s);
        size = std::max<VkDeviceSize>(size, 64 * 1024); // grows rarely: panels are at most ~400 x 300 per scale step
        VkBufferCreateInfo bi{};
        bi.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
        bi.size = size;
        bi.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
        if (vkCreateBuffer(device, &bi, nullptr, &s.buffer) != VK_SUCCESS) {
            return false;
        }
        VkMemoryRequirements req{};
        vkGetBufferMemoryRequirements(device, s.buffer, &req);
        VkMemoryAllocateInfo mi{};
        mi.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
        mi.allocationSize = req.size;
        mi.memoryTypeIndex =
            memoryType(req.memoryTypeBits, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
        if (mi.memoryTypeIndex == UINT32_MAX || vkAllocateMemory(device, &mi, nullptr, &s.memory) != VK_SUCCESS ||
            vkBindBufferMemory(device, s.buffer, s.memory, 0) != VK_SUCCESS ||
            vkMapMemory(device, s.memory, 0, VK_WHOLE_SIZE, 0, &s.mapped) != VK_SUCCESS) {
            destroySlotBuffer(s);
            return false;
        }
        s.size = size;
        return true;
    }
};

OverlayGpu::OverlayGpu() : m_impl(std::make_unique<Impl>()) {}

OverlayGpu::~OverlayGpu() { shutdown(); }

OverlayGpu::Language OverlayGpu::defaultLanguage() { return kOverlayHaveSlang ? Language::Slang : Language::Glsl; }

bool OverlayGpu::languageAvailable(Language language) {
    return language == Language::Slang ? kOverlayHaveSlang : kOverlayHaveGlsl;
}

bool OverlayGpu::supportedFormat(std::uint32_t f, bool& bgra) {
    bgra = f == VK_FORMAT_B8G8R8A8_UNORM || f == VK_FORMAT_B8G8R8A8_SRGB;
    return bgra || f == VK_FORMAT_R8G8B8A8_UNORM || f == VK_FORMAT_R8G8B8A8_SRGB;
}

bool OverlayGpu::init(std::uint64_t device, std::uint64_t physicalDevice, IOverlayDevice& images, Language language) {
    shutdown();
    Impl& d = *m_impl;
    m_images = &images;
    d.device = vkHandle<VkDevice>(device);
    d.physicalDevice = vkHandle<VkPhysicalDevice>(physicalDevice);
    if (!languageAvailable(language)) {
        m_error = "the overlay compose shader was not compiled for the requested language";
        return false;
    }
    auto fail = [&](const char* what) {
        m_error = what;
        shutdown();
        return false;
    };
    VkShaderModuleCreateInfo sm{};
    sm.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    if (language == Language::Slang) {
        sm.codeSize = sizeof(kOverlayComposeSlangSpv);
        sm.pCode = kOverlayComposeSlangSpv;
    } else {
        sm.codeSize = sizeof(kOverlayComposeGlslSpv);
        sm.pCode = kOverlayComposeGlslSpv;
    }
    if (vkCreateShaderModule(d.device, &sm, nullptr, &d.module) != VK_SUCCESS) {
        return fail("vkCreateShaderModule failed");
    }
    VkDescriptorSetLayoutBinding b[3]{};
    b[0].binding = 0;
    b[0].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;
    b[1].binding = 1;
    b[1].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    b[2].binding = 2;
    b[2].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
    for (VkDescriptorSetLayoutBinding& x : b) {
        x.descriptorCount = 1;
        x.stageFlags = VK_SHADER_STAGE_COMPUTE_BIT;
    }
    VkDescriptorSetLayoutCreateInfo sl{};
    sl.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
    sl.bindingCount = 3;
    sl.pBindings = b;
    if (vkCreateDescriptorSetLayout(d.device, &sl, nullptr, &d.setLayout) != VK_SUCCESS) {
        return fail("vkCreateDescriptorSetLayout failed");
    }
    VkPushConstantRange pr{VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(OverlayPush)};
    VkPipelineLayoutCreateInfo pl{};
    pl.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    pl.setLayoutCount = 1;
    pl.pSetLayouts = &d.setLayout;
    pl.pushConstantRangeCount = 1;
    pl.pPushConstantRanges = &pr;
    if (vkCreatePipelineLayout(d.device, &pl, nullptr, &d.layout) != VK_SUCCESS) {
        return fail("vkCreatePipelineLayout failed");
    }
    VkComputePipelineCreateInfo cp{};
    cp.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    cp.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    cp.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    cp.stage.module = d.module;
    cp.stage.pName = "main";
    cp.layout = d.layout;
    if (vkCreateComputePipelines(d.device, VK_NULL_HANDLE, 1, &cp, nullptr, &d.pipeline) != VK_SUCCESS) {
        return fail("vkCreateComputePipelines failed");
    }
    VkDescriptorPoolSize sizes[3] = {{VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, kSlots},
                                     {VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, kSlots},
                                     {VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, kSlots}};
    VkDescriptorPoolCreateInfo dp{};
    dp.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    dp.maxSets = kSlots;
    dp.poolSizeCount = 3;
    dp.pPoolSizes = sizes;
    if (vkCreateDescriptorPool(d.device, &dp, nullptr, &d.pool) != VK_SUCCESS) {
        return fail("vkCreateDescriptorPool failed");
    }
    VkDescriptorSetLayout layouts[kSlots] = {d.setLayout, d.setLayout, d.setLayout};
    VkDescriptorSet sets[kSlots]{};
    VkDescriptorSetAllocateInfo da{};
    da.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    da.descriptorPool = d.pool;
    da.descriptorSetCount = kSlots;
    da.pSetLayouts = layouts;
    if (vkAllocateDescriptorSets(d.device, &da, sets) != VK_SUCCESS) {
        return fail("vkAllocateDescriptorSets failed");
    }
    for (std::uint32_t i = 0; i < kSlots; ++i) {
        d.slots[i].set = sets[i];
    }
    VkSamplerCreateInfo sc{};
    sc.sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO;
    sc.magFilter = sc.minFilter = VK_FILTER_NEAREST;
    sc.mipmapMode = VK_SAMPLER_MIPMAP_MODE_NEAREST;
    sc.addressModeU = sc.addressModeV = sc.addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    sc.maxLod = 0.f;
    if (vkCreateSampler(d.device, &sc, nullptr, &d.sampler) != VK_SUCCESS) {
        return fail("vkCreateSampler failed");
    }
    tap::HostImageInfo like;
    like.imageType = VK_IMAGE_TYPE_2D;
    like.format = VK_FORMAT_R8G8B8A8_UNORM;
    like.width = like.height = 1;
    if (!images.createImage(like, VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT, false, m_dummy)) {
        return fail("cannot create the overlay's dummy debug image");
    }
    d.dummyView = d.makeView(m_dummy.image.vkImage, VK_FORMAT_R8G8B8A8_UNORM, VK_IMAGE_ASPECT_COLOR_BIT);
    if (d.dummyView == VK_NULL_HANDLE) {
        return fail("vkCreateImageView failed (dummy)");
    }
    m_ready = true;
    m_error.clear();
    return true;
}

void OverlayGpu::shutdown() {
    Impl& d = *m_impl;
    if (d.device == VK_NULL_HANDLE) {
        m_ready = false;
        return;
    }
    std::uint64_t last = 0;
    for (const Impl::Slot& s : d.slots) {
        last = std::max(last, s.serial);
    }
    if (m_images) {
        m_images->waitSerial(last);
    }
    for (Impl::Slot& s : d.slots) {
        d.destroySlotBuffer(s);
        s.set = VK_NULL_HANDLE;
        s.serial = 0;
    }
    for (VkImageView* v : {&d.regionView, &d.dummyView, &d.debugView}) {
        if (*v != VK_NULL_HANDLE) {
            vkDestroyImageView(d.device, *v, nullptr);
            *v = VK_NULL_HANDLE;
        }
    }
    d.debugViewImage = 0;
    if (m_images) {
        for (rf::GpuImage* img : {&m_target, &m_region, &m_dummy}) {
            if (img->valid()) {
                m_images->destroyImage(*img);
            }
        }
    }
    if (d.sampler != VK_NULL_HANDLE) {
        vkDestroySampler(d.device, d.sampler, nullptr);
    }
    if (d.pool != VK_NULL_HANDLE) {
        vkDestroyDescriptorPool(d.device, d.pool, nullptr);
    }
    if (d.pipeline != VK_NULL_HANDLE) {
        vkDestroyPipeline(d.device, d.pipeline, nullptr);
    }
    if (d.layout != VK_NULL_HANDLE) {
        vkDestroyPipelineLayout(d.device, d.layout, nullptr);
    }
    if (d.setLayout != VK_NULL_HANDLE) {
        vkDestroyDescriptorSetLayout(d.device, d.setLayout, nullptr);
    }
    if (d.module != VK_NULL_HANDLE) {
        vkDestroyShaderModule(d.device, d.module, nullptr);
    }
    const VkDevice device = d.device;
    *m_impl = Impl{};
    (void)device;
    m_target = m_region = m_dummy = rf::GpuImage{};
    m_ready = false;
}

bool OverlayGpu::prepare(const OverlayFrameDesc& f) {
    Impl& d = *m_impl;
    if (!m_ready) {
        m_error = m_error.empty() ? "overlay GPU not initialised" : m_error;
        return false;
    }
    bool bgra = false;
    if (!supportedFormat(f.frameFormat, bgra) || f.frameW == 0 || f.frameH == 0) {
        m_error = "unsupported back-buffer format for the overlay";
        return false;
    }
    // Target + region images for this back buffer.
    if (!m_target.valid() || d.frameW != f.frameW || d.frameH != f.frameH || d.frameFormat != f.frameFormat) {
        std::uint64_t last = 0;
        for (const Impl::Slot& s : d.slots) {
            last = std::max(last, s.serial);
        }
        m_images->waitSerial(last);
        if (d.regionView != VK_NULL_HANDLE) {
            vkDestroyImageView(d.device, d.regionView, nullptr);
            d.regionView = VK_NULL_HANDLE;
        }
        if (m_target.valid() || m_region.valid()) {
            ++m_rebuilds;
        }
        for (rf::GpuImage* img : {&m_target, &m_region}) {
            if (img->valid()) {
                m_images->destroyImage(*img);
            }
        }
        tap::HostImageInfo like;
        like.imageType = VK_IMAGE_TYPE_2D;
        like.format = f.frameFormat;
        like.width = f.frameW;
        like.height = f.frameH;
        if (!m_images->createImage(like, VK_IMAGE_USAGE_TRANSFER_SRC_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT, true,
                                   m_target)) {
            m_error = "cannot create the overlay's target image";
            return false;
        }
        like.format = kRegionFormat;
        if (!m_images->createImage(like,
                                   VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT |
                                       VK_IMAGE_USAGE_TRANSFER_DST_BIT,
                                   false, m_region)) {
            m_error = "cannot create the overlay's region image";
            return false;
        }
        d.regionView = d.makeView(m_region.image.vkImage, kRegionFormat, VK_IMAGE_ASPECT_COLOR_BIT);
        d.frameW = f.frameW;
        d.frameH = f.frameH;
        d.frameFormat = f.frameFormat;
    }
    // Region: the panel, or the whole frame under a debug view.
    d.debugActive = f.debug && f.debug->vkImage && f.debug->width && f.debug->height;
    Rect panel = f.layer ? f.panel : Rect{};
    const Rect frame{0, 0, static_cast<std::int32_t>(f.frameW), static_cast<std::int32_t>(f.frameH)};
    Rect region = d.debugActive ? frame : panel;
    const std::int32_t x0 = std::max(region.x, 0), y0 = std::max(region.y, 0);
    const std::int32_t x1 = std::min(region.x + region.w, frame.w), y1 = std::min(region.y + region.h, frame.h);
    region = Rect{x0, y0, x1 - x0, y1 - y0};
    if (region.empty()) {
        m_error = "nothing to draw";
        return false;
    }
    if (f.layer && !panel.empty() &&
        f.layer->size() < static_cast<std::size_t>(panel.w) * static_cast<std::size_t>(panel.h)) {
        m_error = "the layer is smaller than the panel";
        return false;
    }
    // The ring slot: reused once the submission that read it completed.
    d.current = (d.current + 1) % kSlots;
    Impl::Slot& slot = d.slots[d.current];
    m_images->waitSerial(slot.serial);
    const std::size_t texels = panel.empty() ? 1u : static_cast<std::size_t>(panel.w) * static_cast<std::size_t>(panel.h);
    if (!d.ensureSlotBuffer(slot, texels * sizeof(Color))) {
        m_error = "cannot allocate the overlay's layer buffer";
        return false;
    }
    if (!panel.empty()) {
        std::memcpy(slot.mapped, f.layer->data(), texels * sizeof(Color));
    }
    // Debug source view.
    if (d.debugActive) {
        d.debug = *f.debug;
        if (d.debugView == VK_NULL_HANDLE || d.debugViewImage != d.debug.vkImage || d.debugViewFormat != d.debug.format ||
            d.debugViewAspect != d.debug.aspect) {
            if (d.debugView != VK_NULL_HANDLE) {
                m_images->waitSerial(d.debugViewSerial);
                vkDestroyImageView(d.device, d.debugView, nullptr);
            }
            d.debugView = d.makeView(d.debug.vkImage, d.debug.format, d.debug.aspect ? d.debug.aspect : 1u);
            d.debugViewImage = d.debug.vkImage;
            d.debugViewFormat = d.debug.format;
            d.debugViewAspect = d.debug.aspect;
            if (d.debugView == VK_NULL_HANDLE) {
                d.debugActive = false;
            }
        }
        d.debugViewSerial = f.serial;
    }
    VkDescriptorImageInfo regionInfo{VK_NULL_HANDLE, d.regionView, VK_IMAGE_LAYOUT_GENERAL};
    VkDescriptorBufferInfo layerInfo{slot.buffer, 0, VK_WHOLE_SIZE};
    VkDescriptorImageInfo debugInfo{d.sampler, d.debugActive ? d.debugView : d.dummyView,
                                    d.debugActive ? VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL : VK_IMAGE_LAYOUT_GENERAL};
    VkWriteDescriptorSet w[3]{};
    for (std::uint32_t i = 0; i < 3; ++i) {
        w[i].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
        w[i].dstSet = slot.set;
        w[i].dstBinding = i;
        w[i].descriptorCount = 1;
    }
    w[0].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE;
    w[0].pImageInfo = &regionInfo;
    w[1].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
    w[1].pBufferInfo = &layerInfo;
    w[2].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
    w[2].pImageInfo = &debugInfo;
    vkUpdateDescriptorSets(d.device, 3, w, 0, nullptr);
    slot.serial = f.serial;

    OverlayPush p;
    p.regionX = region.x;
    p.regionY = region.y;
    p.regionW = static_cast<std::uint32_t>(region.w);
    p.regionH = static_cast<std::uint32_t>(region.h);
    p.panelX = panel.x;
    p.panelY = panel.y;
    p.panelW = panel.empty() ? 0u : static_cast<std::uint32_t>(panel.w);
    p.panelH = panel.empty() ? 0u : static_cast<std::uint32_t>(panel.h);
    p.frameW = f.frameW;
    p.frameH = f.frameH;
    p.flags = (bgra ? kOverlayFlagBgra : 0u) | (d.debugActive ? kOverlayFlagDebug : 0u);
    if (d.debugActive) {
        p.debugSwizzle = d.debug.swizzle;
        p.debugW = d.debug.width;
        p.debugH = d.debug.height;
        for (int i = 0; i < 4; ++i) {
            p.debugScale[i] = d.debug.scale[i];
            p.debugBias[i] = d.debug.bias[i];
        }
    }
    m_push = p;
    m_error.clear();
    return true;
}

void OverlayGpu::submitted(std::uint64_t serial) {
    Impl& d = *m_impl;
    d.slots[d.current].serial = serial;
    if (d.debugActive) {
        d.debugViewSerial = serial;
    }
}

bool OverlayGpu::declare(rg::Graph& graph, rg::TextureRef output, const rf::GpuImage& outputImage) {
    Impl& d = *m_impl;
    if (!m_ready || !m_region.valid() || m_push.regionW == 0 || outputImage.image.vkImage != m_target.image.vkImage) {
        return false;
    }
    rg::ImportedImage region;
    region.image = reinterpret_cast<void*>(static_cast<std::uintptr_t>(m_region.image.vkImage));
    region.format = kRegionFormat;
    region.width = m_region.image.info.width;
    region.height = m_region.image.info.height;
    region.initialLayout = kLayoutGeneral;
    region.finalLayout = kLayoutGeneral;
    region.name = "overlay.region";
    const rg::TextureRef regionRef = graph.importImage(region);
    const Impl::Slot& slot = d.slots[d.current];
    rg::ImportedBuffer layer;
    layer.buffer = reinterpret_cast<void*>(vkValue(slot.buffer));
    layer.size = slot.size;
    layer.name = "overlay.layer";
    const rg::BufferRef layerRef = graph.importBuffer(layer);
    rg::TextureRef debugRef{};
    if (d.debugActive) {
        rg::ImportedImage dbg;
        dbg.image = reinterpret_cast<void*>(static_cast<std::uintptr_t>(d.debug.vkImage));
        dbg.format = d.debug.format;
        dbg.width = d.debug.width;
        dbg.height = d.debug.height;
        dbg.initialLayout = d.debug.layout;
        dbg.finalLayout = d.debug.layout;
        dbg.name = "overlay.debug";
        debugRef = graph.importImage(dbg);
    }
    d.resRegion = regionRef.id;
    d.resBuffer = layerRef.id;
    d.resDebug = debugRef.id;
    d.passCopyIn = graph.addPass("overlay.copy_in", &passTrampoline, this)
                       .use(output, rg::Access::TransferSrc)
                       .use(regionRef, rg::Access::TransferDst)
                       .neverCull()
                       .index();
    rg::PassBuilder compose = graph.addPass("overlay.compose", &passTrampoline, this);
    compose.use(regionRef, rg::Access::StorageReadWrite, {}, rg::kStageCompute)
        .use(layerRef, rg::Access::StorageRead, {}, rg::kStageCompute);
    if (debugRef.valid()) {
        compose.use(debugRef, rg::Access::SampledRead, {}, rg::kStageCompute);
    }
    d.passCompose = compose.neverCull().index();
    d.passCopyOut = graph.addPass("overlay.copy_out", &passTrampoline, this)
                        .use(regionRef, rg::Access::TransferSrc)
                        .use(output, rg::Access::TransferDst)
                        .neverCull()
                        .index();
    return true;
}

rf::IFrameRecorder::Image OverlayGpu::image(std::uint32_t resource) const {
    const Impl& d = *m_impl;
    Image i;
    if (resource != 0 && resource == d.resRegion) {
        i.vkImage = m_region.image.vkImage;
    } else if (resource != 0 && resource == d.resDebug) {
        i.vkImage = d.debug.vkImage;
        i.aspect = d.debug.aspect ? d.debug.aspect : 1u;
    }
    return i;
}

std::uint64_t OverlayGpu::buffer(std::uint32_t resource) const {
    const Impl& d = *m_impl;
    return resource != 0 && resource == d.resBuffer ? vkValue(d.slots[d.current].buffer) : 0u;
}

void OverlayGpu::record(std::uint32_t pass, std::uint64_t commandBuffer) {
    Impl& d = *m_impl;
    const VkCommandBuffer cmd = vkHandle<VkCommandBuffer>(commandBuffer);
    const OverlayPush& p = m_push;
    VkImageCopy copy{};
    copy.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    copy.dstSubresource = copy.srcSubresource;
    copy.extent = {p.regionW, p.regionH, 1};
    if (pass == d.passCopyIn) {
        copy.srcOffset = {p.regionX, p.regionY, 0};
        vkCmdCopyImage(cmd, vkHandle<VkImage>(m_target.image.vkImage), VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                       vkHandle<VkImage>(m_region.image.vkImage), VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &copy);
    } else if (pass == d.passCompose) {
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, d.pipeline);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, d.layout, 0, 1, &d.slots[d.current].set, 0,
                                nullptr);
        vkCmdPushConstants(cmd, d.layout, VK_SHADER_STAGE_COMPUTE_BIT, 0, sizeof(OverlayPush), &p);
        vkCmdDispatch(cmd, (p.regionW + kOverlayGroupSize - 1) / kOverlayGroupSize,
                      (p.regionH + kOverlayGroupSize - 1) / kOverlayGroupSize, 1);
    } else if (pass == d.passCopyOut) {
        copy.dstOffset = {p.regionX, p.regionY, 0};
        vkCmdCopyImage(cmd, vkHandle<VkImage>(m_region.image.vkImage), VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                       vkHandle<VkImage>(m_target.image.vkImage), VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &copy);
    }
}

} // namespace fuse::relight::overlay
