# ctest rl_dxvk_pins (RL-0.2): pins and patch marking of the vendored Relight dependencies.
#   cmake -DFUSE_LINT=<fuse_lint> [-DFUSE_EMULATOR=<emulator|args>] -DFUSE_DIRS=<dir>|<dir>...
#         -DFUSE_SCRATCH=<dir> -P check_pins.cmake
#
# 1. `fuse_lint vendored-pins` per directory: VERSION fields, plus a sha256 for every vendored file
#    (the file as vendored, patches included).
# 2. The marked-edit rule (zlib clause 2, plan §0.4.2), for every directory that has a PATCHES.md:
#    - `// FUSE-DXVK begin: <patch-id> ...` / `// FUSE-DXVK end` lines pair up, with no nesting;
#    - every file with markers has an `upstream_sha256:<path>=` entry in VERSION, and the file hashes
#      to it once its marked blocks (begin line through end line) are removed, CRLF normalised to LF.
#      So everything outside the markers is byte-identical to upstream;
#    - every upstream_sha256 entry names a file that has markers (no stale entries);
#    - every patch id appears in PATCHES.md;
#    - at most 30 marked blocks in total (plan §2.4 patch budget).
#    Files without markers are covered by rule 1: their pinned sha256 is the upstream hash.
cmake_minimum_required(VERSION 3.20)  # -P scripts need modern policies (while(TRUE), IN_LIST)
string(REPLACE "|" ";" _dirs "${FUSE_DIRS}")
string(REPLACE "|" ";" _emulator "${FUSE_EMULATOR}")
set(_failures 0)
set(_max_blocks 30)

macro(_rl_fail msg)
    message(SEND_ERROR "rl_dxvk_pins: ${msg}")
    math(EXPR _failures "${_failures} + 1")
endmacro()

# Removes every marked block (from the start of the begin line to the end of the end line) from
# `text`. Sets <out> to the stripped text, <nblocks> to the block count and <ids> to the patch ids,
# or reports a malformed marker.
function(_rl_strip_marked text rel out nblocks ids)
    set(_rest "${text}")
    set(_kept "")
    set(_n 0)
    set(_ids "")
    while(TRUE)
        string(FIND "${_rest}" "// FUSE-DXVK begin" _b)
        string(FIND "${_rest}" "// FUSE-DXVK end" _e)
        if(_b LESS 0)
            if(NOT _e LESS 0)
                message(SEND_ERROR "rl_dxvk_pins: ${rel}: 'FUSE-DXVK end' without a begin")
                set(_n -1)
            endif()
            break()
        endif()
        if(_e LESS 0 OR _e LESS _b)
            message(SEND_ERROR "rl_dxvk_pins: ${rel}: unbalanced FUSE-DXVK markers")
            set(_n -1)
            break()
        endif()
        # Start of the begin line.
        string(SUBSTRING "${_rest}" 0 ${_b} _before)
        string(FIND "${_before}" "\n" _nl REVERSE)
        math(EXPR _line_start "${_nl} + 1")
        string(SUBSTRING "${_rest}" 0 ${_line_start} _head)
        string(APPEND _kept "${_head}")
        # Patch id: first token after "begin:".
        string(SUBSTRING "${_rest}" ${_b} -1 _from_begin)
        if(_from_begin MATCHES "^// FUSE-DXVK begin: ([A-Za-z0-9._-]+)")
            list(APPEND _ids "${CMAKE_MATCH_1}")
        else()
            message(SEND_ERROR "rl_dxvk_pins: ${rel}: FUSE-DXVK begin marker has no '<patch-id>'")
            set(_n -1)
            break()
        endif()
        # No nested begin before the matching end.
        math(EXPR _after_begin "${_b} + 18")
        string(SUBSTRING "${_rest}" ${_after_begin} -1 _tail)
        string(FIND "${_tail}" "// FUSE-DXVK begin" _nb)
        string(FIND "${_tail}" "// FUSE-DXVK end" _ne)
        if(NOT _nb LESS 0 AND _nb LESS _ne)
            message(SEND_ERROR "rl_dxvk_pins: ${rel}: nested FUSE-DXVK begin")
            set(_n -1)
            break()
        endif()
        # Drop through the end of the end line.
        string(SUBSTRING "${_rest}" ${_e} -1 _from_end)
        string(FIND "${_from_end}" "\n" _eol)
        if(_eol LESS 0)
            set(_rest "")
        else()
            math(EXPR _eol "${_eol} + 1")
            string(SUBSTRING "${_from_end}" ${_eol} -1 _rest)
        endif()
        math(EXPR _n "${_n} + 1")
    endwhile()
    string(APPEND _kept "${_rest}")
    set(${out} "${_kept}" PARENT_SCOPE)
    set(${nblocks} ${_n} PARENT_SCOPE)
    set(${ids} "${_ids}" PARENT_SCOPE)
endfunction()

foreach(_dir IN LISTS _dirs)
    get_filename_component(_name "${_dir}" NAME)
    execute_process(
        COMMAND ${_emulator} "${FUSE_LINT}" vendored-pins --dir "${_dir}" --scratch "${FUSE_SCRATCH}/${_name}"
        RESULT_VARIABLE _rc)
    if(NOT _rc EQUAL 0)
        _rl_fail("vendored-pins failed for ${_dir} (${_rc})")
    endif()

    if(NOT EXISTS "${_dir}/PATCHES.md")
        continue()
    endif()
    file(READ "${_dir}/PATCHES.md" _patches_md)
    file(STRINGS "${_dir}/VERSION" _upstream_lines REGEX "^upstream_sha256:")
    set(_upstream_paths "")
    foreach(_l IN LISTS _upstream_lines)
        if(_l MATCHES "^upstream_sha256:([^=]+)=([0-9a-f]+)$")
            list(APPEND _upstream_paths "${CMAKE_MATCH_1}")
            set(_upstream_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
        else()
            _rl_fail("${_dir}/VERSION: malformed line '${_l}'")
        endif()
    endforeach()

    file(GLOB_RECURSE _files LIST_DIRECTORIES false RELATIVE "${_dir}" "${_dir}/*")
    set(_total_blocks 0)
    set(_marked_paths "")
    foreach(_rel IN LISTS _files)
        if(_rel STREQUAL "PATCHES.md" OR _rel STREQUAL "VERSION")
            continue()
        endif()
        file(STRINGS "${_dir}/${_rel}" _hits REGEX "// FUSE-DXVK (begin|end)")
        if(NOT _hits)
            continue()
        endif()
        list(APPEND _marked_paths "${_rel}")
        file(READ "${_dir}/${_rel}" _text)
        string(REPLACE "\r\n" "\n" _text "${_text}")
        _rl_strip_marked("${_text}" "${_rel}" _stripped _n _ids)
        if(_n LESS 0)
            math(EXPR _failures "${_failures} + 1")
            continue()
        endif()
        math(EXPR _total_blocks "${_total_blocks} + ${_n}")
        foreach(_id IN LISTS _ids)
            string(FIND "${_patches_md}" "${_id}" _pos)
            if(_pos LESS 0)
                _rl_fail("${_rel}: patch id ${_id} is not listed in PATCHES.md")
            endif()
        endforeach()
        if(NOT DEFINED _upstream_${_rel})
            _rl_fail("${_rel} carries FUSE-DXVK markers but VERSION has no upstream_sha256:${_rel} entry")
            continue()
        endif()
        string(SHA256 _h "${_stripped}")
        if(NOT _h STREQUAL _upstream_${_rel})
            _rl_fail("${_rel}: with its marked blocks removed it hashes to ${_h}, upstream is ${_upstream_${_rel}} (unmarked edit?)")
        endif()
    endforeach()
    foreach(_p IN LISTS _upstream_paths)
        if(NOT _p IN_LIST _marked_paths)
            _rl_fail("${_dir}/VERSION: upstream_sha256:${_p} names a file without FUSE-DXVK markers (stale entry)")
        endif()
    endforeach()
    if(_total_blocks GREATER _max_blocks)
        _rl_fail("${_dir}: ${_total_blocks} marked blocks exceed the budget of ${_max_blocks}")
    endif()
    list(LENGTH _marked_paths _nfiles)
    message(STATUS "rl_dxvk_pins: ${_name}: ${_total_blocks} marked block(s) in ${_nfiles} file(s), outside-marker bytes equal upstream")
endforeach()

if(_failures GREATER 0)
    message(FATAL_ERROR "rl_dxvk_pins: ${_failures} failure(s)")
endif()
