// RL-5.5 radiance denoiser on render graph v2: see include/fuse/renderer/denoise/radiance_denoiser.hpp.
#include <fuse/renderer/denoise/radiance_denoiser.hpp>

#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/device.hpp>

#include <algorithm>
#include <cstring>
#include <initializer_list>

#if defined(FUSE_VULKAN_BACKEND)
#include <vulkan/vulkan.h>

// Generated by cmake/rp_rl55.cmake from shaders/denoise/rdn.{slang,comp}:
// kRdn{Slang,Glsl}Spv and FUSE_RDN_{SLANG,GLSL} when built.
#include "rdn_spv.h"
#endif

namespace fuse::renderer::denoise {

namespace {
constexpr u32 kPushBytes = sizeof(RdnPush);
constexpr u64 kFrameStride = (sizeof(RdnFrame) + 255u) & ~u64{255u};

BufferUsage bufferUsage(std::initializer_list<BufferUsage> bits) {
    u32 u = 0;
    for (const BufferUsage b : bits) {
        u |= static_cast<u32>(b);
    }
    return static_cast<BufferUsage>(u);
}

u32 groups(u32 items) { return items == 0u ? 1u : (items + kRdnTile - 1u) / kRdnTile; }
} // namespace

bool rdn_supported(const VulkanDevice* device, const char** reason) {
    const char* why = "stub backend";
    bool ok = false;
#if defined(FUSE_VULKAN_BACKEND)
    why = "no device";
    if (device != nullptr && device->isValid()) {
        const RendererCaps& caps = device->info().caps;
        if (!caps.bufferDeviceAddress || !caps.shaderInt64) {
            why = "bufferDeviceAddress / shaderInt64 missing";
        } else {
            why = "ok";
            ok = true;
        }
    }
#else
    (void)device;
#endif
    if (reason != nullptr) {
        *reason = why;
    }
    return ok;
}

RadianceDenoiser::~RadianceDenoiser() { destroy(); }

bool RadianceDenoiser::init(const RadianceDenoiserDesc& desc) {
    destroy();
    m_desc = desc;
#if defined(FUSE_VULKAN_BACKEND)
    if (desc.allocator == nullptr || desc.bindless == nullptr || desc.framesInFlight == 0u ||
        !rdn_supported(desc.device)) {
        return false;
    }
    m_retired.reserve(8);
    m_initialized = true; // destroy() releases partial state from here on
    BufferDesc ring{};
    ring.size = static_cast<usize>(desc.framesInFlight * kFrameStride);
    ring.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress});
    ring.memoryUsage = MemoryUsage::CpuToGpu;
    ring.name = "radiance_denoiser.frame";
    if (!m_desc.allocator->createBuffer(ring, m_frameRing) || m_frameRing.mapped == nullptr ||
        m_frameRing.deviceAddress == 0u || !createPipeline()) {
        destroy();
        return false;
    }
    return true;
#else
    return false;
#endif
}

void RadianceDenoiser::destroy() {
    if (!m_initialized) {
        return;
    }
#if defined(FUSE_VULKAN_BACKEND)
    collectRetired(~0ull);
    Retired current{};
    current.buffers[0] = m_state;
    current.buffers[1] = m_work;
    current.buffers[2] = m_output;
    destroyRetired(current);
    if (m_frameRing.handle != nullptr) {
        m_desc.allocator->destroyBuffer(m_frameRing);
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    if (m_pipeline != nullptr) {
        vkDestroyPipeline(device, static_cast<VkPipeline>(m_pipeline), nullptr);
    }
    if (m_layoutHandle != nullptr) {
        vkDestroyPipelineLayout(device, static_cast<VkPipelineLayout>(m_layoutHandle), nullptr);
    }
#endif
    m_pipeline = nullptr;
    m_layoutHandle = nullptr;
    m_state = m_work = m_output = Buffer{};
    m_stateQueue = m_workQueue = m_outputQueue = rg::kNoQueue;
    m_frameRing = Buffer{};
    m_frameAddress = 0;
    m_retired.clear();
    m_layout = RdnBufferLayout{};
    m_historyValid = false;
    m_parity = 1u;
    m_passCount = 0;
    m_language = "none";
    m_stats = RdnStats{};
    m_initialized = false;
}

bool RadianceDenoiser::createPipeline() {
#if defined(FUSE_VULKAN_BACKEND)
    const u32* words = nullptr;
    usize bytes = 0;
#if defined(FUSE_RDN_SLANG)
    if (m_desc.language == RdnKernelLanguage::Auto || m_desc.language == RdnKernelLanguage::Slang) {
        words = kRdnSlangSpv;
        bytes = sizeof(kRdnSlangSpv);
        m_language = "slang";
    }
#endif
#if defined(FUSE_RDN_GLSL)
    if (words == nullptr &&
        (m_desc.language == RdnKernelLanguage::Auto || m_desc.language == RdnKernelLanguage::Glsl)) {
        words = kRdnGlslSpv;
        bytes = sizeof(kRdnGlslSpv);
        m_language = "glsl";
    }
#endif
    if (words == nullptr) {
        return false;
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    // The bindless set is part of the layout (and bound) although the kernel
    // reads no descriptor: descriptor-buffer backends need every pipeline after a
    // bindless pass to agree on the layout (VUID-08117).
    VkDescriptorSetLayout setLayout = static_cast<VkDescriptorSetLayout>(m_desc.bindless->layoutHandle());
    VkPushConstantRange range{VK_SHADER_STAGE_COMPUTE_BIT, 0, kPushBytes};
    VkPipelineLayoutCreateInfo layoutInfo{};
    layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutInfo.setLayoutCount = setLayout != VK_NULL_HANDLE ? 1u : 0u;
    layoutInfo.pSetLayouts = &setLayout;
    layoutInfo.pushConstantRangeCount = 1;
    layoutInfo.pPushConstantRanges = &range;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    if (vkCreatePipelineLayout(device, &layoutInfo, nullptr, &layout) != VK_SUCCESS) {
        return false;
    }
    m_layoutHandle = layout;
    VkShaderModuleCreateInfo moduleInfo{};
    moduleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    moduleInfo.codeSize = bytes;
    moduleInfo.pCode = words;
    VkShaderModule module = VK_NULL_HANDLE;
    if (vkCreateShaderModule(device, &moduleInfo, nullptr, &module) != VK_SUCCESS) {
        return false;
    }
    VkComputePipelineCreateInfo info{};
    info.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    info.flags = static_cast<VkPipelineCreateFlags>(m_desc.bindless->pipelineCreateFlags());
    info.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    info.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    info.stage.module = module;
    info.stage.pName = "main";
    info.layout = layout;
    VkPipeline pipeline = VK_NULL_HANDLE;
    const VkResult result = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
    vkDestroyShaderModule(device, module, nullptr);
    m_pipeline = pipeline;
    return result == VK_SUCCESS;
#else
    return false;
#endif
}

bool RadianceDenoiser::createResources(u32 width, u32 height) {
    const RdnBufferLayout layout = RdnBufferLayout::compute(width, height, m_desc.keepIntermediates);
    const BufferUsage usage =
        bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress, BufferUsage::TransferSrc});
    Buffer fresh[3]{};
    const u64 sizes[3] = {layout.stateBytes, layout.workBytes, layout.outputBytes};
    const char* names[3] = {"radiance_denoiser.state", "radiance_denoiser.work", "radiance_denoiser.output"};
    bool ok = true;
    for (u32 i = 0; i < 3u && ok; ++i) {
        const bool host = m_desc.hostVisible || (i == 2u && m_desc.hostVisibleOutput);
        BufferDesc d{};
        d.size = static_cast<usize>(sizes[i]);
        d.usage = usage;
        d.memoryUsage = host ? MemoryUsage::GpuToCpu : MemoryUsage::GpuOnly;
        d.name = names[i];
        ok = m_desc.allocator->createBuffer(d, fresh[i]) && fresh[i].deviceAddress != 0u &&
             (!host || fresh[i].mapped != nullptr);
    }
    if (!ok) {
        Retired failed{};
        for (u32 i = 0; i < 3u; ++i) {
            failed.buffers[i] = fresh[i];
        }
        destroyRetired(failed);
        return false;
    }
    if (m_state.handle != nullptr) {
        Retired old{};
        old.buffers[0] = m_state;
        old.buffers[1] = m_work;
        old.buffers[2] = m_output;
        old.serial = m_frameSerial;
        m_retired.push_back(old);
        ++m_stats.retired;
    }
    m_state = fresh[0];
    m_work = fresh[1];
    m_output = fresh[2];
    m_stateQueue = m_workQueue = m_outputQueue = rg::kNoQueue;
    m_layout = layout;
    m_historyValid = false;
    ++m_stats.rebuilds;
    return true;
}

void RadianceDenoiser::destroyRetired(Retired& r) {
    for (Buffer& b : r.buffers) {
        if (b.handle != nullptr) {
            m_desc.allocator->destroyBuffer(b);
        }
    }
    r = Retired{};
}

u32 RadianceDenoiser::collectRetired(u64 completedSerial) {
    u32 collected = 0;
    usize keep = 0;
    for (usize i = 0; i < m_retired.size(); ++i) {
        if (m_retired[i].serial > completedSerial) {
            m_retired[keep++] = m_retired[i];
            continue;
        }
        destroyRetired(m_retired[i]);
        ++collected;
    }
    m_retired.resize(keep);
    m_stats.retired = m_stats.retired >= collected ? m_stats.retired - collected : 0u;
    return collected;
}

const f32* RadianceDenoiser::mappedOutputD() const {
    return m_output.mapped != nullptr
               ? reinterpret_cast<const f32*>(static_cast<const u8*>(m_output.mapped) + m_layout.outD)
               : nullptr;
}

const f32* RadianceDenoiser::mappedOutputS() const {
    return m_output.mapped != nullptr
               ? reinterpret_cast<const f32*>(static_cast<const u8*>(m_output.mapped) + m_layout.outS)
               : nullptr;
}

bool RadianceDenoiser::beginFrame(u64 frameSerial, const RdnFrameDesc& frame) {
    m_passCount = 0;
    m_stats.passes = 0;
    if (!m_initialized || frame.width == 0u || frame.height == 0u || frame.diffuse == 0u || frame.specular == 0u ||
        frame.normal == 0u || frame.depth == 0u || frame.motion == 0u ||
        (m_settings.gradients && frame.gradient == 0u) || (m_settings.instanceTest && frame.instance == 0u)) {
        return false;
    }
    m_frameSerial = frameSerial;
    if (frame.width != m_layout.width || frame.height != m_layout.height || m_state.handle == nullptr) {
        if (!createResources(frame.width, frame.height)) {
            return false;
        }
    }
    if (frame.reset) {
        m_historyValid = false;
    }
    m_parity ^= 1u;
    RdnFrame c = rdn_resolve(m_settings, frame.width, frame.height, m_historyValid, frame.camera, frame.prevCamera);
    c.inDiffuse = frame.diffuse;
    c.inSpecular = frame.specular;
    c.inNormal = frame.normal;
    c.inDepth = frame.depth;
    c.inMotion = frame.motion;
    c.inInstance = m_settings.instanceTest ? frame.instance : 0u;
    c.inGradient = m_settings.gradients ? frame.gradient : 0u;
    rdn_bind_arenas(c, m_layout, m_state.deviceAddress, m_work.deviceAddress, m_output.deviceAddress, m_parity);
    m_constants = c;
    m_passCount = rdn_build_passes(c, m_layout, m_work.deviceAddress, m_output.deviceAddress, m_passes, kRdnMaxPasses);
    m_stats.history = m_historyValid;
    const u64 slot = frameSerial % m_desc.framesInFlight;
    std::memcpy(static_cast<u8*>(m_frameRing.mapped) + slot * kFrameStride, &c, sizeof(c));
    m_frameAddress = m_frameRing.deviceAddress + slot * kFrameStride;
    m_historyValid = true; // the next frame reprojects this one
    return true;
}

RdnGraphRefs RadianceDenoiser::importInto(rg::Graph& graph) {
    RdnGraphRefs refs{};
    if (!m_initialized || m_state.handle == nullptr) {
        return refs;
    }
    refs.state = graph.importBuffer(
        rg::ImportedBuffer{m_state.handle, m_state.desc.size, m_stateQueue, &m_stateQueue, "radiance_denoiser.state"});
    refs.work = graph.importBuffer(
        rg::ImportedBuffer{m_work.handle, m_work.desc.size, m_workQueue, &m_workQueue, "radiance_denoiser.work"});
    refs.output = graph.importBuffer(rg::ImportedBuffer{m_output.handle, m_output.desc.size, m_outputQueue,
                                                        &m_outputQueue, "radiance_denoiser.output"});
    refs.valid = true;
    return refs;
}

void RadianceDenoiser::addPasses(rg::Graph& graph, const RdnGraphRefs& refs, const RdnGraphInputs& inputs) {
    if (!m_initialized || !refs.valid || m_passCount == 0u || inputs.count == 0u) {
        return;
    }
    constexpr u8 kCs = rg::kStageCompute;
    for (u32 k = 0; k < m_passCount; ++k) {
        const RdnPassDesc& p = m_passes[k];
        PassRecord& r = m_records[k];
        r = PassRecord{};
        r.self = this;
        r.push.frame = m_frameAddress;
        for (u32 j = 0; j < 6u; ++j) {
            r.push.a[j] = p.args.a[j];
        }
        r.push.pass = p.args.pass;
        r.push.step = p.args.step;
        r.groups[0] = groups(p.gridW);
        r.groups[1] = groups(p.gridH);
        rg::PassBuilder pass = graph.addPass(p.name, &RadianceDenoiser::recordDispatch, &r);
        pass.use(refs.state, rg::Access::StorageReadWrite, {}, kCs)
            .use(refs.work, rg::Access::StorageReadWrite, {}, kCs);
        if (p.readsInputs) {
            for (u32 j = 0; j < inputs.count; ++j) {
                pass.use(inputs.buffers[j], rg::Access::StorageRead, inputs.ranges[j], kCs);
            }
        }
        if (p.writesOutput) {
            pass.use(refs.output, rg::Access::StorageWrite, {}, kCs);
        }
        ++m_stats.passes;
    }
}

void RadianceDenoiser::recordDispatch(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const RadianceDenoiser& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, static_cast<VkPipeline>(self.m_pipeline));
    self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, self.m_layoutHandle, 0);
    vkCmdPushConstants(cmd, static_cast<VkPipelineLayout>(self.m_layoutHandle), VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       kPushBytes, &r.push);
    vkCmdDispatch(cmd, r.groups[0], r.groups[1], 1u);
#else
    (void)context;
    (void)user;
#endif
}

} // namespace fuse::renderer::denoise
