// WP-6.3 screen-space fallback on Vulkan: see include/fuse/renderer/ssfx_gpu/ssfx_gpu.hpp.
#include <fuse/renderer/ssfx_gpu/ssfx_gpu.hpp>

#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/device.hpp>

#include <algorithm>
#include <cstring>
#include <initializer_list>

#if defined(FUSE_VULKAN_BACKEND)
#include <vulkan/vulkan.h>

// Generated by cmake/rp_wp63.cmake from shaders/ssfx/*: kSx<Kernel><Slang|Glsl>Spv and
// FUSE_SSFX_GPU_{SLANG,GLSL} when every kernel of a language exists.
#include "ssfx_gpu_spv.h"
#endif

namespace fuse::renderer::ssfx_gpu {

namespace {
constexpr u32 kPushBytes = sizeof(SsfxPush);
constexpr u32 kFrameStride = 768u; ///< ring slot size (>= sizeof(SsfxFrameConstants), 256-aligned)
static_assert(sizeof(SsfxFrameConstants) <= kFrameStride, "frame ring slot");
constexpr u32 kOutputFormat = static_cast<u32>(GpuFormat::R16G16B16A16Sfloat);
constexpr u64 kTexel = 16u; ///< f32x4
constexpr u64 kScalar = 4u; ///< f32

BufferUsage bufferUsage(std::initializer_list<BufferUsage> bits) {
    u32 u = 0;
    for (const BufferUsage b : bits) {
        u |= static_cast<u32>(b);
    }
    return static_cast<BufferUsage>(u);
}

ImageUsage imageUsage(std::initializer_list<ImageUsage> bits) {
    u32 u = 0;
    for (const ImageUsage b : bits) {
        u |= static_cast<u32>(b);
    }
    return static_cast<ImageUsage>(u);
}

u64 align256(u64 v) { return (v + 255u) & ~u64{255u}; }

u32 groups(u32 items, u32 size) { return items == 0u ? 1u : (items + size - 1u) / size; }

#if defined(FUSE_VULKAN_BACKEND)
struct Code {
    const u32* words = nullptr;
    usize bytes = 0;
};
template <usize N>
Code code(const u32 (&spv)[N]) {
    return Code{spv, sizeof(spv)};
}
#endif
} // namespace

SsfxBufferLayout SsfxBufferLayout::compute(u32 width, u32 height) {
    SsfxBufferLayout l{};
    u64 cursor = 0;
    auto take = [&](u64 bytes) {
        const u64 at = cursor;
        cursor = align256(cursor + std::max<u64>(bytes, 16u));
        return at;
    };
    const u64 n = static_cast<u64>(width) * height;
    l.prepared = take(n * kTexel);
    l.normals = take(n * kTexel);
    l.radiance = take(n * kTexel);
    l.albedo = take(n * kTexel);
    l.diffuse = take(n * kTexel);
    l.ao = take(n * kScalar);
    l.ssr = take(n * kTexel);
    l.gi = take(n * kTexel);
    l.bounce[0] = take(n * kTexel);
    l.bounce[1] = take(n * kTexel);
    l.workBytes = cursor;
    return l;
}

SsfxCapabilities querySsfxCapabilities(const VulkanDevice* device) {
    SsfxCapabilities c{};
#if defined(FUSE_VULKAN_BACKEND)
    if (device == nullptr || !device->isValid()) {
        return c;
    }
    const RendererCaps& caps = device->info().caps;
    if (!caps.bufferDeviceAddress || !caps.shaderInt64) {
        c.reason = "bufferDeviceAddress / shaderInt64 missing";
        return c;
    }
    VkFormatProperties props{};
    vkGetPhysicalDeviceFormatProperties(static_cast<VkPhysicalDevice>(device->nativePhysicalDevice()),
                                        static_cast<VkFormat>(kOutputFormat), &props);
    if ((props.optimalTilingFeatures & VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT) == 0u) {
        c.reason = "RGBA16F storage images unsupported";
        return c;
    }
    c.ssfx = true;
    c.reason = "ok";
#else
    (void)device;
    c.reason = "stub backend";
#endif
    return c;
}

SsfxGpu::~SsfxGpu() { destroy(); }

bool SsfxGpu::init(const SsfxGpuDesc& desc) {
    destroy();
    m_desc = desc;
#if defined(FUSE_VULKAN_BACKEND)
    if (desc.allocator == nullptr || desc.bindless == nullptr || desc.framesInFlight == 0u) {
        return false;
    }
    if (!querySsfxCapabilities(desc.device).ssfx) {
        return false;
    }
    m_retired.reserve(8);
    m_initialized = true; // destroy() releases partial state from here on
    BufferDesc ring{};
    ring.size = static_cast<usize>(desc.framesInFlight) * kFrameStride;
    ring.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress});
    ring.memoryUsage = MemoryUsage::CpuToGpu;
    ring.name = "ssfx_gpu.frame";
    if (!m_desc.allocator->createBuffer(ring, m_frameRing) || m_frameRing.mapped == nullptr ||
        m_frameRing.deviceAddress == 0u || !createPipelines()) {
        destroy();
        return false;
    }
    return true;
#else
    return false;
#endif
}

void SsfxGpu::destroy() {
    if (!m_initialized) {
        return;
    }
#if defined(FUSE_VULKAN_BACKEND)
    collectRetired(~0ull);
    Retired current{};
    current.buffer = m_work;
    current.image = m_output.image;
    current.slots[0] = m_output.slot;
    for (u32 i = 0; i < kInputCount; ++i) {
        current.slots[1u + i] = m_inputSlots[i];
    }
    destroyRetired(current);
    if (m_frameRing.handle != nullptr) {
        m_desc.allocator->destroyBuffer(m_frameRing);
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    for (void*& pipeline : m_pipelines) {
        if (pipeline != nullptr) {
            vkDestroyPipeline(device, static_cast<VkPipeline>(pipeline), nullptr);
            pipeline = nullptr;
        }
    }
    if (m_layoutHandle != nullptr) {
        vkDestroyPipelineLayout(device, static_cast<VkPipelineLayout>(m_layoutHandle), nullptr);
    }
#endif
    m_layoutHandle = nullptr;
    m_work = Buffer{};
    m_workQueue = rg::kNoQueue;
    m_output = Output{};
    m_frameRing = Buffer{};
    m_frameAddress = 0;
    m_retired.clear();
    for (u32 i = 0; i < kInputCount; ++i) {
        m_inputImages[i] = nullptr;
        m_inputSlots[i] = BindlessSlotHandle{};
        m_inputHandles[i] = 0u;
    }
    m_width = m_height = 0;
    m_layout = SsfxBufferLayout{};
    m_recordCount = 0;
    m_language = "none";
    m_stats = SsfxStats{};
    m_constants = SsfxFrameConstants{};
    m_hasDump = false;
    m_initialized = false;
}

bool SsfxGpu::createPipelines() {
#if defined(FUSE_VULKAN_BACKEND)
    Code k[kKernelCount]{};
    bool found = false;
#if defined(FUSE_SSFX_GPU_SLANG)
    if (m_desc.language == SsfxKernelLanguage::Auto || m_desc.language == SsfxKernelLanguage::Slang) {
        k[kPrepare] = code(kSxPrepareSlangSpv);
        k[kGtao] = code(kSxGtaoSlangSpv);
        k[kSsr] = code(kSxSsrSlangSpv);
        k[kSsgi] = code(kSxSsgiSlangSpv);
        k[kCompose] = code(kSxComposeSlangSpv);
        m_language = "slang";
        found = true;
    }
#endif
#if defined(FUSE_SSFX_GPU_GLSL)
    if (!found && (m_desc.language == SsfxKernelLanguage::Auto || m_desc.language == SsfxKernelLanguage::Glsl)) {
        k[kPrepare] = code(kSxPrepareGlslSpv);
        k[kGtao] = code(kSxGtaoGlslSpv);
        k[kSsr] = code(kSxSsrGlslSpv);
        k[kSsgi] = code(kSxSsgiGlslSpv);
        k[kCompose] = code(kSxComposeGlslSpv);
        m_language = "glsl";
        found = true;
    }
#endif
    if (!found) {
        return false;
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    VkDescriptorSetLayout setLayout = static_cast<VkDescriptorSetLayout>(m_desc.bindless->layoutHandle());
    VkPushConstantRange range{VK_SHADER_STAGE_COMPUTE_BIT, 0, kPushBytes};
    VkPipelineLayoutCreateInfo layoutInfo{};
    layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutInfo.setLayoutCount = setLayout != VK_NULL_HANDLE ? 1u : 0u;
    layoutInfo.pSetLayouts = &setLayout;
    layoutInfo.pushConstantRangeCount = 1;
    layoutInfo.pPushConstantRanges = &range;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    if (vkCreatePipelineLayout(device, &layoutInfo, nullptr, &layout) != VK_SUCCESS) {
        return false;
    }
    m_layoutHandle = layout;
    const VkPipelineCreateFlags createFlags = static_cast<VkPipelineCreateFlags>(m_desc.bindless->pipelineCreateFlags());
    for (u32 i = 0; i < kKernelCount; ++i) {
        VkShaderModuleCreateInfo moduleInfo{};
        moduleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        moduleInfo.codeSize = k[i].bytes;
        moduleInfo.pCode = k[i].words;
        VkShaderModule module = VK_NULL_HANDLE;
        if (vkCreateShaderModule(device, &moduleInfo, nullptr, &module) != VK_SUCCESS) {
            return false;
        }
        VkComputePipelineCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
        info.flags = createFlags;
        info.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        info.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
        info.stage.module = module;
        info.stage.pName = "main";
        info.layout = layout;
        VkPipeline pipeline = VK_NULL_HANDLE;
        const VkResult result = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
        vkDestroyShaderModule(device, module, nullptr);
        m_pipelines[i] = pipeline;
        if (result != VK_SUCCESS) {
            return false;
        }
    }
    return true;
#else
    return false;
#endif
}

bool SsfxGpu::createWork(u32 width, u32 height) {
    const SsfxBufferLayout layout = SsfxBufferLayout::compute(width, height);
    BufferDesc work{};
    work.size = static_cast<usize>(layout.workBytes);
    work.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress, BufferUsage::TransferSrc});
    work.memoryUsage = MemoryUsage::GpuOnly;
    work.name = "ssfx_gpu.work";
    Buffer fresh{};
    if (!m_desc.allocator->createBuffer(work, fresh) || fresh.deviceAddress == 0u) {
        if (fresh.handle != nullptr) {
            m_desc.allocator->destroyBuffer(fresh);
        }
        return false;
    }
    if (m_work.handle != nullptr) {
        Retired old{};
        old.buffer = m_work;
        retire(old);
    }
    m_work = fresh;
    m_workQueue = rg::kNoQueue;
    m_layout = layout;
    ++m_stats.workRebuilds;
    return true;
}

bool SsfxGpu::createOutput(u32 width, u32 height) {
    Output o{};
    TextureDesc d{};
    d.width = width;
    d.height = height;
    d.format = static_cast<GpuFormat>(kOutputFormat);
    d.usage = imageUsage({ImageUsage::Storage, ImageUsage::Sampled, ImageUsage::TransferSrc});
    d.name = "ssfx_gpu.output";
    if (!m_desc.allocator->createImage(d, o.image)) {
        return false;
    }
    o.slot = m_desc.bindless->registerTextureSlot(o.image, true);
    if (!o.slot.isValid()) {
        m_desc.allocator->destroyImage(o.image);
        return false;
    }
    if (m_output.image.image != nullptr) {
        Retired old{};
        old.image = m_output.image;
        old.slots[0] = m_output.slot;
        retire(old);
    }
    m_output = o;
    ++m_stats.outputRebuilds;
    return true;
}

bool SsfxGpu::bindInput(u32 index, const Texture* image) {
    void* handle = image != nullptr ? image->image : nullptr;
    if (handle == m_inputImages[index] && (handle == nullptr || m_inputSlots[index].isValid())) {
        return true;
    }
    if (m_inputSlots[index].isValid()) {
        Retired old{};
        old.slots[1u + index] = m_inputSlots[index];
        retire(old);
    }
    m_inputSlots[index] = BindlessSlotHandle{};
    m_inputImages[index] = nullptr;
    m_inputHandles[index] = 0u;
    if (handle == nullptr) {
        return true;
    }
    m_inputSlots[index] = m_desc.bindless->registerTextureSlot(*image, false);
    if (!m_inputSlots[index].isValid()) {
        return false;
    }
    m_inputImages[index] = handle;
    m_inputHandles[index] = m_desc.bindless->shaderHandle(m_inputSlots[index]);
    ++m_stats.inputBinds;
    return true;
}

void SsfxGpu::retire(Retired r) {
    r.serial = m_frameSerial;
    m_retired.push_back(r);
    ++m_stats.retired;
}

void SsfxGpu::destroyRetired(Retired& r) {
    for (BindlessSlotHandle& slot : r.slots) {
        if (slot.isValid()) {
            m_desc.bindless->unregisterSlot(slot);
        }
    }
    if (r.buffer.handle != nullptr) {
        m_desc.allocator->destroyBuffer(r.buffer);
    }
    if (r.image.image != nullptr) {
        m_desc.allocator->destroyImage(r.image);
    }
    r = Retired{};
}

u32 SsfxGpu::collectRetired(u64 completedSerial) {
    u32 collected = 0;
    usize keep = 0;
    for (usize i = 0; i < m_retired.size(); ++i) {
        if (m_retired[i].serial > completedSerial) {
            m_retired[keep++] = m_retired[i];
            continue;
        }
        destroyRetired(m_retired[i]);
        ++collected;
    }
    m_retired.resize(keep);
    m_stats.retired = m_stats.retired >= collected ? m_stats.retired - collected : 0u;
    return collected;
}

bool SsfxGpu::beginFrame(u64 frameSerial, const SsfxGpuSettings& settings, const SsfxCameraDesc& camera,
                         const f32 (&ambient)[3], const SsfxFrameImages& images) {
    if (!m_initialized) {
        return false;
    }
    const Texture* inputs[kInputCount] = {images.depth, images.normalAo, images.albedo, images.roughMetal, images.lit};
    for (const Texture* t : inputs) {
        if (t == nullptr || t->image == nullptr) {
            return false;
        }
    }
    const u32 w = images.depth->desc.width;
    const u32 h = images.depth->desc.height;
    if (w == 0u || h == 0u) {
        return false;
    }
    for (const Texture* t : inputs) {
        if (t->desc.width != w || t->desc.height != h) {
            return false;
        }
    }
    SsfxFrameConstants c{};
    if (!resolve_constants(settings, camera, ambient, w, h, c)) {
        return false;
    }
    m_frameSerial = frameSerial;
    m_recordCount = 0;
    m_stats.passes = 0;
    m_stats.aoRan = m_stats.ssrRan = false;
    m_stats.ssgiBounces = 0;
    if (w != m_width || h != m_height || m_work.handle == nullptr || m_output.image.image == nullptr) {
        if (!createWork(w, h) || !createOutput(w, h)) {
            return false;
        }
        m_width = w;
        m_height = h;
    }
    for (u32 i = 0; i < kInputCount; ++i) {
        if (!bindInput(i, inputs[i])) {
            return false;
        }
    }
    const u64 work = m_work.deviceAddress;
    c.prepared = work + m_layout.prepared;
    c.normals = work + m_layout.normals;
    c.radiance = work + m_layout.radiance;
    c.albedo = work + m_layout.albedo;
    c.diffuse = work + m_layout.diffuse;
    c.ao = work + m_layout.ao;
    c.ssr = work + m_layout.ssr;
    c.gi = work + m_layout.gi;
    c.bounce0 = work + m_layout.bounce[0];
    c.bounce1 = work + m_layout.bounce[1];
    c.dump = images.dumpAddress;
    c.inputDepth = m_inputHandles[0];
    c.inputNormal = m_inputHandles[1];
    c.inputAlbedo = m_inputHandles[2];
    c.inputRoughMetal = m_inputHandles[3];
    c.inputLit = m_inputHandles[4];
    c.output = m_desc.bindless->shaderHandle(m_output.slot);
    // SSGI with zero bounces writes no indirect light: compose must not read the (stale) section.
    if (c.giBounces == 0u) {
        c.flags &= ~static_cast<u32>(kSsfxFlagSsgi);
    }
    // Sky fallback: only with a sky source (the WP-8.2 AtParams of this frame).
    c.sky = (c.flags & (kSsfxFlagSky | kSsfxFlagSkyGi)) != 0u ? images.skyAddress : 0u;
    if (c.sky == 0u) {
        c.flags &= ~static_cast<u32>(kSsfxFlagSky | kSsfxFlagSkyGi);
    }
    m_hasDump = images.dumpAddress != 0u;
    m_constants = c;
    const u32 slot = static_cast<u32>(frameSerial % m_desc.framesInFlight);
    const u64 offset = static_cast<u64>(slot) * kFrameStride;
    std::memcpy(static_cast<u8*>(m_frameRing.mapped) + offset, &c, sizeof(c));
    m_frameAddress = m_frameRing.deviceAddress + offset;
    return true;
}

SsfxGraphRefs SsfxGpu::importInto(rg::Graph& graph) {
    SsfxGraphRefs refs{};
    if (!m_initialized || m_work.handle == nullptr) {
        return refs;
    }
    refs.work = graph.importBuffer(
        rg::ImportedBuffer{m_work.handle, m_work.desc.size, m_workQueue, &m_workQueue, "ssfx_gpu.work"});
    rg::ImportedImage i{};
    i.image = m_output.image.image;
    i.view = m_output.image.view;
    i.format = kOutputFormat;
    i.width = m_width;
    i.height = m_height;
    i.initialLayout = m_output.layout;
    i.initialQueue = m_output.queue;
    i.layoutTracker = &m_output.layout;
    i.queueTracker = &m_output.queue;
    i.name = "ssfx_gpu.output";
    refs.output = graph.importImage(i);
    return refs;
}

SsfxGpu::PassRecord* SsfxGpu::nextRecord(u32 kernel) {
    if (m_recordCount >= kMaxPasses) {
        return nullptr;
    }
    PassRecord* r = &m_records[m_recordCount++];
    *r = PassRecord{};
    r->self = this;
    r->kernel = kernel;
    r->push.frame = m_frameAddress;
    r->groups[0] = groups(m_width, kSsfxTile);
    r->groups[1] = groups(m_height, kSsfxTile);
    return r;
}

void SsfxGpu::addPasses(rg::Graph& graph, const SsfxGraphRefs& refs, const SsfxGraphInputs& inputs) {
    if (!m_initialized || !refs.work.valid() || !refs.output.valid() || !inputs.normalAo.valid() ||
        !inputs.albedo.valid() || !inputs.roughMetal.valid() || !inputs.depth.valid() || !inputs.lit.valid()) {
        return;
    }
    const SsfxFrameConstants& c = m_constants;

    if (PassRecord* r = nextRecord(kPrepare)) {
        ++m_stats.passes;
        graph.addPass("ssfx.prepare", &SsfxGpu::recordDispatch, r)
            .use(inputs.depth, rg::Access::SampledRead, {}, rg::kStageCompute)
            .use(inputs.normalAo, rg::Access::SampledRead, {}, rg::kStageCompute)
            .use(inputs.albedo, rg::Access::SampledRead, {}, rg::kStageCompute)
            .use(inputs.roughMetal, rg::Access::SampledRead, {}, rg::kStageCompute)
            .use(inputs.lit, rg::Access::SampledRead, {}, rg::kStageCompute)
            .use(refs.work, rg::Access::StorageReadWrite, {}, rg::kStageCompute);
    }
    if ((c.flags & kSsfxFlagAo) != 0u) {
        if (PassRecord* r = nextRecord(kGtao)) {
            ++m_stats.passes;
            m_stats.aoRan = true;
            graph.addPass("ssfx.gtao", &SsfxGpu::recordDispatch, r)
                .use(refs.work, rg::Access::StorageReadWrite, {}, rg::kStageCompute);
        }
    }
    if ((c.flags & kSsfxFlagSsr) != 0u) {
        if (PassRecord* r = nextRecord(kSsr)) {
            ++m_stats.passes;
            m_stats.ssrRan = true;
            rg::PassBuilder pass = graph.addPass("ssfx.ssr", &SsfxGpu::recordDispatch, r);
            pass.use(refs.work, rg::Access::StorageReadWrite, {}, rg::kStageCompute);
            if ((c.flags & kSsfxFlagSky) != 0u && inputs.sky.valid()) {
                pass.use(inputs.sky, rg::Access::StorageRead, {}, rg::kStageCompute); // the sky fallback's LUTs
            }
        }
    }
    if ((c.flags & kSsfxFlagSsgi) != 0u) {
        // ssgi_kernel::run_bounces: bounce 0 gathers the lit radiance; bounce b > 0 the previous bounce's
        // direct + indirect from the ping-pong sections.
        const u64 base = m_work.deviceAddress;
        u64 in = base + m_layout.radiance;
        u64 next = base + m_layout.bounce[0];
        u64 spare = base + m_layout.bounce[1];
        for (u32 bounce = 0; bounce < c.giBounces; ++bounce) {
            PassRecord* r = nextRecord(kSsgi);
            if (r == nullptr) {
                break;
            }
            const bool last = bounce + 1u == c.giBounces;
            r->push.src = in;
            r->push.dst = last ? 0u : next;
            r->push.mode = bounce;
            ++m_stats.passes;
            ++m_stats.ssgiBounces;
            rg::PassBuilder pass = graph.addPass("ssfx.ssgi", &SsfxGpu::recordDispatch, r);
            pass.use(refs.work, rg::Access::StorageReadWrite, {}, rg::kStageCompute);
            if ((c.flags & kSsfxFlagSkyGi) != 0u && inputs.sky.valid()) {
                pass.use(inputs.sky, rg::Access::StorageRead, {}, rg::kStageCompute);
            }
            if (!last) {
                in = next;
                const u64 written = next;
                next = spare;
                spare = written;
            }
        }
    }
    if (PassRecord* r = nextRecord(kCompose)) {
        ++m_stats.passes;
        rg::PassBuilder compose = graph.addPass("ssfx.compose", &SsfxGpu::recordDispatch, r);
        compose.use(refs.work, rg::Access::StorageRead, {}, rg::kStageCompute);
        compose.use(refs.output, rg::Access::StorageWrite, {}, rg::kStageCompute);
        if (m_hasDump && inputs.dump.valid()) {
            compose.use(inputs.dump, rg::Access::StorageWrite,
                        rg::BufferRange{0, static_cast<u64>(m_width) * m_height * kTexel}, rg::kStageCompute);
        }
    }
}

u64 SsfxGpu::copyBytes(SsfxCopySource what) const {
    const u64 n = static_cast<u64>(m_width) * m_height;
    return what == SsfxCopySource::Ao ? n * kScalar : n * kTexel;
}

void SsfxGpu::addCopy(rg::Graph& graph, const SsfxGraphRefs& refs, SsfxCopySource what, rg::BufferRef dst,
                      u64 dstOffset) {
    if (!m_initialized || !dst.valid() || !refs.work.valid()) {
        return;
    }
    PassRecord* r = nextRecord(kKernelCount);
    if (r == nullptr) {
        return;
    }
    u64 src = 0;
    switch (what) {
    case SsfxCopySource::Prepared: src = m_layout.prepared; break;
    case SsfxCopySource::Normals: src = m_layout.normals; break;
    case SsfxCopySource::Radiance: src = m_layout.radiance; break;
    case SsfxCopySource::Albedo: src = m_layout.albedo; break;
    case SsfxCopySource::Diffuse: src = m_layout.diffuse; break;
    case SsfxCopySource::Ao: src = m_layout.ao; break;
    case SsfxCopySource::Ssr: src = m_layout.ssr; break;
    case SsfxCopySource::Gi: src = m_layout.gi; break;
    }
    r->copySrc = src;
    r->copyBytes = copyBytes(what);
    r->copyDst = dstOffset;
    r->copyFrom = refs.work;
    r->copyTo = dst;
    ++m_stats.passes;
    graph.addPass("ssfx.copy", &SsfxGpu::recordCopy, r)
        .use(refs.work, rg::Access::TransferSrc, rg::BufferRange{r->copySrc, r->copyBytes})
        .use(dst, rg::Access::TransferDst, rg::BufferRange{dstOffset, r->copyBytes});
}

void SsfxGpu::recordDispatch(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const SsfxGpu& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, static_cast<VkPipeline>(self.m_pipelines[r.kernel]));
    self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, self.m_layoutHandle, 0);
    vkCmdPushConstants(cmd, static_cast<VkPipelineLayout>(self.m_layoutHandle), VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       kPushBytes, &r.push);
    vkCmdDispatch(cmd, r.groups[0], r.groups[1], r.groups[2]);
#else
    (void)context;
    (void)user;
#endif
}

void SsfxGpu::recordCopy(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    const VkBufferCopy region{r.copySrc, r.copyDst, r.copyBytes};
    vkCmdCopyBuffer(cmd, static_cast<VkBuffer>(context.buffer(r.copyFrom)), static_cast<VkBuffer>(context.buffer(r.copyTo)),
                    1, &region);
#else
    (void)context;
    (void)user;
#endif
}

} // namespace fuse::renderer::ssfx_gpu
