// WP-6.5 radiance cascades (research) on Vulkan: see include/fuse/renderer/research/rc/rc_gpu.hpp.
#include <fuse/renderer/research/rc/rc_gpu.hpp>

#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/bindless.hpp>
#include <fuse/renderer/vk/device.hpp>

#include <cstring>
#include <initializer_list>

#if defined(FUSE_VULKAN_BACKEND)
#include <vulkan/vulkan.h>

// Generated by cmake/rp_wp65.cmake from research/radiance_cascades/shaders/*: kRc<Kernel><Slang|Glsl>Spv and
// FUSE_RC_GPU_{SLANG,GLSL} when every kernel of a language exists.
#include "rc_gpu_spv.h"
#endif

namespace fuse::renderer::research::rc {

namespace {
constexpr u32 kPushBytes = sizeof(RcPush);
constexpr u64 kRecord = 16u; ///< f32x4

BufferUsage bufferUsage(std::initializer_list<BufferUsage> bits) {
    u32 u = 0;
    for (const BufferUsage b : bits) {
        u |= static_cast<u32>(b);
    }
    return static_cast<BufferUsage>(u);
}

u64 align256(u64 v) { return (v + 255u) & ~u64{255u}; }

u32 groups(u64 items) { return items == 0u ? 1u : static_cast<u32>((items + kRcGroupSize - 1u) / kRcGroupSize); }

bool sameLayout(const RcLayout& a, const RcLayout& b) {
    if (a.cascades != b.cascades || a.dirTotal != b.dirTotal || a.maxRecords != b.maxRecords) {
        return false;
    }
    for (u32 i = 0; i < a.cascades; ++i) {
        if (a.probesX[i] != b.probesX[i] || a.probesY[i] != b.probesY[i] || a.dirs[i] != b.dirs[i]) {
            return false;
        }
    }
    return true;
}

#if defined(FUSE_VULKAN_BACKEND)
struct Code {
    const u32* words = nullptr;
    usize bytes = 0;
};
template <usize N>
Code code(const u32 (&spv)[N]) {
    return Code{spv, sizeof(spv)};
}
#endif
} // namespace

RcBufferLayout RcBufferLayout::compute(const RcLayout& layout, u32 width, u32 height) {
    RcBufferLayout l{};
    u64 cursor = 0;
    auto take = [&](u64 bytes) {
        const u64 at = cursor;
        cursor = align256(cursor + (bytes < 16u ? 16u : bytes));
        return at;
    };
    l.cascade[0] = take(layout.maxRecords * kRecord);
    l.cascade[1] = take(layout.maxRecords * kRecord);
    l.output = take(static_cast<u64>(width) * height * kRecord);
    l.workBytes = cursor;
    return l;
}

RcCapabilities queryRcCapabilities(const VulkanDevice* device) {
    RcCapabilities c{};
#if defined(FUSE_VULKAN_BACKEND)
    if (device == nullptr || !device->isValid()) {
        return c;
    }
    const RendererCaps& caps = device->info().caps;
    if (!caps.bufferDeviceAddress || !caps.shaderInt64) {
        c.reason = "bufferDeviceAddress / shaderInt64 missing";
        return c;
    }
    c.rc = true;
    c.reason = "ok";
#else
    (void)device;
    c.reason = "stub backend";
#endif
    return c;
}

RadianceCascadesGpu::~RadianceCascadesGpu() { destroy(); }

bool RadianceCascadesGpu::init(const RcGpuDesc& desc) {
    destroy();
    m_desc = desc;
#if defined(FUSE_VULKAN_BACKEND)
    if (desc.allocator == nullptr || !queryRcCapabilities(desc.device).rc) {
        return false;
    }
    m_retired.reserve(8);
    m_initialized = true; // destroy() releases partial state from here on
    if (!createPipelines()) {
        destroy();
        return false;
    }
    return true;
#else
    return false;
#endif
}

void RadianceCascadesGpu::destroy() {
    if (!m_initialized) {
        return;
    }
#if defined(FUSE_VULKAN_BACKEND)
    collectRetired(~0ull);
    Retired current{};
    current.work = m_work;
    current.dirs = m_dirs;
    destroyRetired(current);
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    for (void*& pipeline : m_pipelines) {
        if (pipeline != nullptr) {
            vkDestroyPipeline(device, static_cast<VkPipeline>(pipeline), nullptr);
            pipeline = nullptr;
        }
    }
    if (m_layoutHandle != nullptr) {
        vkDestroyPipelineLayout(device, static_cast<VkPipelineLayout>(m_layoutHandle), nullptr);
    }
#endif
    m_layoutHandle = nullptr;
    m_work = Buffer{};
    m_dirs = Buffer{};
    m_workQueue = rg::kNoQueue;
    m_retired.clear();
    m_width = m_height = 0;
    m_scene = 0;
    m_layout = RcLayout{};
    m_buffers = RcBufferLayout{};
    m_recordCount = 0;
    m_language = "none";
    m_stats = RcGpuStats{};
    m_initialized = false;
}

bool RadianceCascadesGpu::createPipelines() {
#if defined(FUSE_VULKAN_BACKEND)
    Code k[kKernelCount]{};
    bool found = false;
#if defined(FUSE_RC_GPU_SLANG)
    if (m_desc.language == RcKernelLanguage::Auto || m_desc.language == RcKernelLanguage::Slang) {
        k[kCascade] = code(kRcCascadeSlangSpv);
        k[kGather] = code(kRcGatherSlangSpv);
        m_language = "slang";
        found = true;
    }
#endif
#if defined(FUSE_RC_GPU_GLSL)
    if (!found && (m_desc.language == RcKernelLanguage::Auto || m_desc.language == RcKernelLanguage::Glsl)) {
        k[kCascade] = code(kRcCascadeGlslSpv);
        k[kGather] = code(kRcGatherGlslSpv);
        m_language = "glsl";
        found = true;
    }
#endif
    if (!found) {
        return false;
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    VkDescriptorSetLayout setLayout =
        m_desc.bindless != nullptr ? static_cast<VkDescriptorSetLayout>(m_desc.bindless->layoutHandle()) : VK_NULL_HANDLE;
    VkPushConstantRange range{VK_SHADER_STAGE_COMPUTE_BIT, 0, kPushBytes};
    VkPipelineLayoutCreateInfo layoutInfo{};
    layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutInfo.setLayoutCount = setLayout != VK_NULL_HANDLE ? 1u : 0u;
    layoutInfo.pSetLayouts = &setLayout;
    layoutInfo.pushConstantRangeCount = 1;
    layoutInfo.pPushConstantRanges = &range;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    if (vkCreatePipelineLayout(device, &layoutInfo, nullptr, &layout) != VK_SUCCESS) {
        return false;
    }
    m_layoutHandle = layout;
    const VkPipelineCreateFlags createFlags =
        m_desc.bindless != nullptr ? static_cast<VkPipelineCreateFlags>(m_desc.bindless->pipelineCreateFlags()) : 0u;
    for (u32 i = 0; i < kKernelCount; ++i) {
        VkShaderModuleCreateInfo moduleInfo{};
        moduleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        moduleInfo.codeSize = k[i].bytes;
        moduleInfo.pCode = k[i].words;
        VkShaderModule module = VK_NULL_HANDLE;
        if (vkCreateShaderModule(device, &moduleInfo, nullptr, &module) != VK_SUCCESS) {
            return false;
        }
        VkComputePipelineCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
        info.flags = createFlags;
        info.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        info.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
        info.stage.module = module;
        info.stage.pName = "main";
        info.layout = layout;
        VkPipeline pipeline = VK_NULL_HANDLE;
        const VkResult result = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
        vkDestroyShaderModule(device, module, nullptr);
        m_pipelines[i] = pipeline;
        if (result != VK_SUCCESS) {
            return false;
        }
    }
    return true;
#else
    return false;
#endif
}

bool RadianceCascadesGpu::rebuild(const RcLayout& layout, u32 width, u32 height) {
    const RcBufferLayout buffers = RcBufferLayout::compute(layout, width, height);
    BufferDesc work{};
    work.size = static_cast<usize>(buffers.workBytes);
    work.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress, BufferUsage::TransferSrc});
    work.memoryUsage = MemoryUsage::GpuOnly;
    work.name = "rc.work";
    buildDirectionTable(layout, m_dirScratch);
    BufferDesc dirs{};
    dirs.size = m_dirScratch.size() * sizeof(f32);
    dirs.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress});
    dirs.memoryUsage = MemoryUsage::CpuToGpu;
    dirs.name = "rc.dirs";
    Buffer freshWork{};
    Buffer freshDirs{};
    const bool ok = m_desc.allocator->createBuffer(work, freshWork) && freshWork.deviceAddress != 0u &&
                    m_desc.allocator->createBuffer(dirs, freshDirs) && freshDirs.deviceAddress != 0u &&
                    freshDirs.mapped != nullptr;
    if (!ok) {
        Retired r{};
        r.work = freshWork;
        r.dirs = freshDirs;
        destroyRetired(r);
        return false;
    }
    std::memcpy(freshDirs.mapped, m_dirScratch.data(), dirs.size);
    if (m_work.handle != nullptr || m_dirs.handle != nullptr) {
        Retired old{};
        old.work = m_work;
        old.dirs = m_dirs;
        old.serial = m_frameSerial;
        m_retired.push_back(old);
        ++m_stats.retired;
    }
    m_work = freshWork;
    m_dirs = freshDirs;
    m_workQueue = rg::kNoQueue;
    m_buffers = buffers;
    ++m_stats.layoutRebuilds;
    return true;
}

void RadianceCascadesGpu::destroyRetired(Retired& r) {
    if (r.work.handle != nullptr) {
        m_desc.allocator->destroyBuffer(r.work);
    }
    if (r.dirs.handle != nullptr) {
        m_desc.allocator->destroyBuffer(r.dirs);
    }
    r = Retired{};
}

u32 RadianceCascadesGpu::collectRetired(u64 completedSerial) {
    u32 collected = 0;
    usize keep = 0;
    for (usize i = 0; i < m_retired.size(); ++i) {
        if (m_retired[i].serial > completedSerial) {
            m_retired[keep++] = m_retired[i];
            continue;
        }
        destroyRetired(m_retired[i]);
        ++collected;
    }
    m_retired.resize(keep);
    m_stats.retired = m_stats.retired >= collected ? m_stats.retired - collected : 0u;
    return collected;
}

bool RadianceCascadesGpu::beginFrame(u64 frameSerial, const RcSettings& settings, u32 width, u32 height,
                                     u64 sceneAddress) {
    if (!m_initialized || sceneAddress == 0u) {
        return false;
    }
    RcLayout layout{};
    if (!RcLayout::compute(settings, width, height, layout)) {
        return false;
    }
    m_frameSerial = frameSerial;
    m_recordCount = 0;
    m_stats.passes = 0;
    // The direction table depends on the per-cascade direction counts only; the work buffer on the record
    // counts and the extent.
    if (m_work.handle == nullptr || width != m_width || height != m_height || !sameLayout(layout, m_layout)) {
        if (!rebuild(layout, width, height)) {
            return false;
        }
        m_width = width;
        m_height = height;
    }
    m_layout = layout;
    m_settings = settings;
    m_scene = sceneAddress;
    return true;
}

RcGraphRefs RadianceCascadesGpu::importInto(rg::Graph& graph) {
    RcGraphRefs refs{};
    if (!m_initialized || m_work.handle == nullptr) {
        return refs;
    }
    refs.work =
        graph.importBuffer(rg::ImportedBuffer{m_work.handle, m_work.desc.size, m_workQueue, &m_workQueue, "rc.work"});
    return refs;
}

RadianceCascadesGpu::PassRecord* RadianceCascadesGpu::nextRecord(u32 kernel) {
    if (m_recordCount >= kMaxPasses) {
        return nullptr;
    }
    PassRecord* r = &m_records[m_recordCount++];
    *r = PassRecord{};
    r->self = this;
    r->kernel = kernel;
    return r;
}

void RadianceCascadesGpu::addPasses(rg::Graph& graph, const RcGraphRefs& refs, rg::BufferRef scene) {
    if (!m_initialized || !refs.work.valid() || !scene.valid() || m_layout.cascades == 0u) {
        return;
    }
    const u64 work = m_work.deviceAddress;
    u64 upper = 0;
    for (u32 ci = m_layout.cascades; ci-- > 0u;) {
        PassRecord* r = nextRecord(kCascade);
        if (r == nullptr) {
            return;
        }
        r->push = makeCascadePush(m_layout, m_settings, ci, m_width, m_height);
        r->push.scene = m_scene;
        r->push.dirs = m_dirs.deviceAddress + static_cast<u64>(m_layout.dirOffset[ci]) * kRecord;
        r->push.upper = upper;
        r->push.dst = work + m_buffers.cascade[ci & 1u];
        r->groups = groups(r->push.count);
        upper = r->push.dst;
        ++m_stats.passes;
        graph.addPass("rc.cascade", &RadianceCascadesGpu::recordDispatch, r)
            .use(scene, rg::Access::StorageRead, {}, rg::kStageCompute)
            .use(refs.work, rg::Access::StorageReadWrite, {}, rg::kStageCompute);
    }
    if (PassRecord* r = nextRecord(kGather)) {
        r->push = makeGatherPush(m_layout, m_settings, m_width, m_height);
        r->push.upper = upper;
        r->push.dst = work + m_buffers.output;
        r->groups = groups(r->push.count);
        ++m_stats.passes;
        graph.addPass("rc.gather", &RadianceCascadesGpu::recordDispatch, r)
            .use(refs.work, rg::Access::StorageReadWrite, {}, rg::kStageCompute);
    }
}

void RadianceCascadesGpu::addCopyOutput(rg::Graph& graph, const RcGraphRefs& refs, rg::BufferRef dst, u64 dstOffset) {
    if (!m_initialized || !dst.valid() || !refs.work.valid()) {
        return;
    }
    PassRecord* r = nextRecord(kKernelCount);
    if (r == nullptr) {
        return;
    }
    r->copySrc = m_buffers.output;
    r->copyBytes = outputBytes();
    r->copyDst = dstOffset;
    r->copyFrom = refs.work;
    r->copyTo = dst;
    ++m_stats.passes;
    graph.addPass("rc.copy", &RadianceCascadesGpu::recordCopy, r)
        .use(refs.work, rg::Access::TransferSrc, rg::BufferRange{r->copySrc, r->copyBytes})
        .use(dst, rg::Access::TransferDst, rg::BufferRange{dstOffset, r->copyBytes});
}

void RadianceCascadesGpu::recordDispatch(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const RadianceCascadesGpu& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, static_cast<VkPipeline>(self.m_pipelines[r.kernel]));
    if (self.m_desc.bindless != nullptr) {
        self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, self.m_layoutHandle, 0);
    }
    vkCmdPushConstants(cmd, static_cast<VkPipelineLayout>(self.m_layoutHandle), VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       kPushBytes, &r.push);
    vkCmdDispatch(cmd, r.groups, 1u, 1u);
#else
    (void)context;
    (void)user;
#endif
}

void RadianceCascadesGpu::recordCopy(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    const VkBufferCopy region{r.copySrc, r.copyDst, r.copyBytes};
    vkCmdCopyBuffer(cmd, static_cast<VkBuffer>(context.buffer(r.copyFrom)),
                    static_cast<VkBuffer>(context.buffer(r.copyTo)), 1, &region);
#else
    (void)context;
    (void)user;
#endif
}

} // namespace fuse::renderer::research::rc
