// WP-1.5 material resolve: see include/fuse/renderer/material_resolve/material_resolve.hpp.
#include <fuse/renderer/material_resolve/material_resolve.hpp>

#include <fuse/renderer/deferred/gbuffer.hpp>
#include <fuse/renderer/visbuffer/vis_format.hpp>
#include <fuse/renderer/visbuffer/visbuffer.hpp>
#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/device.hpp>

#include <cstring>
#include <initializer_list>

#if defined(FUSE_VULKAN_BACKEND)
#include <vulkan/vulkan.h>

// Generated by cmake/rp_wp15.cmake from shaders/material_resolve/*: kMr<Kernel><Slang|Glsl>Spv and
// FUSE_MATERIAL_RESOLVE_{SLANG,GLSL} when every kernel of a language exists (the forward reference
// shaders are GLSL only).
#include "material_resolve_spv.h"
#endif

namespace fuse::renderer::material_resolve {

namespace {
constexpr u32 kPushBytes = sizeof(ResolvePush);
constexpr u32 kFrameStride = 256u; ///< ring slot size (>= sizeof(ResolveFrameConstants), 256-aligned)
static_assert(sizeof(ResolveFrameConstants) <= kFrameStride, "frame ring slot");
constexpr u32 kGBufferTargets = kResolveColorAttachments - 1u;
constexpr u32 kSlotMaterialId = kGBufferTargets;      ///< Targets::layouts / queues index
constexpr u32 kSlotForwardIds = kGBufferTargets + 1u;
constexpr u32 kSlotForwardDepth = kGBufferTargets + 2u;
constexpr u32 kSlotBins = kGBufferTargets + 3u; ///< queues only

#if defined(FUSE_VULKAN_BACKEND)
struct Code {
    const u32* words = nullptr;
    usize bytes = 0;
};
template <usize N>
Code code(const u32 (&spv)[N]) {
    return Code{spv, sizeof(spv)};
}
struct KernelSet {
    Code classify, attributes, resolveVs, resolveFs, forwardVs, forwardFs;
};

VkFormat gbufferFormat(u32 i) { return static_cast<VkFormat>(GBufferLayout::format(static_cast<GBufferAttachment>(i))); }
#endif

BufferUsage bufferUsage(std::initializer_list<BufferUsage> bits) {
    u32 u = 0;
    for (const BufferUsage b : bits) {
        u |= static_cast<u32>(b);
    }
    return static_cast<BufferUsage>(u);
}

ImageUsage imageUsage(std::initializer_list<ImageUsage> bits) {
    u32 u = 0;
    for (const ImageUsage b : bits) {
        u |= static_cast<u32>(b);
    }
    return static_cast<ImageUsage>(u);
}
} // namespace

ResolveCapabilities queryResolveCapabilities(const VulkanDevice* device) {
    ResolveCapabilities c{};
#if defined(FUSE_VULKAN_BACKEND)
    const visbuffer::VisCapabilities vis = visbuffer::queryVisCapabilities(device);
    if (!vis.raster) {
        c.reason = vis.rasterReason;
        return c;
    }
    VkPhysicalDeviceProperties props{};
    vkGetPhysicalDeviceProperties(static_cast<VkPhysicalDevice>(device->nativePhysicalDevice()), &props);
    if (props.limits.maxColorAttachments < kResolveColorAttachments) {
        c.reason = "fewer than 7 colour attachments";
        return c;
    }
    c.resolve = true;
    c.forward = props.limits.maxColorAttachments >= kForwardColorAttachments;
    c.reason = "ok";
#else
    (void)device;
    c.reason = "stub backend";
#endif
    return c;
}

MaterialResolve::~MaterialResolve() { destroy(); }

bool MaterialResolve::init(const MaterialResolveDesc& desc) {
    destroy();
    m_desc = desc;
#if defined(FUSE_VULKAN_BACKEND)
    if (desc.allocator == nullptr || desc.bindless == nullptr || desc.framesInFlight == 0u) {
        return false;
    }
    const ResolveCapabilities caps = queryResolveCapabilities(desc.device);
    if (!caps.resolve || (desc.forward && !caps.forward)) {
        return false;
    }
    m_retired.reserve(4);
    m_initialized = true; // destroy() releases partial state from here on
    BufferDesc ring{};
    ring.size = static_cast<usize>(desc.framesInFlight) * kFrameStride;
    ring.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress});
    ring.memoryUsage = MemoryUsage::CpuToGpu;
    ring.name = "material_resolve.frame";
    if (!m_desc.allocator->createBuffer(ring, m_frameRing) || m_frameRing.mapped == nullptr ||
        m_frameRing.deviceAddress == 0u || !createPipelines() ||
        (desc.width > 0u && desc.height > 0u && !resize(desc.width, desc.height))) {
        destroy();
        return false;
    }
    m_stats.targetRebuilds = desc.width > 0u ? 1u : 0u;
    return true;
#else
    return false;
#endif
}

void MaterialResolve::destroy() {
    if (!m_initialized) {
        return;
    }
#if defined(FUSE_VULKAN_BACKEND)
    collectRetired(~0ull);
    destroyTargets(m_targets);
    if (m_frameRing.handle != nullptr) {
        m_desc.allocator->destroyBuffer(m_frameRing);
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    for (void*& pipeline : m_resolvePipelines) {
        if (pipeline != nullptr) {
            vkDestroyPipeline(device, static_cast<VkPipeline>(pipeline), nullptr);
            pipeline = nullptr;
        }
    }
    for (void* pipeline : {m_classifyPipeline, m_attributesPipeline, m_forwardPipeline}) {
        if (pipeline != nullptr) {
            vkDestroyPipeline(device, static_cast<VkPipeline>(pipeline), nullptr);
        }
    }
    for (void* layout : {m_graphicsLayout, m_computeLayout}) {
        if (layout != nullptr) {
            vkDestroyPipelineLayout(device, static_cast<VkPipelineLayout>(layout), nullptr);
        }
    }
#endif
    m_classifyPipeline = m_attributesPipeline = m_forwardPipeline = nullptr;
    m_graphicsLayout = m_computeLayout = nullptr;
    m_targets = Targets{};
    m_frameRing = Buffer{};
    m_frameAddress = 0;
    m_retired.clear();
    m_width = m_height = 0;
    m_recordCount = 0;
    m_language = "none";
    m_stats = ResolveStats{};
    m_initialized = false;
}

bool MaterialResolve::createPipelines() {
#if defined(FUSE_VULKAN_BACKEND)
    KernelSet k{};
    bool found = false;
#if defined(FUSE_MATERIAL_RESOLVE_SLANG)
    if (m_desc.language == ResolveKernelLanguage::Auto || m_desc.language == ResolveKernelLanguage::Slang) {
        k.classify = code(kMrClassifySlangSpv);
        k.attributes = code(kMrAttributesSlangSpv);
        k.resolveVs = code(kMrResolveVsSlangSpv);
        k.resolveFs = code(kMrResolveFsSlangSpv);
        m_language = "slang";
        found = true;
    }
#endif
#if defined(FUSE_MATERIAL_RESOLVE_GLSL)
    if (!found && (m_desc.language == ResolveKernelLanguage::Auto || m_desc.language == ResolveKernelLanguage::Glsl)) {
        k.classify = code(kMrClassifyGlslSpv);
        k.attributes = code(kMrAttributesGlslSpv);
        k.resolveVs = code(kMrResolveVsGlslSpv);
        k.resolveFs = code(kMrResolveFsGlslSpv);
        m_language = "glsl";
        found = true;
    }
    k.forwardVs = code(kMrForwardVsGlslSpv);
    k.forwardFs = code(kMrForwardFsGlslSpv);
#endif
    if (!found || (m_desc.forward && k.forwardVs.words == nullptr)) {
        return false;
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    VkDescriptorSetLayout setLayout = static_cast<VkDescriptorSetLayout>(m_desc.bindless->layoutHandle());
    auto makeLayout = [&](VkShaderStageFlags stages, void*& out) {
        VkPushConstantRange range{stages, 0, kPushBytes};
        VkPipelineLayoutCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
        info.setLayoutCount = setLayout != VK_NULL_HANDLE ? 1u : 0u;
        info.pSetLayouts = &setLayout;
        info.pushConstantRangeCount = 1;
        info.pPushConstantRanges = &range;
        VkPipelineLayout layout = VK_NULL_HANDLE;
        const bool ok = vkCreatePipelineLayout(device, &info, nullptr, &layout) == VK_SUCCESS;
        out = layout;
        return ok;
    };
    if (!makeLayout(VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, m_graphicsLayout) ||
        !makeLayout(VK_SHADER_STAGE_COMPUTE_BIT, m_computeLayout)) {
        return false;
    }
    auto module = [&](const Code& c) {
        VkShaderModuleCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        info.codeSize = c.bytes;
        info.pCode = c.words;
        VkShaderModule m = VK_NULL_HANDLE;
        vkCreateShaderModule(device, &info, nullptr, &m);
        return m;
    };
    const VkPipelineCreateFlags createFlags = static_cast<VkPipelineCreateFlags>(m_desc.bindless->pipelineCreateFlags());
    auto compute = [&](const Code& c, void*& out) {
        VkShaderModule m = module(c);
        if (m == VK_NULL_HANDLE) {
            return false;
        }
        VkComputePipelineCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
        info.flags = createFlags;
        info.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        info.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
        info.stage.module = m;
        info.stage.pName = "main";
        info.layout = static_cast<VkPipelineLayout>(m_computeLayout);
        VkPipeline pipeline = VK_NULL_HANDLE;
        const VkResult result = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
        vkDestroyShaderModule(device, m, nullptr);
        out = pipeline;
        return result == VK_SUCCESS;
    };
    // Resolve (7 colour attachments, no depth, specialised by bin) or forward (8 + D32, LESS).
    auto graphics = [&](const Code& vsCode, const Code& fsCode, const u32* bin, bool forward, void*& out) {
        VkShaderModule vs = module(vsCode);
        VkShaderModule fs = module(fsCode);
        if (vs == VK_NULL_HANDLE || fs == VK_NULL_HANDLE) {
            vkDestroyShaderModule(device, vs, nullptr);
            vkDestroyShaderModule(device, fs, nullptr);
            return false;
        }
        const VkSpecializationMapEntry entry{0u, 0u, sizeof(u32)};
        VkSpecializationInfo spec{};
        spec.mapEntryCount = 1;
        spec.pMapEntries = &entry;
        spec.dataSize = sizeof(u32);
        spec.pData = bin;
        VkPipelineShaderStageCreateInfo stages[2]{};
        stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
        stages[0].module = vs;
        stages[0].pName = "main";
        stages[0].pSpecializationInfo = bin != nullptr ? &spec : nullptr;
        stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
        stages[1].module = fs;
        stages[1].pName = "main";
        stages[1].pSpecializationInfo = bin != nullptr ? &spec : nullptr;
        VkPipelineVertexInputStateCreateInfo vertexInput{};
        vertexInput.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
        VkPipelineInputAssemblyStateCreateInfo assembly{};
        assembly.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
        assembly.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
        VkPipelineViewportStateCreateInfo viewport{};
        viewport.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
        viewport.viewportCount = 1;
        viewport.scissorCount = 1;
        VkPipelineRasterizationStateCreateInfo rasterization{};
        rasterization.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
        rasterization.polygonMode = VK_POLYGON_MODE_FILL;
        rasterization.cullMode = VK_CULL_MODE_NONE; // forward: two-sided like the visibility raster
        rasterization.lineWidth = 1.f;
        VkPipelineMultisampleStateCreateInfo multisample{};
        multisample.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
        multisample.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;
        VkPipelineDepthStencilStateCreateInfo depth{};
        depth.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
        depth.depthTestEnable = forward ? VK_TRUE : VK_FALSE;
        depth.depthWriteEnable = forward ? VK_TRUE : VK_FALSE;
        depth.depthCompareOp = VK_COMPARE_OP_LESS;
        VkPipelineColorBlendAttachmentState blendAttachments[kForwardColorAttachments]{};
        VkFormat formats[kForwardColorAttachments]{};
        const u32 colorCount = forward ? kForwardColorAttachments : kResolveColorAttachments;
        for (u32 i = 0; i < colorCount; ++i) {
            blendAttachments[i].colorWriteMask =
                VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
            formats[i] = i < kGBufferTargets ? gbufferFormat(i)
                                             : (i == kSlotMaterialId ? static_cast<VkFormat>(kMaterialIdFormat)
                                                                     : static_cast<VkFormat>(visbuffer::kVisRasterFormat));
        }
        VkPipelineColorBlendStateCreateInfo blend{};
        blend.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
        blend.attachmentCount = colorCount;
        blend.pAttachments = blendAttachments;
        const VkDynamicState dynamics[2] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
        VkPipelineDynamicStateCreateInfo dynamic{};
        dynamic.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
        dynamic.dynamicStateCount = 2;
        dynamic.pDynamicStates = dynamics;
        VkPipelineRenderingCreateInfo rendering{};
        rendering.sType = VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO;
        rendering.colorAttachmentCount = colorCount;
        rendering.pColorAttachmentFormats = formats;
        rendering.depthAttachmentFormat = forward ? static_cast<VkFormat>(visbuffer::kVisDepthFormat) : VK_FORMAT_UNDEFINED;
        VkGraphicsPipelineCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
        info.pNext = &rendering;
        info.flags = createFlags;
        info.stageCount = 2;
        info.pStages = stages;
        info.pVertexInputState = &vertexInput;
        info.pInputAssemblyState = &assembly;
        info.pViewportState = &viewport;
        info.pRasterizationState = &rasterization;
        info.pMultisampleState = &multisample;
        info.pDepthStencilState = &depth;
        info.pColorBlendState = &blend;
        info.pDynamicState = &dynamic;
        info.layout = static_cast<VkPipelineLayout>(m_graphicsLayout);
        VkPipeline pipeline = VK_NULL_HANDLE;
        const VkResult result = vkCreateGraphicsPipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
        vkDestroyShaderModule(device, vs, nullptr);
        vkDestroyShaderModule(device, fs, nullptr);
        out = pipeline;
        return result == VK_SUCCESS;
    };
    if (!compute(k.classify, m_classifyPipeline) || !compute(k.attributes, m_attributesPipeline)) {
        return false;
    }
    static constexpr u32 kBins[kBinCount + 1u] = {kBinEmpty, kBinFlat, kBinTextured, kBinNormalMapped, kBinUber};
    for (u32 b = 0; b <= kBinCount; ++b) {
        if (!graphics(k.resolveVs, k.resolveFs, &kBins[b], false, m_resolvePipelines[b])) {
            return false;
        }
    }
    return !m_desc.forward || graphics(k.forwardVs, k.forwardFs, nullptr, true, m_forwardPipeline);
#else
    return false;
#endif
}

bool MaterialResolve::createTargets(Targets& t, u32 width, u32 height) {
    t = Targets{};
    bool ok = true;
    auto image = [&](Texture& tex, u32 format, ImageUsage usage, const char* name) {
        TextureDesc d{};
        d.width = width;
        d.height = height;
        d.format = static_cast<GpuFormat>(format);
        d.usage = usage;
        d.name = name;
        ok = ok && m_desc.allocator->createImage(d, tex);
    };
    static const char* const kNames[kGBufferTargets] = {"gbuffer.rt0_normal_ao", "gbuffer.rt1_albedo",
                                                        "gbuffer.rt2_rough_metal", "gbuffer.rt3_velocity",
                                                        "gbuffer.rt4_depth",       "gbuffer.rt5_emissive"};
    const ImageUsage colour = imageUsage({ImageUsage::ColorAttachment, ImageUsage::Sampled, ImageUsage::TransferSrc});
    for (u32 i = 0; i < kGBufferTargets; ++i) {
        image(t.gbuffer[i], static_cast<u32>(GBufferLayout::format(static_cast<GBufferAttachment>(i))), colour, kNames[i]);
    }
    image(t.materialId, kMaterialIdFormat, colour, "gbuffer.material_id");
    if (m_desc.forward) {
        image(t.forwardIds, visbuffer::kVisRasterFormat, imageUsage({ImageUsage::ColorAttachment, ImageUsage::TransferSrc}),
              "material_resolve.forward_ids");
        image(t.forwardDepth, visbuffer::kVisDepthFormat,
              imageUsage({ImageUsage::DepthStencilAttachment, ImageUsage::TransferSrc}), "material_resolve.forward_depth");
    }
    const u32 tiles = ((width + kTileSize - 1u) / kTileSize) * ((height + kTileSize - 1u) / kTileSize);
    BufferDesc bins{};
    bins.size = static_cast<usize>(ResolveBinLayout::bytes(tiles));
    bins.usage = bufferUsage({BufferUsage::Storage, BufferUsage::Indirect, BufferUsage::TransferDst, BufferUsage::TransferSrc,
                              BufferUsage::ShaderDeviceAddress});
    bins.memoryUsage = MemoryUsage::GpuOnly;
    bins.name = "material_resolve.bins";
    ok = ok && m_desc.allocator->createBuffer(bins, t.bins) && t.bins.deviceAddress != 0u;
    if (ok) {
        t.binsSlot = m_desc.bindless->registerBufferSlot(t.bins, false);
        ok = t.binsSlot.isValid();
    }
    for (u8& q : t.queues) {
        q = rg::kNoQueue;
    }
    if (!ok) {
        destroyTargets(t);
    }
    return ok;
}

void MaterialResolve::destroyTargets(Targets& t) {
    if (t.binsSlot.isValid()) {
        m_desc.bindless->unregisterSlot(t.binsSlot);
    }
    for (Texture& image : t.gbuffer) {
        if (image.image != nullptr) {
            m_desc.allocator->destroyImage(image);
        }
    }
    for (Texture* image : {&t.materialId, &t.forwardIds, &t.forwardDepth}) {
        if (image->image != nullptr) {
            m_desc.allocator->destroyImage(*image);
        }
    }
    if (t.bins.handle != nullptr) {
        m_desc.allocator->destroyBuffer(t.bins);
    }
    t = Targets{};
}

bool MaterialResolve::resize(u32 width, u32 height) {
    if (!m_initialized || width == 0u || height == 0u || width > 0xFFFFu * kTileSize || height > 0xFFFFu * kTileSize) {
        return false;
    }
    if (width == m_width && height == m_height && m_targets.bins.handle != nullptr) {
        return true;
    }
    Targets fresh{};
    if (!createTargets(fresh, width, height)) {
        return false;
    }
    if (m_targets.bins.handle != nullptr) {
        m_retired.push_back(Retired{m_targets, m_frameSerial});
        ++m_stats.retired;
    }
    m_targets = fresh;
    m_width = width;
    m_height = height;
    ++m_stats.targetRebuilds;
    return true;
}

u32 MaterialResolve::collectRetired(u64 completedSerial) {
    u32 collected = 0;
    usize keep = 0;
    for (usize i = 0; i < m_retired.size(); ++i) {
        if (m_retired[i].serial > completedSerial) {
            m_retired[keep++] = m_retired[i];
            continue;
        }
        destroyTargets(m_retired[i].targets);
        ++collected;
    }
    m_retired.resize(keep);
    m_stats.retired = m_stats.retired >= collected ? m_stats.retired - collected : 0u;
    return collected;
}

bool MaterialResolve::beginFrame(u64 frameSerial, const ResolveFrameDesc& frame) {
    if (!m_initialized || m_targets.bins.handle == nullptr) {
        return false;
    }
    m_frameSerial = frameSerial;
    m_recordCount = 0;
    m_stats.resolvePasses = 0;
    m_stats.forwardPasses = 0;
    ResolveFrameConstants c{};
    std::memcpy(c.viewProj, frame.viewProj, sizeof(c.viewProj));
    std::memcpy(c.prevViewProj, frame.prevViewProj, sizeof(c.prevViewProj));
    c.width = m_width;
    c.height = m_height;
    c.tilesX = tilesX();
    c.tilesY = tilesY();
    c.scene = frame.scene;
    c.vis = frame.vis;
    c.sampler = frame.sampler;
    c.tileCapacity = c.tilesX * c.tilesY;
    c.bins = m_targets.bins.deviceAddress;
    c.binsHandle = m_desc.bindless->shaderHandle(m_targets.binsSlot);
    const u64 offset = (frameSerial % m_desc.framesInFlight) * kFrameStride;
    std::memcpy(static_cast<u8*>(m_frameRing.mapped) + offset, &c, sizeof(c));
    m_frameAddress = m_frameRing.deviceAddress + offset;
    return true;
}

ResolveGraphRefs MaterialResolve::importInto(rg::Graph& graph) {
    ResolveGraphRefs refs{};
    if (!m_initialized || m_targets.bins.handle == nullptr) {
        return refs;
    }
    auto image = [&](Texture& tex, u32 slot, const char* name) {
        rg::ImportedImage i{};
        i.image = tex.image;
        i.view = tex.view;
        i.format = static_cast<u32>(tex.desc.format);
        i.width = m_width;
        i.height = m_height;
        i.initialLayout = m_targets.layouts[slot];
        i.initialQueue = m_targets.queues[slot];
        i.layoutTracker = &m_targets.layouts[slot];
        i.queueTracker = &m_targets.queues[slot];
        i.name = name;
        return graph.importImage(i);
    };
    for (u32 i = 0; i < kGBufferTargets; ++i) {
        refs.gbuffer[i] = image(m_targets.gbuffer[i], i, GBufferLayout::debugName(static_cast<GBufferAttachment>(i)));
    }
    refs.materialId = image(m_targets.materialId, kSlotMaterialId, "gbuffer.material_id");
    if (m_targets.forwardIds.image != nullptr) {
        refs.forwardIds = image(m_targets.forwardIds, kSlotForwardIds, "material_resolve.forward_ids");
        refs.forwardDepth = image(m_targets.forwardDepth, kSlotForwardDepth, "material_resolve.forward_depth");
    }
    refs.bins = graph.importBuffer(rg::ImportedBuffer{m_targets.bins.handle, m_targets.bins.desc.size,
                                                      m_targets.queues[kSlotBins], &m_targets.queues[kSlotBins],
                                                      "material_resolve.bins"});
    return refs;
}

MaterialResolve::PassRecord* MaterialResolve::nextRecord() {
    if (m_recordCount >= kMaxPasses) {
        return nullptr;
    }
    PassRecord* r = &m_records[m_recordCount++];
    *r = PassRecord{};
    r->self = this;
    r->push.frame = m_frameAddress;
    return r;
}

void MaterialResolve::addResolve(rg::Graph& graph, const ResolveGraphRefs& refs, rg::TextureRef vis,
                                 const gpu_scene::GpuSceneGraphRefs& scene, ResolvePath path) {
    if (!m_initialized || !vis.valid() || !refs.bins.valid() || m_recordCount + 3u > kMaxPasses) {
        return;
    }
    const bool binned = path == ResolvePath::Binned;
    if (binned) {
        PassRecord* reset = nextRecord();
        reset->refs = refs;
        graph.addPass("resolve.reset", &MaterialResolve::recordReset, reset).use(refs.bins, rg::Access::TransferDst);
        PassRecord* classify = nextRecord();
        classify->refs = refs;
        rg::PassBuilder pass = graph.addPass("resolve.classify", &MaterialResolve::recordClassify, classify);
        pass.use(vis, rg::Access::StorageRead, {}, rg::kStageCompute);
        gpu_scene::GpuScene::useAll(pass, scene, rg::Access::StorageRead, rg::kStageCompute);
        pass.use(refs.bins, rg::Access::StorageReadWrite, {}, rg::kStageCompute);
    }
    PassRecord* r = nextRecord();
    r->refs = refs;
    r->path = path;
    ++m_stats.resolvePasses;
    rg::PassBuilder pass = graph.addPass("resolve.gbuffer", &MaterialResolve::recordResolve, r);
    pass.use(vis, rg::Access::StorageRead, {}, rg::kStageFragment);
    gpu_scene::GpuScene::useAll(pass, scene, rg::Access::StorageRead, rg::kStageFragment);
    if (scene.indices.valid()) {
        pass.use(scene.indices, rg::Access::StorageRead, {}, rg::kStageFragment);
    }
    if (binned) {
        pass.use(refs.bins, rg::Access::IndirectRead).use(refs.bins, rg::Access::StorageRead, {}, rg::kStageVertex);
    }
    for (const rg::TextureRef& t : refs.gbuffer) {
        pass.use(t, rg::Access::ColorAttachmentWrite);
    }
    pass.use(refs.materialId, rg::Access::ColorAttachmentWrite);
}

void MaterialResolve::addAttributeDump(rg::Graph& graph, const ResolveGraphRefs& refs, rg::TextureRef vis,
                                       const gpu_scene::GpuSceneGraphRefs& scene, rg::BufferRef out, u64 outAddress) {
    if (!m_initialized || !vis.valid() || !out.valid()) {
        return;
    }
    PassRecord* r = nextRecord();
    if (r == nullptr) {
        return;
    }
    r->refs = refs;
    r->push.out = outAddress;
    rg::PassBuilder pass = graph.addPass("resolve.attributes", &MaterialResolve::recordAttributes, r);
    pass.use(vis, rg::Access::StorageRead, {}, rg::kStageCompute);
    gpu_scene::GpuScene::useAll(pass, scene, rg::Access::StorageRead, rg::kStageCompute);
    if (scene.indices.valid()) {
        pass.use(scene.indices, rg::Access::StorageRead, {}, rg::kStageCompute);
    }
    pass.use(out, rg::Access::StorageWrite,
             rg::BufferRange{0, static_cast<u64>(m_width) * m_height * sizeof(ResolveAttributeTexel)}, rg::kStageCompute);
}

void MaterialResolve::addForward(rg::Graph& graph, const ResolveGraphRefs& refs, const gpu_scene::GpuSceneGraphRefs& scene,
                                 const culling::InstanceCuller& culler, const culling::CullGraphRefs& cullRefs,
                                 culling::CullPhase phase, bool clear) {
    if (!m_initialized || m_forwardPipeline == nullptr || !refs.forwardIds.valid()) {
        return;
    }
    PassRecord* r = nextRecord();
    if (r == nullptr) {
        return;
    }
    r->refs = refs;
    r->culler = &culler;
    r->phase = phase;
    r->indices = scene.indices;
    r->clear = clear;
    ++m_stats.forwardPasses;
    rg::PassBuilder pass = graph.addPass("resolve.forward", &MaterialResolve::recordForward, r);
    culler.useDraws(pass, cullRefs, phase);
    gpu_scene::GpuScene::useAll(pass, scene, rg::Access::StorageRead, rg::kStageVertex | rg::kStageFragment);
    if (scene.indices.valid()) {
        pass.use(scene.indices, rg::Access::IndexRead);
    }
    for (const rg::TextureRef& t : refs.gbuffer) {
        pass.use(t, rg::Access::ColorAttachmentWrite);
    }
    pass.use(refs.materialId, rg::Access::ColorAttachmentWrite)
        .use(refs.forwardIds, rg::Access::ColorAttachmentWrite)
        .use(refs.forwardDepth, rg::Access::DepthAttachmentWrite);
}

void MaterialResolve::recordReset(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    // kBinCount VkDrawIndirectCommand {6, 0, 0, 0} (classify counts instances) + the draw count 1.
    static constexpr u32 kReset[ResolveBinLayout::kResetBytes / 4u] = {
        ResolveBinLayout::kVerticesPerTile, 0u, 0u, 0u, ResolveBinLayout::kVerticesPerTile, 0u, 0u, 0u,
        ResolveBinLayout::kVerticesPerTile, 0u, 0u, 0u, ResolveBinLayout::kVerticesPerTile, 0u, 0u, 0u,
        1u,                                 0u, 0u, 0u};
    static_assert(ResolveBinLayout::kDrawCountOffset == 64u && sizeof(kReset) == ResolveBinLayout::kResetBytes,
                  "reset block: args then the draw count");
    vkCmdUpdateBuffer(static_cast<VkCommandBuffer>(context.commandBuffer), static_cast<VkBuffer>(context.buffer(r.refs.bins)),
                      0, sizeof(kReset), kReset);
#else
    (void)context;
    (void)user;
#endif
}

void MaterialResolve::recordClassify(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const MaterialResolve& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, static_cast<VkPipeline>(self.m_classifyPipeline));
    self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, self.m_computeLayout, 0);
    vkCmdPushConstants(cmd, static_cast<VkPipelineLayout>(self.m_computeLayout), VK_SHADER_STAGE_COMPUTE_BIT, 0, kPushBytes,
                       &r.push);
    vkCmdDispatch(cmd, self.tilesX(), self.tilesY(), 1);
#else
    (void)context;
    (void)user;
#endif
}

void MaterialResolve::recordAttributes(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const MaterialResolve& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, static_cast<VkPipeline>(self.m_attributesPipeline));
    self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, self.m_computeLayout, 0);
    vkCmdPushConstants(cmd, static_cast<VkPipelineLayout>(self.m_computeLayout), VK_SHADER_STAGE_COMPUTE_BIT, 0, kPushBytes,
                       &r.push);
    vkCmdDispatch(cmd, self.tilesX(), self.tilesY(), 1);
#else
    (void)context;
    (void)user;
#endif
}

void MaterialResolve::recordResolve(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const MaterialResolve& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    VkRenderingAttachmentInfo colors[kResolveColorAttachments]{};
    for (u32 i = 0; i < kResolveColorAttachments; ++i) {
        colors[i].sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO;
        colors[i].imageView =
            static_cast<VkImageView>(context.imageView(i < kGBufferTargets ? r.refs.gbuffer[i] : r.refs.materialId));
        colors[i].imageLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
        colors[i].loadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE; // every pixel is written exactly once
        colors[i].storeOp = VK_ATTACHMENT_STORE_OP_STORE;
    }
    VkRenderingInfo rendering{};
    rendering.sType = VK_STRUCTURE_TYPE_RENDERING_INFO;
    rendering.renderArea.extent = {self.m_width, self.m_height};
    rendering.layerCount = 1;
    rendering.colorAttachmentCount = kResolveColorAttachments;
    rendering.pColorAttachments = colors;
    vkCmdBeginRendering(cmd, &rendering);
    const VkPipelineLayout layout = static_cast<VkPipelineLayout>(self.m_graphicsLayout);
    self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, self.m_graphicsLayout, 0);
    const VkViewport viewport{0.f, 0.f, static_cast<f32>(self.m_width), static_cast<f32>(self.m_height), 0.f, 1.f};
    const VkRect2D scissor{{0, 0}, {self.m_width, self.m_height}};
    vkCmdSetViewport(cmd, 0, 1, &viewport);
    vkCmdSetScissor(cmd, 0, 1, &scissor);
    vkCmdPushConstants(cmd, layout, VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0, kPushBytes, &r.push);
    if (r.path == ResolvePath::Binned) {
        // One draw per bin, as vkCmdDrawIndirectCount with the constant count 1 (maxDrawCount 1), not
        // vkCmdDrawIndirect: Lavapipe's vkCmdDrawIndirect inherits the indirect draw-count buffer of an
        // earlier *IndirectCount draw in the command buffer (the visibility pass's), see ResolveBinLayout.
        const VkBuffer bins = static_cast<VkBuffer>(context.buffer(r.refs.bins));
        for (u32 b = 0; b < kBinCount; ++b) {
            vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, static_cast<VkPipeline>(self.m_resolvePipelines[b]));
            vkCmdDrawIndirectCount(cmd, bins, static_cast<VkDeviceSize>(b) * ResolveBinLayout::kArgsStride, bins,
                                   ResolveBinLayout::kDrawCountOffset, 1u, ResolveBinLayout::kArgsStride);
        }
    } else {
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, static_cast<VkPipeline>(self.m_resolvePipelines[kBinUber]));
        vkCmdDraw(cmd, 3, 1, 0, 0);
    }
    vkCmdEndRendering(cmd);
#else
    (void)context;
    (void)user;
#endif
}

void MaterialResolve::recordForward(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const MaterialResolve& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    VkRenderingAttachmentInfo colors[kForwardColorAttachments]{};
    for (u32 i = 0; i < kForwardColorAttachments; ++i) {
        const rg::TextureRef ref =
            i < kGBufferTargets ? r.refs.gbuffer[i] : (i == kSlotMaterialId ? r.refs.materialId : r.refs.forwardIds);
        colors[i].sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO;
        colors[i].imageView = static_cast<VkImageView>(context.imageView(ref));
        colors[i].imageLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
        colors[i].loadOp = r.clear ? VK_ATTACHMENT_LOAD_OP_CLEAR : VK_ATTACHMENT_LOAD_OP_LOAD;
        colors[i].storeOp = VK_ATTACHMENT_STORE_OP_STORE;
        // The resolve's empty-pixel values (fuse_mr_gbuffer_empty): 0, RT4 depth = 1 (far), ids ~0.
        if (i == static_cast<u32>(GBufferAttachment::Depth)) {
            colors[i].clearValue.color.float32[0] = 1.f;
        } else if (i >= kGBufferTargets) {
            colors[i].clearValue.color.uint32[0] = kNoMaterial;
            colors[i].clearValue.color.uint32[1] = kNoMaterial;
        }
    }
    VkRenderingAttachmentInfo depth{};
    depth.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO;
    depth.imageView = static_cast<VkImageView>(context.imageView(r.refs.forwardDepth));
    depth.imageLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;
    depth.loadOp = r.clear ? VK_ATTACHMENT_LOAD_OP_CLEAR : VK_ATTACHMENT_LOAD_OP_LOAD;
    depth.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
    depth.clearValue.depthStencil.depth = 1.f;
    VkRenderingInfo rendering{};
    rendering.sType = VK_STRUCTURE_TYPE_RENDERING_INFO;
    rendering.renderArea.extent = {self.m_width, self.m_height};
    rendering.layerCount = 1;
    rendering.colorAttachmentCount = kForwardColorAttachments;
    rendering.pColorAttachments = colors;
    rendering.pDepthAttachment = &depth;
    vkCmdBeginRendering(cmd, &rendering);
    if (r.indices.valid()) {
        const VkPipelineLayout layout = static_cast<VkPipelineLayout>(self.m_graphicsLayout);
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, static_cast<VkPipeline>(self.m_forwardPipeline));
        self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, self.m_graphicsLayout, 0);
        const VkViewport viewport{0.f, 0.f, static_cast<f32>(self.m_width), static_cast<f32>(self.m_height), 0.f, 1.f};
        const VkRect2D scissor{{0, 0}, {self.m_width, self.m_height}};
        vkCmdSetViewport(cmd, 0, 1, &viewport);
        vkCmdSetScissor(cmd, 0, 1, &scissor);
        vkCmdBindIndexBuffer(cmd, static_cast<VkBuffer>(context.buffer(r.indices)), 0, VK_INDEX_TYPE_UINT32);
        vkCmdPushConstants(cmd, layout, VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0, kPushBytes, &r.push);
        r.culler->recordDraws(cmd, r.phase);
    }
    vkCmdEndRendering(cmd);
#else
    (void)context;
    (void)user;
#endif
}

} // namespace fuse::renderer::material_resolve
