// E06 (AP-RT-COOKED): see include/fuse/renderer/cooked_assets/cooked_mesh.hpp.
#include <fuse/renderer/cooked_assets/cooked_mesh.hpp>

#include <fuse/compute_kernel/launch.hpp>
#include <fuse/renderer/geometry/meshlet_bounds_kernel.hpp>
#include <fuse/renderer/geometry/meshlet_builder.hpp>
#include <fuse/renderer/geometry/vertex_codec_kernel.hpp>

#include <cmath>
#include <cstring>
#include <vector>

namespace fuse::renderer::cooked_assets {

namespace {

constexpr u32 kUnmapped = 0xFFFFFFFFu;

template <typename T>
kernel::Span<const T> cspan(const std::vector<T>& v) {
    return kernel::make_span(v.data(), static_cast<u32>(v.size()));
}

template <typename T>
kernel::Span<T> mspan(std::vector<T>& v) {
    return kernel::make_span(v.data(), static_cast<u32>(v.size()));
}

bool fail(std::string* error, const std::string& message) {
    if (error != nullptr) {
        *error = "cooked mesh: " + message;
    }
    return false;
}

void sourceBounds(const asset::CookedMesh& mesh, f32 lo[3], f32 hi[3]) {
    const u32 n = mesh.vertex_count();
    for (u32 a = 0; a < 3u; ++a) {
        lo[a] = 0.f;
        hi[a] = 0.f;
    }
    for (u32 v = 0; v < n; ++v) {
        for (u32 a = 0; a < 3u; ++a) {
            const f32 x = mesh.positions[v * 3u + a];
            lo[a] = v == 0u || x < lo[a] ? x : lo[a];
            hi[a] = v == 0u || x > hi[a] ? x : hi[a];
        }
    }
}

geometry::MeshletRecord toRecord(const asset::CookedMeshlet& c) {
    geometry::MeshletRecord r{};
    r.vertex_offset = c.vertex_offset;
    r.triangle_offset = c.triangle_offset;
    r.vertex_count = c.vertex_count;
    r.triangle_count = c.triangle_count;
    r.submesh = c.submesh;
    for (u32 a = 0; a < 3u; ++a) {
        r.center[a] = c.center[a];
        r.cone_apex[a] = c.cone_apex[a];
        r.cone_axis[a] = c.cone_axis[a];
        r.cone_axis_s8[a] = c.cone_axis_s8[a];
        r.aabb_min[a] = c.aabb_min[a];
        r.aabb_max[a] = c.aabb_max[a];
    }
    r.radius = c.radius;
    r.cone_cutoff = c.cone_cutoff;
    r.cone_cutoff_s8 = c.cone_cutoff_s8;
    return r;
}

geometry::dag::DagLodBounds toBounds(const asset::ClusterDagTable::Bounds& b) {
    geometry::dag::DagLodBounds o{};
    for (u32 a = 0; a < 3u; ++a) {
        o.center[a] = b.center[a];
    }
    o.radius = b.radius;
    o.error = b.error;
    return o;
}

/// Why the adopt path cannot be used ("" when it can).
std::string adoptBlocker(const asset::CookedMesh& mesh) {
    if (mesh.meshlets.empty()) {
        return "no meshlet table";
    }
    const u32 n = mesh.vertex_count();
    if (mesh.tangents.size() != static_cast<usize>(n) * 4u) {
        return "no tangent stream";
    }
    if (mesh.normals.size() != static_cast<usize>(n) * 3u) {
        return "no normal stream";
    }
    for (u32 v = 0; v < n; ++v) {
        const f32* nv = &mesh.normals[v * 3u];
        if (!(nv[0] * nv[0] + nv[1] * nv[1] + nv[2] * nv[2] > 1e-24f)) {
            return "zero-length normals (regenerated by the builder)";
        }
    }
    const asset::MeshletTable& t = mesh.meshlets;
    if (t.max_vertices < 3u || t.max_vertices > geometry::kMeshletFormatMaxVertices || t.max_triangles < 1u ||
        t.max_triangles > geometry::kMeshletFormatMaxTriangles) {
        return "meshlet limits out of range";
    }
    for (u32 i = 0; i < static_cast<u32>(t.vertices.size()); ++i) {
        if (t.vertices[i] >= n) {
            return "meshlet vertex out of range";
        }
    }
    for (const asset::CookedMeshlet& m : t.meshlets) {
        if (static_cast<u64>(m.vertex_offset) + m.vertex_count > t.vertices.size() ||
            static_cast<u64>(m.triangle_offset) + m.triangle_count > t.triangles.size()) {
            return "meshlet range out of bounds";
        }
    }
    const asset::ClusterDagTable& d = mesh.cluster_dag;
    for (const u32 v : d.lod_vertices) {
        if (v >= n) {
            return "DAG vertex out of range";
        }
    }
    return {};
}

bool adopt(const asset::CookedMesh& src, CookedMeshletResult& out, kernel::Backend backend, std::string* error) {
    const asset::MeshletTable& table = src.meshlets;
    const u32 n = src.vertex_count();
    // First-use renumbering over the meshlet triangles (the WP-1.2 builder's fetch order), then DAG-only vertices.
    std::vector<u32> remap(n, kUnmapped);
    std::vector<u32> sourceOf;
    sourceOf.reserve(n);
    auto use = [&](u32 fmshVertex) {
        if (remap[fmshVertex] == kUnmapped) {
            remap[fmshVertex] = static_cast<u32>(sourceOf.size());
            sourceOf.push_back(fmshVertex);
        }
    };
    for (const asset::CookedMeshlet& m : table.meshlets) {
        for (u32 t = 0; t < m.triangle_count; ++t) {
            const u32 packed = table.triangles[m.triangle_offset + t];
            for (u32 c = 0; c < 3u; ++c) {
                const u32 local = (packed >> (8u * c)) & 255u;
                if (local >= m.vertex_count) {
                    return fail(error, "meshlet triangle index out of range");
                }
                use(table.vertices[m.vertex_offset + local]);
            }
        }
    }
    for (u32 v = 0; v < static_cast<u32>(table.vertices.size()); ++v) {
        use(table.vertices[v]); // vertices listed by a meshlet but not used by its triangles
    }
    for (const u32 v : src.cluster_dag.lod_vertices) {
        use(v);
    }
    const u32 used = static_cast<u32>(sourceOf.size());
    if (used == 0u) {
        return fail(error, "meshlet table references no vertex");
    }

    std::vector<f32> pos(static_cast<usize>(used) * 3u), nrm(static_cast<usize>(used) * 3u),
        tng(static_cast<usize>(used) * 4u), uv(static_cast<usize>(used) * 2u, 0.f);
    f32 lo[3] = {0.f, 0.f, 0.f};
    f32 hi[3] = {0.f, 0.f, 0.f};
    const bool hasUv = src.uvs.size() == static_cast<usize>(n) * 2u;
    for (u32 v = 0; v < used; ++v) {
        const u32 s = sourceOf[v];
        for (u32 a = 0; a < 3u; ++a) {
            pos[v * 3u + a] = src.positions[s * 3u + a];
            nrm[v * 3u + a] = src.normals[s * 3u + a];
            lo[a] = v == 0u || pos[v * 3u + a] < lo[a] ? pos[v * 3u + a] : lo[a];
            hi[a] = v == 0u || pos[v * 3u + a] > hi[a] ? pos[v * 3u + a] : hi[a];
        }
        // Supplied tangents as the WP-1.2 builder takes them (oct-encoded as given, handedness to +-1).
        for (u32 k = 0; k < 3u; ++k) {
            tng[v * 4u + k] = src.tangents[s * 4u + k];
        }
        tng[v * 4u + 3u] = src.tangents[s * 4u + 3u] < 0.f ? -1.f : 1.f;
        if (hasUv) {
            uv[v * 2u] = src.uvs[s * 2u];
            uv[v * 2u + 1u] = src.uvs[s * 2u + 1u];
        }
    }

    geometry::MeshletMesh& m = out.mesh;
    m = geometry::MeshletMesh{};
    m.quant = geometry::compute_quant_params(lo, hi);
    m.max_vertices = table.max_vertices;
    m.max_triangles = table.max_triangles;
    m.flags = geometry::kMeshletFlagNormalsFromSource | geometry::kMeshletFlagTangentsFromSource |
              (hasUv ? geometry::kMeshletFlagUvFromSource : 0u);
    for (const asset::MeshletTable::SubmeshRange& r : table.submeshes) {
        m.submeshes.push_back(geometry::SubmeshRange{r.meshlet_offset, r.meshlet_count, r.material_index, r.triangle_count});
    }
    m.meshlets.reserve(table.meshlets.size());
    for (const asset::CookedMeshlet& c : table.meshlets) {
        m.meshlets.push_back(toRecord(c));
    }
    m.meshlet_vertices.resize(table.vertices.size());
    for (usize i = 0; i < table.vertices.size(); ++i) {
        m.meshlet_vertices[i] = remap[table.vertices[i]];
    }
    m.meshlet_triangles = table.triangles;
    m.source_vertices = sourceOf;

    m.positions.resize(static_cast<usize>(used) * 4u);
    m.normals.resize(used);
    m.tangents.resize(used);
    m.uvs.resize(used);
    geometry::vertex_codec::EncodeParams ep{};
    ep.positions = cspan(pos);
    ep.normals = cspan(nrm);
    ep.tangents = cspan(tng);
    ep.uvs = cspan(uv);
    ep.quant = m.quant;
    ep.out_pos = mspan(m.positions);
    ep.out_nrm = mspan(m.normals);
    ep.out_tan = mspan(m.tangents);
    ep.out_uv = mspan(m.uvs);
    if (!kernel::launch(backend, geometry::vertex_codec::make_encode_launch(used), geometry::vertex_codec::EncodeKernel{},
                        ep)
             .ok) {
        return fail(error, "vertex encode launch failed");
    }
    // Bounds on the decoded positions (conservative for what the GPU rasterises).
    geometry::DecodedVertices decoded;
    geometry::decode_vertices(m, decoded, backend);
    geometry::bounds_kernel::Params bp{};
    bp.meshlets = mspan(m.meshlets);
    bp.meshlet_vertices = cspan(m.meshlet_vertices);
    bp.positions = cspan(decoded.positions);
    if (!kernel::launch(backend, geometry::bounds_kernel::make_launch(static_cast<u32>(m.meshlets.size())),
                        geometry::bounds_kernel::Kernel{}, bp)
             .ok) {
        return fail(error, "meshlet bounds launch failed");
    }
    std::string why;
    if (!geometry::validate_meshlet_mesh(m, &why)) {
        return fail(error, "adopted meshlet table failed validation: " + why);
    }

    // Cluster DAG (cluster ids [0, leaf count) are the meshlets above).
    const asset::ClusterDagTable& d = src.cluster_dag;
    out.hasDag = false;
    out.dag = geometry::dag::ClusterDag{};
    if (!d.empty()) {
        geometry::dag::ClusterDag& g = out.dag;
        g.leaf_cluster_count = d.leaf_cluster_count;
        g.level_count = d.level_count;
        for (const asset::CookedMeshlet& c : d.lod_clusters) {
            g.lod_clusters.push_back(toRecord(c));
        }
        g.lod_meshlet_vertices.resize(d.lod_vertices.size());
        for (usize i = 0; i < d.lod_vertices.size(); ++i) {
            g.lod_meshlet_vertices[i] = remap[d.lod_vertices[i]];
        }
        g.lod_meshlet_triangles = d.lod_triangles;
        for (const asset::ClusterDagTable::Group& gr : d.groups) {
            geometry::dag::DagGroup o{};
            o.bounds = toBounds(gr.bounds);
            o.member_offset = gr.member_offset;
            o.member_count = gr.member_count;
            o.child_offset = gr.child_offset;
            o.child_count = gr.child_count;
            o.depth = gr.depth;
            o.submesh = gr.submesh;
            o.reserved = gr.reserved;
            g.groups.push_back(o);
        }
        g.group_members = d.group_members;
        for (const asset::ClusterDagTable::Link& l : d.links) {
            geometry::dag::DagClusterLink o{};
            o.self = toBounds(l.self);
            o.parent = toBounds(l.parent);
            o.group = l.group;
            o.refined = l.refined;
            g.links.push_back(o);
        }
        // LOD cluster bounds on the decoded positions too (the leaf spheres were grown above; links keep the cook's
        // LOD spheres, which bound the simplified geometry with the DAG builder's slack).
        geometry::bounds_kernel::Params lp{};
        lp.meshlets = mspan(g.lod_clusters);
        lp.meshlet_vertices = cspan(g.lod_meshlet_vertices);
        lp.positions = cspan(decoded.positions);
        if (!g.lod_clusters.empty() &&
            !kernel::launch(backend, geometry::bounds_kernel::make_launch(static_cast<u32>(g.lod_clusters.size())),
                            geometry::bounds_kernel::Kernel{}, lp)
                 .ok) {
            return fail(error, "DAG cluster bounds launch failed");
        }
        if (!geometry::dag::validate_cluster_dag(m, g, &why)) {
            return fail(error, "adopted cluster DAG failed validation: " + why);
        }
        out.hasDag = true;
    }
    out.path = CookedMeshPath::Adopted;
    return true;
}

bool build(const asset::CookedMesh& src, CookedMeshletResult& out, kernel::Backend backend, std::string* error) {
    const u32 n = src.vertex_count();
    geometry::MeshletSource s{};
    s.positions = src.positions.data();
    s.normals = src.normals.size() == static_cast<usize>(n) * 3u ? src.normals.data() : nullptr;
    s.uvs = src.uvs.size() == static_cast<usize>(n) * 2u ? src.uvs.data() : nullptr;
    s.tangents = src.tangents.size() == static_cast<usize>(n) * 4u ? src.tangents.data() : nullptr;
    s.vertex_count = n;
    s.indices = src.indices.data();
    s.index_count = static_cast<u32>(src.indices.size());
    for (const asset::CookedMesh::Submesh& sm : src.submeshes) {
        s.submeshes.push_back(geometry::MeshletSourceSubmesh{sm.index_offset, sm.index_count, sm.material_index});
    }
    geometry::MeshletBuildOptions o{};
    o.backend = backend;
    std::string why;
    if (!geometry::build_meshlets(s, o, out.mesh, &why)) {
        return fail(error, why);
    }
    out.hasDag = false;
    out.dag = geometry::dag::ClusterDag{};
    out.path = CookedMeshPath::Built;
    return true;
}

} // namespace

const char* cooked_mesh_path_name(CookedMeshPath path) { return path == CookedMeshPath::Adopted ? "adopted" : "built"; }

bool cooked_mesh_to_meshlets(const asset::CookedMesh& mesh, CookedMeshletResult& out, std::string* error,
                             kernel::Backend backend) {
    out = CookedMeshletResult{};
    const u32 n = mesh.vertex_count();
    if (n == 0u || mesh.positions.size() != static_cast<usize>(n) * 3u || mesh.indices.empty() ||
        mesh.indices.size() % 3u != 0u) {
        return fail(error, "no triangles");
    }
    sourceBounds(mesh, out.boundsMin, out.boundsMax);
    const std::string blocker = adoptBlocker(mesh);
    if (blocker.empty()) {
        std::string why;
        if (adopt(mesh, out, backend, &why)) {
            return true;
        }
        // An inconsistent section is not fatal: the streams are enough to build meshlets.
        out.note = why;
    } else {
        out.note = blocker;
    }
    const std::string note = out.note;
    f32 lo[3];
    f32 hi[3];
    std::memcpy(lo, out.boundsMin, sizeof(lo));
    std::memcpy(hi, out.boundsMax, sizeof(hi));
    if (!build(mesh, out, backend, error)) {
        return false;
    }
    out.note = note;
    std::memcpy(out.boundsMin, lo, sizeof(lo));
    std::memcpy(out.boundsMax, hi, sizeof(hi));
    return true;
}

} // namespace fuse::renderer::cooked_assets
