# Usage: cmake -DNM=<nm> -DOBJECTS=<obj;...> -DEXPECT=present|absent -P check_b1_assert_codegen.cmake
if(NOT NM OR NOT OBJECTS OR NOT EXPECT)
    message(FATAL_ERROR "NM, OBJECTS and EXPECT are required")
endif()
set(_fatal_symbol "_ZN4fuse9assertion5fatalEPKcS2_j")
set(_found FALSE)
foreach(_obj IN LISTS OBJECTS)
    execute_process(COMMAND "${NM}" -u "${_obj}" OUTPUT_VARIABLE _undefined RESULT_VARIABLE _rc)
    if(NOT _rc EQUAL 0)
        message(FATAL_ERROR "${NM} failed on ${_obj}")
    endif()
    string(FIND "${_undefined}" "${_fatal_symbol}" _pos)
    if(NOT _pos EQUAL -1)
        set(_found TRUE)
    endif()
endforeach()
if(EXPECT STREQUAL "present" AND NOT _found)
    message(FATAL_ERROR "FUSE_ASSERT probe does not call fuse::assertion::fatal in a debug build")
elseif(EXPECT STREQUAL "absent" AND _found)
    message(FATAL_ERROR "FUSE_ASSERT probe still calls fuse::assertion::fatal outside debug (not a no-op)")
endif()
message(STATUS "FUSE_ASSERT codegen: fatal call ${EXPECT} as expected")
