# Usage: cmake -DNM=<nm> -DARTIFACT_LIST=<file> -DSOURCE_ROOTS=<dir|dir...> -P check_b7_shipping_binaries.cmake
#
# B7.10 "Shipping build compiles with zero warnings, zero debug code included — verified by binary
# inspection", engine-wide half (the header/macro half is fuse_core_b7_shipping_strip). Runs in a
# FUSE_SHIPPING build dir over every fuse_* static library and every shipped (non-test) executable that build
# produced (ARTIFACT_LIST, generated by fuse_b7_shipping_binaries_test in Core/tests/CMakeLists.txt):
#   - no object references fuse::assertion::fatal (FUSE_ASSERT / FUSE_VERIFY / FUSE_UNREACHABLE
#     compiled out) and no executable links it in at all;
#   - no object references fuse::profiler::ProfileScope (FUSE_PROFILE_SCOPE compiled out) and no
#     executable contains ProfileScope code;
#   - none of the string literals passed to stripped macros in non-test FUSE sources
#     (FUSE_LOG_TRACE..ERROR format strings, FUSE_ASSERT/VERIFY messages, FUSE_PROFILE_* names)
#     survives in any artifact.
if(NOT NM OR NOT ARTIFACT_LIST OR NOT SOURCE_ROOTS)
    message(FATAL_ERROR "NM, ARTIFACT_LIST and SOURCE_ROOTS are required")
endif()

file(STRINGS "${ARTIFACT_LIST}" _artifacts)
list(FILTER _artifacts EXCLUDE REGEX "^[ \t]*$")
list(LENGTH _artifacts _artifact_count)
if(_artifact_count EQUAL 0)
    message(FATAL_ERROR "shipping binaries: artifact list is empty (nothing inspected)")
endif()

set(_fatal_sym "_ZN4fuse9assertion5fatalEPKcS2_j")
set(_scope_sym "_ZN4fuse8profiler12ProfileScope")

# --- Literals passed to macros that shipping strips (non-test sources only). ----------------------
string(REPLACE "|" ";" SOURCE_ROOTS "${SOURCE_ROOTS}")
set(_macro_re "FUSE_(LOG_(TRACE|DEBUG|INFO|WARN|ERROR)|PROFILE_[A-Z_]+|ASSERT|VERIFY)[ \t]*\\(")
set(_literals "")
foreach(_root IN LISTS SOURCE_ROOTS)
    file(GLOB_RECURSE _srcs "${_root}/*.cpp" "${_root}/*.hpp" "${_root}/*.h" "${_root}/*.inl")
    list(FILTER _srcs EXCLUDE REGEX "/tests/")
    foreach(_src IN LISTS _srcs)
        file(STRINGS "${_src}" _lines REGEX "${_macro_re}")
        foreach(_line IN LISTS _lines)
            if(_line MATCHES "^[ \t]*#[ \t]*define")
                continue()
            endif()
            # Macro name, optional leading non-string arguments, then the first string literal.
            string(REGEX MATCHALL "${_macro_re}[^\"]*\"[^\"]*\"" _calls "${_line}")
            foreach(_call IN LISTS _calls)
                string(REGEX REPLACE "^[^\"]*\"([^\"]*)\"$" "\\1" _lit "${_call}")
                # Printf specifiers split the literal; check the longest fixed run of it.
                string(REGEX REPLACE "%[-+ #0-9.]*[a-zA-Z]+" "\n" _lit "${_lit}")
                string(REPLACE "\n" ";" _parts "${_lit}")
                foreach(_p IN LISTS _parts)
                    string(STRIP "${_p}" _p)
                    string(LENGTH "${_p}" _len)
                    if(_len GREATER_EQUAL 8 AND NOT _p MATCHES "\\\\")
                        list(APPEND _literals "${_p}")
                    endif()
                endforeach()
            endforeach()
        endforeach()
    endforeach()
endforeach()
list(REMOVE_DUPLICATES _literals)
list(LENGTH _literals _literal_total)
if(_literal_total EQUAL 0)
    message(FATAL_ERROR "shipping binaries: no stripped-macro literals found under ${SOURCE_ROOTS} (scan broken)")
endif()

# --- Inspect artifacts. ----------------------------------------------------------------------------
set(_errors "")
set(_haystack "")
foreach(_art IN LISTS _artifacts)
    if(NOT EXISTS "${_art}")
        list(APPEND _errors "missing artifact ${_art} (build the shipping tree first)")
        continue()
    endif()
    get_filename_component(_name "${_art}" NAME)
    if(_art MATCHES "\\.(a|lib)$")
        # Archives: undefined references per member object.
        execute_process(COMMAND "${NM}" -u "${_art}" OUTPUT_VARIABLE _syms RESULT_VARIABLE _rc
                        ERROR_QUIET)
        set(_what "references")
    else()
        # Linked executables: any trace of the symbol means the code was linked in.
        execute_process(COMMAND "${NM}" "${_art}" OUTPUT_VARIABLE _syms RESULT_VARIABLE _rc
                        ERROR_QUIET)
        set(_what "links")
    endif()
    if(NOT _rc EQUAL 0)
        list(APPEND _errors "${NM} failed on ${_name}")
        continue()
    endif()
    foreach(_pair IN ITEMS "${_fatal_sym}|fuse::assertion::fatal" "${_scope_sym}|fuse::profiler::ProfileScope")
        string(REPLACE "|" ";" _pair "${_pair}")
        list(GET _pair 0 _sym)
        list(GET _pair 1 _pretty)
        string(FIND "${_syms}" "${_sym}" _pos)
        if(NOT _pos EQUAL -1)
            list(APPEND _errors "${_name} ${_what} ${_pretty}")
        endif()
    endforeach()
    # Quoted append only: binary strings may hold ';' or '[' and must never be list-expanded.
    file(STRINGS "${_art}" _s)
    string(APPEND _haystack "${_s}\n")
endforeach()
set(_literal_count 0)
foreach(_lit IN LISTS _literals)
    math(EXPR _literal_count "${_literal_count} + 1")
    string(FIND "${_haystack}" "${_lit}" _pos)
    if(NOT _pos EQUAL -1)
        list(APPEND _errors "stripped-macro string '${_lit}' present in a shipping artifact")
    endif()
endforeach()

if(_errors)
    list(JOIN _errors "\n  " _msg)
    message(FATAL_ERROR "shipping binaries: debug code found:\n  ${_msg}")
endif()
message(STATUS "shipping binaries: ${_artifact_count} artifacts clean — no assert/ProfileScope code, "
               "${_literal_count} stripped-macro strings absent")
