# WP-0.8 lint (cmake -DCL_DIR=<core_logic> -P check_includes.cmake): the pure-logic cores and
# their BMC harnesses may include only <stdint.h>, <stddef.h> and core_logic headers (the
# native BMC shim also <stdio.h>/<stdlib.h>). Anything else — Vulkan, STL, platform headers —
# would break the "no Vulkan types, BMC-ready" contract.
if(NOT CL_DIR)
    message(FATAL_ERROR "CL_DIR not set")
endif()
file(GLOB_RECURSE _files
    "${CL_DIR}/include/*.hpp" "${CL_DIR}/src/*.cpp" "${CL_DIR}/bmc/*.hpp" "${CL_DIR}/bmc/*.cpp"
    "${CL_DIR}/tests/rg_oracle.hpp")
set(_allowed "<stdint.h>" "<stddef.h>" "<stdio.h>" "<stdlib.h>")
set(_bad 0)
set(_count 0)
foreach(_f IN LISTS _files)
    math(EXPR _count "${_count} + 1")
    file(STRINGS "${_f}" _incs REGEX "^[ \t]*#[ \t]*include")
    foreach(_line IN LISTS _incs)
        string(REGEX REPLACE "^[ \t]*#[ \t]*include[ \t]*" "" _what "${_line}")
        string(STRIP "${_what}" _what)
        if(_what MATCHES "^\"(fuse/core_logic/[a-z_]+\\.hpp|bmc_shim\\.hpp|rg_oracle\\.hpp)\"$")
            continue()
        endif()
        list(FIND _allowed "${_what}" _idx)
        if(_idx GREATER -1)
            if(_what STREQUAL "<stdio.h>" OR _what STREQUAL "<stdlib.h>")
                if(NOT _f MATCHES "bmc_shim\\.hpp$")
                    message(SEND_ERROR "${_f}: ${_what} is only allowed in bmc/bmc_shim.hpp")
                    set(_bad 1)
                endif()
            endif()
            continue()
        endif()
        message(SEND_ERROR "${_f}: forbidden include ${_what}")
        set(_bad 1)
    endforeach()
    # Vulkan identifiers in code (comments may name the Vulkan structures WP-0.3 maps onto).
    file(STRINGS "${_f}" _vk REGEX "(Vk[A-Z][A-Za-z]+|vk[A-Z][A-Za-z]+\\(|VK_[A-Z_]+)")
    foreach(_vl IN LISTS _vk)
        if(NOT _vl MATCHES "^[ \t]*//")
            message(SEND_ERROR "${_f}: Vulkan identifier in core_logic code: ${_vl}")
            set(_bad 1)
        endif()
    endforeach()
endforeach()
if(_count EQUAL 0)
    message(FATAL_ERROR "no core_logic sources found under ${CL_DIR}")
endif()
if(_bad)
    message(FATAL_ERROR "core_logic include lint failed")
endif()
message(STATUS "core_logic include lint: ${_count} files clean")
