// WP-8.2 Hillaire atmosphere on Vulkan: see include/fuse/renderer/atmosphere/atmosphere_gpu.hpp.
#include <fuse/renderer/atmosphere/atmosphere_gpu.hpp>

#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/device.hpp>

#include <algorithm>
#include <cstring>
#include <initializer_list>

#if defined(FUSE_VULKAN_BACKEND)
#include <vulkan/vulkan.h>

// Generated by cmake/rp_wp82.cmake from shaders/atmosphere/*: kAt<Kernel><Slang|Glsl>Spv and
// FUSE_ATMOSPHERE_GPU_{SLANG,GLSL} when every kernel of a language exists.
#include "atmosphere_gpu_spv.h"
#endif

namespace fuse::renderer::atmosphere {

namespace {
constexpr u32 kPushBytes = sizeof(AtPush);
constexpr u32 kFrameStride = 512u; ///< ring slot size (>= sizeof(AtParams), 256-aligned)
static_assert(sizeof(AtParams) <= kFrameStride, "frame ring slot");
constexpr u64 kTexel = sizeof(AtTexel);

BufferUsage bufferUsage(std::initializer_list<BufferUsage> bits) {
    u32 u = 0;
    for (const BufferUsage b : bits) {
        u |= static_cast<u32>(b);
    }
    return static_cast<BufferUsage>(u);
}

u64 align256(u64 v) { return (v + 255u) & ~u64{255u}; }

u32 groups(u32 items, u32 size) { return items == 0u ? 1u : (items + size - 1u) / size; }

#if defined(FUSE_VULKAN_BACKEND)
struct Code {
    const u32* words = nullptr;
    usize bytes = 0;
};
template <usize N>
Code code(const u32 (&spv)[N]) {
    return Code{spv, sizeof(spv)};
}
#endif
} // namespace

AtmosphereBufferLayout AtmosphereBufferLayout::compute(const AtParams& p) {
    AtmosphereBufferLayout l{};
    u64 cursor = 0;
    u32 index = 0;
    auto take = [&](u64 texels) {
        const u64 at = cursor;
        l.bytes[index++] = texels * kTexel;
        cursor = align256(cursor + std::max<u64>(texels * kTexel, 16u));
        return at;
    };
    const u64 volume = static_cast<u64>(p.apWidth) * p.apHeight * p.apDepth;
    l.transmittance = take(static_cast<u64>(p.transWidth) * p.transHeight);
    l.multiscatter = take(static_cast<u64>(p.msWidth) * p.msHeight);
    l.skyView = take(static_cast<u64>(p.skyWidth) * p.skyHeight);
    l.aerialScatter = take(volume);
    l.aerialTransmittance = take(volume);
    l.totalBytes = cursor;
    return l;
}

AtmosCapabilities queryAtmosphereCapabilities(const VulkanDevice* device) {
    AtmosCapabilities c{};
#if defined(FUSE_VULKAN_BACKEND)
    if (device == nullptr || !device->isValid()) {
        return c;
    }
    const RendererCaps& caps = device->info().caps;
    if (!caps.bufferDeviceAddress || !caps.shaderInt64) {
        c.reason = "bufferDeviceAddress / shaderInt64 missing";
        return c;
    }
    c.atmosphere = true;
    c.reason = "ok";
#else
    (void)device;
    c.reason = "stub backend";
#endif
    return c;
}

AtmosphereGpu::~AtmosphereGpu() { destroy(); }

bool AtmosphereGpu::init(const AtmosphereGpuDesc& desc) {
    destroy();
    m_desc = desc;
#if defined(FUSE_VULKAN_BACKEND)
    if (desc.allocator == nullptr || desc.bindless == nullptr || desc.framesInFlight == 0u) {
        return false;
    }
    if (!queryAtmosphereCapabilities(desc.device).atmosphere) {
        return false;
    }
    m_retired.reserve(8);
    m_initialized = true; // destroy() releases partial state from here on
    BufferDesc ring{};
    ring.size = static_cast<usize>(desc.framesInFlight) * kFrameStride;
    ring.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress});
    ring.memoryUsage = MemoryUsage::CpuToGpu;
    ring.name = "atmosphere_gpu.frame";
    if (!m_desc.allocator->createBuffer(ring, m_frameRing) || m_frameRing.mapped == nullptr ||
        m_frameRing.deviceAddress == 0u || !createPipelines()) {
        destroy();
        return false;
    }
    return true;
#else
    return false;
#endif
}

void AtmosphereGpu::destroy() {
    if (!m_initialized) {
        return;
    }
#if defined(FUSE_VULKAN_BACKEND)
    collectRetired(~0ull);
    if (m_luts.handle != nullptr) {
        m_desc.allocator->destroyBuffer(m_luts);
    }
    if (m_frameRing.handle != nullptr) {
        m_desc.allocator->destroyBuffer(m_frameRing);
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    for (void*& pipeline : m_pipelines) {
        if (pipeline != nullptr) {
            vkDestroyPipeline(device, static_cast<VkPipeline>(pipeline), nullptr);
            pipeline = nullptr;
        }
    }
    if (m_layoutHandle != nullptr) {
        vkDestroyPipelineLayout(device, static_cast<VkPipelineLayout>(m_layoutHandle), nullptr);
    }
#endif
    m_layoutHandle = nullptr;
    m_luts = Buffer{};
    m_lutQueue = rg::kNoQueue;
    m_frameRing = Buffer{};
    m_frameAddress = 0;
    m_retired.clear();
    m_layout = AtmosphereBufferLayout{};
    m_params = AtParams{};
    m_staticParams = AtParams{};
    m_staticDirty = true;
    m_staticThisFrame = false;
    m_recordCount = 0;
    m_language = "none";
    m_stats = AtmosphereStats{};
    m_initialized = false;
}

bool AtmosphereGpu::createPipelines() {
#if defined(FUSE_VULKAN_BACKEND)
    Code k[kKernelCount]{};
    bool found = false;
#if defined(FUSE_ATMOSPHERE_GPU_SLANG)
    if (m_desc.language == AtmosKernelLanguage::Auto || m_desc.language == AtmosKernelLanguage::Slang) {
        k[kTransmittance] = code(kAtTransmittanceSlangSpv);
        k[kMultiScatter] = code(kAtMultiscatterSlangSpv);
        k[kSkyView] = code(kAtSkyviewSlangSpv);
        k[kAerial] = code(kAtAerialSlangSpv);
        k[kProbe] = code(kAtProbeSlangSpv);
        m_language = "slang";
        found = true;
    }
#endif
#if defined(FUSE_ATMOSPHERE_GPU_GLSL)
    if (!found && (m_desc.language == AtmosKernelLanguage::Auto || m_desc.language == AtmosKernelLanguage::Glsl)) {
        k[kTransmittance] = code(kAtTransmittanceGlslSpv);
        k[kMultiScatter] = code(kAtMultiscatterGlslSpv);
        k[kSkyView] = code(kAtSkyviewGlslSpv);
        k[kAerial] = code(kAtAerialGlslSpv);
        k[kProbe] = code(kAtProbeGlslSpv);
        m_language = "glsl";
        found = true;
    }
#endif
    if (!found) {
        return false;
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    VkDescriptorSetLayout setLayout = static_cast<VkDescriptorSetLayout>(m_desc.bindless->layoutHandle());
    VkPushConstantRange range{VK_SHADER_STAGE_COMPUTE_BIT, 0, kPushBytes};
    VkPipelineLayoutCreateInfo layoutInfo{};
    layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutInfo.setLayoutCount = setLayout != VK_NULL_HANDLE ? 1u : 0u;
    layoutInfo.pSetLayouts = &setLayout;
    layoutInfo.pushConstantRangeCount = 1;
    layoutInfo.pPushConstantRanges = &range;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    if (vkCreatePipelineLayout(device, &layoutInfo, nullptr, &layout) != VK_SUCCESS) {
        return false;
    }
    m_layoutHandle = layout;
    const VkPipelineCreateFlags createFlags = static_cast<VkPipelineCreateFlags>(m_desc.bindless->pipelineCreateFlags());
    for (u32 i = 0; i < kKernelCount; ++i) {
        VkShaderModuleCreateInfo moduleInfo{};
        moduleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        moduleInfo.codeSize = k[i].bytes;
        moduleInfo.pCode = k[i].words;
        VkShaderModule module = VK_NULL_HANDLE;
        if (vkCreateShaderModule(device, &moduleInfo, nullptr, &module) != VK_SUCCESS) {
            return false;
        }
        VkComputePipelineCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
        info.flags = createFlags;
        info.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        info.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
        info.stage.module = module;
        info.stage.pName = "main";
        info.layout = layout;
        VkPipeline pipeline = VK_NULL_HANDLE;
        const VkResult result = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
        vkDestroyShaderModule(device, module, nullptr);
        m_pipelines[i] = pipeline;
        if (result != VK_SUCCESS) {
            return false;
        }
    }
    return true;
#else
    return false;
#endif
}

bool AtmosphereGpu::createLuts(const AtmosphereBufferLayout& layout) {
    BufferDesc d{};
    d.size = static_cast<usize>(layout.totalBytes);
    d.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress, BufferUsage::TransferSrc});
    d.memoryUsage = MemoryUsage::GpuOnly;
    d.name = "atmosphere_gpu.luts";
    Buffer fresh{};
    if (!m_desc.allocator->createBuffer(d, fresh) || fresh.deviceAddress == 0u) {
        if (fresh.handle != nullptr) {
            m_desc.allocator->destroyBuffer(fresh);
        }
        return false;
    }
    if (m_luts.handle != nullptr) {
        Retired old{};
        old.buffer = m_luts;
        old.serial = m_frameSerial;
        m_retired.push_back(old);
        ++m_stats.retired;
    }
    m_luts = fresh;
    m_lutQueue = rg::kNoQueue;
    m_layout = layout;
    m_staticDirty = true;
    ++m_stats.lutRebuilds;
    return true;
}

u32 AtmosphereGpu::collectRetired(u64 completedSerial) {
    u32 collected = 0;
    usize keep = 0;
    for (usize i = 0; i < m_retired.size(); ++i) {
        if (m_retired[i].serial > completedSerial) {
            m_retired[keep++] = m_retired[i];
            continue;
        }
        if (m_retired[i].buffer.handle != nullptr) {
            m_desc.allocator->destroyBuffer(m_retired[i].buffer);
        }
        ++collected;
    }
    m_retired.resize(keep);
    m_stats.retired = m_stats.retired >= collected ? m_stats.retired - collected : 0u;
    return collected;
}

bool AtmosphereGpu::beginFrame(u64 frameSerial, const AtmosphereLutSettings& settings, const AtmosphereLutView& view) {
    if (!m_initialized) {
        return false;
    }
    AtParams p{};
    if (!resolve_at_params(settings, view, p)) {
        return false;
    }
    m_frameSerial = frameSerial;
    m_recordCount = 0;
    m_stats.passes = 0;
    m_stats.staticRan = false;
    const AtmosphereBufferLayout layout = AtmosphereBufferLayout::compute(p);
    if (m_luts.handle == nullptr || layout.totalBytes != m_layout.totalBytes ||
        layout.transmittance != m_layout.transmittance || layout.multiscatter != m_layout.multiscatter ||
        layout.skyView != m_layout.skyView || layout.aerialScatter != m_layout.aerialScatter ||
        layout.aerialTransmittance != m_layout.aerialTransmittance) {
        if (!createLuts(layout)) {
            return false;
        }
    }
    if (!at_static_equal(p, m_staticParams)) {
        m_staticDirty = true;
    }
    const u64 base = m_luts.deviceAddress;
    p.transmittance = base + m_layout.transmittance;
    p.multiscatter = base + m_layout.multiscatter;
    p.skyView = base + m_layout.skyView;
    p.aerialScatter = base + m_layout.aerialScatter;
    p.aerialTransmittance = base + m_layout.aerialTransmittance;
    m_params = p;
    const u32 slot = static_cast<u32>(frameSerial % m_desc.framesInFlight);
    const u64 offset = static_cast<u64>(slot) * kFrameStride;
    std::memcpy(static_cast<u8*>(m_frameRing.mapped) + offset, &p, sizeof(p));
    m_frameAddress = m_frameRing.deviceAddress + offset;
    return true;
}

AtmosphereGraphRefs AtmosphereGpu::importInto(rg::Graph& graph) {
    AtmosphereGraphRefs refs{};
    if (!m_initialized || m_luts.handle == nullptr) {
        return refs;
    }
    refs.luts = graph.importBuffer(
        rg::ImportedBuffer{m_luts.handle, m_luts.desc.size, m_lutQueue, &m_lutQueue, "atmosphere_gpu.luts"});
    return refs;
}

AtmosphereGpu::PassRecord* AtmosphereGpu::nextRecord(u32 kernel) {
    if (m_recordCount >= kMaxPasses) {
        return nullptr;
    }
    PassRecord* r = &m_records[m_recordCount++];
    *r = PassRecord{};
    r->self = this;
    r->kernel = kernel;
    r->push.params = m_frameAddress;
    return r;
}

rg::BufferRange AtmosphereGpu::range(AtmosLut which) const {
    switch (which) {
    case AtmosLut::Transmittance: return rg::BufferRange{m_layout.transmittance, m_layout.bytes[0]};
    case AtmosLut::MultiScatter: return rg::BufferRange{m_layout.multiscatter, m_layout.bytes[1]};
    case AtmosLut::SkyView: return rg::BufferRange{m_layout.skyView, m_layout.bytes[2]};
    case AtmosLut::AerialScatter: return rg::BufferRange{m_layout.aerialScatter, m_layout.bytes[3]};
    case AtmosLut::AerialTransmittance: return rg::BufferRange{m_layout.aerialTransmittance, m_layout.bytes[4]};
    }
    return rg::BufferRange{};
}

void AtmosphereGpu::addPasses(rg::Graph& graph, const AtmosphereGraphRefs& refs) {
    if (!m_initialized || !refs.luts.valid()) {
        return;
    }
    const AtParams& p = m_params;
    const u8 cs = rg::kStageCompute;
    if (m_staticDirty) {
        PassRecord* t = nextRecord(kTransmittance);
        PassRecord* m = nextRecord(kMultiScatter);
        if (t != nullptr && m != nullptr) {
            t->groups[0] = groups(p.transWidth, kAtTile);
            t->groups[1] = groups(p.transHeight, kAtTile);
            graph.addPass("atmos.transmittance", &AtmosphereGpu::recordDispatch, t)
                .use(refs.luts, rg::Access::StorageWrite, range(AtmosLut::Transmittance), cs);
            m->groups[0] = groups(p.msWidth, kAtTile);
            m->groups[1] = groups(p.msHeight, kAtTile);
            graph.addPass("atmos.multiscatter", &AtmosphereGpu::recordDispatch, m)
                .use(refs.luts, rg::Access::StorageRead, range(AtmosLut::Transmittance), cs)
                .use(refs.luts, rg::Access::StorageWrite, range(AtmosLut::MultiScatter), cs);
            m_stats.passes += 2u;
            m_stats.staticRan = true;
            ++m_stats.staticBuilds;
            m_staticDirty = false;
            m_staticParams = p;
        }
    }
    if (PassRecord* s = nextRecord(kSkyView)) {
        s->groups[0] = groups(p.skyWidth, kAtTile);
        s->groups[1] = groups(p.skyHeight, kAtTile);
        graph.addPass("atmos.skyview", &AtmosphereGpu::recordDispatch, s)
            .use(refs.luts, rg::Access::StorageRead, range(AtmosLut::Transmittance), cs)
            .use(refs.luts, rg::Access::StorageRead, range(AtmosLut::MultiScatter), cs)
            .use(refs.luts, rg::Access::StorageWrite, range(AtmosLut::SkyView), cs);
        ++m_stats.passes;
    }
    if (PassRecord* a = nextRecord(kAerial)) {
        a->groups[0] = groups(p.apWidth, kAtTile);
        a->groups[1] = groups(p.apHeight, kAtTile);
        graph.addPass("atmos.aerial", &AtmosphereGpu::recordDispatch, a)
            .use(refs.luts, rg::Access::StorageRead, range(AtmosLut::Transmittance), cs)
            .use(refs.luts, rg::Access::StorageRead, range(AtmosLut::MultiScatter), cs)
            .use(refs.luts, rg::Access::StorageWrite, range(AtmosLut::AerialScatter), cs)
            .use(refs.luts, rg::Access::StorageWrite, range(AtmosLut::AerialTransmittance), cs);
        ++m_stats.passes;
    }
}

u64 AtmosphereGpu::lutBytes(AtmosLut which) const { return range(which).size; }

void AtmosphereGpu::addCopy(rg::Graph& graph, const AtmosphereGraphRefs& refs, AtmosLut which, rg::BufferRef dst,
                            u64 dstOffset) {
    if (!m_initialized || !dst.valid() || !refs.luts.valid()) {
        return;
    }
    PassRecord* r = nextRecord(kKernelCount);
    if (r == nullptr) {
        return;
    }
    const rg::BufferRange src = range(which);
    r->copySrc = src.offset;
    r->copyBytes = src.size;
    r->copyDst = dstOffset;
    r->copyFrom = refs.luts;
    r->copyTo = dst;
    ++m_stats.passes;
    graph.addPass("atmos.copy", &AtmosphereGpu::recordCopy, r)
        .use(refs.luts, rg::Access::TransferSrc, src)
        .use(dst, rg::Access::TransferDst, rg::BufferRange{dstOffset, src.size});
}

void AtmosphereGpu::addProbe(rg::Graph& graph, const AtmosphereGraphRefs& refs, rg::BufferRef srcBuffer, u64 srcAddress,
                             rg::BufferRef dstBuffer, u64 dstAddress, u32 count) {
    if (!m_initialized || !refs.luts.valid() || !srcBuffer.valid() || !dstBuffer.valid() || count == 0u) {
        return;
    }
    PassRecord* r = nextRecord(kProbe);
    if (r == nullptr) {
        return;
    }
    r->push.src = srcAddress;
    r->push.dst = dstAddress;
    r->push.mode = count;
    r->groups[0] = groups(count, 64u);
    ++m_stats.passes;
    const u8 cs = rg::kStageCompute;
    graph.addPass("atmos.probe", &AtmosphereGpu::recordDispatch, r)
        .use(refs.luts, rg::Access::StorageRead, {}, cs)
        .use(srcBuffer, rg::Access::StorageRead, rg::BufferRange{0, static_cast<u64>(count) * kAtProbeInputs * kTexel}, cs)
        .use(dstBuffer, rg::Access::StorageWrite, rg::BufferRange{0, static_cast<u64>(count) * kAtProbeOutputs * kTexel},
             cs);
}

void AtmosphereGpu::recordDispatch(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const AtmosphereGpu& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, static_cast<VkPipeline>(self.m_pipelines[r.kernel]));
    self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, self.m_layoutHandle, 0);
    vkCmdPushConstants(cmd, static_cast<VkPipelineLayout>(self.m_layoutHandle), VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       kPushBytes, &r.push);
    vkCmdDispatch(cmd, r.groups[0], r.groups[1], r.groups[2]);
#else
    (void)context;
    (void)user;
#endif
}

void AtmosphereGpu::recordCopy(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    const VkBufferCopy region{r.copySrc, r.copyDst, r.copyBytes};
    vkCmdCopyBuffer(cmd, static_cast<VkBuffer>(context.buffer(r.copyFrom)),
                    static_cast<VkBuffer>(context.buffer(r.copyTo)), 1, &region);
#else
    (void)context;
    (void)user;
#endif
}

} // namespace fuse::renderer::atmosphere
