// FUSE Relight RL-4.2: the raster remaster's GPU half (see raster_renderer.hpp).
#include <fuse/relight/render/raster/raster_renderer.hpp>

#include <fuse/relight/render/frame/bindless_images.hpp>
#include <fuse/relight/render/frame/renderer_context.hpp>
#include <fuse/relight/render/frame/scene_adapter.hpp>
#include <fuse/relight/render/material/bsdf_host.hpp>
#include <fuse/relight/render/raster/raster_options.hpp>
#include <fuse/relight/render/raster/raster_scene.hpp>

#include <fuse/renderer/gpu_scene/gpu_scene.hpp>
#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/bindless.hpp>
#include <fuse/renderer/vk/device.hpp>

// Last: <vulkan/vulkan.h> (volk shim; brings <windows.h> into PE builds) without the DrawState macro.
#include <fuse/relight/render/frame/vk_dispatch.hpp>

#include "raster_spv.h" // generated by render/raster/CMakeLists.txt from Relight/shaders/raster

#include <algorithm>
#include <cinttypes>
#include <cstdio>
#include <cstring>
#include <map>
#include <tuple>
#include <unordered_map>

namespace fuse::relight::render::raster {

namespace rr = fuse::renderer;
namespace rg = fuse::renderer::rg;
namespace rf = fuse::relight::render::frame;
using rf::vkHandle;
using rf::vkValue;

namespace {

constexpr VkFormat kAlbedoFormat = VK_FORMAT_R8G8B8A8_UNORM;
constexpr VkFormat kNormalFormat = VK_FORMAT_R16G16B16A16_SFLOAT;
constexpr VkFormat kEmissiveFormat = VK_FORMAT_R16G16B16A16_SFLOAT;
constexpr VkFormat kPositionFormat = VK_FORMAT_R32G32B32A32_SFLOAT;
constexpr VkFormat kDepthFormat = VK_FORMAT_D32_SFLOAT;
constexpr std::uint32_t kGBufferTargets = 4;
constexpr std::uint32_t kRing = 4;

/// std430 push constants (raster_common.glsl RasterPush).
struct Push {
    std::uint64_t vertices = 0;
    std::uint64_t draws = 0;
    std::uint64_t frame = 0;
    std::uint32_t drawIndex = 0;
    std::uint32_t pass = 0;
};
static_assert(sizeof(Push) == 32, "RasterPush");

enum : std::uint32_t { kPassGBuffer = 0, kPassDecal = 1, kPassForward = 2, kPassShadow = 3, kPassLight = 4 };

struct Target {
    VkImage image = VK_NULL_HANDLE;
    VkDeviceMemory memory = VK_NULL_HANDLE;
    VkImageView view = VK_NULL_HANDLE;
    VkFormat format = VK_FORMAT_UNDEFINED;
    std::uint32_t width = 0, height = 0;
    rr::BindlessSlotHandle slot{};
    std::uint32_t handle = 0;
    bool valid() const { return image != VK_NULL_HANDLE; }
};

struct RingSlot {
    rr::Buffer vertices{}, draws{}, frame{};
    std::uint64_t serial = 0; ///< retire serial of the frame that used it last
};

/// Key of a forward pipeline: the D3D blend state (Vulkan values) and the output format.
using BlendKey = std::tuple<bool, std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t, std::uint32_t,
                            std::uint32_t, std::uint32_t, std::uint32_t>;

class RasterRenderer final : public rf::IFrameRenderer {
public:
    explicit RasterRenderer(const rf::FrameConfig&) { m_config = RasterConfig::fromOptions(); }
    ~RasterRenderer() override { detach(); }

    bool attach(rf::RendererContext& context, tap::IFrameHost& host, rf::BindlessImageRegistry& registry) override;
    void detach() override;
    bool prepare(const rf::FrameInputs& in, std::uint64_t retireSerial) override;
    void collect(std::uint64_t completedSerial) override;
    std::string recordJson() const override;
    std::string headerJson() const override;
    const std::string& lastError() const override { return m_error; }

    bool declare(rg::Graph& graph, rg::TextureRef output, const rf::GpuImage& outputImage) override;
    Image image(std::uint32_t resource) const override;
    std::uint64_t buffer(std::uint32_t) const override { return 0; }
    void record(std::uint32_t pass, std::uint64_t commandBuffer) override;

private:
    bool createTarget(Target& t, VkFormat format, std::uint32_t w, std::uint32_t h, VkImageUsageFlags usage,
                      VkImageAspectFlags aspect);
    void retireTarget(Target& t, std::uint64_t serial);
    void destroyTarget(Target& t);
    bool ensureTargets(std::uint32_t w, std::uint32_t h, std::uint64_t serial);
    bool ensureShadowMap(std::uint32_t size, std::uint64_t serial);
    VkShaderModule module(const std::uint32_t* words, std::size_t bytes);
    VkPipeline createPipeline(VkShaderModule vs, VkShaderModule fs, const VkFormat* colors, std::uint32_t colorCount,
                              VkFormat depth, const VkPipelineColorBlendAttachmentState* blend);
    bool ensurePipelines(VkFormat output);
    VkPipeline forwardPipeline(const scene::BlendMode& b);
    bool ensureBuffer(rr::Buffer& b, std::size_t bytes, const char* name, std::uint64_t serial);
    std::uint32_t samplerHandle(const tap::CaptureDrawRecord::SamplerFacts& s);
    void setDrawState(VkCommandBuffer cmd, const RasterDraw& d) const;
    void beginPass(VkCommandBuffer cmd, VkPipeline pipeline) const;

    RasterConfig m_config;
    rf::RendererContext* m_context = nullptr;
    tap::IFrameHost* m_host = nullptr;
    rf::BindlessImageRegistry* m_registry = nullptr;
    VkDevice m_device = VK_NULL_HANDLE;
    std::string m_error;
    TierPlan m_plan;
    std::uint32_t m_available = implementedFeatures();

    VkShaderModule m_surfaceVs = VK_NULL_HANDLE, m_gbufferFs = VK_NULL_HANDLE, m_decalFs = VK_NULL_HANDLE,
                   m_forwardFs = VK_NULL_HANDLE, m_shadowFs = VK_NULL_HANDLE, m_lightVs = VK_NULL_HANDLE, m_lightFs = VK_NULL_HANDLE;
    VkPipelineLayout m_layout = VK_NULL_HANDLE;
    VkFormat m_outputFormat = VK_FORMAT_UNDEFINED;
    VkPipeline m_gbuffer = VK_NULL_HANDLE, m_decal = VK_NULL_HANDLE, m_light = VK_NULL_HANDLE,
               m_shadowPipe = VK_NULL_HANDLE;
    std::map<BlendKey, VkPipeline> m_forward;
    std::vector<VkPipeline> m_oldPipelines;

    Target m_targets[kGBufferTargets];
    Target m_depth, m_shadow;
    std::vector<std::pair<Target, std::uint64_t>> m_retiredTargets;
    rr::Buffer m_lut{};
    std::uint32_t m_nearestSampler = 0;
    rr::BindlessSlotHandle m_nearestSlot{};
    std::unordered_map<std::uint32_t, std::pair<rr::BindlessSlotHandle, std::uint32_t>> m_samplers;
    RingSlot m_ring[kRing];
    std::uint32_t m_slot = 0;
    std::vector<std::pair<rr::Buffer, std::uint64_t>> m_retiredBuffers;
    std::vector<std::pair<VkImageView, std::uint64_t>> m_retiredViews;
    std::uint64_t m_completed = 0;
    std::uint64_t m_serial = 0;      ///< retire serial of the prepared frame
    VkImageView m_outputView = VK_NULL_HANDLE; ///< this frame's view of FUSE's output image

    // The prepared frame.
    RasterFrame m_frame;
    bool m_prepared = false;
    std::uint64_t m_vertexAddress = 0, m_drawAddress = 0, m_frameAddress = 0;
    struct GameTexture {
        tap::ResourceId id = tap::kNoResource;
        tap::HostImageInfo info;
    };
    std::vector<GameTexture> m_gameTextures;
    // Graph ids of this frame's resources.
    std::unordered_map<std::uint32_t, Image> m_images;
    std::uint32_t m_pass[5] = {~0u, ~0u, ~0u, ~0u, ~0u};
    std::uint32_t m_frames = 0;
};

// ---- resources ------------------------------------------------------------------------------------------------------

std::uint32_t memoryTypeFor(VkPhysicalDevice pd, std::uint32_t bits, VkMemoryPropertyFlags flags) {
    VkPhysicalDeviceMemoryProperties p{};
    vkGetPhysicalDeviceMemoryProperties(pd, &p);
    for (std::uint32_t i = 0; i < p.memoryTypeCount; ++i) {
        if ((bits & (1u << i)) && (p.memoryTypes[i].propertyFlags & flags) == flags) {
            return i;
        }
    }
    return UINT32_MAX;
}

bool RasterRenderer::createTarget(Target& t, VkFormat format, std::uint32_t w, std::uint32_t h,
                                  VkImageUsageFlags usage, VkImageAspectFlags aspect) {
    t = Target{};
    VkImageCreateInfo ci{};
    ci.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    ci.imageType = VK_IMAGE_TYPE_2D;
    ci.format = format;
    ci.extent = {w, h, 1};
    ci.mipLevels = 1;
    ci.arrayLayers = 1;
    ci.samples = VK_SAMPLE_COUNT_1_BIT;
    ci.tiling = VK_IMAGE_TILING_OPTIMAL;
    ci.usage = usage | VK_IMAGE_USAGE_SAMPLED_BIT;
    ci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    ci.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    if (vkCreateImage(m_device, &ci, nullptr, &t.image) != VK_SUCCESS) {
        t.image = VK_NULL_HANDLE;
        return false;
    }
    VkMemoryRequirements req{};
    vkGetImageMemoryRequirements(m_device, t.image, &req);
    VkMemoryAllocateInfo mi{};
    mi.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
    mi.allocationSize = req.size;
    const VkPhysicalDevice pd = static_cast<VkPhysicalDevice>(m_context->device().nativePhysicalDevice());
    mi.memoryTypeIndex = memoryTypeFor(pd, req.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (mi.memoryTypeIndex == UINT32_MAX) {
        mi.memoryTypeIndex = memoryTypeFor(pd, req.memoryTypeBits, 0);
    }
    if (mi.memoryTypeIndex == UINT32_MAX || vkAllocateMemory(m_device, &mi, nullptr, &t.memory) != VK_SUCCESS ||
        vkBindImageMemory(m_device, t.image, t.memory, 0) != VK_SUCCESS) {
        destroyTarget(t);
        return false;
    }
    VkImageViewCreateInfo vi{};
    vi.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    vi.image = t.image;
    vi.viewType = VK_IMAGE_VIEW_TYPE_2D;
    vi.format = format;
    vi.subresourceRange = {aspect, 0, 1, 0, 1};
    if (vkCreateImageView(m_device, &vi, nullptr, &t.view) != VK_SUCCESS) {
        t.view = VK_NULL_HANDLE;
        destroyTarget(t);
        return false;
    }
    t.format = format;
    t.width = w;
    t.height = h;
    rr::Texture tex;
    tex.image = t.image;
    tex.view = t.view;
    tex.desc.width = w;
    tex.desc.height = h;
    tex.desc.format = static_cast<rr::GpuFormat>(format);
    tex.desc.usage = rr::ImageUsage::Sampled;
    t.slot = m_context->bindless().registerTextureSlot(tex, false);
    t.handle = m_context->bindless().shaderHandle(t.slot);
    if (!t.handle) {
        destroyTarget(t);
        return false;
    }
    return true;
}

void RasterRenderer::destroyTarget(Target& t) {
    if (t.view != VK_NULL_HANDLE) {
        vkDestroyImageView(m_device, t.view, nullptr);
    }
    if (t.image != VK_NULL_HANDLE) {
        vkDestroyImage(m_device, t.image, nullptr);
    }
    if (t.memory != VK_NULL_HANDLE) {
        vkFreeMemory(m_device, t.memory, nullptr);
    }
    t = Target{};
}

void RasterRenderer::retireTarget(Target& t, std::uint64_t serial) {
    if (!t.valid()) {
        return;
    }
    if (t.slot.isValid()) {
        m_context->bindless().retireSlot(t.slot, serial);
    }
    m_retiredTargets.emplace_back(t, serial);
    t = Target{};
}

bool RasterRenderer::ensureTargets(std::uint32_t w, std::uint32_t h, std::uint64_t serial) {
    if (m_depth.valid() && m_depth.width == w && m_depth.height == h) {
        return true;
    }
    for (Target& t : m_targets) {
        retireTarget(t, serial);
    }
    retireTarget(m_depth, serial);
    const VkFormat formats[kGBufferTargets] = {kAlbedoFormat, kNormalFormat, kEmissiveFormat, kPositionFormat};
    for (std::uint32_t i = 0; i < kGBufferTargets; ++i) {
        if (!createTarget(m_targets[i], formats[i], w, h, VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, VK_IMAGE_ASPECT_COLOR_BIT)) {
            m_error = "G-buffer target creation failed";
            return false;
        }
    }
    if (!createTarget(m_depth, kDepthFormat, w, h, VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT, VK_IMAGE_ASPECT_DEPTH_BIT)) {
        m_error = "depth target creation failed";
        return false;
    }
    return true;
}

bool RasterRenderer::ensureShadowMap(std::uint32_t size, std::uint64_t serial) {
    if (m_shadow.valid() && m_shadow.width == size) {
        return true;
    }
    retireTarget(m_shadow, serial);
    return createTarget(m_shadow, kDepthFormat, size, size, VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT,
                        VK_IMAGE_ASPECT_DEPTH_BIT);
}

bool RasterRenderer::ensureBuffer(rr::Buffer& b, std::size_t bytes, const char* name, std::uint64_t serial) {
    if (b.handle && b.desc.size >= bytes) {
        return true;
    }
    if (b.handle) {
        m_retiredBuffers.emplace_back(b, serial);
        b = rr::Buffer{};
    }
    rr::BufferDesc d;
    d.size = std::max<std::size_t>(bytes + bytes / 2, 4096);
    d.usage = static_cast<rr::BufferUsage>(static_cast<std::uint32_t>(rr::BufferUsage::Storage) |
                                          static_cast<std::uint32_t>(rr::BufferUsage::ShaderDeviceAddress));
    d.memoryUsage = rr::MemoryUsage::CpuToGpu;
    d.name = name;
    return m_context->allocator().createBuffer(d, b) && b.mapped != nullptr && b.deviceAddress != 0;
}

std::uint32_t RasterRenderer::samplerHandle(const tap::CaptureDrawRecord::SamplerFacts& s) {
    // D3DTADDRESS: 1 wrap, 2 mirror, 3 clamp, 4 border, 5 mirror once; D3DTEXF: <= 1 nearest.
    const std::uint32_t address = s.addressU == 2 ? VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT
                                  : s.addressU == 3 ? VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE
                                  : s.addressU == 4 ? VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER
                                  : s.addressU == 5 ? VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE
                                                    : VK_SAMPLER_ADDRESS_MODE_REPEAT;
    const std::uint32_t filter = s.magFilter <= 1 ? VK_FILTER_NEAREST : VK_FILTER_LINEAR;
    const std::uint32_t key = address | filter << 8;
    auto it = m_samplers.find(key);
    if (it != m_samplers.end()) {
        return it->second.second;
    }
    rr::SamplerDesc d;
    d.minFilter = filter;
    d.magFilter = filter;
    d.addressMode = address;
    d.maxLod = 0.f; // mip 0: the capture samples the base level of legacy textures
    d.name = "relight.raster.sampler";
    const rr::BindlessSlotHandle slot = m_context->bindless().acquireSampler(d);
    const std::uint32_t handle = m_context->bindless().shaderHandle(slot);
    m_samplers.emplace(key, std::make_pair(slot, handle));
    return handle;
}

// ---- pipelines ------------------------------------------------------------------------------------------------------

VkShaderModule RasterRenderer::module(const std::uint32_t* words, std::size_t bytes) {
    VkShaderModuleCreateInfo ci{};
    ci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    ci.codeSize = bytes;
    ci.pCode = words;
    VkShaderModule m = VK_NULL_HANDLE;
    return vkCreateShaderModule(m_device, &ci, nullptr, &m) == VK_SUCCESS ? m : VK_NULL_HANDLE;
}

VkPipeline RasterRenderer::createPipeline(VkShaderModule vs, VkShaderModule fs, const VkFormat* colors,
                                          std::uint32_t colorCount, VkFormat depth,
                                          const VkPipelineColorBlendAttachmentState* blend) {
    VkPipelineShaderStageCreateInfo stages[2]{};
    stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vs;
    stages[0].pName = "main";
    stages[1] = stages[0];
    stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = fs;
    VkPipelineVertexInputStateCreateInfo vertexInput{};
    vertexInput.sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO;
    VkPipelineInputAssemblyStateCreateInfo assembly{};
    assembly.sType = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO;
    assembly.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;
    VkPipelineViewportStateCreateInfo viewport{};
    viewport.sType = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO;
    viewport.viewportCount = 1;
    viewport.scissorCount = 1;
    VkPipelineRasterizationStateCreateInfo raster{};
    raster.sType = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO;
    raster.polygonMode = VK_POLYGON_MODE_FILL;
    raster.lineWidth = 1.f;
    VkPipelineMultisampleStateCreateInfo multisample{};
    multisample.sType = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO;
    multisample.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;
    VkPipelineDepthStencilStateCreateInfo ds{};
    ds.sType = VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO;
    ds.depthCompareOp = VK_COMPARE_OP_LESS_OR_EQUAL;
    VkPipelineColorBlendStateCreateInfo cb{};
    cb.sType = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO;
    VkPipelineColorBlendAttachmentState opaque[kGBufferTargets]{};
    for (VkPipelineColorBlendAttachmentState& a : opaque) {
        a.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT |
                           VK_COLOR_COMPONENT_A_BIT;
    }
    cb.attachmentCount = colorCount;
    cb.pAttachments = blend ? blend : opaque;
    const VkDynamicState dynamic[] = {VK_DYNAMIC_STATE_VIEWPORT,          VK_DYNAMIC_STATE_SCISSOR,
                                      VK_DYNAMIC_STATE_CULL_MODE,         VK_DYNAMIC_STATE_FRONT_FACE,
                                      VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE, VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE,
                                      VK_DYNAMIC_STATE_DEPTH_COMPARE_OP,  VK_DYNAMIC_STATE_BLEND_CONSTANTS};
    VkPipelineDynamicStateCreateInfo dyn{};
    dyn.sType = VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO;
    dyn.dynamicStateCount = static_cast<std::uint32_t>(std::size(dynamic));
    dyn.pDynamicStates = dynamic;
    VkPipelineRenderingCreateInfo rendering{};
    rendering.sType = VK_STRUCTURE_TYPE_PIPELINE_RENDERING_CREATE_INFO;
    rendering.colorAttachmentCount = colorCount;
    rendering.pColorAttachmentFormats = colors;
    rendering.depthAttachmentFormat = depth;
    VkGraphicsPipelineCreateInfo ci{};
    ci.sType = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO;
    ci.pNext = &rendering;
    ci.flags = m_context->bindless().pipelineCreateFlags();
    ci.stageCount = fs != VK_NULL_HANDLE ? 2u : 1u;
    ci.pStages = stages;
    ci.pVertexInputState = &vertexInput;
    ci.pInputAssemblyState = &assembly;
    ci.pViewportState = &viewport;
    ci.pRasterizationState = &raster;
    ci.pMultisampleState = &multisample;
    ci.pDepthStencilState = &ds;
    ci.pColorBlendState = &cb;
    ci.pDynamicState = &dyn;
    ci.layout = m_layout;
    VkPipeline p = VK_NULL_HANDLE;
    return vkCreateGraphicsPipelines(m_device, VK_NULL_HANDLE, 1, &ci, nullptr, &p) == VK_SUCCESS ? p : VK_NULL_HANDLE;
}

bool RasterRenderer::ensurePipelines(VkFormat output) {
    if (!m_gbuffer) {
        const VkFormat colors[kGBufferTargets] = {kAlbedoFormat, kNormalFormat, kEmissiveFormat, kPositionFormat};
        m_gbuffer = createPipeline(m_surfaceVs, m_gbufferFs, colors, kGBufferTargets, kDepthFormat, nullptr);
        if (!m_gbuffer) {
            m_error = "G-buffer pipeline creation failed";
            return false;
        }
    }
    if (!m_decal && (m_available & kFeatureDecals)) {
        VkPipelineColorBlendAttachmentState b{};
        b.blendEnable = VK_TRUE;
        b.srcColorBlendFactor = VK_BLEND_FACTOR_SRC_ALPHA;
        b.dstColorBlendFactor = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA;
        b.colorBlendOp = VK_BLEND_OP_ADD;
        b.srcAlphaBlendFactor = VK_BLEND_FACTOR_ZERO;
        b.dstAlphaBlendFactor = VK_BLEND_FACTOR_ONE;
        b.alphaBlendOp = VK_BLEND_OP_ADD;
        b.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT | VK_COLOR_COMPONENT_B_BIT;
        const VkFormat albedo = kAlbedoFormat;
        m_decal = createPipeline(m_surfaceVs, m_decalFs, &albedo, 1, kDepthFormat, &b);
        if (!m_decal) {
            m_available &= ~static_cast<std::uint32_t>(kFeatureDecals); // degrade: decals drawn as opaque
        }
    }
    if (!m_shadowPipe && (m_available & kFeatureShadows)) {
        m_shadowPipe = createPipeline(m_surfaceVs, m_shadowFs, nullptr, 0, kDepthFormat, nullptr);
        if (!m_shadowPipe) {
            m_available &= ~static_cast<std::uint32_t>(kFeatureShadows);
        }
    }
    if (m_outputFormat != output) {
        if (m_light) {
            m_oldPipelines.push_back(m_light);
            m_light = VK_NULL_HANDLE;
        }
        for (auto& [key, p] : m_forward) {
            m_oldPipelines.push_back(p);
        }
        m_forward.clear();
        m_outputFormat = output;
    }
    if (!m_light) {
        m_light = createPipeline(m_lightVs, m_lightFs, &output, 1, VK_FORMAT_UNDEFINED, nullptr);
        if (!m_light) {
            m_error = "lighting pipeline creation failed";
            return false;
        }
    }
    return true;
}

VkPipeline RasterRenderer::forwardPipeline(const scene::BlendMode& b) {
    const BlendKey key{b.enableBlending, b.colorSrcFactor, b.colorDstFactor, b.colorBlendOp, b.alphaSrcFactor,
                       b.alphaDstFactor, b.alphaBlendOp, b.writeMask, static_cast<std::uint32_t>(m_outputFormat)};
    auto it = m_forward.find(key);
    if (it != m_forward.end()) {
        return it->second;
    }
    VkPipelineColorBlendAttachmentState a{};
    a.blendEnable = b.enableBlending ? VK_TRUE : VK_FALSE;
    a.srcColorBlendFactor = static_cast<VkBlendFactor>(b.colorSrcFactor);
    a.dstColorBlendFactor = static_cast<VkBlendFactor>(b.colorDstFactor);
    a.colorBlendOp = static_cast<VkBlendOp>(b.colorBlendOp);
    a.srcAlphaBlendFactor = static_cast<VkBlendFactor>(b.alphaSrcFactor);
    a.dstAlphaBlendFactor = static_cast<VkBlendFactor>(b.alphaDstFactor);
    a.alphaBlendOp = static_cast<VkBlendOp>(b.alphaBlendOp);
    a.colorWriteMask = b.writeMask & 0xfu;
    const VkFormat output = m_outputFormat;
    const VkPipeline p = createPipeline(m_surfaceVs, m_forwardFs, &output, 1, kDepthFormat, &a);
    m_forward.emplace(key, p);
    return p;
}

// ---- lifetime -------------------------------------------------------------------------------------------------------

bool RasterRenderer::attach(rf::RendererContext& context, tap::IFrameHost& host, rf::BindlessImageRegistry& registry) {
    detach();
    m_context = &context;
    m_host = &host;
    m_registry = &registry;
    m_device = static_cast<VkDevice>(context.device().nativeHandle());
    m_available = implementedFeatures();
    m_plan = planTier(context.stats().tier, m_config.tier, m_available);
    const auto fail = [&](const char* why) {
        m_error = why;
        detach();
        return false;
    };
    m_surfaceVs = module(kRasterSurfaceVsSpv, sizeof(kRasterSurfaceVsSpv));
    m_gbufferFs = module(kRasterGbufferFsSpv, sizeof(kRasterGbufferFsSpv));
    m_decalFs = module(kRasterDecalFsSpv, sizeof(kRasterDecalFsSpv));
    m_forwardFs = module(kRasterForwardFsSpv, sizeof(kRasterForwardFsSpv));
    m_shadowFs = module(kRasterShadowFsSpv, sizeof(kRasterShadowFsSpv));
    m_lightVs = module(kRasterLightVsSpv, sizeof(kRasterLightVsSpv));
    m_lightFs = module(kRasterLightFsSpv, sizeof(kRasterLightFsSpv));
    if (!m_surfaceVs || !m_gbufferFs || !m_decalFs || !m_forwardFs || !m_shadowFs || !m_lightVs || !m_lightFs) {
        return fail("shader module creation failed");
    }
    VkDescriptorSetLayout set = static_cast<VkDescriptorSetLayout>(context.bindless().layoutHandle());
    VkPushConstantRange range{VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0, sizeof(Push)};
    VkPipelineLayoutCreateInfo li{};
    li.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    li.setLayoutCount = 1;
    li.pSetLayouts = &set;
    li.pushConstantRangeCount = 1;
    li.pPushConstantRanges = &range;
    if (vkCreatePipelineLayout(m_device, &li, nullptr, &m_layout) != VK_SUCCESS) {
        m_layout = VK_NULL_HANDLE;
        return fail("pipeline layout creation failed");
    }
    // The RL-4.3 BSDF's albedo table, read by the lighting (raster_lighting.glsl) by device address.
    const render::material::AlbedoLut& lut = render::material::sharedAlbedoLut();
    if (!lut.valid() || !ensureBuffer(m_lut, lut.size() * sizeof(float), "relight.raster.bsdf_lut", 0)) {
        return fail("BSDF albedo table upload failed");
    }
    std::memcpy(m_lut.mapped, lut.data(), lut.size() * sizeof(float));
    rr::SamplerDesc nearest;
    nearest.addressMode = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE;
    nearest.maxLod = 0.f;
    nearest.name = "relight.raster.nearest";
    m_nearestSlot = context.bindless().acquireSampler(nearest);
    m_nearestSampler = context.bindless().shaderHandle(m_nearestSlot);
    if (!m_nearestSampler) {
        return fail("sampler slot unavailable");
    }
    return true;
}

void RasterRenderer::detach() {
    if (!m_context) {
        return;
    }
    // The caller made the GPU idle (orchestrator detach waits for the host and FUSE).
    for (Target& t : m_targets) {
        if (t.slot.isValid()) {
            m_context->bindless().retireSlot(t.slot, 0);
        }
        destroyTarget(t);
    }
    for (Target* t : {&m_depth, &m_shadow}) {
        if (t->slot.isValid()) {
            m_context->bindless().retireSlot(t->slot, 0);
        }
        destroyTarget(*t);
    }
    for (auto& [t, serial] : m_retiredTargets) {
        destroyTarget(t);
    }
    m_retiredTargets.clear();
    for (RingSlot& r : m_ring) {
        for (rr::Buffer* b : {&r.vertices, &r.draws, &r.frame}) {
            if (b->handle) {
                m_context->allocator().destroyBuffer(*b);
            }
        }
        r = RingSlot{};
    }
    for (auto& [b, serial] : m_retiredBuffers) {
        m_context->allocator().destroyBuffer(b);
    }
    m_retiredBuffers.clear();
    for (auto& [view, serial] : m_retiredViews) {
        vkDestroyImageView(m_device, view, nullptr);
    }
    m_retiredViews.clear();
    m_outputView = VK_NULL_HANDLE;
    if (m_lut.handle) {
        m_context->allocator().destroyBuffer(m_lut);
    }
    m_lut = rr::Buffer{};
    for (auto& [key, s] : m_samplers) {
        m_context->bindless().releaseSampler(s.first);
    }
    m_samplers.clear();
    if (m_nearestSlot.isValid()) {
        m_context->bindless().releaseSampler(m_nearestSlot);
    }
    m_nearestSlot = {};
    m_context->bindless().collectRetired(UINT64_MAX);
    for (auto& [key, p] : m_forward) {
        m_oldPipelines.push_back(p);
    }
    m_forward.clear();
    for (VkPipeline p : {m_gbuffer, m_decal, m_light, m_shadowPipe}) {
        m_oldPipelines.push_back(p);
    }
    for (VkPipeline p : m_oldPipelines) {
        if (p != VK_NULL_HANDLE) {
            vkDestroyPipeline(m_device, p, nullptr);
        }
    }
    m_oldPipelines.clear();
    m_gbuffer = m_decal = m_light = m_shadowPipe = VK_NULL_HANDLE;
    m_outputFormat = VK_FORMAT_UNDEFINED;
    if (m_layout) {
        vkDestroyPipelineLayout(m_device, m_layout, nullptr);
    }
    m_layout = VK_NULL_HANDLE;
    for (VkShaderModule* m : {&m_surfaceVs, &m_gbufferFs, &m_decalFs, &m_forwardFs, &m_shadowFs, &m_lightVs, &m_lightFs}) {
        if (*m) {
            vkDestroyShaderModule(m_device, *m, nullptr);
        }
        *m = VK_NULL_HANDLE;
    }
    m_prepared = false;
    m_context = nullptr;
    m_host = nullptr;
    m_registry = nullptr;
    m_device = VK_NULL_HANDLE;
}

void RasterRenderer::collect(std::uint64_t completed) {
    m_completed = std::max(m_completed, completed);
    if (!m_context) {
        return;
    }
    auto t = std::remove_if(m_retiredTargets.begin(), m_retiredTargets.end(), [&](auto& e) {
        if (e.second > completed) {
            return false;
        }
        destroyTarget(e.first);
        return true;
    });
    m_retiredTargets.erase(t, m_retiredTargets.end());
    auto b = std::remove_if(m_retiredBuffers.begin(), m_retiredBuffers.end(), [&](auto& e) {
        if (e.second > completed) {
            return false;
        }
        m_context->allocator().destroyBuffer(e.first);
        return true;
    });
    m_retiredBuffers.erase(b, m_retiredBuffers.end());
    auto v = std::remove_if(m_retiredViews.begin(), m_retiredViews.end(), [&](auto& e) {
        if (e.second > completed) {
            return false;
        }
        vkDestroyImageView(m_device, e.first, nullptr);
        return true;
    });
    m_retiredViews.erase(v, m_retiredViews.end());
}

// ---- the frame ------------------------------------------------------------------------------------------------------

bool RasterRenderer::prepare(const rf::FrameInputs& in, std::uint64_t serial) {
    m_prepared = false;
    m_error.clear();
    if (!m_context || !m_layout || !in.backBuffer || !in.draws) {
        m_error = "not attached";
        return false;
    }
    const tap::HostImageInfo& bb = *in.backBuffer;
    // Game textures: 2D, single layer, single sample, registered with a live bindless slot.
    std::unordered_map<tap::ResourceId, tap::HostImageInfo> infos;
    auto textureHandle = [&](tap::ResourceId id) -> std::uint32_t {
        tap::HostImageInfo info;
        if (!m_host->textureInfo(id, info) || info.imageType != VK_IMAGE_TYPE_2D || info.arrayLayers != 1 ||
            info.samples != 1 || info.aspects != VK_IMAGE_ASPECT_COLOR_BIT) {
            return 0u;
        }
        const std::uint32_t h = m_registry->shaderHandle(id);
        if (h) {
            infos[id] = info;
        }
        return h;
    };
    BuildInputs bi;
    bi.frame = in.frame;
    bi.draws = in.draws;
    bi.count = in.count;
    bi.classifications = in.classifications;
    bi.sceneDraw = in.sceneDraw;
    bi.haveClear = in.haveClear;
    bi.clearColor = in.clearColor;
    bi.width = bb.width;
    bi.height = bb.height;
    bi.textureHandle = textureHandle;
    bi.samplerHandle = [this](const tap::CaptureDrawRecord::SamplerFacts& s) { return samplerHandle(s); };
    bi.replacementMaterial = in.replacementMaterial;
    if (in.sceneLights || in.lights) {
        for (const rf::AdapterLight& a : in.sceneLights ? *in.sceneLights : rf::adapterLights(*in.lights)) {
            RasterLight l;
            l.light = a.light;
            l.slot = m_context->adapter().lightSlot(a.key);
            bi.lights.push_back(l);
        }
    }
    m_plan = planTier(m_context->stats().tier, m_config.tier, m_available);
    BuildOptions opt;
    opt.features = m_plan.enabled;
    std::copy(std::begin(m_config.ambient), std::end(m_config.ambient), opt.ambient);
    opt.exposure = m_config.exposure;
    opt.fog = m_config.fog;
    opt.fallbackLightMode = m_config.fallbackLightMode;
    std::copy(std::begin(m_config.fallbackRadiance), std::end(m_config.fallbackRadiance), opt.fallbackRadiance);
    std::copy(std::begin(m_config.fallbackDirection), std::end(m_config.fallbackDirection), opt.fallbackDirection);
    if (!m_config.decals) {
        opt.features &= ~static_cast<std::uint32_t>(kFeatureDecals);
    }
    if (!buildRasterFrame(bi, opt, m_frame)) {
        m_error = "no scene draw to render";
        return false;
    }
    if (!ensurePipelines(static_cast<VkFormat>(bb.format)) || !ensureTargets(bb.width, bb.height, serial) ||
        (m_frame.shadow && !ensureShadowMap(m_config.shadowMapSize, serial))) {
        if (m_error.empty()) {
            m_error = "raster resources unavailable";
        }
        return false;
    }
    m_gameTextures.clear();
    for (const tap::ResourceId id : m_frame.textures) {
        auto it = infos.find(id);
        if (it != infos.end()) {
            m_gameTextures.push_back(GameTexture{id, it->second});
        }
    }

    // Upload into a ring slot whose last frame completed.
    std::uint32_t slot = kRing;
    for (std::uint32_t i = 0; i < kRing; ++i) {
        const std::uint32_t s = (m_slot + i) % kRing;
        if (m_ring[s].serial <= m_completed) {
            slot = s;
            break;
        }
    }
    if (slot == kRing) {
        m_error = "every raster upload slot is in flight";
        return false;
    }
    m_slot = (slot + 1) % kRing;
    RingSlot& r = m_ring[slot];
    const std::size_t vbytes = m_frame.vertices.size() * sizeof(RasterVertex);
    const std::size_t dbytes = m_frame.gpuDraws.size() * sizeof(RasterDrawGpu);
    // Frame buffer: constants | grid | light list | directional list (16-byte aligned sections).
    auto align16 = [](std::size_t v) { return (v + 15u) & ~static_cast<std::size_t>(15u); };
    const std::size_t gridOff = align16(sizeof(RasterFrameGpu));
    const std::size_t listOff = align16(gridOff + m_frame.grid.size() * 4u);
    const std::size_t dirOff = align16(listOff + std::max<std::size_t>(m_frame.lightList.size(), 1u) * 4u);
    const std::size_t fbytes = dirOff + std::max<std::size_t>(m_frame.directional.size(), 1u) * 4u;
    if (!ensureBuffer(r.vertices, vbytes, "relight.raster.vertices", r.serial) ||
        !ensureBuffer(r.draws, dbytes, "relight.raster.draws", r.serial) ||
        !ensureBuffer(r.frame, fbytes, "relight.raster.frame", r.serial)) {
        m_error = "raster upload buffers unavailable";
        return false;
    }
    r.serial = serial;
    std::memcpy(r.vertices.mapped, m_frame.vertices.data(), vbytes);
    std::memcpy(r.draws.mapped, m_frame.gpuDraws.data(), dbytes);
    RasterFrameGpu& k = m_frame.constants;
    auto* base = static_cast<std::uint8_t*>(r.frame.mapped);
    k.grid = r.frame.deviceAddress + gridOff;
    k.lightList = r.frame.deviceAddress + listOff;
    k.directional = r.frame.deviceAddress + dirOff;
    k.lut = m_lut.deviceAddress;
    for (std::uint32_t i = 0; i < kGBufferTargets; ++i) {
        k.gbuffer[i] = m_targets[i].handle;
    }
    k.handles[1] = m_frame.shadow ? m_shadow.handle : 0u;
    k.handles[2] = m_nearestSampler;
    k.handles[3] = m_context->scene().headerHandle();
    if (m_frame.shadow) {
        k.shadowParams[0] = 1.f / static_cast<float>(m_shadow.width);
        k.shadowParams[1] = 0.002f;
        k.shadowParams[2] /= static_cast<float>(m_shadow.width); // world size of one shadow texel
    }
    std::memcpy(base, &k, sizeof(k));
    std::memcpy(base + gridOff, m_frame.grid.data(), m_frame.grid.size() * 4u);
    std::memcpy(base + listOff, m_frame.lightList.data(), m_frame.lightList.size() * 4u);
    std::memcpy(base + dirOff, m_frame.directional.data(), m_frame.directional.size() * 4u);
    m_serial = serial;
    m_vertexAddress = r.vertices.deviceAddress;
    m_drawAddress = r.draws.deviceAddress;
    m_frameAddress = r.frame.deviceAddress;
    m_prepared = true;
    ++m_frames;
    return true;
}

bool RasterRenderer::declare(rg::Graph& graph, rg::TextureRef output, const rf::GpuImage& outputImage) {
    if (!m_prepared) {
        return false;
    }
    // A view of FUSE's output image for this frame (the orchestrator recreates the image on resize).
    VkImageViewCreateInfo vi{};
    vi.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    vi.image = vkHandle<VkImage>(outputImage.image.vkImage);
    vi.viewType = VK_IMAGE_VIEW_TYPE_2D;
    vi.format = static_cast<VkFormat>(outputImage.image.info.format);
    vi.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    if (vi.format != m_outputFormat || vkCreateImageView(m_device, &vi, nullptr, &m_outputView) != VK_SUCCESS) {
        m_outputView = VK_NULL_HANDLE;
        m_error = "cannot view FUSE's output image";
        return false;
    }
    m_retiredViews.emplace_back(m_outputView, m_serial);
    m_images.clear();
    for (std::uint32_t& p : m_pass) {
        p = ~0u;
    }
    m_images[output.id] = Image{0, VK_IMAGE_ASPECT_COLOR_BIT}; // FrameGpu resolves the output itself
    auto import = [&](const Target& t, const char* name, VkImageAspectFlags aspect) {
        rg::ImportedImage i;
        i.image = t.image;
        i.view = t.view;
        i.format = static_cast<std::uint32_t>(t.format);
        i.width = t.width;
        i.height = t.height;
        i.initialLayout = 0; // every pass that reads a target first writes it this frame
        i.name = name;
        const rg::TextureRef ref = graph.importImage(i);
        m_images[ref.id] = Image{vkValue(t.image), aspect};
        return ref;
    };
    const char* names[kGBufferTargets] = {"raster.albedo", "raster.normal", "raster.emissive", "raster.position"};
    rg::TextureRef gbuffer[kGBufferTargets];
    for (std::uint32_t i = 0; i < kGBufferTargets; ++i) {
        gbuffer[i] = import(m_targets[i], names[i], VK_IMAGE_ASPECT_COLOR_BIT);
    }
    const rg::TextureRef depth = import(m_depth, "raster.depth", VK_IMAGE_ASPECT_DEPTH_BIT);
    const rg::TextureRef shadow = m_frame.shadow ? import(m_shadow, "raster.shadow", VK_IMAGE_ASPECT_DEPTH_BIT)
                                                 : rg::TextureRef{};
    // DXVK's images, sampled in their own layout (the graph transitions to SHADER_READ_ONLY and back when needed).
    std::vector<rg::TextureRef> games;
    for (const GameTexture& g : m_gameTextures) {
        rg::ImportedImage i;
        i.image = reinterpret_cast<void*>(static_cast<std::uintptr_t>(g.info.vkImage));
        i.format = g.info.format;
        i.width = g.info.width;
        i.height = g.info.height;
        i.mipLevels = g.info.mipLevels;
        i.arrayLayers = g.info.arrayLayers;
        const std::uint32_t layout =
            g.info.layout ? g.info.layout : static_cast<std::uint32_t>(VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
        i.initialLayout = layout;
        i.finalLayout = layout;
        i.name = "raster.game_texture";
        const rg::TextureRef ref = graph.importImage(i);
        m_images[ref.id] = Image{g.info.vkImage, VK_IMAGE_ASPECT_COLOR_BIT};
        games.push_back(ref);
    }
    auto useGames = [&](rg::PassBuilder& p) {
        for (const rg::TextureRef& t : games) {
            p.use(t, rg::Access::SampledRead, {}, rg::kStageFragment);
        }
    };
    bool anyDecal = false, anyBlend = false;
    for (const RasterDraw& d : m_frame.draws) {
        anyDecal |= d.bucket == Bucket::Decal;
        anyBlend |= d.bucket == Bucket::Blend;
    }
    if (m_frame.shadow) {
        m_pass[kPassShadow] = graph.addPass("raster.shadow", nullptr, nullptr)
                                  .use(shadow, rg::Access::DepthAttachmentWrite)
                                  .index();
    }
    {
        rg::PassBuilder p = graph.addPass("raster.gbuffer", nullptr, nullptr);
        for (const rg::TextureRef& t : gbuffer) {
            p.use(t, rg::Access::ColorAttachmentWrite);
        }
        p.use(depth, rg::Access::DepthAttachmentWrite);
        useGames(p);
        m_pass[kPassGBuffer] = p.index();
    }
    if (anyDecal && m_decal) {
        rg::PassBuilder p = graph.addPass("raster.decal", nullptr, nullptr);
        p.use(gbuffer[0], rg::Access::ColorAttachmentWrite).use(depth, rg::Access::DepthAttachmentRead);
        useGames(p);
        m_pass[kPassDecal] = p.index();
    }
    {
        rg::PassBuilder p = graph.addPass("raster.light", nullptr, nullptr);
        for (const rg::TextureRef& t : gbuffer) {
            p.use(t, rg::Access::SampledRead, {}, rg::kStageFragment);
        }
        if (shadow.valid()) {
            p.use(shadow, rg::Access::SampledRead, {}, rg::kStageFragment);
        }
        p.use(output, rg::Access::ColorAttachmentWrite).neverCull();
        m_pass[kPassLight] = p.index();
    }
    if (anyBlend) {
        rg::PassBuilder p = graph.addPass("raster.forward", nullptr, nullptr);
        p.use(output, rg::Access::ColorAttachmentWrite).use(depth, rg::Access::DepthAttachmentWrite);
        if (shadow.valid()) {
            p.use(shadow, rg::Access::SampledRead, {}, rg::kStageFragment);
        }
        useGames(p);
        p.neverCull();
        m_pass[kPassForward] = p.index();
    }
    return true;
}

rf::IFrameRecorder::Image RasterRenderer::image(std::uint32_t resource) const {
    auto it = m_images.find(resource);
    return it != m_images.end() ? it->second : Image{};
}

void RasterRenderer::beginPass(VkCommandBuffer cmd, VkPipeline pipeline) const {
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline);
    m_context->bindless().bind(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, m_layout, 0);
    const float constants[4] = {1.f, 1.f, 1.f, 1.f};
    vkCmdSetBlendConstants(cmd, constants);
}

void RasterRenderer::setDrawState(VkCommandBuffer cmd, const RasterDraw& d) const {
    // DXVK's D3D9 viewport: the draw's D3D rectangle (the whole target when it has none), origin + half-pixel
    // correction, flipped (negative height), MinZ bias below 0.5; the scissor is the rectangle (D3D clips to it).
    std::uint32_t rx = 0, ry = 0, rw = m_frame.width, rh = m_frame.height;
    if (d.viewportWidth > 0 && d.viewportHeight > 0) {
        rx = d.viewportX;
        ry = d.viewportY;
        rw = d.viewportWidth;
        rh = d.viewportHeight;
    }
    const float x = static_cast<float>(rx), y = static_cast<float>(ry);
    const float w = static_cast<float>(rw), h = static_cast<float>(rh);
    const float zBias = d.minZ >= 0.5f ? 0.f : 0.001f;
    VkViewport vp{x + 0.5f, y + h + 0.5f, w, -h, std::clamp(d.minZ, 0.f, 1.f),
                  std::clamp(std::max(d.maxZ, d.minZ + zBias), 0.f, 1.f)};
    vkCmdSetViewport(cmd, 0, 1, &vp);
    const VkRect2D scissor{{static_cast<std::int32_t>(rx), static_cast<std::int32_t>(ry)}, {rw, rh}};
    vkCmdSetScissor(cmd, 0, 1, &scissor);
    // D3DCULL: 1 none, 2 CW -> front, 3 CCW -> back; front face clockwise (DXVK).
    vkCmdSetCullMode(cmd, d.cullMode == 2 ? VK_CULL_MODE_FRONT_BIT
                                          : (d.cullMode == 3 ? VK_CULL_MODE_BACK_BIT : VK_CULL_MODE_NONE));
    vkCmdSetFrontFace(cmd, VK_FRONT_FACE_CLOCKWISE);
    vkCmdSetDepthTestEnable(cmd, d.zEnable ? VK_TRUE : VK_FALSE);
    vkCmdSetDepthWriteEnable(cmd, d.zEnable && d.zWrite ? VK_TRUE : VK_FALSE);
    vkCmdSetDepthCompareOp(cmd, VK_COMPARE_OP_LESS_OR_EQUAL);
}

void RasterRenderer::record(std::uint32_t pass, std::uint64_t commandBuffer) {
    const VkCommandBuffer cmd = vkHandle<VkCommandBuffer>(commandBuffer);
    Push push;
    push.vertices = m_vertexAddress;
    push.draws = m_drawAddress;
    push.frame = m_frameAddress;
    auto colorAttachment = [](const Target& t, VkAttachmentLoadOp load) {
        VkRenderingAttachmentInfo a{};
        a.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO;
        a.imageView = t.view;
        a.imageLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
        a.loadOp = load;
        a.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
        return a;
    };
    auto depthAttachment = [](const Target& t, VkAttachmentLoadOp load, bool write) {
        VkRenderingAttachmentInfo a{};
        a.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO;
        a.imageView = t.view;
        a.imageLayout = write ? VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL
                              : VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL;
        a.loadOp = load;
        a.storeOp = write ? VK_ATTACHMENT_STORE_OP_STORE : VK_ATTACHMENT_STORE_OP_NONE;
        a.clearValue.depthStencil = {1.f, 0};
        return a;
    };
    auto begin = [&](const VkRenderingAttachmentInfo* colors, std::uint32_t count, const VkRenderingAttachmentInfo* depth,
                     std::uint32_t w, std::uint32_t h) {
        VkRenderingInfo ri{};
        ri.sType = VK_STRUCTURE_TYPE_RENDERING_INFO;
        ri.renderArea = {{0, 0}, {w, h}};
        ri.layerCount = 1;
        ri.colorAttachmentCount = count;
        ri.pColorAttachments = colors;
        ri.pDepthAttachment = depth;
        vkCmdBeginRendering(cmd, &ri);
    };
    auto draw = [&](const RasterDraw& d, std::uint32_t passId) {
        push.drawIndex = d.gpu;
        push.pass = passId;
        vkCmdPushConstants(cmd, m_layout, VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0, sizeof(push),
                           &push);
        vkCmdDraw(cmd, d.vertexCount, 1, d.firstVertex, d.gpu);
    };
    const std::uint32_t w = m_frame.width, h = m_frame.height;
    if (pass == m_pass[kPassShadow]) {
        const VkRenderingAttachmentInfo da = depthAttachment(m_shadow, VK_ATTACHMENT_LOAD_OP_CLEAR, true);
        begin(nullptr, 0, &da, m_shadow.width, m_shadow.height);
        beginPass(cmd, m_shadowPipe);
        const VkViewport vp{0.f, 0.f, static_cast<float>(m_shadow.width), static_cast<float>(m_shadow.height), 0.f, 1.f};
        vkCmdSetViewport(cmd, 0, 1, &vp);
        const VkRect2D sc{{0, 0}, {m_shadow.width, m_shadow.height}};
        vkCmdSetScissor(cmd, 0, 1, &sc);
        vkCmdSetCullMode(cmd, VK_CULL_MODE_NONE);
        vkCmdSetFrontFace(cmd, VK_FRONT_FACE_CLOCKWISE);
        vkCmdSetDepthTestEnable(cmd, VK_TRUE);
        vkCmdSetDepthWriteEnable(cmd, VK_TRUE);
        vkCmdSetDepthCompareOp(cmd, VK_COMPARE_OP_LESS_OR_EQUAL);
        for (const RasterDraw& d : m_frame.draws) {
            if (d.bucket == Bucket::Opaque && d.castShadow) {
                draw(d, kPassShadow);
            }
        }
        vkCmdEndRendering(cmd);
    } else if (pass == m_pass[kPassGBuffer]) {
        VkRenderingAttachmentInfo colors[kGBufferTargets];
        for (std::uint32_t i = 0; i < kGBufferTargets; ++i) {
            colors[i] = colorAttachment(m_targets[i], VK_ATTACHMENT_LOAD_OP_CLEAR);
        }
        const VkRenderingAttachmentInfo da = depthAttachment(m_depth, VK_ATTACHMENT_LOAD_OP_CLEAR, true);
        begin(colors, kGBufferTargets, &da, w, h);
        beginPass(cmd, m_gbuffer);
        for (const RasterDraw& d : m_frame.draws) {
            if (d.bucket == Bucket::Opaque) {
                setDrawState(cmd, d);
                draw(d, kPassGBuffer);
            }
        }
        vkCmdEndRendering(cmd);
    } else if (pass == m_pass[kPassDecal]) {
        const VkRenderingAttachmentInfo color = colorAttachment(m_targets[0], VK_ATTACHMENT_LOAD_OP_LOAD);
        const VkRenderingAttachmentInfo da = depthAttachment(m_depth, VK_ATTACHMENT_LOAD_OP_LOAD, false);
        begin(&color, 1, &da, w, h);
        beginPass(cmd, m_decal);
        for (const RasterDraw& d : m_frame.draws) {
            if (d.bucket == Bucket::Decal) {
                setDrawState(cmd, d);
                vkCmdSetDepthWriteEnable(cmd, VK_FALSE);
                draw(d, kPassDecal);
            }
        }
        vkCmdEndRendering(cmd);
    } else if (pass == m_pass[kPassLight]) {
        VkRenderingAttachmentInfo color{};
        color.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO;
        color.imageView = m_outputView;
        color.imageLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
        color.loadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE; // the full-screen triangle writes every pixel
        color.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
        begin(&color, 1, nullptr, w, h);
        beginPass(cmd, m_light);
        const VkViewport vp{0.f, 0.f, static_cast<float>(w), static_cast<float>(h), 0.f, 1.f};
        vkCmdSetViewport(cmd, 0, 1, &vp);
        const VkRect2D sc{{0, 0}, {w, h}};
        vkCmdSetScissor(cmd, 0, 1, &sc);
        vkCmdSetCullMode(cmd, VK_CULL_MODE_NONE);
        vkCmdSetFrontFace(cmd, VK_FRONT_FACE_CLOCKWISE);
        vkCmdSetDepthTestEnable(cmd, VK_FALSE);
        vkCmdSetDepthWriteEnable(cmd, VK_FALSE);
        vkCmdSetDepthCompareOp(cmd, VK_COMPARE_OP_ALWAYS);
        push.pass = kPassLight;
        vkCmdPushConstants(cmd, m_layout, VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT, 0, sizeof(push),
                           &push);
        vkCmdDraw(cmd, 3, 1, 0, 0);
        vkCmdEndRendering(cmd);
    } else if (pass == m_pass[kPassForward]) {
        VkRenderingAttachmentInfo color{};
        color.sType = VK_STRUCTURE_TYPE_RENDERING_ATTACHMENT_INFO;
        color.imageView = m_outputView;
        color.imageLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
        color.loadOp = VK_ATTACHMENT_LOAD_OP_LOAD;
        color.storeOp = VK_ATTACHMENT_STORE_OP_STORE;
        const VkRenderingAttachmentInfo da = depthAttachment(m_depth, VK_ATTACHMENT_LOAD_OP_LOAD, true);
        begin(&color, 1, &da, w, h);
        VkPipeline bound = VK_NULL_HANDLE;
        // Submission order (D3D's): blended draws are never sorted.
        for (const RasterDraw& d : m_frame.draws) {
            if (d.bucket != Bucket::Blend) {
                continue;
            }
            const VkPipeline p = forwardPipeline(d.blend);
            if (p == VK_NULL_HANDLE) {
                continue;
            }
            if (p != bound) {
                beginPass(cmd, p);
                bound = p;
            }
            setDrawState(cmd, d);
            draw(d, kPassForward);
        }
        vkCmdEndRendering(cmd);
    }
}

std::string RasterRenderer::headerJson() const {
    char buf[512];
    std::snprintf(buf, sizeof(buf),
                  "\"device_tier\":%u,\"option_tier\":%d,\"tier\":%u,\"requested\":\"%s\",\"enabled\":\"%s\","
                  "\"degraded\":\"%s\"",
                  m_plan.deviceTier, m_plan.optionTier, m_plan.tier, featureList(m_plan.requested).c_str(),
                  featureList(m_plan.enabled).c_str(), m_plan.degraded.c_str());
    return buf;
}

std::string RasterRenderer::recordJson() const {
    if (!m_prepared && m_error.empty()) {
        return "\"rendered\":false";
    }
    const RasterStats& s = m_frame.stats;
    std::string order;
    std::map<std::string, std::uint32_t> skips;
    for (const RasterDraw& d : m_frame.draws) {
        if (d.bucket == Bucket::Blend) {
            order += order.empty() ? "" : ",";
            order += std::to_string(d.source);
        } else if (d.bucket == Bucket::Skipped) {
            ++skips[d.skipReason];
        }
    }
    std::string skipJson;
    for (const auto& [why, n] : skips) {
        skipJson += (skipJson.empty() ? "\"" : ",\"") + why + "\":" + std::to_string(n);
    }
    char buf[1536];
    std::snprintf(buf, sizeof(buf),
                  "\"rendered\":%s,\"error\":\"%s\",\"tier\":%u,\"features\":\"%s\",\"degraded\":\"%s\",\"draws\":%u,"
                  "\"opaque\":%u,\"decals\":%u,\"blended\":%u,\"skipped\":%u,\"unlit\":%u,\"textured\":%u,"
                  "\"replaced\":%u,\"triangles\":%u,\"lights\":%u,\"directional\":%u,\"clustered\":%u,"
                  "\"clusters_used\":%u,\"fallback_light\":%s,\"fog\":%u,\"shadow\":%s,\"game_textures\":%zu,"
                  "\"vertex_captured\":%u,\"capture_clip\":%u,\"pretransformed\":%u,\"emissive_vertex\":%u,"
                  "\"viewports\":%u",
                  m_prepared ? "true" : "false", m_error.c_str(), m_plan.tier,
                  featureList(m_frame.constants.counts[3]).c_str(), m_plan.degraded.c_str(), s.draws, s.opaque,
                  s.decals, s.blended, s.skipped, s.unlit, s.textured, s.replaced, s.triangles, s.lights, s.directional,
                  s.clustered, s.clustersUsed, s.fallbackLight ? "true" : "false", s.fogMode,
                  s.shadow ? "true" : "false", m_gameTextures.size(), s.vertexCaptured, s.captureClip, s.preTransformed,
                  s.emissiveVertex, s.viewports);
    return std::string(buf) + ",\"blend_order\":[" + order + "],\"skips\":{" + skipJson + "}";
}

} // namespace

std::unique_ptr<rf::IFrameRenderer> createRasterRenderer(const rf::FrameConfig& config) {
    return std::make_unique<RasterRenderer>(config);
}

} // namespace fuse::relight::render::raster
