add_executable(fuse_mechanics_tests
    test_register_interact.cpp
)

target_link_libraries(fuse_mechanics_tests PRIVATE fuse_mechanics fuse_core)
target_compile_features(fuse_mechanics_tests PRIVATE cxx_std_17)
add_test(NAME fuse_mechanics_tests COMMAND fuse_mechanics_tests)

add_executable(fuse_mechanics_inventory_provider_tests
    test_inventory_provider.cpp
)

target_link_libraries(fuse_mechanics_inventory_provider_tests PRIVATE fuse_mechanics fuse_core)
target_compile_features(fuse_mechanics_inventory_provider_tests PRIVATE cxx_std_17)
add_test(NAME fuse_mechanics_inventory_provider COMMAND fuse_mechanics_inventory_provider_tests)

add_executable(fuse_mechanics_action_stub_tests
    test_action_stubs.cpp
)

target_link_libraries(fuse_mechanics_action_stub_tests PRIVATE fuse_mechanics fuse_core)
target_compile_features(fuse_mechanics_action_stub_tests PRIVATE cxx_std_17)
add_test(NAME fuse_mechanics_action_stubs COMMAND fuse_mechanics_action_stub_tests)

add_executable(fuse_mechanics_health_tests test_health_component.cpp)
target_link_libraries(fuse_mechanics_health_tests PRIVATE fuse_mechanics fuse_core)
target_compile_features(fuse_mechanics_health_tests PRIVATE cxx_std_17)
add_test(NAME fuse_mechanics_health COMMAND fuse_mechanics_health_tests)

add_executable(fuse_mechanics_trigger_zone_tests test_trigger_zone.cpp)
target_link_libraries(fuse_mechanics_trigger_zone_tests PRIVATE fuse_mechanics fuse_core)
target_compile_features(fuse_mechanics_trigger_zone_tests PRIVATE cxx_std_17)
add_test(NAME fuse_mechanics_trigger_zone COMMAND fuse_mechanics_trigger_zone_tests)

add_executable(fuse_mechanics_toggle_tests test_toggle_component.cpp)
target_link_libraries(fuse_mechanics_toggle_tests PRIVATE fuse_mechanics fuse_core)
target_compile_features(fuse_mechanics_toggle_tests PRIVATE cxx_std_17)
add_test(NAME fuse_mechanics_toggle COMMAND fuse_mechanics_toggle_tests)

add_executable(fuse_mechanics_console_method_tests test_console_method_component.cpp)
target_link_libraries(fuse_mechanics_console_method_tests PRIVATE fuse_mechanics fuse_core)
target_compile_features(fuse_mechanics_console_method_tests PRIVATE cxx_std_17)
add_test(NAME fuse_mechanics_console_method COMMAND fuse_mechanics_console_method_tests)

add_executable(fuse_mechanics_polyhedron_trigger_tests test_polyhedron_trigger.cpp)
target_link_libraries(fuse_mechanics_polyhedron_trigger_tests PRIVATE fuse_mechanics fuse_core)
target_compile_features(fuse_mechanics_polyhedron_trigger_tests PRIVATE cxx_std_17)
add_test(NAME fuse_mechanics_polyhedron_trigger COMMAND fuse_mechanics_polyhedron_trigger_tests)
