// FUSE Relight RL-5.6: volumetrics and the particle composite on the GPU (see volumetrics_gpu.hpp).
#include <fuse/relight/render/volumetrics/volumetrics_gpu.hpp>

#include <fuse/relight/render/pathtrace/pt_gpu.hpp>
#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/device.hpp>

#include <algorithm>
#include <cstring>

#if defined(FUSE_VULKAN_BACKEND)
#include <vulkan/vulkan.h>

// Generated by render/volumetrics/embed_spirv.cmake: kRlVol{Slang,Glsl}Spv, FUSE_RL_VOL_{SLANG,GLSL}.
#include "rl_vol_spv.h"
#endif

namespace fuse::relight::render::volumetrics {

namespace rr = fuse::renderer;
namespace rg = fuse::renderer::rg;

namespace {
constexpr u32 kGroup = 64u;
constexpr u64 kBlockBytes = 512u;
constexpr u64 kParamsOffset = 128u;
constexpr u64 kIntsOffset = 304u;
constexpr u64 kSystemsOffset = 352u;
static_assert(kParamsOffset + kVolParamWordCount * 16u == kIntsOffset, "block layout (rl_vol.comp)");
static_assert(kIntsOffset + kVolIntWordCount * 16u == kSystemsOffset, "block layout (rl_vol.comp)");
static_assert(kSystemsOffset + kVolSystemCount * 16u <= kBlockBytes, "block layout (rl_vol.comp)");

u64 align256(u64 v) { return (v + 255u) & ~u64{255u}; }

u32 storageUsage() {
    return static_cast<u32>(rr::BufferUsage::Storage) | static_cast<u32>(rr::BufferUsage::ShaderDeviceAddress) |
           static_cast<u32>(rr::BufferUsage::TransferSrc);
}

constexpr const char* kSectionNames[kVolSections] = {"relight.vol.current",     "relight.vol.history0",
                                                     "relight.vol.history1",    "relight.vol.reservoirs0",
                                                     "relight.vol.reservoirs1", "relight.vol.integrated",
                                                     "relight.vol.output"};
} // namespace

VolExternal volExternalFromPathTracer(const pathtrace::PathTracerGpu& pt, const pathtrace::PtGraphRefs& refs) {
    VolExternal e;
    const pathtrace::PtTraceBindings b = pt.traceBindings();
    const u64 pixels = u64(b.width) * b.height;
    e.color = refs.outputs;
    e.colorRange = rg::BufferRange{u64(pathtrace::kPtOutRadiance) * pt.outputStride(), pixels * 16u};
    e.colorAddress = pt.outputAddress(pathtrace::kPtOutRadiance);
    e.depth = refs.outputs;
    e.depthRange = rg::BufferRange{u64(pathtrace::kPtOutDepth) * pt.outputStride(), pixels * 4u};
    e.depthAddress = pt.outputAddress(pathtrace::kPtOutDepth);
    e.lights = refs.lights;
    e.tlas = refs.rt.tlas;
    e.tlasAddress = b.tlas;
    return e;
}

VolumetricsGpu::VolumetricsGpu() = default;
VolumetricsGpu::~VolumetricsGpu() { destroy(); }

bool VolumetricsGpu::init(const VolumetricsGpuDesc& desc) {
    destroy();
    m_desc = desc;
#if defined(FUSE_VULKAN_BACKEND)
    if (desc.device == nullptr || desc.allocator == nullptr || desc.bindless == nullptr || desc.framesInFlight == 0u ||
        desc.framesInFlight > kMaxSlots) {
        m_reason = "incomplete VolumetricsGpuDesc";
        return false;
    }
    m_retired.reserve(32);
    m_initialized = true;
    if (!createPipeline()) {
        m_reason = "no volumetrics kernel of the requested language / pipeline creation failed";
        destroy();
        return false;
    }
    m_reason = "ok";
    return true;
#else
    m_reason = "stub backend";
    return false;
#endif
}

void VolumetricsGpu::destroy() {
    if (!m_initialized) {
        return;
    }
#if defined(FUSE_VULKAN_BACKEND)
    collectRetired(~0ull);
    for (rr::Buffer& b : m_sections) {
        if (b.handle != nullptr) {
            m_desc.allocator->destroyBuffer(b);
        }
        b = rr::Buffer{};
    }
    if (m_ring.handle != nullptr) {
        m_desc.allocator->destroyBuffer(m_ring);
    }
    m_ring = rr::Buffer{};
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    if (m_pipeline != nullptr) {
        vkDestroyPipeline(device, static_cast<VkPipeline>(m_pipeline), nullptr);
    }
    if (m_layoutHandle != nullptr) {
        vkDestroyPipelineLayout(device, static_cast<VkPipelineLayout>(m_layoutHandle), nullptr);
    }
#endif
    m_pipeline = nullptr;
    m_layoutHandle = nullptr;
    m_retired.clear();
    for (u64& b : m_sectionBytes) {
        b = 0;
    }
    m_slotStride = 0;
    m_historyValid = false;
    m_frameReady = false;
    m_language = "none";
    m_stats = VolumetricsGpuStats{};
    m_initialized = false;
}

bool VolumetricsGpu::createPipeline() {
#if defined(FUSE_VULKAN_BACKEND)
    const u32* words = nullptr;
    usize bytes = 0;
#if defined(FUSE_RL_VOL_SLANG)
    if (m_desc.language == VolKernelLanguage::Auto || m_desc.language == VolKernelLanguage::Slang) {
        words = kRlVolSlangSpv;
        bytes = sizeof(kRlVolSlangSpv);
        m_language = "slang";
    }
#endif
#if defined(FUSE_RL_VOL_GLSL)
    if (words == nullptr && (m_desc.language == VolKernelLanguage::Auto || m_desc.language == VolKernelLanguage::Glsl)) {
        words = kRlVolGlslSpv;
        bytes = sizeof(kRlVolGlslSpv);
        m_language = "glsl";
    }
#endif
    if (words == nullptr) {
        return false;
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    VkDescriptorSetLayout setLayout = static_cast<VkDescriptorSetLayout>(m_desc.bindless->layoutHandle());
    VkPushConstantRange range{VK_SHADER_STAGE_COMPUTE_BIT, 0, static_cast<u32>(sizeof(Push))};
    VkPipelineLayoutCreateInfo layoutInfo{};
    layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutInfo.setLayoutCount = 1u;
    layoutInfo.pSetLayouts = &setLayout;
    layoutInfo.pushConstantRangeCount = 1;
    layoutInfo.pPushConstantRanges = &range;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    if (vkCreatePipelineLayout(device, &layoutInfo, nullptr, &layout) != VK_SUCCESS) {
        return false;
    }
    m_layoutHandle = layout;
    VkShaderModuleCreateInfo moduleInfo{};
    moduleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
    moduleInfo.codeSize = bytes;
    moduleInfo.pCode = words;
    VkShaderModule module = VK_NULL_HANDLE;
    if (vkCreateShaderModule(device, &moduleInfo, nullptr, &module) != VK_SUCCESS) {
        return false;
    }
    VkComputePipelineCreateInfo info{};
    info.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    info.flags = static_cast<VkPipelineCreateFlags>(m_desc.bindless->pipelineCreateFlags());
    info.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    info.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    info.stage.module = module;
    info.stage.pName = "main";
    info.layout = layout;
    VkPipeline pipeline = VK_NULL_HANDLE;
    const VkResult result = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
    vkDestroyShaderModule(device, module, nullptr);
    m_pipeline = pipeline;
    return result == VK_SUCCESS;
#else
    return false;
#endif
}

bool VolumetricsGpu::ensureBuffer(rr::Buffer& buffer, u64 bytes, u32 memory, const char* name, u8* queue) {
    if (buffer.handle != nullptr && bytes <= buffer.desc.size) {
        return true;
    }
    rr::BufferDesc d{};
    d.size = static_cast<usize>(bytes);
    d.usage = static_cast<rr::BufferUsage>(storageUsage());
    d.memoryUsage = static_cast<rr::MemoryUsage>(memory);
    d.name = name;
    rr::Buffer fresh{};
    if (!m_desc.allocator->createBuffer(d, fresh) || fresh.mapped == nullptr || fresh.deviceAddress == 0u) {
        if (fresh.handle != nullptr) {
            m_desc.allocator->destroyBuffer(fresh);
        }
        return false;
    }
    if (buffer.handle != nullptr) {
        m_retired.push_back(Retired{buffer, m_frameSerial});
        ++m_stats.reallocations;
    }
    buffer = fresh;
    if (queue != nullptr) {
        *queue = rg::kNoQueue;
    }
    return true;
}

bool VolumetricsGpu::beginFrame(u64 frameSerial, const VolFrameDesc& desc, u32 lightCount,
                                std::span<const particles::GpuParticleVertex> vertices) {
    m_frameReady = false;
    if (!m_initialized || desc.width == 0u || desc.height == 0u || desc.gridX == 0u || desc.gridY == 0u ||
        desc.gridZ == 0u) {
        return false;
    }
    m_frameSerial = frameSerial;
    m_stats.passes = 0;
    const bool resized = desc.gridX != m_frame.gridX || desc.gridY != m_frame.gridY || desc.gridZ != m_frame.gridZ ||
                         desc.width != m_frame.width || desc.height != m_frame.height;
    m_frame = desc;
    m_lightCount = lightCount;
    m_froxels = desc.gridX * desc.gridY * desc.gridZ;
    m_columns = desc.gridX * desc.gridY;
    m_pixels = desc.width * desc.height;
    u64 want[kVolSections];
    want[kVolSecCurrent] = u64(m_froxels) * 16u;
    want[kVolSecHistory0] = want[kVolSecCurrent];
    want[kVolSecHistory1] = want[kVolSecCurrent];
    want[kVolSecReservoir0] = u64(m_froxels) * 32u;
    want[kVolSecReservoir1] = want[kVolSecReservoir0];
    want[kVolSecIntegrated] = want[kVolSecCurrent];
    want[kVolSecOutput] = u64(m_pixels) * 16u;
    bool reallocated = false;
    for (u32 s = 0; s < kVolSections; ++s) {
        const bool had = m_sections[s].handle != nullptr;
        const u64 before = had ? m_sections[s].desc.size : 0u;
        if (!ensureBuffer(m_sections[s], align256(want[s]), static_cast<u32>(rr::MemoryUsage::GpuToCpu),
                          kSectionNames[s], &m_sectionQueues[s])) {
            m_reason = "volumetrics section buffer";
            return false;
        }
        reallocated = reallocated || !had || m_sections[s].desc.size != before;
        m_sectionBytes[s] = want[s];
    }
    if (resized || reallocated) {
        m_historyValid = false;
    }
    // Ring slot: block + particle vertices.
    const u64 vertexBytes = align256(std::max<u64>(vertices.size_bytes(), 16u));
    const u64 slotBytes = kBlockBytes + vertexBytes;
    if (m_ring.handle == nullptr || slotBytes > m_slotStride) {
        const u64 stride = align256(std::max<u64>(slotBytes + slotBytes / 2u, 4096u));
        if (m_ring.handle != nullptr) {
            m_retired.push_back(Retired{m_ring, frameSerial});
            m_ring = rr::Buffer{};
            ++m_stats.reallocations;
        }
        if (!ensureBuffer(m_ring, stride * m_desc.framesInFlight, static_cast<u32>(rr::MemoryUsage::CpuToGpu),
                          "relight.vol.ring", &m_ringQueue)) {
            m_reason = "volumetrics ring";
            return false;
        }
        m_slotStride = stride;
    }
    m_slotOffset = u64(frameSerial % m_desc.framesInFlight) * m_slotStride;
    m_slotBytes = slotBytes;
    m_verticesOffset = m_slotOffset + kBlockBytes;
    if (!vertices.empty()) {
        std::memcpy(static_cast<u8*>(m_ring.mapped) + m_verticesOffset, vertices.data(), vertices.size_bytes());
    }
    m_cur ^= 1u;
    m_flags = desc.flags | (m_historyValid ? u32(kVolHistory) : 0u);
    if (m_flags & kVolParticles) {
        // Quads past the uploaded vertices are clamped by the system table (never read out of bounds).
        const u32 quads = static_cast<u32>(vertices.size() / 4u);
        for (u32 s = 0; s < std::min(m_frame.systemCount, kVolSystemCount); ++s) {
            VolParticleSystem& sys = m_frame.systems[s];
            sys.firstQuad = std::min(sys.firstQuad, quads);
            sys.quadCount = std::min(sys.quadCount, quads - sys.firstQuad);
        }
    }
    m_frameReady = true;
    ++m_stats.frames;
    return true;
}

u32 VolumetricsGpu::historySection(bool current) const {
    return (m_cur == 0u) == current ? kVolSecHistory0 : kVolSecHistory1;
}
u32 VolumetricsGpu::reservoirSection(bool current) const {
    return (m_cur == 0u) == current ? kVolSecReservoir0 : kVolSecReservoir1;
}
u64 VolumetricsGpu::outputAddress() const { return m_sections[kVolSecOutput].deviceAddress; }

bool VolumetricsGpu::addPasses(rg::Graph& graph, const VolExternal& ext) {
    if (!m_initialized || !m_frameReady || ext.colorAddress == 0u || !ext.color.valid()) {
        m_reason = "frame not begun / no colour input";
        return false;
    }
    const u32 hCur = historySection(true);
    const u32 hPrev = historySection(false);
    const u32 rCur = reservoirSection(true);
    const u32 rPrev = reservoirSection(false);
    const bool lightsOn = ext.lights.lightCount > 0u && ext.lights.tableAddress != 0u;
    const bool shadows = (m_flags & kVolShadows) != 0u && ext.tlasAddress != 0u && ext.tlas.valid();

    // Block.
    u8* slot = static_cast<u8*>(m_ring.mapped) + m_slotOffset;
    const u64 addr[16] = {m_sections[kVolSecCurrent].deviceAddress,
                          m_sections[hPrev].deviceAddress,
                          m_sections[hCur].deviceAddress,
                          m_sections[rPrev].deviceAddress,
                          m_sections[rCur].deviceAddress,
                          m_sections[kVolSecIntegrated].deviceAddress,
                          ext.colorAddress,
                          m_sections[kVolSecOutput].deviceAddress,
                          ext.depthAddress,
                          m_ring.deviceAddress + m_verticesOffset,
                          0u, 0u, 0u, 0u, 0u, 0u};
    std::memcpy(slot, addr, sizeof(addr));
    VolFrameDesc d = m_frame;
    d.flags = m_flags;
    if (!shadows) {
        d.flags &= ~u32(kVolShadows);
    }
    Word params[kVolParamWordCount];
    VolUint4 ints[kVolIntWordCount];
    packVolParams(d, lightsOn ? m_lightCount : 0u, params, ints);
    std::memcpy(slot + kParamsOffset, params, sizeof(params));
    std::memcpy(slot + kIntsOffset, ints, sizeof(ints));
    VolUint4 systems[kVolSystemCount];
    for (u32 s = 0; s < kVolSystemCount; ++s) {
        systems[s] = VolUint4{d.systems[s].firstQuad, d.systems[s].quadCount, d.systems[s].blend, d.systems[s].flags};
    }
    std::memcpy(slot + kSystemsOffset, systems, sizeof(systems));

    m_refs = VolGraphRefs{};
    for (u32 s = 0; s < kVolSections; ++s) {
        m_refs.sections[s] = graph.importBuffer(rg::ImportedBuffer{
            m_sections[s].handle, m_sections[s].desc.size, m_sectionQueues[s], &m_sectionQueues[s], kSectionNames[s]});
    }
    m_refs.ring =
        graph.importBuffer(rg::ImportedBuffer{m_ring.handle, m_ring.desc.size, m_ringQueue, &m_ringQueue, "relight.vol.ring"});
    m_refs.ringRange = rg::BufferRange{m_slotOffset, m_slotBytes};
    m_refs.valid = true;

    Push base{};
    base.block = m_ring.deviceAddress + m_slotOffset;
    base.tlas = shadows ? ext.tlasAddress : 0u;
    base.lightTable = lightsOn ? ext.lights.tableAddress : 0u;
    base.lightTree = lightsOn ? ext.lights.tree.header : 0u;
    auto range = [&](u32 s) { return rg::BufferRange{0u, m_sectionBytes[s]}; };
    u32 count = 0;
    auto add = [&](const char* name, u32 stage, u32 items) -> rg::PassBuilder {
        PassRecord& r = m_records[count++];
        r = PassRecord{};
        r.self = this;
        r.push = base;
        r.push.stage = stage;
        r.push.count = items;
        r.groups = (items + kGroup - 1u) / kGroup;
        ++m_stats.passes;
        rg::PassBuilder pass = graph.addPass(name, &VolumetricsGpu::record, &r);
        pass.use(m_refs.ring, rg::Access::StorageRead, m_refs.ringRange, rg::kStageCompute);
        return pass;
    };
    auto read = [&](rg::PassBuilder& p, u32 s) {
        p.use(m_refs.sections[s], rg::Access::StorageRead, range(s), rg::kStageCompute);
    };
    auto write = [&](rg::PassBuilder& p, u32 s) {
        p.use(m_refs.sections[s], rg::Access::StorageWrite, range(s), rg::kStageCompute);
    };
    {
        rg::PassBuilder p = add("relight.vol.inject", kVolInject, m_froxels);
        if (lightsOn) {
            p.use(ext.lights.ring, rg::Access::StorageRead, ext.lights.tableRange, rg::kStageCompute);
            if (ext.lights.tree.tree.valid()) {
                p.use(ext.lights.tree.tree, rg::Access::StorageRead, ext.lights.tree.range, rg::kStageCompute);
            }
        }
        if (shadows) {
            p.use(ext.tlas, rg::Access::AccelerationStructureRead, {}, rg::kStageCompute);
        }
        read(p, rPrev);
        write(p, kVolSecCurrent);
        write(p, rCur);
    }
    {
        rg::PassBuilder p = add("relight.vol.temporal", kVolTemporal, m_froxels);
        read(p, kVolSecCurrent);
        read(p, hPrev);
        write(p, hCur);
    }
    {
        rg::PassBuilder p = add("relight.vol.integrate", kVolIntegrate, m_columns);
        read(p, hCur);
        write(p, kVolSecIntegrated);
    }
    {
        rg::PassBuilder p = add("relight.vol.apply", kVolApply, m_pixels);
        read(p, kVolSecIntegrated);
        p.use(ext.color, rg::Access::StorageRead, ext.colorRange, rg::kStageCompute);
        if (ext.depthAddress != 0u && ext.depth.valid()) {
            p.use(ext.depth, rg::Access::StorageRead, ext.depthRange, rg::kStageCompute);
        }
        write(p, kVolSecOutput);
    }
    m_historyValid = true;
    return true;
}

void VolumetricsGpu::record(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const VolumetricsGpu& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, static_cast<VkPipeline>(self.m_pipeline));
    self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, self.m_layoutHandle, 0);
    vkCmdPushConstants(cmd, static_cast<VkPipelineLayout>(self.m_layoutHandle), VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       static_cast<u32>(sizeof(Push)), &r.push);
    vkCmdDispatch(cmd, r.groups, 1u, 1u);
#else
    (void)context;
    (void)user;
#endif
}

u32 VolumetricsGpu::collectRetired(u64 completedSerial) {
    u32 collected = 0;
    usize keep = 0;
    for (usize i = 0; i < m_retired.size(); ++i) {
        if (m_retired[i].serial > completedSerial) {
            m_retired[keep++] = m_retired[i];
            continue;
        }
        if (m_retired[i].buffer.handle != nullptr) {
            m_desc.allocator->destroyBuffer(m_retired[i].buffer);
        }
        ++collected;
    }
    m_retired.resize(keep);
    return collected;
}

const void* VolumetricsGpu::mappedSection(u32 section) const {
    return section < kVolSections ? m_sections[section].mapped : nullptr;
}

} // namespace fuse::relight::render::volumetrics
