// FUSE Relight RL-4.4: the Relight light set on the GPU (see light_set_gpu.hpp).
#include <fuse/relight/render/lights/light_set_gpu.hpp>

#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/device.hpp>

#include <algorithm>
#include <cstring>

#if defined(FUSE_VULKAN_BACKEND)
#include <vulkan/vulkan.h>

// Generated by render/lights/embed_spirv.cmake: kRlLight{Convert,Sample}{Slang,Glsl}Spv and
// FUSE_RL_LIGHTS_{SLANG,GLSL} when the kernels of a language exist.
#include "rl_lights_spv.h"
#endif

namespace fuse::relight::render::lights {

namespace rr = fuse::renderer;
namespace rg = fuse::renderer::rg;
namespace lt = fuse::renderer::light_tree;

namespace {
constexpr u32 kPushBytes = 48u;
constexpr u32 kGroup = 64u;
constexpr u64 kWordBytes = sizeof(lk::float4);

u64 align256(u64 v) { return (v + 255u) & ~u64{255u}; }

rr::BufferUsage ringUsage() {
    return static_cast<rr::BufferUsage>(static_cast<u32>(rr::BufferUsage::Storage) |
                                        static_cast<u32>(rr::BufferUsage::ShaderDeviceAddress) |
                                        static_cast<u32>(rr::BufferUsage::TransferSrc));
}
} // namespace

static_assert(sizeof(lk::float4) == 16u, "packed words");

RelightLightsSlotLayout RelightLightsSlotLayout::compute(u32 gameLights, u32 lights) {
    RelightLightsSlotLayout l{};
    u64 cursor = 0;
    auto take = [&](u64 bytes) {
        const u64 at = cursor;
        cursor = align256(cursor + std::max<u64>(bytes, 16u));
        return at;
    };
    l.d3d = take(u64(gameLights) * lk::kRlD3dWords * kWordBytes);
    l.table = take(u64(lights) * lk::kRlLightWords * kWordBytes);
    l.bytes = cursor;
    return l;
}

RelightLightsGpu::~RelightLightsGpu() { destroy(); }

bool RelightLightsGpu::init(const RelightLightsGpuDesc& desc) {
    destroy();
    m_desc = desc;
#if defined(FUSE_VULKAN_BACKEND)
    if (desc.allocator == nullptr || desc.framesInFlight == 0u || desc.framesInFlight > kMaxSlots) {
        return false;
    }
    if (!lt::queryLightTreeCapabilities(desc.device).gpu) {
        return false;
    }
    lt::LightTreeGpuDesc td{};
    td.device = desc.device;
    td.allocator = desc.allocator;
    td.bindless = desc.bindless;
    td.language = desc.language == LightKernelLanguage::Glsl    ? lt::LightTreeKernelLanguage::Glsl
                  : desc.language == LightKernelLanguage::Slang ? lt::LightTreeKernelLanguage::Slang
                                                                : lt::LightTreeKernelLanguage::Auto;
    td.framesInFlight = desc.framesInFlight;
    td.initialLights = std::max(desc.initialLights, 1u);
    m_retired.reserve(8);
    m_initialized = true; // destroy() releases partial state from here on
    const u32 lights = std::max(desc.initialLights, 1u);
    if (!m_tree.init(td) || !createPipelines() ||
        !ensureCapacity(RelightLightsSlotLayout::compute(lights, lights).bytes)) {
        destroy();
        return false;
    }
    return true;
#else
    return false;
#endif
}

void RelightLightsGpu::destroy() {
    if (!m_initialized) {
        return;
    }
#if defined(FUSE_VULKAN_BACKEND)
    collectRetired(~0ull);
    m_tree.destroy();
    if (m_ring.handle != nullptr) {
        m_desc.allocator->destroyBuffer(m_ring);
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    for (void* p : {m_convertPipeline, m_samplePipeline}) {
        if (p != nullptr) {
            vkDestroyPipeline(device, static_cast<VkPipeline>(p), nullptr);
        }
    }
    if (m_layoutHandle != nullptr) {
        vkDestroyPipelineLayout(device, static_cast<VkPipelineLayout>(m_layoutHandle), nullptr);
    }
#endif
    m_convertPipeline = nullptr;
    m_samplePipeline = nullptr;
    m_layoutHandle = nullptr;
    m_ring = rr::Buffer{};
    m_ringQueue = rg::kNoQueue;
    m_slotStride = 0;
    m_slot = 0;
    m_layout = RelightLightsSlotLayout{};
    m_tableAddress = 0;
    m_lightCount = 0;
    m_gameCount = 0;
    m_retired.clear();
    m_recordCount = 0;
    m_language = "none";
    m_stats = RelightLightsGpuStats{};
    m_initialized = false;
}

bool RelightLightsGpu::createPipelines() {
#if defined(FUSE_VULKAN_BACKEND)
    const u32* convertWords = nullptr;
    usize convertBytes = 0;
    const u32* sampleWords = nullptr;
    usize sampleBytes = 0;
#if defined(FUSE_RL_LIGHTS_SLANG)
    if (m_desc.language == LightKernelLanguage::Auto || m_desc.language == LightKernelLanguage::Slang) {
        convertWords = kRlLightConvertSlangSpv;
        convertBytes = sizeof(kRlLightConvertSlangSpv);
        sampleWords = kRlLightSampleSlangSpv;
        sampleBytes = sizeof(kRlLightSampleSlangSpv);
        m_language = "slang";
    }
#endif
#if defined(FUSE_RL_LIGHTS_GLSL)
    if (convertWords == nullptr &&
        (m_desc.language == LightKernelLanguage::Auto || m_desc.language == LightKernelLanguage::Glsl)) {
        convertWords = kRlLightConvertGlslSpv;
        convertBytes = sizeof(kRlLightConvertGlslSpv);
        sampleWords = kRlLightSampleGlslSpv;
        sampleBytes = sizeof(kRlLightSampleGlslSpv);
        m_language = "glsl";
    }
#endif
    if (convertWords == nullptr || sampleWords == nullptr) {
        return false;
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    VkDescriptorSetLayout setLayout = m_desc.bindless != nullptr
                                          ? static_cast<VkDescriptorSetLayout>(m_desc.bindless->layoutHandle())
                                          : VK_NULL_HANDLE;
    VkPushConstantRange range{VK_SHADER_STAGE_COMPUTE_BIT, 0, kPushBytes};
    VkPipelineLayoutCreateInfo layoutInfo{};
    layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutInfo.setLayoutCount = setLayout != VK_NULL_HANDLE ? 1u : 0u;
    layoutInfo.pSetLayouts = &setLayout;
    layoutInfo.pushConstantRangeCount = 1;
    layoutInfo.pPushConstantRanges = &range;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    if (vkCreatePipelineLayout(device, &layoutInfo, nullptr, &layout) != VK_SUCCESS) {
        return false;
    }
    m_layoutHandle = layout;
    auto make = [&](const u32* words, usize bytes, void*& out) {
        VkShaderModuleCreateInfo moduleInfo{};
        moduleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        moduleInfo.codeSize = bytes;
        moduleInfo.pCode = words;
        VkShaderModule module = VK_NULL_HANDLE;
        if (vkCreateShaderModule(device, &moduleInfo, nullptr, &module) != VK_SUCCESS) {
            return false;
        }
        VkComputePipelineCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
        info.flags = m_desc.bindless != nullptr
                         ? static_cast<VkPipelineCreateFlags>(m_desc.bindless->pipelineCreateFlags())
                         : 0u;
        info.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        info.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
        info.stage.module = module;
        info.stage.pName = "main";
        info.layout = layout;
        VkPipeline pipeline = VK_NULL_HANDLE;
        const VkResult result = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
        vkDestroyShaderModule(device, module, nullptr);
        out = pipeline;
        return result == VK_SUCCESS;
    };
    return make(convertWords, convertBytes, m_convertPipeline) && make(sampleWords, sampleBytes, m_samplePipeline);
#else
    return false;
#endif
}

bool RelightLightsGpu::ensureCapacity(u64 slotBytes) {
    if (m_ring.handle != nullptr && slotBytes <= m_slotStride) {
        return true;
    }
    const u64 stride = align256(std::max<u64>(slotBytes + slotBytes / 2u, 4096u));
    rr::BufferDesc d{};
    d.size = static_cast<usize>(stride * m_desc.framesInFlight);
    d.usage = ringUsage();
    d.memoryUsage = rr::MemoryUsage::CpuToGpu;
    d.name = "relight.lights.ring";
    rr::Buffer fresh{};
    if (!m_desc.allocator->createBuffer(d, fresh) || fresh.mapped == nullptr || fresh.deviceAddress == 0u) {
        if (fresh.handle != nullptr) {
            m_desc.allocator->destroyBuffer(fresh);
        }
        return false;
    }
    if (m_ring.handle != nullptr) {
        m_retired.push_back(Retired{m_ring, m_frameSerial});
        ++m_stats.reallocations;
    }
    m_ring = fresh;
    m_ringQueue = rg::kNoQueue;
    m_slotStride = stride;
    return true;
}

bool RelightLightsGpu::beginFrame(u64 frameSerial, const RelightLightSet& set) {
    if (!m_initialized) {
        return false;
    }
    m_frameSerial = frameSerial;
    m_recordCount = 0;
    m_stats.convertPasses = 0;
    m_stats.samplePasses = 0;
    m_lightCount = set.lightCount();
    m_gameCount = set.gameLightCount();
    m_params = set.convertParams();
    const RelightLightsSlotLayout layout = RelightLightsSlotLayout::compute(m_gameCount, m_lightCount);
    if (!ensureCapacity(layout.bytes) || !m_tree.beginFrame(frameSerial, set.tree())) {
        return false;
    }
    m_slot = static_cast<u32>(frameSerial % m_desc.framesInFlight);
    const u64 base = static_cast<u64>(m_slot) * m_slotStride;
    u8* slot = static_cast<u8*>(m_ring.mapped) + base;
    const u64 d3dBytes = u64(m_gameCount) * lk::kRlD3dWords * kWordBytes;
    if (d3dBytes != 0u) {
        std::memcpy(slot + layout.d3d, set.gameInputs().data(), static_cast<usize>(d3dBytes));
    }
    // Host part of the table: authored lights and emissive triangles (the game part is the convert pass's output).
    const u64 gameTableBytes = u64(m_gameCount) * lk::kRlLightWords * kWordBytes;
    const u64 tableBytes = u64(m_lightCount) * lk::kRlLightWords * kWordBytes;
    if (tableBytes > gameTableBytes) {
        std::memcpy(slot + layout.table + gameTableBytes,
                    reinterpret_cast<const u8*>(set.table().data()) + gameTableBytes,
                    static_cast<usize>(tableBytes - gameTableBytes));
    }
    m_stats.uploadBytes += d3dBytes + (tableBytes - gameTableBytes);
    ++m_stats.frames;
    m_layout = layout;
    m_tableAddress = m_ring.deviceAddress + base + layout.table;
    return true;
}

const void* RelightLightsGpu::mappedTable() const {
    if (m_ring.mapped == nullptr) {
        return nullptr;
    }
    return static_cast<const u8*>(m_ring.mapped) + static_cast<u64>(m_slot) * m_slotStride + m_layout.table;
}

RelightLightsGraphRefs RelightLightsGpu::importInto(rg::Graph& graph) {
    RelightLightsGraphRefs refs{};
    if (!m_initialized || m_ring.handle == nullptr) {
        return refs;
    }
    refs.ring = graph.importBuffer(
        rg::ImportedBuffer{m_ring.handle, m_ring.desc.size, m_ringQueue, &m_ringQueue, "relight.lights.ring"});
    const u64 base = static_cast<u64>(m_slot) * m_slotStride;
    refs.d3dRange = rg::BufferRange{base + m_layout.d3d, std::max<u64>(u64(m_gameCount) * lk::kRlD3dWords * kWordBytes, 16u)};
    refs.tableRange =
        rg::BufferRange{base + m_layout.table, std::max<u64>(u64(m_lightCount) * lk::kRlLightWords * kWordBytes, 16u)};
    refs.d3dAddress = m_ring.deviceAddress + base + m_layout.d3d;
    refs.tableAddress = m_tableAddress;
    refs.lightCount = m_lightCount;
    refs.gameLightCount = m_gameCount;
    refs.tree = m_tree.importInto(graph);
    return refs;
}

bool RelightLightsGpu::addConvertPass(rg::Graph& graph, const RelightLightsGraphRefs& refs) {
    if (!m_initialized || !refs.ring.valid()) {
        return false;
    }
    if (refs.gameLightCount == 0u) {
        return true;
    }
    if (m_recordCount >= kMaxPasses) {
        return false;
    }
    PassRecord& r = m_records[m_recordCount++];
    r = PassRecord{};
    r.self = this;
    r.convert = true;
    r.convertPush.source = refs.d3dAddress;
    r.convertPush.table = refs.tableAddress;
    r.convertPush.count = refs.gameLightCount;
    r.convertPush.leastSquares = m_params.leastSquares;
    r.convertPush.sphereRadius = m_params.sphereRadius;
    r.convertPush.intensityFactor = m_params.intensityFactor;
    r.convertPush.maxIntensity = m_params.maxIntensity;
    r.convertPush.distantIntensity = m_params.distantIntensity;
    r.convertPush.distantAngle = m_params.distantAngle;
    r.groups = (refs.gameLightCount + kGroup - 1u) / kGroup;
    ++m_stats.convertPasses;
    graph.addPass("relight.lights.convert", &RelightLightsGpu::recordDispatch, &r)
        .use(refs.ring, rg::Access::StorageRead, refs.d3dRange, rg::kStageCompute)
        .use(refs.ring, rg::Access::StorageWrite,
             rg::BufferRange{refs.tableRange.offset, u64(refs.gameLightCount) * lk::kRlLightWords * kWordBytes},
             rg::kStageCompute);
    return true;
}

bool RelightLightsGpu::addSamplePass(rg::Graph& graph, const RelightLightsGraphRefs& refs, rg::BufferRef queries,
                                     u64 queriesOffset, u64 queriesAddress, rg::BufferRef results, u64 resultsOffset,
                                     u64 resultsAddress, u32 count) {
    if (!m_initialized || !refs.ring.valid() || !refs.tree.tree.valid() || !queries.valid() || !results.valid() ||
        count == 0u || queriesAddress == 0u || resultsAddress == 0u || m_recordCount >= kMaxPasses) {
        return false;
    }
    PassRecord& r = m_records[m_recordCount++];
    r = PassRecord{};
    r.self = this;
    r.convert = false;
    r.samplePush.table = refs.tableAddress;
    r.samplePush.tree = refs.tree.header;
    r.samplePush.queries = queriesAddress;
    r.samplePush.results = resultsAddress;
    r.samplePush.count = count;
    r.samplePush.lightCount = refs.lightCount;
    r.groups = (count + kGroup - 1u) / kGroup;
    ++m_stats.samplePasses;
    graph.addPass("relight.lights.sample", &RelightLightsGpu::recordDispatch, &r)
        .use(refs.ring, rg::Access::StorageRead, refs.tableRange, rg::kStageCompute)
        .use(refs.tree.tree, rg::Access::StorageRead, refs.tree.range, rg::kStageCompute)
        .use(queries, rg::Access::StorageRead,
             rg::BufferRange{queriesOffset, u64(count) * lk::kRlQueryWords * kWordBytes}, rg::kStageCompute)
        .use(results, rg::Access::StorageWrite,
             rg::BufferRange{resultsOffset, u64(count) * lk::kRlResultWords * kWordBytes}, rg::kStageCompute);
    return true;
}

void RelightLightsGpu::recordDispatch(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const RelightLightsGpu& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE,
                      static_cast<VkPipeline>(r.convert ? self.m_convertPipeline : self.m_samplePipeline));
    if (self.m_desc.bindless != nullptr) {
        self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, self.m_layoutHandle, 0);
    }
    const void* push = r.convert ? static_cast<const void*>(&r.convertPush) : static_cast<const void*>(&r.samplePush);
    vkCmdPushConstants(cmd, static_cast<VkPipelineLayout>(self.m_layoutHandle), VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       kPushBytes, push);
    vkCmdDispatch(cmd, r.groups, 1u, 1u);
#else
    (void)context;
    (void)user;
#endif
}

u32 RelightLightsGpu::collectRetired(u64 completedSerial) {
    u32 collected = m_tree.collectRetired(completedSerial);
    usize keep = 0;
    for (usize i = 0; i < m_retired.size(); ++i) {
        if (m_retired[i].serial > completedSerial) {
            m_retired[keep++] = m_retired[i];
            continue;
        }
        if (m_retired[i].buffer.handle != nullptr) {
            m_desc.allocator->destroyBuffer(m_retired[i].buffer);
        }
        ++collected;
    }
    m_retired.resize(keep);
    return collected;
}

} // namespace fuse::relight::render::lights
