"""Command line: python -m fuse_assetgen <command> ...  (run from Tools/FUSE/AssetGen or with it on PYTHONPATH)

  list                                   registered generators (name, version, description)
  validate RECIPE...                     schema-check recipes (exit 1 on any problem)
  generate RECIPE... [--seed N] [--cache DIR] [--lock FILE] [--out DIR] [--no-cache]
                                         generate (cache hits reuse verified blobs), materialise into
                                         <cache>/assets/<id>/ (and --out), merge licence records into --lock
  verify RECIPE... [--cache DIR] [--sample F] [--sample-seed N]
                                         regenerate uncached and compare bytes with the cache (the
                                         asset_determinism drift check; --sample picks a fraction)
  hash RECIPE... [--seed N]              print the cache key and output sha256s without writing
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from . import __version__
from .cache import Cache
from .licence import merge_into_lock, repo_root
from .pipeline import cache_key, generate, run_generator
from .registry import load_builtin_generators
from .schema import RecipeError, load_and_validate
from .seed import derive_seed

DEFAULT_CACHE = repo_root() / "build" / "asset-cache"


def _cmd_list(args, reg) -> int:
    for name in reg.names():
        g = reg.get(name)
        print(f"{name}\tv{g.version}\t{g.description}")
    return 0


def _cmd_validate(args, reg) -> int:
    bad = 0
    for path in args.recipes:
        try:
            r = load_and_validate(path, reg)
            print(f"ok   {path}: {r['id']} ({r['generator']}, seed {r['seed']})")
        except RecipeError as exc:
            bad += 1
            for p in exc.problems:
                print(f"FAIL {p}", file=sys.stderr)
    return 1 if bad else 0


def _cmd_generate(args, reg) -> int:
    records = []
    for path in args.recipes:
        try:
            res = generate(path, args.cache, seed=args.seed, registry=reg, use_cache=not args.no_cache)
        except RecipeError as exc:
            for p in exc.problems:
                print(f"FAIL {p}", file=sys.stderr)
            return 1
        if args.out:
            Cache(args.cache).materialise(res.recipe["id"], res.outputs, dest_root=args.out)
        print(f"{'hit ' if res.cache_hit else 'gen '} {res.recipe['id']} key {res.key[:16]}")
        for name, digest in res.digests():
            print(f"      {name} {digest}")
        records.append(res.record)
    if args.lock:
        merge_into_lock(args.lock, records)
        print(f"licence records merged into {args.lock}")
    if args.records:
        Path(args.records).write_text(json.dumps({"schema": 1, "assets": records}, indent=2) + "\n", encoding="utf-8")
    return 0


def _cmd_verify(args, reg) -> int:
    recipes = list(args.recipes)
    if args.sample < 1.0:
        # Deterministic sample: keep a recipe when a hash of (sample seed, path) falls under the fraction.
        recipes = [p for p in recipes if derive_seed(args.sample_seed, Path(p).as_posix()) < args.sample * 2.0 ** 64]
    cache = Cache(args.cache)
    drift = 0
    for path in recipes:
        recipe = load_and_validate(path, reg)
        key, _ = cache_key(recipe, reg.get(recipe["generator"]))
        cached = cache.lookup(key)
        fresh = run_generator(recipe, reg)
        if cached is None:
            print(f"miss {recipe['id']}: not in cache (generate first)")
            continue
        if cached != fresh:
            drift += 1
            print(f"DRIFT {recipe['id']}: regenerated bytes differ from the cache", file=sys.stderr)
        else:
            print(f"ok   {recipe['id']}")
    return 1 if drift else 0


def _cmd_hash(args, reg) -> int:
    import hashlib
    for path in args.recipes:
        recipe = load_and_validate(path, reg, seed_override=args.seed)
        key, _ = cache_key(recipe, reg.get(recipe["generator"]))
        print(f"{recipe['id']} key {key}")
        for name, data in run_generator(recipe, reg):
            print(f"  {name} {hashlib.sha256(data).hexdigest()}")
    return 0


def main(argv=None) -> int:
    sys.dont_write_bytecode = True  # keep __pycache__ out of the source tree
    ap = argparse.ArgumentParser(prog="fuse_assetgen", description=f"FUSE AssetGen {__version__}")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("list")
    p = sub.add_parser("validate")
    p.add_argument("recipes", nargs="+")
    p = sub.add_parser("generate")
    p.add_argument("recipes", nargs="+")
    p.add_argument("--seed", type=int)
    p.add_argument("--cache", default=str(DEFAULT_CACHE))
    p.add_argument("--lock", help="licence lock to merge records into (e.g. Content/licences.lock.json)")
    p.add_argument("--records", help="write this run's licence records as a schema-1 lock fragment")
    p.add_argument("--out", help="also copy outputs to <out>/<id>/")
    p.add_argument("--no-cache", action="store_true")
    p = sub.add_parser("verify")
    p.add_argument("recipes", nargs="+")
    p.add_argument("--cache", default=str(DEFAULT_CACHE))
    p.add_argument("--sample", type=float, default=1.0)
    p.add_argument("--sample-seed", type=int, default=0)
    p = sub.add_parser("hash")
    p.add_argument("recipes", nargs="+")
    p.add_argument("--seed", type=int)
    args = ap.parse_args(argv)
    reg = load_builtin_generators()
    return {"list": _cmd_list, "validate": _cmd_validate, "generate": _cmd_generate,
            "verify": _cmd_verify, "hash": _cmd_hash}[args.cmd](args, reg)
