// Asset plan W0.7 layered materials on Vulkan: see include/fuse/renderer/material_layers/material_layers.hpp.
#include <fuse/renderer/material_layers/material_layers.hpp>

#include <fuse/renderer/material_layers/ml_mips.hpp>
#include <fuse/renderer/vk/allocator.hpp>
#include <fuse/renderer/vk/device.hpp>
#include <fuse/renderer/vk/upload_queue.hpp>

#include <algorithm>
#include <cstring>
#include <initializer_list>

#if defined(FUSE_VULKAN_BACKEND)
#include <vulkan/vulkan.h>

// Generated by cmake/rp_w07.cmake from shaders/material_layers/*: kMl<Kernel><Slang|Glsl>Spv and
// FUSE_MATERIAL_LAYERS_{SLANG,GLSL} when every kernel of a language exists.
#include "material_layers_spv.h"
#endif

namespace fuse::renderer::material_layers {

namespace {
constexpr u32 kPushBytes = sizeof(MlPush);
constexpr u32 kFrameStride = 256u; ///< ring slot size (>= sizeof(MlParams), 256-aligned)
static_assert(sizeof(MlParams) <= kFrameStride, "frame ring slot");

BufferUsage bufferUsage(std::initializer_list<BufferUsage> bits) {
    u32 u = 0;
    for (const BufferUsage b : bits) {
        u |= static_cast<u32>(b);
    }
    return static_cast<BufferUsage>(u);
}

u64 align256(u64 v) { return (v + 255u) & ~u64{255u}; }
u32 groups(u32 items, u32 size) { return items == 0u ? 1u : (items + size - 1u) / size; }

#if defined(FUSE_VULKAN_BACKEND)
struct Code {
    const u32* words = nullptr;
    usize bytes = 0;
};
template <usize N>
Code code(const u32 (&spv)[N]) {
    return Code{spv, sizeof(spv)};
}
#endif
} // namespace

MlLibraryLayout MlLibraryLayout::compute(u32 textureCount, u32 materialCount, u32 ballCount, u64 texelCount) {
    MlLibraryLayout l{};
    u64 cursor = 0;
    l.lut = cursor;
    cursor = align256(cursor + u64{kMlLutEntries} * 4u);
    l.textures = cursor;
    cursor = align256(cursor + std::max<u64>(u64{textureCount} * sizeof(MlTexture), 16u));
    l.materials = cursor;
    cursor = align256(cursor + std::max<u64>(u64{materialCount} * sizeof(MlMaterial), 16u));
    l.balls = cursor;
    cursor = align256(cursor + std::max<u64>(u64{ballCount} * sizeof(MlBall), 16u));
    l.texels = cursor;
    cursor = align256(cursor + std::max<u64>(texelCount * 4u, 16u));
    l.bytes = cursor;
    return l;
}

MlCapabilities queryMaterialLayerCapabilities(const VulkanDevice* device) {
    MlCapabilities c{};
#if defined(FUSE_VULKAN_BACKEND)
    if (device == nullptr || !device->isValid()) {
        return c;
    }
    const RendererCaps& caps = device->info().caps;
    if (!caps.bufferDeviceAddress || !caps.shaderInt64) {
        c.reason = "bufferDeviceAddress / shaderInt64 missing";
        return c;
    }
    c.layers = true;
    c.reason = "ok";
#else
    (void)device;
    c.reason = "stub backend";
#endif
    return c;
}

MaterialLayers::~MaterialLayers() { destroy(); }

bool MaterialLayers::init(const MaterialLayersDesc& desc) {
    destroy();
    m_desc = desc;
#if defined(FUSE_VULKAN_BACKEND)
    if (desc.allocator == nullptr || desc.bindless == nullptr || desc.framesInFlight == 0u) {
        return false;
    }
    if (!queryMaterialLayerCapabilities(desc.device).layers) {
        return false;
    }
    m_retired.reserve(8);
    m_initialized = true; // destroy() releases partial state from here on
    BufferDesc ring{};
    ring.size = static_cast<usize>(desc.framesInFlight) * kFrameStride;
    ring.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress});
    ring.memoryUsage = MemoryUsage::CpuToGpu;
    ring.name = "materials.params";
    if (!m_desc.allocator->createBuffer(ring, m_frameRing) || m_frameRing.mapped == nullptr ||
        m_frameRing.deviceAddress == 0u || !createPipelines()) {
        destroy();
        return false;
    }
    return true;
#else
    return false;
#endif
}

void MaterialLayers::destroy() {
    if (!m_initialized) {
        return;
    }
#if defined(FUSE_VULKAN_BACKEND)
    collectRetired(~0ull);
    for (BindlessSlotHandle& slot : m_resolveImageSlots) {
        if (slot.isValid()) {
            m_desc.bindless->unregisterSlot(slot);
        }
    }
    if (m_resolveTableSlot.isValid()) {
        m_desc.bindless->unregisterSlot(m_resolveTableSlot);
    }
    for (Texture& image : m_resolveImages) {
        if (image.image != nullptr) {
            m_desc.allocator->destroyImage(image);
        }
    }
    for (Buffer* b : {&m_library, &m_image, &m_frameRing, &m_resolveTable}) {
        if (b->handle != nullptr) {
            m_desc.allocator->destroyBuffer(*b);
        }
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    for (void*& pipeline : m_pipelines) {
        if (pipeline != nullptr) {
            vkDestroyPipeline(device, static_cast<VkPipeline>(pipeline), nullptr);
            pipeline = nullptr;
        }
    }
    if (m_layoutHandle != nullptr) {
        vkDestroyPipelineLayout(device, static_cast<VkPipelineLayout>(m_layoutHandle), nullptr);
    }
#endif
    m_layoutHandle = nullptr;
    m_resolveTable = Buffer{};
    m_resolveTableQueue = rg::kNoQueue;
    m_resolveTableSlot = BindlessSlotHandle{};
    m_resolveTableHandle = 0;
    m_resolveImages.clear();
    m_resolveImageSlots.clear();
    m_resolveImageHandles.clear();
    m_library = Buffer{};
    m_image = Buffer{};
    m_frameRing = Buffer{};
    m_libraryQueue = rg::kNoQueue;
    m_imageQueue = rg::kNoQueue;
    m_frameAddress = 0;
    m_retired.clear();
    m_layout = MlLibraryLayout{};
    m_params = MlParams{};
    m_textureCount = m_materialCount = m_ballCount = 0;
    m_recordCount = 0;
    m_language = "none";
    m_stats = MaterialLayerStats{};
    m_initialized = false;
}

bool MaterialLayers::createPipelines() {
#if defined(FUSE_VULKAN_BACKEND)
    Code k[kKernelCount]{};
    bool found = false;
#if defined(FUSE_MATERIAL_LAYERS_SLANG)
    if (m_desc.language == MlKernelLanguage::Auto || m_desc.language == MlKernelLanguage::Slang) {
        k[kEval] = code(kMlEvalSlangSpv);
        k[kBalls] = code(kMlBallsSlangSpv);
        m_language = "slang";
        found = true;
    }
#endif
#if defined(FUSE_MATERIAL_LAYERS_GLSL)
    if (!found && (m_desc.language == MlKernelLanguage::Auto || m_desc.language == MlKernelLanguage::Glsl)) {
        k[kEval] = code(kMlEvalGlslSpv);
        k[kBalls] = code(kMlBallsGlslSpv);
        m_language = "glsl";
        found = true;
    }
#endif
    if (!found) {
        return false;
    }
    const VkDevice device = static_cast<VkDevice>(m_desc.device->nativeHandle());
    VkDescriptorSetLayout setLayout = static_cast<VkDescriptorSetLayout>(m_desc.bindless->layoutHandle());
    VkPushConstantRange range{VK_SHADER_STAGE_COMPUTE_BIT, 0, kPushBytes};
    VkPipelineLayoutCreateInfo layoutInfo{};
    layoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
    layoutInfo.setLayoutCount = setLayout != VK_NULL_HANDLE ? 1u : 0u;
    layoutInfo.pSetLayouts = &setLayout;
    layoutInfo.pushConstantRangeCount = 1;
    layoutInfo.pPushConstantRanges = &range;
    VkPipelineLayout layout = VK_NULL_HANDLE;
    if (vkCreatePipelineLayout(device, &layoutInfo, nullptr, &layout) != VK_SUCCESS) {
        return false;
    }
    m_layoutHandle = layout;
    const VkPipelineCreateFlags createFlags = static_cast<VkPipelineCreateFlags>(m_desc.bindless->pipelineCreateFlags());
    for (u32 i = 0; i < kKernelCount; ++i) {
        VkShaderModuleCreateInfo moduleInfo{};
        moduleInfo.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
        moduleInfo.codeSize = k[i].bytes;
        moduleInfo.pCode = k[i].words;
        VkShaderModule module = VK_NULL_HANDLE;
        if (vkCreateShaderModule(device, &moduleInfo, nullptr, &module) != VK_SUCCESS) {
            return false;
        }
        VkComputePipelineCreateInfo info{};
        info.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
        info.flags = createFlags;
        info.stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
        info.stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
        info.stage.module = module;
        info.stage.pName = "main";
        info.layout = layout;
        VkPipeline pipeline = VK_NULL_HANDLE;
        const VkResult result = vkCreateComputePipelines(device, VK_NULL_HANDLE, 1, &info, nullptr, &pipeline);
        vkDestroyShaderModule(device, module, nullptr);
        m_pipelines[i] = pipeline;
        if (result != VK_SUCCESS) {
            return false;
        }
    }
    return true;
#else
    return false;
#endif
}

void MaterialLayers::retire(Buffer& buffer) {
    if (buffer.handle != nullptr) {
        Retired old{};
        old.buffer = buffer;
        old.serial = m_frameSerial;
        m_retired.push_back(old);
        ++m_stats.retired;
    }
    buffer = Buffer{};
}

bool MaterialLayers::createBuffer(u64 bytes, const char* name, bool hostVisible, Buffer& target, u8& queue) {
    BufferDesc d{};
    d.size = static_cast<usize>(bytes);
    d.usage = bufferUsage({BufferUsage::Storage, BufferUsage::ShaderDeviceAddress, BufferUsage::TransferSrc});
    d.memoryUsage = hostVisible ? MemoryUsage::CpuToGpu : MemoryUsage::GpuOnly;
    d.name = name;
    Buffer fresh{};
    if (!m_desc.allocator->createBuffer(d, fresh) || fresh.deviceAddress == 0u ||
        (hostVisible && fresh.mapped == nullptr)) {
        if (fresh.handle != nullptr) {
            m_desc.allocator->destroyBuffer(fresh);
        }
        return false;
    }
    retire(target);
    target = fresh;
    queue = rg::kNoQueue;
    return true;
}

u32 MaterialLayers::collectRetired(u64 completedSerial) {
    u32 collected = 0;
    usize keep = 0;
    for (usize i = 0; i < m_retired.size(); ++i) {
        if (m_retired[i].serial > completedSerial) {
            m_retired[keep++] = m_retired[i];
            continue;
        }
        if (m_retired[i].buffer.handle != nullptr) {
            m_desc.allocator->destroyBuffer(m_retired[i].buffer);
        }
        if (m_retired[i].image.image != nullptr) {
            m_desc.allocator->destroyImage(m_retired[i].image);
        }
        ++collected;
    }
    m_retired.resize(keep);
    m_stats.retired = m_stats.retired >= collected ? m_stats.retired - collected : 0u;
    return collected;
}

void MaterialLayers::retireResolveTable() {
    for (usize i = 0; i < m_resolveImages.size(); ++i) {
        if (m_resolveImageSlots[i].isValid()) {
            m_desc.bindless->retireSlot(m_resolveImageSlots[i], m_frameSerial);
        }
        if (m_resolveImages[i].image != nullptr) {
            Retired old{};
            old.image = m_resolveImages[i];
            old.serial = m_frameSerial;
            m_retired.push_back(old);
            ++m_stats.retired;
        }
    }
    m_resolveImages.clear();
    m_resolveImageSlots.clear();
    m_resolveImageHandles.clear();
    if (m_resolveTableSlot.isValid()) {
        m_desc.bindless->retireSlot(m_resolveTableSlot, m_frameSerial);
    }
    m_resolveTableSlot = BindlessSlotHandle{};
    m_resolveTableHandle = 0;
    retire(m_resolveTable);
    m_resolveTableQueue = rg::kNoQueue;
    m_stats.resolveImages = 0;
    m_stats.resolveImageBytes = 0;
}

bool MaterialLayers::buildResolveTable(const MlLibrary& library, UploadQueue& upload) {
    retireResolveTable();
    MlMipChains chains;
    ml_build_mips(library, chains);
    const u32 tc = static_cast<u32>(library.textures().size());
    const u32 mc = static_cast<u32>(library.materials().size());
    std::vector<MlTexture> rows = library.textures();
    m_resolveImages.resize(tc);
    m_resolveImageSlots.resize(tc);
    m_resolveImageHandles.assign(tc, 0u);
    for (u32 t = 0; t < tc; ++t) {
        const MlTexture& src = library.textures()[t];
        TextureDesc td{};
        td.width = src.width;
        td.height = src.height;
        td.mipLevels = chains.levelCount[t];
        td.format = (src.flags & kMlTexSrgb) != 0u ? GpuFormat::R8G8B8A8Srgb : GpuFormat::R8G8B8A8Unorm;
        td.usage = static_cast<ImageUsage>(static_cast<u32>(ImageUsage::Sampled) | static_cast<u32>(ImageUsage::TransferDst));
        td.name = "materials.resolve_texture";
        if (!m_desc.allocator->createImage(td, m_resolveImages[t])) {
            return false;
        }
        UploadImageDesc ud{};
        ud.width = src.width;
        ud.height = src.height;
        ud.mipLevels = td.mipLevels;
        ud.bytesPerTexel = 4u;
        usize offset = 0;
        const u32* texels = chains.texels.data() + chains.levels[chains.firstLevel[t]].offset;
        if (!upload.stageImage(texels, ud, offset) || !upload.recordImageCopy(m_resolveImages[t].image, offset, ud)) {
            return false;
        }
        m_resolveImageSlots[t] = m_desc.bindless->registerTextureSlot(m_resolveImages[t], false);
        m_resolveImageHandles[t] = m_desc.bindless->shaderHandle(m_resolveImageSlots[t]);
        if (m_resolveImageHandles[t] == kBindlessInvalidShaderHandle) {
            return false;
        }
        rows[t].offset = m_resolveImageHandles[t];
        ++m_stats.resolveImages;
        m_stats.resolveImageBytes += chains.textureTexels(t) * 4u;
    }
    const u64 materialsOffset = align256(sizeof(MlResolveTable));
    const u64 texturesOffset = align256(materialsOffset + std::max<u64>(u64{mc} * sizeof(MlMaterial), 16u));
    const u64 bytes = align256(texturesOffset + std::max<u64>(u64{tc} * sizeof(MlTexture), 16u));
    if (!createBuffer(bytes, "materials.resolve_table", true, m_resolveTable, m_resolveTableQueue)) {
        return false;
    }
    u8* base = static_cast<u8*>(m_resolveTable.mapped);
    MlResolveTable header{};
    header.materials = m_resolveTable.deviceAddress + materialsOffset;
    header.textures = m_resolveTable.deviceAddress + texturesOffset;
    header.materialCount = mc;
    header.textureCount = tc;
    std::memcpy(base, &header, sizeof(header));
    if (mc > 0u) {
        std::memcpy(base + materialsOffset, library.materials().data(), u64{mc} * sizeof(MlMaterial));
    }
    if (tc > 0u) {
        std::memcpy(base + texturesOffset, rows.data(), u64{tc} * sizeof(MlTexture));
    }
    m_resolveTableSlot = m_desc.bindless->registerBufferSlot(m_resolveTable, false);
    m_resolveTableHandle = m_desc.bindless->shaderHandle(m_resolveTableSlot);
    return m_resolveTableHandle != kBindlessInvalidShaderHandle;
}

bool MaterialLayers::setLibrary(const MlLibrary& library, UploadQueue* upload) {
    if (!m_initialized) {
        return false;
    }
    const u32 tc = static_cast<u32>(library.textures().size());
    const u32 mc = static_cast<u32>(library.materials().size());
    const u32 bc = static_cast<u32>(std::min<usize>(library.balls().size(), kMlMaxBalls));
    const MlLibraryLayout l = MlLibraryLayout::compute(tc, mc, bc, library.texels().size());
    if (!createBuffer(l.bytes, "materials.library", true, m_library, m_libraryQueue)) {
        return false;
    }
    u8* base = static_cast<u8*>(m_library.mapped);
    std::memcpy(base + l.lut, library.lut(), u64{kMlLutEntries} * 4u);
    if (tc > 0u) {
        std::memcpy(base + l.textures, library.textures().data(), u64{tc} * sizeof(MlTexture));
    }
    if (mc > 0u) {
        std::memcpy(base + l.materials, library.materials().data(), u64{mc} * sizeof(MlMaterial));
    }
    if (bc > 0u) {
        std::memcpy(base + l.balls, library.balls().data(), u64{bc} * sizeof(MlBall));
    }
    if (!library.texels().empty()) {
        std::memcpy(base + l.texels, library.texels().data(), library.texels().size() * 4u);
    }
    m_layout = l;
    m_textureCount = tc;
    m_materialCount = mc;
    m_ballCount = bc;
    ++m_stats.libraryUploads;
    if (upload != nullptr) {
        return buildResolveTable(library, *upload);
    }
    retireResolveTable();
    return true;
}

bool MaterialLayers::beginFrame(u64 frameSerial, const MlFrameDesc& frame) {
    if (!m_initialized || m_library.handle == nullptr) {
        return false;
    }
    m_frameSerial = frameSerial;
    m_recordCount = 0;
    m_stats.passes = 0;
    MlParams p = frame.params;
    const u64 imageBytes = std::max<u64>(static_cast<u64>(p.width) * p.height * 16u, 16u);
    if (m_image.handle == nullptr || m_image.desc.size != imageBytes) {
        if (!createBuffer(imageBytes, "materials.image", false, m_image, m_imageQueue)) {
            return false;
        }
        ++m_stats.imageRebuilds;
    }
    const u64 lib = m_library.deviceAddress;
    p.lut = lib + m_layout.lut;
    p.textures = lib + m_layout.textures;
    p.materials = lib + m_layout.materials;
    p.balls = lib + m_layout.balls;
    p.texels = lib + m_layout.texels;
    p.image = m_image.deviceAddress;
    p.textureCount = m_textureCount;
    p.materialCount = m_materialCount;
    p.ballCount = p.ballCount < m_ballCount ? p.ballCount : m_ballCount;
    m_params = p;
    const u32 slot = static_cast<u32>(frameSerial % m_desc.framesInFlight);
    const u64 offset = static_cast<u64>(slot) * kFrameStride;
    std::memcpy(static_cast<u8*>(m_frameRing.mapped) + offset, &p, sizeof(p));
    m_frameAddress = m_frameRing.deviceAddress + offset;
    return true;
}

MaterialLayerRefs MaterialLayers::importInto(rg::Graph& graph) {
    MaterialLayerRefs refs{};
    if (!m_initialized || m_library.handle == nullptr) {
        return refs;
    }
    refs.library = graph.importBuffer(rg::ImportedBuffer{m_library.handle, m_library.desc.size, m_libraryQueue,
                                                         &m_libraryQueue, "materials.library"});
    if (m_image.handle != nullptr) {
        refs.image = graph.importBuffer(rg::ImportedBuffer{m_image.handle, m_image.desc.size, m_imageQueue, &m_imageQueue,
                                                           "materials.image"});
    }
    if (m_resolveTable.handle != nullptr) {
        refs.resolveTable = graph.importBuffer(rg::ImportedBuffer{m_resolveTable.handle, m_resolveTable.desc.size,
                                                                  m_resolveTableQueue, &m_resolveTableQueue,
                                                                  "materials.resolve_table"});
    }
    return refs;
}

MaterialLayers::PassRecord* MaterialLayers::nextRecord(u32 kernel) {
    if (m_recordCount >= kMaxPasses) {
        return nullptr;
    }
    PassRecord* r = &m_records[m_recordCount++];
    *r = PassRecord{};
    r->self = this;
    r->kernel = kernel;
    r->push.params = m_frameAddress;
    return r;
}

void MaterialLayers::addEval(rg::Graph& graph, const MaterialLayerRefs& refs, rg::BufferRef srcBuffer, u64 srcAddress,
                             rg::BufferRef dstBuffer, u64 dstAddress, u32 count) {
    if (!m_initialized || !refs.library.valid() || !srcBuffer.valid() || !dstBuffer.valid() || count == 0u) {
        return;
    }
    PassRecord* r = nextRecord(kEval);
    if (r == nullptr) {
        return;
    }
    r->push.src = srcAddress;
    r->push.dst = dstAddress;
    r->push.count = count;
    r->groups[0] = groups(count, kMlEvalGroup);
    ++m_stats.passes;
    const u8 cs = rg::kStageCompute;
    graph.addPass("materials.eval", &MaterialLayers::recordDispatch, r)
        .use(refs.library, rg::Access::StorageRead, {}, cs)
        .use(srcBuffer, rg::Access::StorageRead, rg::BufferRange{0, u64{count} * sizeof(MlSurface)}, cs)
        .use(dstBuffer, rg::Access::StorageWrite, rg::BufferRange{0, u64{count} * sizeof(MlResult)}, cs);
}

void MaterialLayers::addBalls(rg::Graph& graph, const MaterialLayerRefs& refs) {
    if (!m_initialized || !refs.library.valid() || !refs.image.valid()) {
        return;
    }
    PassRecord* r = nextRecord(kBalls);
    if (r == nullptr) {
        return;
    }
    r->groups[0] = groups(m_params.width, kMlTile);
    r->groups[1] = groups(m_params.height, kMlTile);
    ++m_stats.passes;
    const u8 cs = rg::kStageCompute;
    graph.addPass("materials.balls", &MaterialLayers::recordDispatch, r)
        .use(refs.library, rg::Access::StorageRead, {}, cs)
        .use(refs.image, rg::Access::StorageWrite, {}, cs);
}

void MaterialLayers::addCopyImage(rg::Graph& graph, const MaterialLayerRefs& refs, rg::BufferRef dst, u64 dstOffset) {
    if (!m_initialized || !refs.image.valid() || !dst.valid()) {
        return;
    }
    PassRecord* r = nextRecord(kKernelCount);
    if (r == nullptr) {
        return;
    }
    r->copyBytes = std::max<u64>(imageBytes(), 16u);
    r->copyDst = dstOffset;
    r->copyFrom = refs.image;
    r->copyTo = dst;
    ++m_stats.passes;
    graph.addPass("materials.copy", &MaterialLayers::recordCopy, r)
        .use(refs.image, rg::Access::TransferSrc, rg::BufferRange{0, r->copyBytes})
        .use(dst, rg::Access::TransferDst, rg::BufferRange{dstOffset, r->copyBytes});
}

void MaterialLayers::recordDispatch(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    const MaterialLayers& self = *r.self;
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, static_cast<VkPipeline>(self.m_pipelines[r.kernel]));
    self.m_desc.bindless->bind(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, self.m_layoutHandle, 0);
    vkCmdPushConstants(cmd, static_cast<VkPipelineLayout>(self.m_layoutHandle), VK_SHADER_STAGE_COMPUTE_BIT, 0,
                       kPushBytes, &r.push);
    vkCmdDispatch(cmd, r.groups[0], r.groups[1], r.groups[2]);
#else
    (void)context;
    (void)user;
#endif
}

void MaterialLayers::recordCopy(const rg::PassContext& context, void* user) {
#if defined(FUSE_VULKAN_BACKEND)
    const PassRecord& r = *static_cast<const PassRecord*>(user);
    VkCommandBuffer cmd = static_cast<VkCommandBuffer>(context.commandBuffer);
    const VkBufferCopy region{0, r.copyDst, r.copyBytes};
    vkCmdCopyBuffer(cmd, static_cast<VkBuffer>(context.buffer(r.copyFrom)),
                    static_cast<VkBuffer>(context.buffer(r.copyTo)), 1, &region);
#else
    (void)context;
    (void)user;
#endif
}

} // namespace fuse::renderer::material_layers
