# fuse_package_gate (master plan Appendix A: "Icons, installer, docs, CI badge names").
# Run by ctest (LABELS "gate;lint") via cmake -P; registered in cmake/FusePackaging.cmake.
#
#   1. Self-test: every validator below is fed a seeded known-bad and known-good sample and must
#      reject / accept them (same convention as fuse_lint).
#   2. cpack -G TGZ into FUSE_OUT, list + extract the archive and verify:
#        * every expected file (programs, icons, desktop entry, licences) is present, and nothing
#          outside bin/ share/ (plus a macOS .app) is packaged, and no path names Torque/T3D;
#        * icon PNGs are real PNGs at their hicolor size; the SVG is an <svg> titled FUSE;
#        * the desktop entry is valid (built-in validator + desktop-file-validate when installed),
#          is named FUSE, and its Exec / Icon resolve to the packaged program / icon;
#        * the programs are executable;
#   3. CPack metadata (CPackConfig.cmake: name "fuse", vendor "FUSE", no Torque/T3D product naming
#      in any name / vendor / description / contact / NSIS / DEB field); with dpkg-deb available the
#      DEB is built too and its control fields get the same check.
#
# Inputs (-D): FUSE_CPACK, FUSE_CPACK_CONFIG, FUSE_CONFIG, FUSE_OUT, FUSE_EXPECTED ('|' list),
#              FUSE_PROGRAMS, FUSE_REQUIRED_PROGRAMS, FUSE_ICON_SIZES ('|' lists), FUSE_DATADIR.

cmake_minimum_required(VERSION 3.21)

foreach(_v FUSE_CPACK FUSE_CPACK_CONFIG FUSE_OUT FUSE_EXPECTED FUSE_ICON_SIZES FUSE_DATADIR)
    if(NOT DEFINED ${_v} OR "${${_v}}" STREQUAL "")
        message(FATAL_ERROR "fuse_package_gate: missing -D${_v}")
    endif()
endforeach()
foreach(_v FUSE_EXPECTED FUSE_PROGRAMS FUSE_REQUIRED_PROGRAMS FUSE_ICON_SIZES)
    string(REPLACE "|" ";" ${_v} "${${_v}}")
endforeach()

set(_banned_regex "[Tt][Oo][Rr][Qq][Uu][Ee]|[Tt]3[Dd]")

# ---- validators ----------------------------------------------------------------------------------
# Each appends human-readable problems to the list named by `out`.

# Reads a text file into a list of lines without CMake list/escape mangling (';' -> <SC>).
function(_fuse_read_lines path out)
    file(READ "${path}" _txt)
    string(REPLACE "\r\n" "\n" _txt "${_txt}")
    string(REPLACE "[" "<LB>" _txt "${_txt}")
    string(REPLACE "]" "<RB>" _txt "${_txt}")
    string(REPLACE ";" "<SC>" _txt "${_txt}")
    string(REPLACE "\n" ";" _lines "${_txt}")
    set(${out} "${_lines}" PARENT_SCOPE)
endfunction()

function(_fuse_unmangle s out)
    string(REPLACE "<LB>" "[" s "${s}")
    string(REPLACE "<RB>" "]" s "${s}")
    string(REPLACE "<SC>" ";" s "${s}")
    set(${out} "${s}" PARENT_SCOPE)
endfunction()

# Freedesktop desktop entry (spec 1.5 subset) for a FUSE application launcher.
function(fuse_validate_desktop path out)
    set(_p "${${out}}")
    if(NOT EXISTS "${path}")
        list(APPEND _p "desktop: ${path} missing")
        set(${out} "${_p}" PARENT_SCOPE)
        return()
    endif()
    _fuse_read_lines("${path}" _lines)
    set(_group "")
    set(_seen_main FALSE)
    set(_keys "")
    foreach(_raw IN LISTS _lines)
        if(_raw STREQUAL "" OR _raw MATCHES "^#")
            continue()
        endif()
        if(_raw MATCHES "^<LB>(.*)<RB>$")
            set(_group "${CMAKE_MATCH_1}")
            if(NOT _seen_main AND NOT _group STREQUAL "Desktop Entry")
                list(APPEND _p "desktop: first group is [${_group}], expected [Desktop Entry]")
            endif()
            set(_seen_main TRUE)
            continue()
        endif()
        if(NOT _seen_main)
            list(APPEND _p "desktop: key before [Desktop Entry]: ${_raw}")
            continue()
        endif()
        if(NOT _raw MATCHES "^([A-Za-z0-9-]+)(<LB>[^=]+<RB>)?[ ]*=[ ]*(.*)$")
            list(APPEND _p "desktop: malformed line: ${_raw}")
            continue()
        endif()
        set(_k "${CMAKE_MATCH_1}${CMAKE_MATCH_2}")
        _fuse_unmangle("${CMAKE_MATCH_3}" _val)
        if(NOT _group STREQUAL "Desktop Entry")
            continue()
        endif()
        if("|${_k}|" IN_LIST _keys)
            list(APPEND _p "desktop: duplicate key ${_k}")
        endif()
        list(APPEND _keys "|${_k}|")
        string(MAKE_C_IDENTIFIER "${_k}" _id)
        set(_de_${_id} "${_val}")
        set(_de_has_${_id} TRUE)
    endforeach()
    if(NOT _seen_main)
        list(APPEND _p "desktop: no [Desktop Entry] group")
    endif()
    foreach(_req Type Name Exec Icon Categories)
        if(NOT _de_has_${_req})
            list(APPEND _p "desktop: required key ${_req} missing")
        endif()
    endforeach()
    if(_de_has_Type AND NOT _de_Type STREQUAL "Application")
        list(APPEND _p "desktop: Type=${_de_Type}, expected Application")
    endif()
    if(_de_has_Version AND NOT _de_Version MATCHES "^1\\.[0-5]$")
        list(APPEND _p "desktop: Version=${_de_Version} is not a spec version (1.0-1.5)")
    endif()
    foreach(_b Terminal StartupNotify NoDisplay Hidden)
        if(_de_has_${_b} AND NOT _de_${_b} MATCHES "^(true|false)$")
            list(APPEND _p "desktop: ${_b}=${_de_${_b}} is not a boolean")
        endif()
    endforeach()
    if(_de_has_Categories AND NOT _de_Categories MATCHES ";$")
        list(APPEND _p "desktop: Categories must end with ';'")
    endif()
    if(_de_has_Name AND NOT _de_Name MATCHES "FUSE")
        list(APPEND _p "desktop: Name='${_de_Name}' does not say FUSE")
    endif()
    foreach(_k Name GenericName Comment Keywords Exec Icon StartupWMClass)
        if(_de_has_${_k} AND _de_${_k} MATCHES "${_banned_regex}")
            list(APPEND _p "desktop: ${_k}='${_de_${_k}}' uses Torque/T3D product naming")
        endif()
    endforeach()
    if(_de_has_Icon AND (_de_Icon MATCHES "/" OR _de_Icon MATCHES "\\.(png|svg|xpm)$"))
        list(APPEND _p "desktop: Icon=${_de_Icon} should be a themed icon name (no path / extension)")
    endif()
    # Results for the caller (Exec program / Icon name resolution).
    set(${out} "${_p}" PARENT_SCOPE)
    set(FUSE_DESKTOP_EXEC "${_de_Exec}" PARENT_SCOPE)
    set(FUSE_DESKTOP_ICON "${_de_Icon}" PARENT_SCOPE)
endfunction()

# PNG signature + IHDR size.
function(fuse_validate_png path size out)
    set(_p "${${out}}")
    if(NOT EXISTS "${path}")
        list(APPEND _p "png: ${path} missing")
    else()
        file(READ "${path}" _hex LIMIT 24 HEX)
        string(LENGTH "${_hex}" _n)
        if(_n LESS 48 OR NOT _hex MATCHES "^89504e470d0a1a0a0000000d49484452")
            list(APPEND _p "png: ${path} is not a PNG")
        else()
            string(SUBSTRING "${_hex}" 32 8 _w)
            string(SUBSTRING "${_hex}" 40 8 _h)
            math(EXPR _w "0x${_w}")
            math(EXPR _h "0x${_h}")
            if(NOT _w EQUAL size OR NOT _h EQUAL size)
                list(APPEND _p "png: ${path} is ${_w}x${_h}, expected ${size}x${size}")
            endif()
        endif()
    endif()
    set(${out} "${_p}" PARENT_SCOPE)
endfunction()

# Archive listing (paths relative to the top-level dir) against the expected payload.
function(fuse_validate_listing listing expected out)
    set(_p "${${out}}")
    foreach(_e IN LISTS expected)
        if(NOT _e IN_LIST listing)
            list(APPEND _p "package: expected file '${_e}' missing")
        endif()
    endforeach()
    foreach(_f IN LISTS listing)
        if(NOT _f MATCHES "^(bin|share)(/|$)" AND NOT _f MATCHES "^fuse_editor\\.app(/|$)")
            list(APPEND _p "package: unexpected top-level entry '${_f}' (only bin/, share/)")
        endif()
        if(_f MATCHES "${_banned_regex}")
            list(APPEND _p "package: path '${_f}' uses Torque/T3D naming")
        endif()
    endforeach()
    set(${out} "${_p}" PARENT_SCOPE)
endfunction()

# CPack metadata fields in a CPackConfig.cmake-style file (set(CPACK_X "value") lines).
function(fuse_validate_cpack_metadata path out)
    set(_p "${${out}}")
    _fuse_read_lines("${path}" _lines)
    set(_name "")
    set(_vendor "")
    set(_fields 0)
    foreach(_raw IN LISTS _lines)
        if(NOT _raw MATCHES "^set\\((CPACK_[A-Z0-9_]+) \"(.*)\"\\)$")
            continue()
        endif()
        set(_k "${CMAKE_MATCH_1}")
        _fuse_unmangle("${CMAKE_MATCH_2}" _val)
        # Product-facing metadata only (not paths, generators or tool locations).
        if(NOT _k MATCHES "(NAME|VENDOR|DESCRIPTION|SUMMARY|DISPLAY|CONTACT|MAINTAINER|HOMEPAGE|URL|INSTALL_DIRECTORY|EXECUTABLES|SECTION|PROVIDES|HELP_LINK|START_MENU|INSTALL_REGISTRY_KEY)"
           OR _k MATCHES "_FILE$|_DIR$|_DIRECTORY_PATH$|CPACK_OUTPUT_CONFIG_FILE|CPACK_CMAKE_GENERATOR|CPACK_INSTALL_CMAKE_PROJECTS|CPACK_SYSTEM_NAME|CPACK_TOPLEVEL_TAG")
            continue()
        endif()
        math(EXPR _fields "${_fields} + 1")
        if(_val MATCHES "${_banned_regex}")
            list(APPEND _p "metadata: ${_k}='${_val}' uses Torque/T3D product naming")
        endif()
        if(_k STREQUAL "CPACK_PACKAGE_NAME")
            set(_name "${_val}")
        elseif(_k STREQUAL "CPACK_PACKAGE_VENDOR")
            set(_vendor "${_val}")
        endif()
    endforeach()
    if(NOT _name STREQUAL "fuse")
        list(APPEND _p "metadata: CPACK_PACKAGE_NAME='${_name}', expected 'fuse'")
    endif()
    if(NOT _vendor STREQUAL "FUSE")
        list(APPEND _p "metadata: CPACK_PACKAGE_VENDOR='${_vendor}', expected 'FUSE'")
    endif()
    if(_fields LESS 4)
        list(APPEND _p "metadata: only ${_fields} product metadata field(s) found in ${path}")
    endif()
    set(${out} "${_p}" PARENT_SCOPE)
endfunction()

# ---- 1. self-test --------------------------------------------------------------------------------
set(_st "${FUSE_OUT}/selftest")
file(REMOVE_RECURSE "${_st}")
set(_selftest_ok TRUE)
# `cond` is a ;-list of if() arguments, e.g. "_n;EQUAL;0".
macro(_fuse_expect cond what)
    if(${cond})
        message(STATUS "self-test ok: ${what}")
    else()
        message(STATUS "self-test FAILED: ${what}")
        set(_selftest_ok FALSE)
    endif()
endmacro()

file(WRITE "${_st}/good.desktop" "# c\n[Desktop Entry]\nType=Application\nVersion=1.5\nName=FUSE Editor\nName[de]=FUSE Editor\nExec=fuse_editor\nIcon=fuse\nTerminal=false\nCategories=Development;IDE;\n\n[Desktop Action x]\nName=X\n")
file(WRITE "${_st}/bad.desktop" "Type=Application\n[Desktop Entry]\nType=Link\nName=Torque3D Editor\nName=Dup\nExec=t3d_editor\nIcon=/opt/torque.png\nTerminal=yes\nCategories=Development\nbad line\n")
set(_g "")
fuse_validate_desktop("${_st}/good.desktop" _g)
foreach(_x IN LISTS _g)
    message(STATUS "  unexpected: ${_x}")
endforeach()
list(LENGTH _g _gn)
_fuse_expect("_gn;EQUAL;0" "desktop validator accepts a valid FUSE entry")
set(_b "")
fuse_validate_desktop("${_st}/bad.desktop" _b)
list(LENGTH _b _bn)
# key before group, Type, duplicate Name, Name not FUSE, Name/Exec/Icon Torque naming, Icon path,
# Terminal boolean, Categories ';', malformed line => >= 10
_fuse_expect("_bn;GREATER_EQUAL;10" "desktop validator flags seeded bad entry (${_bn} problems)")

# Positive case: a real committed icon (CMake cannot write NUL bytes for a synthetic PNG).
set(_g "")
fuse_validate_png("${CMAKE_CURRENT_LIST_DIR}/../Source/FUSE/Branding/fuse_32.png" 32 _g)
list(LENGTH _g _gn)
_fuse_expect("_gn;EQUAL;0" "png validator accepts a 32x32 PNG")
set(_b "")
fuse_validate_png("${CMAKE_CURRENT_LIST_DIR}/../Source/FUSE/Branding/fuse_32.png" 48 _b)
file(WRITE "${_st}/fake.png" "not a png at all, just text padding....")
fuse_validate_png("${_st}/fake.png" 16 _b)
fuse_validate_png("${_st}/missing.png" 16 _b)
list(LENGTH _b _bn)
_fuse_expect("_bn;EQUAL;3" "png validator flags wrong size, non-PNG and missing file (${_bn})")

set(_g "")
fuse_validate_listing("bin;bin/fuse_cook;share;share/doc/fuse/LICENSE.md" "bin/fuse_cook;share/doc/fuse/LICENSE.md" _g)
list(LENGTH _g _gn)
_fuse_expect("_gn;EQUAL;0" "listing validator accepts the expected payload")
set(_b "")
fuse_validate_listing("bin;bin/fuse_cook;lib/libz.a;share/torque3d/x" "bin/fuse_cook;bin/fuse_editor" _b)
list(LENGTH _b _bn)
_fuse_expect("_bn;EQUAL;3" "listing validator flags missing file, stray lib/ and Torque path (${_bn})")

file(WRITE "${_st}/good_cpack.cmake" "set(CPACK_PACKAGE_NAME \"fuse\")\nset(CPACK_PACKAGE_VENDOR \"FUSE\")\nset(CPACK_PACKAGE_DESCRIPTION_SUMMARY \"FUSE engine\")\nset(CPACK_NSIS_DISPLAY_NAME \"FUSE 0.1\")\nset(CPACK_PACKAGE_EXECUTABLES \"fuse_editor;FUSE Editor\")\nset(CPACK_INSTALL_CMAKE_PROJECTS \"/src/torque-fork/build;FUSE;fuse;/\")\n")
file(WRITE "${_st}/bad_cpack.cmake" "set(CPACK_PACKAGE_NAME \"Torque3D\")\nset(CPACK_PACKAGE_VENDOR \"GarageGames\")\nset(CPACK_PACKAGE_DESCRIPTION_SUMMARY \"FUSE (T3D fork)\")\nset(CPACK_DEBIAN_PACKAGE_MAINTAINER \"Torque team\")\n")
set(_g "")
fuse_validate_cpack_metadata("${_st}/good_cpack.cmake" _g)
foreach(_x IN LISTS _g)
    message(STATUS "  unexpected: ${_x}")
endforeach()
list(LENGTH _g _gn)
_fuse_expect("_gn;EQUAL;0" "metadata validator accepts FUSE metadata (paths are not metadata)")
set(_b "")
fuse_validate_cpack_metadata("${_st}/bad_cpack.cmake" _b)
list(LENGTH _b _bn)
# 3 Torque/T3D fields + wrong name + wrong vendor => 5
_fuse_expect("_bn;EQUAL;5" "metadata validator flags Torque/T3D naming and wrong name/vendor (${_bn})")

if(NOT _selftest_ok)
    message(FATAL_ERROR "fuse_package_gate: self-test FAILED (validators cannot detect seeded violations)")
endif()
file(REMOVE_RECURSE "${_st}")

# ---- 2. build the TGZ and verify its payload -------------------------------------------------------
set(_problems "")
if(NOT EXISTS "${FUSE_CPACK_CONFIG}")
    message(FATAL_ERROR "fuse_package_gate: ${FUSE_CPACK_CONFIG} missing (configure first)")
endif()
foreach(_req IN LISTS FUSE_REQUIRED_PROGRAMS)
    if(NOT _req IN_LIST FUSE_PROGRAMS)
        list(APPEND _problems "package: required program ${_req} is not a configured target")
    endif()
endforeach()

set(_pkgdir "${FUSE_OUT}/pkg")
file(REMOVE_RECURSE "${_pkgdir}")
set(_cfg_args "")
if(FUSE_CONFIG)
    set(_cfg_args -C "${FUSE_CONFIG}")
endif()
execute_process(
    COMMAND "${FUSE_CPACK}" -G TGZ --config "${FUSE_CPACK_CONFIG}" ${_cfg_args} -B "${_pkgdir}"
    RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
message(STATUS "cpack -G TGZ: rc=${_rc}\n${_out}${_err}")
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "fuse_package_gate: cpack -G TGZ failed")
endif()
file(GLOB_RECURSE _tgz "${_pkgdir}/*.tar.gz")
list(LENGTH _tgz _ntgz)
if(NOT _ntgz EQUAL 1)
    message(FATAL_ERROR "fuse_package_gate: expected exactly one .tar.gz under ${_pkgdir}, got '${_tgz}'")
endif()
get_filename_component(_tgz_name "${_tgz}" NAME)
message(STATUS "package: ${_tgz_name}")
if(NOT _tgz_name MATCHES "^fuse-")
    list(APPEND _problems "package: file name '${_tgz_name}' does not start with 'fuse-'")
endif()

set(_x "${FUSE_OUT}/extract")
file(REMOVE_RECURSE "${_x}")
file(MAKE_DIRECTORY "${_x}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xzf "${_tgz}" WORKING_DIRECTORY "${_x}" RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "fuse_package_gate: could not extract ${_tgz}")
endif()
file(GLOB _tops LIST_DIRECTORIES true "${_x}/*")
list(LENGTH _tops _ntops)
if(NOT _ntops EQUAL 1)
    message(FATAL_ERROR "fuse_package_gate: archive must have one top-level directory, got '${_tops}'")
endif()
set(_root "${_tops}")
get_filename_component(_top_name "${_root}" NAME)
if(NOT _top_name MATCHES "^fuse-")
    list(APPEND _problems "package: top-level directory '${_top_name}' does not start with 'fuse-'")
endif()
file(GLOB_RECURSE _files LIST_DIRECTORIES false RELATIVE "${_root}" "${_root}/*")
list(SORT _files)
list(LENGTH _files _nfiles)
message(STATUS "package payload: ${_nfiles} file(s)")
foreach(_f IN LISTS _files)
    message(STATUS "  ${_f}")
endforeach()
fuse_validate_listing("${_files}" "${FUSE_EXPECTED}" _problems)

foreach(_px IN LISTS FUSE_ICON_SIZES)
    fuse_validate_png("${_root}/${FUSE_DATADIR}/icons/hicolor/${_px}x${_px}/apps/fuse.png" ${_px} _problems)
endforeach()
fuse_validate_png("${_root}/${FUSE_DATADIR}/pixmaps/fuse.png" 48 _problems)
set(_svg "${_root}/${FUSE_DATADIR}/icons/hicolor/scalable/apps/fuse.svg")
if(EXISTS "${_svg}")
    file(READ "${_svg}" _svgtxt)
    if(NOT _svgtxt MATCHES "<svg[^>]*xmlns=\"http://www.w3.org/2000/svg\"" OR NOT _svgtxt MATCHES "<title>FUSE</title>")
        list(APPEND _problems "icon: fuse.svg is not an SVG titled FUSE")
    endif()
endif()

set(_desktop "${_root}/${FUSE_DATADIR}/applications/fuse.desktop")
fuse_validate_desktop("${_desktop}" _problems)
if(EXISTS "${_desktop}")
    string(REGEX REPLACE " .*" "" _exec "${FUSE_DESKTOP_EXEC}")
    if(NOT _exec STREQUAL "fuse_editor")
        list(APPEND _problems "desktop: Exec=${FUSE_DESKTOP_EXEC} does not launch fuse_editor")
    elseif("fuse_editor" IN_LIST FUSE_PROGRAMS AND NOT EXISTS "${_root}/bin/fuse_editor")
        list(APPEND _problems "desktop: Exec program bin/fuse_editor not packaged")
    endif()
    if(NOT EXISTS "${_root}/${FUSE_DATADIR}/icons/hicolor/scalable/apps/${FUSE_DESKTOP_ICON}.svg")
        list(APPEND _problems "desktop: Icon=${FUSE_DESKTOP_ICON} has no packaged hicolor icon")
    endif()
    find_program(_dfv desktop-file-validate)
    if(_dfv)
        execute_process(COMMAND "${_dfv}" "${_desktop}" RESULT_VARIABLE _rc OUTPUT_VARIABLE _o ERROR_VARIABLE _e)
        message(STATUS "desktop-file-validate: rc=${_rc} ${_o}${_e}")
        if(NOT _rc EQUAL 0 OR "${_o}${_e}" MATCHES "error:")
            list(APPEND _problems "desktop: desktop-file-validate rejected fuse.desktop: ${_o}${_e}")
        endif()
    else()
        message(STATUS "desktop-file-validate not installed: built-in desktop entry validator only")
    endif()
endif()

if(CMAKE_HOST_UNIX)
    foreach(_t IN LISTS FUSE_PROGRAMS)
        set(_bin "${_root}/bin/${_t}")
        if(EXISTS "${_bin}")
            execute_process(COMMAND test -x "${_bin}" RESULT_VARIABLE _rc)
            if(NOT _rc EQUAL 0)
                list(APPEND _problems "package: bin/${_t} is not executable")
            endif()
        endif()
    endforeach()
endif()

# ---- 3. metadata ---------------------------------------------------------------------------------
fuse_validate_cpack_metadata("${FUSE_CPACK_CONFIG}" _problems)

find_program(_dpkg_deb dpkg-deb)
if(_dpkg_deb AND CMAKE_HOST_UNIX AND NOT CMAKE_HOST_APPLE)
    execute_process(
        COMMAND "${FUSE_CPACK}" -G DEB --config "${FUSE_CPACK_CONFIG}" ${_cfg_args} -B "${_pkgdir}"
        RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _err)
    file(GLOB_RECURSE _deb "${_pkgdir}/*.deb")
    if(NOT _rc EQUAL 0 OR NOT _deb)
        list(APPEND _problems "deb: cpack -G DEB failed: ${_out}${_err}")
    else()
        list(GET _deb 0 _deb)
        get_filename_component(_deb_name "${_deb}" NAME)
        execute_process(COMMAND "${_dpkg_deb}" -f "${_deb}" RESULT_VARIABLE _rc OUTPUT_VARIABLE _ctl)
        message(STATUS "deb: ${_deb_name}\n${_ctl}")
        if(NOT _ctl MATCHES "(^|\n)Package: fuse\n")
            list(APPEND _problems "deb: control Package is not 'fuse'")
        endif()
        if(_ctl MATCHES "${_banned_regex}")
            list(APPEND _problems "deb: control fields use Torque/T3D naming")
        endif()
        execute_process(COMMAND "${_dpkg_deb}" -c "${_deb}" OUTPUT_VARIABLE _debls)
        if(NOT _debls MATCHES "/share/applications/fuse\\.desktop" OR NOT _debls MATCHES "/share/icons/hicolor/256x256/apps/fuse\\.png")
            list(APPEND _problems "deb: payload lacks fuse.desktop / hicolor icon")
        endif()
    endif()
else()
    message(STATUS "dpkg-deb not available: DEB generation not exercised")
endif()

list(LENGTH _problems _np)
foreach(_p IN LISTS _problems)
    message(STATUS "  ${_p}")
endforeach()
message(STATUS "fuse_package_gate: ${_nfiles} packaged file(s), ${_np} problem(s)")
if(_np GREATER 0)
    message(FATAL_ERROR "fuse_package_gate FAILED")
endif()
