# FUSE Track A P6 shipping gate — game runtime without Qt, editor shell, or
# legacy engine GUI. Editor remains a separate target (FUSE_BUILD_EDITOR).

function(fuse_shipping_force_options)
    if(NOT FUSE_SHIPPING)
        return()
    endif()

    get_property(_fuse_shipping_logged GLOBAL PROPERTY FUSE_SHIPPING_FORCE_LOGGED)
    if(NOT _fuse_shipping_logged)
        message(STATUS "FUSE_SHIPPING=ON — forcing editor, T3D/T2D, and Qt present OFF")
        set_property(GLOBAL PROPERTY FUSE_SHIPPING_FORCE_LOGGED TRUE)
    endif()

    set(FUSE_BUILD_EDITOR OFF CACHE BOOL
        "Build fuse_editor Qt 6 desktop shell (requires Qt6; desktop-only)" FORCE)
    set(FUSE_BUILD_T3D OFF CACHE BOOL
        "Build Torque3D application target(s)" FORCE)
    set(FUSE_BUILD_T2D OFF CACHE BOOL
        "Build Torque2D engine target (requires submodule)" FORCE)
    set(FUSE_ENABLE_QT_PRESENT OFF CACHE BOOL
        "Allow vkQueuePresentKHR when display+Qt Vulkan surface available (OFF for headless CI)" FORCE)

    if(DEFINED FUSE_BUILD_COMPAT_TS)
        set(FUSE_BUILD_COMPAT_TS OFF CACHE BOOL
            "Build quarantined dialect script VMs under Compat/" FORCE)
    endif()
endfunction()

# FATAL_ERROR if a runtime target's link interface names Qt5/Qt6.
function(fuse_assert_target_not_qt target)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "fuse_assert_target_not_qt: '${target}' is not a CMake target")
    endif()

    foreach(_prop LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
        get_target_property(_fuse_qt_libs "${target}" ${_prop})
        if(NOT _fuse_qt_libs)
            continue()
        endif()
        if("${_fuse_qt_libs}" MATCHES "[Qq]t[56]")
            message(FATAL_ERROR
                "FUSE: target '${target}' must not link Qt (${_prop}: ${_fuse_qt_libs})")
        endif()
    endforeach()
endfunction()

function(fuse_shipping_add_qt_ban_cmake_test)
    get_property(_fuse_qt_ban_done GLOBAL PROPERTY FUSE_P6_SHIPPING_QT_BAN_CMAKE)
    if(_fuse_qt_ban_done)
        return()
    endif()
    set_property(GLOBAL PROPERTY FUSE_P6_SHIPPING_QT_BAN_CMAKE TRUE)

    if(NOT FUSE_BUILD_CORE_TESTS)
        return()
    endif()

    set(_fuse_qt_ban_body
        "# Generated by cmake/FuseShipping.cmake — P6 shipping Qt ban (no Qt compile).\n")

    foreach(_fuse_qt_ban_tgt fuse_core fuse_runtime_smoke)
        if(NOT TARGET "${_fuse_qt_ban_tgt}")
            continue()
        endif()
        string(APPEND _fuse_qt_ban_body "
set(_fuse_${_fuse_qt_ban_tgt}_link \"$<TARGET_PROPERTY:${_fuse_qt_ban_tgt},LINK_LIBRARIES>\")
set(_fuse_${_fuse_qt_ban_tgt}_iface \"$<TARGET_PROPERTY:${_fuse_qt_ban_tgt},INTERFACE_LINK_LIBRARIES>\")
foreach(_lib IN LISTS _fuse_${_fuse_qt_ban_tgt}_link _fuse_${_fuse_qt_ban_tgt}_iface)
    if(_lib MATCHES \"[Qq]t[56]\")
        message(FATAL_ERROR
            \"FUSE P6 shipping: ${_fuse_qt_ban_tgt} must not link Qt (\${_lib})\")
    endif()
endforeach()
")
    endforeach()

    set(_fuse_qt_ban_script "${CMAKE_BINARY_DIR}/cmake/fuse_p6_shipping_qt_ban.cmake")
    file(GENERATE OUTPUT "${_fuse_qt_ban_script}" CONTENT "${_fuse_qt_ban_body}")
    add_test(NAME fuse_p6_shipping_qt_ban_cmake
        COMMAND ${CMAKE_COMMAND} -P "${_fuse_qt_ban_script}")
endfunction()

# Configure-time Qt ban for shipping / non-editor product graphs, plus a
# generate-time ctest that expands LINK_LIBRARIES genex without compiling Qt.
function(fuse_shipping_assert_runtime_targets)
    fuse_shipping_force_options()

    if(FUSE_SHIPPING OR NOT FUSE_BUILD_EDITOR)
        if(TARGET fuse_runtime_smoke)
            fuse_assert_target_not_qt(fuse_runtime_smoke)
        endif()
        if(TARGET fuse_core)
            fuse_assert_target_not_qt(fuse_core)
        endif()
    endif()

    fuse_shipping_add_qt_ban_cmake_test()
endfunction()

fuse_shipping_force_options()

# Shipping links drop unreferenced code: each function/datum gets its own section and the linker
# discards the unreachable ones, so debug-only helpers (assert fatal path, profiler scopes) that no
# shipped call site references are not carried into shipped executables. fuse_b7_shipping_binaries
# (below) inspects the result.
if(FUSE_SHIPPING AND CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
    add_compile_options($<$<COMPILE_LANGUAGE:C,CXX>:-ffunction-sections> $<$<COMPILE_LANGUAGE:C,CXX>:-fdata-sections>)
    if(APPLE)
        add_link_options(-Wl,-dead_strip)
    else()
        add_link_options(-Wl,--gc-sections)
    endif()
endif()

# B7.10 engine-wide binary inspection: every fuse_* static library and every shipped (non-test) executable
# built from Source/FUSE + Tools/FUSE in a FUSE_SHIPPING tree must carry no FUSE_ASSERT fatal
# references, no ProfileScope code and none of the strings passed to stripped log/assert/profiler
# macros (Source/FUSE/Core/tests/check_b7_shipping_binaries.cmake). Call once at the end of the
# top-level CMakeLists.txt, after every FUSE target exists.
function(_fuse_shipping_collect_targets dir out_targets out_tests)
    get_property(_targets DIRECTORY "${dir}" PROPERTY BUILDSYSTEM_TARGETS)
    get_property(_tests DIRECTORY "${dir}" PROPERTY TESTS)
    get_property(_subdirs DIRECTORY "${dir}" PROPERTY SUBDIRECTORIES)
    set(_all ${_targets})
    set(_all_tests ${_tests})
    foreach(_sd IN LISTS _subdirs)
        _fuse_shipping_collect_targets("${_sd}" _t _ts)
        list(APPEND _all ${_t})
        list(APPEND _all_tests ${_ts})
    endforeach()
    set(${out_targets} ${_all} PARENT_SCOPE)
    set(${out_tests} ${_all_tests} PARENT_SCOPE)
endfunction()

function(fuse_shipping_add_binary_strip_test)
    if(NOT FUSE_SHIPPING OR NOT FUSE_BUILD_CORE_TESTS)
        return()
    endif()
    if(NOT CMAKE_NM OR CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        message(STATUS "FUSE: fuse_b7_shipping_binaries skipped (needs nm; GNU/Clang toolchains)")
        return()
    endif()

    _fuse_shipping_collect_targets("${CMAKE_SOURCE_DIR}" _targets _all_tests)
    set(_lines "")
    set(_count 0)
    foreach(_t IN LISTS _targets)
        get_target_property(_type ${_t} TYPE)
        get_target_property(_imported ${_t} IMPORTED)
        if(_imported)
            continue()
        endif()
        get_target_property(_sdir ${_t} SOURCE_DIR)
        set(_is_fuse OFF)
        foreach(_root "${CMAKE_SOURCE_DIR}/Source/FUSE/" "${CMAKE_SOURCE_DIR}/Tools/FUSE")
            string(FIND "${_sdir}/" "${_root}" _pos)
            if(_pos EQUAL 0)
                set(_is_fuse ON)
            endif()
        endforeach()
        if(NOT _is_fuse)
            continue()
        endif()
        if(_type STREQUAL "STATIC_LIBRARY" AND _t MATCHES "^fuse_")
            # Engine libraries; test-only helper libraries live under */tests.
            if(_sdir MATCHES "/tests(/|$)")
                continue()
            endif()
        elseif(_type STREQUAL "EXECUTABLE")
            # Shipped programs (demos, tools). Test harnesses — anything under */tests, or an
            # executable registered as a ctest of the same name (gates, runtime smoke) — exercise
            # debug hooks such as ProfileScope or the assert handler on purpose.
            if(_sdir MATCHES "/tests(/|$)" OR _t IN_LIST _all_tests)
                continue()
            endif()
            # ... or built only from sources under a tests/ directory (e.g. Renderer/cmake/*.cmake gates).
            get_target_property(_srcs ${_t} SOURCES)
            set(_test_only ON)
            foreach(_src IN LISTS _srcs)
                if(NOT _src MATCHES "(^|/)tests/")
                    set(_test_only OFF)
                endif()
            endforeach()
            if(_test_only)
                continue()
            endif()
        else()
            continue()
        endif()
        string(APPEND _lines "$<TARGET_FILE:${_t}>\n")
        math(EXPR _count "${_count} + 1")
    endforeach()

    set(_list "${CMAKE_BINARY_DIR}/cmake/fuse_b7_shipping_binaries.txt")
    file(GENERATE OUTPUT "${_list}" CONTENT "${_lines}")
    add_test(NAME fuse_b7_shipping_binaries
        COMMAND ${CMAKE_COMMAND}
            -DNM=${CMAKE_NM}
            -DARTIFACT_LIST=${_list}
            "-DSOURCE_ROOTS=${CMAKE_SOURCE_DIR}/Source/FUSE|${CMAKE_SOURCE_DIR}/Tools/FUSE"
            -P "${CMAKE_SOURCE_DIR}/Source/FUSE/Core/tests/check_b7_shipping_binaries.cmake")
    set_tests_properties(fuse_b7_shipping_binaries PROPERTIES LABELS "gate" TIMEOUT 600)
    message(STATUS "FUSE: fuse_b7_shipping_binaries inspects ${_count} shipping artifacts")
endfunction()
