# WP-0.6 zero-overhead check (cmake -P): -DNM=<nm> -DEXPECT=absent|present -DFILES=<a>|<b>|...
# absent: no Tracy symbol (tracy::*, ___tracy_*, fuse::profiler::tracy_adapter::*) is defined or
# referenced by any file (FUSE_TRACY=OFF build). present: at least one is (negative control).
if(NOT NM OR NOT EXPECT OR NOT FILES)
    message(FATAL_ERROR "usage: cmake -DNM=<nm> -DEXPECT=absent|present -DFILES=a|b -P FuseTracySymbolCheck.cmake")
endif()
string(REPLACE "|" ";" _files "${FILES}")
set(_hits 0)
foreach(_file IN LISTS _files)
    if(NOT EXISTS "${_file}")
        message(FATAL_ERROR "missing: ${_file}")
    endif()
    execute_process(COMMAND "${NM}" -C "${_file}" OUTPUT_VARIABLE _out ERROR_VARIABLE _err RESULT_VARIABLE _rc)
    if(NOT _rc EQUAL 0)
        message(FATAL_ERROR "${NM} failed on ${_file}: ${_err}")
    endif()
    string(REGEX MATCHALL "[^\n]*(tracy::|___tracy_|tracy_adapter|TracyC|tracy_malloc)[^\n]*" _matches "${_out}")
    list(LENGTH _matches _n)
    math(EXPR _hits "${_hits} + ${_n}")
    if(_n GREATER 0 AND EXPECT STREQUAL "absent")
        list(SUBLIST _matches 0 5 _shown)
        string(REPLACE ";" "\n  " _shown "${_shown}")
        message(SEND_ERROR "${_file}: ${_n} Tracy symbol(s) in a FUSE_TRACY=OFF build, e.g.\n  ${_shown}")
    endif()
    message(STATUS "${_file}: ${_n} Tracy symbol(s)")
endforeach()
if(EXPECT STREQUAL "present" AND _hits EQUAL 0)
    message(FATAL_ERROR "no Tracy symbols found: the symbol check would not detect an enabled build")
endif()
