# FUSE Track A P6 shipping gate — game runtime without Qt, editor shell, or
# legacy engine GUI. Editor remains a separate target (FUSE_BUILD_EDITOR).

function(fuse_shipping_force_options)
    if(NOT FUSE_SHIPPING)
        return()
    endif()

    get_property(_fuse_shipping_logged GLOBAL PROPERTY FUSE_SHIPPING_FORCE_LOGGED)
    if(NOT _fuse_shipping_logged)
        message(STATUS "FUSE_SHIPPING=ON — forcing editor, T3D/T2D, and Qt present OFF")
        set_property(GLOBAL PROPERTY FUSE_SHIPPING_FORCE_LOGGED TRUE)
    endif()

    set(FUSE_BUILD_EDITOR OFF CACHE BOOL
        "Build fuse_editor Qt 6 desktop shell (requires Qt6; desktop-only)" FORCE)
    set(FUSE_BUILD_T3D OFF CACHE BOOL
        "Build Torque3D application target(s)" FORCE)
    set(FUSE_BUILD_T2D OFF CACHE BOOL
        "Build Torque2D engine target (requires submodule)" FORCE)
    set(FUSE_ENABLE_QT_PRESENT OFF CACHE BOOL
        "Allow vkQueuePresentKHR when display+Qt Vulkan surface available (OFF for headless CI)" FORCE)

    if(DEFINED FUSE_BUILD_COMPAT_TS)
        set(FUSE_BUILD_COMPAT_TS OFF CACHE BOOL
            "Build quarantined dialect script VMs under Compat/" FORCE)
    endif()
endfunction()

# FATAL_ERROR if a runtime target's link interface names Qt5/Qt6.
function(fuse_assert_target_not_qt target)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "fuse_assert_target_not_qt: '${target}' is not a CMake target")
    endif()

    foreach(_prop LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
        get_target_property(_fuse_qt_libs "${target}" ${_prop})
        if(NOT _fuse_qt_libs)
            continue()
        endif()
        if("${_fuse_qt_libs}" MATCHES "[Qq]t[56]")
            message(FATAL_ERROR
                "FUSE: target '${target}' must not link Qt (${_prop}: ${_fuse_qt_libs})")
        endif()
    endforeach()
endfunction()

function(fuse_shipping_add_qt_ban_cmake_test)
    get_property(_fuse_qt_ban_done GLOBAL PROPERTY FUSE_P6_SHIPPING_QT_BAN_CMAKE)
    if(_fuse_qt_ban_done)
        return()
    endif()
    set_property(GLOBAL PROPERTY FUSE_P6_SHIPPING_QT_BAN_CMAKE TRUE)

    if(NOT FUSE_BUILD_CORE_TESTS)
        return()
    endif()

    set(_fuse_qt_ban_body
        "# Generated by cmake/FuseShipping.cmake — P6 shipping Qt ban (no Qt compile).\n")

    foreach(_fuse_qt_ban_tgt fuse_core fuse_runtime_smoke)
        if(NOT TARGET "${_fuse_qt_ban_tgt}")
            continue()
        endif()
        string(APPEND _fuse_qt_ban_body "
set(_fuse_${_fuse_qt_ban_tgt}_link \"$<TARGET_PROPERTY:${_fuse_qt_ban_tgt},LINK_LIBRARIES>\")
set(_fuse_${_fuse_qt_ban_tgt}_iface \"$<TARGET_PROPERTY:${_fuse_qt_ban_tgt},INTERFACE_LINK_LIBRARIES>\")
foreach(_lib IN LISTS _fuse_${_fuse_qt_ban_tgt}_link _fuse_${_fuse_qt_ban_tgt}_iface)
    if(_lib MATCHES \"[Qq]t[56]\")
        message(FATAL_ERROR
            \"FUSE P6 shipping: ${_fuse_qt_ban_tgt} must not link Qt (\${_lib})\")
    endif()
endforeach()
")
    endforeach()

    set(_fuse_qt_ban_script "${CMAKE_BINARY_DIR}/cmake/fuse_p6_shipping_qt_ban.cmake")
    file(GENERATE OUTPUT "${_fuse_qt_ban_script}" CONTENT "${_fuse_qt_ban_body}")
    add_test(NAME fuse_p6_shipping_qt_ban_cmake
        COMMAND ${CMAKE_COMMAND} -P "${_fuse_qt_ban_script}")
endfunction()

# Configure-time Qt ban for shipping / non-editor product graphs, plus a
# generate-time ctest that expands LINK_LIBRARIES genex without compiling Qt.
function(fuse_shipping_assert_runtime_targets)
    fuse_shipping_force_options()

    if(FUSE_SHIPPING OR NOT FUSE_BUILD_EDITOR)
        if(TARGET fuse_runtime_smoke)
            fuse_assert_target_not_qt(fuse_runtime_smoke)
        endif()
        if(TARGET fuse_core)
            fuse_assert_target_not_qt(fuse_core)
        endif()
    endif()

    fuse_shipping_add_qt_ban_cmake_test()
endfunction()

fuse_shipping_force_options()
