# WP-0.2 (docs/unification/RENDERER-EXECUTION.md): load Vulkan through the vendored volk meta-loader
# (Engine/lib/volk, pinned in its VERSION; lint gate fuse_lint_vendored_pins_volk).
#
# fuse_volk_attach(<target> IMPLEMENTATION <source>)
#   * <target> stops linking the Vulkan loader (Vulkan::Vulkan is removed from its link interface) and
#     links only the headers: the loader library is opened at run time (volkInitialize: dlopen of
#     libvulkan.so.1 / LoadLibrary of vulkan-1.dll). So no import library is needed at link time, and
#     no vk* symbol is imported (`nm -D --undefined-only` shows none).
#   * VK_NO_PROTOTYPES is PUBLIC, and a generated `vulkan/vulkan.h` shim comes first on the PUBLIC
#     include path: it includes the real vulkan.h without prototypes, then volk.h. Every `vk*` name that
#     <target> and its consumers use is then volk's function-pointer global. Sources keep including
#     <vulkan/vulkan.h> unchanged. A TU that reaches the real header by another path gets no prototypes
#     and fails to compile instead of silently calling the loader's export.
#   * <source> (src/vk/vk_loader.cpp) compiles volk.c (VOLK_IMPLEMENTATION) and owns the load policy.
#
# Rule for mixed images: code that calls vk* as *functions* against the linked loader (fuse_core's
# Win32/X11 surface creation) must not also see the shim, and volk must not define those names. That
# is why vk_loader.cpp #undefs every VK_USE_PLATFORM_* before the implementation: the platform surface
# entry points stay loader exports.
#
# fuse_volk_auto_init(<target> SOURCE <source> SYMBOL <anchor> [DISABLED])
#   * <source> (src/vk/vk_loader_autoinit.cpp) opens the loader during static initialisation. It is
#     an archive member nothing references, pulled into an image only by a forced undefined <anchor>
#     (`-u` / `/INCLUDE:`) on <target>'s INTERFACE_LINK_OPTIONS, i.e. into every image that links
#     <target> directly or transitively.
#   * A consuming image opts out with the target property FUSE_RHI_VOLK_NO_AUTO_INIT (evaluated on the
#     image being linked): `set_target_properties(d3d9 PROPERTIES FUSE_RHI_VOLK_NO_AUTO_INIT ON)`.
#     Nothing in <target> then loads the loader before an explicit vkloader::initialize() (or the
#     first VulkanInstance / adopted VulkanDevice): no LoadLibrary from DllMain.
#   * DISABLED (the FUSE_RHI_VOLK_AUTO_INIT=OFF cache option) drops it for every image and compiles
#     <source> with FUSE_RHI_VOLK_NO_AUTO_INIT.
#
# Windows: FuseFindVulkan.cmake is unchanged. MinGW's fallback imported target (System32/vulkan-1.dll plus
# the vendored Khronos headers) and the SDK target both still supply the headers here. fuse_core's Win32
# WSI keeps linking the loader for vkCreateWin32SurfaceKHR.

function(fuse_volk_attach target)
    cmake_parse_arguments(ARG "" "IMPLEMENTATION" "" ${ARGN})
    set(_volk_dir "${FUSE_VENDOR_DIR}/volk")
    if(NOT EXISTS "${_volk_dir}/volk.h" OR NOT EXISTS "${_volk_dir}/volk.c" OR NOT EXISTS "${_volk_dir}/VERSION")
        message(FATAL_ERROR "FuseVolk: vendored volk missing under ${_volk_dir} (volk.h, volk.c, VERSION)")
    endif()

    # Locate the real <vulkan/vulkan.h> behind whichever target FuseFindVulkan / FindVulkan provided.
    set(_candidates "")
    if(DEFINED Vulkan_INCLUDE_DIR)
        list(APPEND _candidates "${Vulkan_INCLUDE_DIR}")
    endif()
    foreach(_t Vulkan::Headers Vulkan::Vulkan)
        if(TARGET ${_t})
            get_target_property(_inc ${_t} INTERFACE_INCLUDE_DIRECTORIES)
            if(_inc)
                list(APPEND _candidates ${_inc})
            endif()
        endif()
    endforeach()
    set(_vk_inc "")
    foreach(_d IN LISTS _candidates)
        if(NOT _d MATCHES "\\$<" AND EXISTS "${_d}/vulkan/vulkan.h")
            set(_vk_inc "${_d}")
            break()
        endif()
    endforeach()
    if(_vk_inc STREQUAL "")
        message(FATAL_ERROR "FuseVolk: no Vulkan headers found (searched: ${_candidates})")
    endif()

    set(_shim_dir "${CMAKE_BINARY_DIR}/fuse_volk/include")
    file(CONFIGURE OUTPUT "${_shim_dir}/vulkan/vulkan.h" CONTENT
"/* Generated by cmake/FuseVolk.cmake (WP-0.2). Do not edit. Stands in for <vulkan/vulkan.h> on the
 * include path of targets attached to volk: the real header (@_vk_inc@) without prototypes,
 * then volk.h, so every vk* name is a volk function-pointer global loaded at run time. */
#ifndef FUSE_VOLK_VULKAN_SHIM_H_
#define FUSE_VOLK_VULKAN_SHIM_H_
#ifndef VK_NO_PROTOTYPES
#define VK_NO_PROTOTYPES
#endif
#include \"@_vk_inc@/vulkan/vulkan.h\"
#include <volk.h>
#endif
" @ONLY)

    get_target_property(_srcdir ${target} SOURCE_DIR)
    target_sources(${target} PRIVATE "${ARG_IMPLEMENTATION}")
    target_include_directories(${target} BEFORE PUBLIC "$<BUILD_INTERFACE:${_shim_dir}>")
    # SYSTEM: third-party code (volk.c is compiled inside the implementation TU).
    target_include_directories(${target} SYSTEM PUBLIC "$<BUILD_INTERFACE:${_volk_dir}>" "$<BUILD_INTERFACE:${_vk_inc}>")
    target_compile_definitions(${target} PUBLIC VK_NO_PROTOTYPES FUSE_RHI_VOLK=1)
    target_link_libraries(${target} PUBLIC ${CMAKE_DL_LIBS})

    # Drop the link-time loader. Renderer/CMakeLists.txt links Vulkan::Vulkan PUBLIC; volk replaces it.
    foreach(_prop LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
        get_target_property(_libs ${target} ${_prop})
        if(_libs)
            list(REMOVE_ITEM _libs Vulkan::Vulkan)
            set_property(TARGET ${target} PROPERTY ${_prop} "${_libs}")
        endif()
    endforeach()

    file(STRINGS "${_volk_dir}/VERSION" _volk_version REGEX "^version=")
    set_property(DIRECTORY "${_srcdir}" APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_volk_dir}/VERSION")
    message(STATUS "FUSE: ${target} loads Vulkan through vendored volk (${_volk_version}; headers ${_vk_inc})")
endfunction()

function(fuse_volk_auto_init target)
    cmake_parse_arguments(ARG "DISABLED" "SOURCE;SYMBOL" "" ${ARGN})
    if(NOT ARG_SOURCE OR NOT ARG_SYMBOL)
        message(FATAL_ERROR "fuse_volk_auto_init(${target}): SOURCE and SYMBOL are required")
    endif()
    target_sources(${target} PRIVATE "${ARG_SOURCE}")
    if(ARG_DISABLED)
        set_source_files_properties("${ARG_SOURCE}" TARGET_DIRECTORY ${target}
                                    PROPERTIES COMPILE_DEFINITIONS FUSE_RHI_VOLK_NO_AUTO_INIT=1)
        message(STATUS "FUSE: ${target} volk auto-init disabled (FUSE_RHI_VOLK_AUTO_INIT=OFF): explicit vkloader::initialize()")
        return()
    endif()
    # C symbol decoration: a leading underscore on Mach-O and 32-bit Windows (i686 MinGW / x86 MSVC).
    set(_sym "${ARG_SYMBOL}")
    if(APPLE OR (WIN32 AND CMAKE_SIZEOF_VOID_P EQUAL 4))
        set(_sym "_${ARG_SYMBOL}")
    endif()
    if(MSVC)
        set(_force "LINKER:/INCLUDE:${_sym}")
    else()
        set(_force "LINKER:-u,${_sym}")
    endif()
    target_link_options(${target} INTERFACE
        "$<$<NOT:$<BOOL:$<TARGET_PROPERTY:FUSE_RHI_VOLK_NO_AUTO_INIT>>>:${_force}>")
endfunction()
