# Frame integration (docs/unification/RENDERER-EXECUTION.md, "Frame integration"): FrameComposer, one complete
# deferred frame on render graph v2 from the finished packages' public APIs. Owned by the frame integration
# package; other packages must not edit this file.
#
#   fuse_frame          STATIC  FrameComposer (include/fuse/renderer/frame/**, src/frame/**) over the WP-1.x .. 9.2
#                               packages (incl. 2.3 forward, 4.4 frame generation, 7.1 light tree, 7.2 ReSTIR) + the
#                               composer's own kernel (frame.sky / .aerial / .gather / .resolve / .shadow_pack /
#                               .restir / .reflect)
#   fc_frame kernel     SPIR-V  Slang (primary) + GLSL twin, embedded in fuse_frame (shaders/frame/)
#   fuse_rp_frame_*     ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

set(_fuse_frame_kernels "FRAME|Frame|fc_frame.comp|fc_frame.slang")

# Script mode (build step): embed the kernel's SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-DFRAME_SLANG=<spv>] [-DFRAME_GLSL=<spv>] -P rp_frame.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_frame.cmake from shaders/frame/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_frame_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_FRAME_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_frame_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kFc${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_frame_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_frame_inc "${_fuse_frame_root}/include/fuse/renderer/frame")
set(_fuse_frame_src "${_fuse_frame_root}/src/frame")
set(_fuse_frame_shd "${_fuse_frame_root}/shaders/frame")
set(_fuse_frame_shd_root "${_fuse_frame_root}/shaders")
set(_fuse_frame_common_inc "${_fuse_frame_root}/shaders/common")

file(GLOB _fuse_frame_shader_files CONFIGURE_DEPENDS "${_fuse_frame_shd}/*")
add_library(fuse_frame STATIC
    ${_fuse_frame_src}/frame_composer.cpp
    ${_fuse_frame_inc}/frame_types.hpp
    ${_fuse_frame_inc}/frame_composer.hpp
    ${_fuse_frame_shader_files}
)
set_source_files_properties(${_fuse_frame_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_frame PUBLIC
    fuse_gpu_scene fuse_culling fuse_visbuffer fuse_material_resolve fuse_temporal fuse_vsm fuse_vsm_raster fuse_rt
    fuse_rt_effects fuse_denoise fuse_ddgi_gpu fuse_lighting_gpu fuse_ssfx_gpu fuse_atmosphere_gpu fuse_volumetric_gpu
    fuse_clouds_gpu fuse_gsplat fuse_fsr3 fuse_post_gpu fuse_light_tree fuse_restir fuse_forward fuse_framegen)
fuse_apply_cxx23(fuse_frame)

# Kernel, embedded into the library (Slang primary, GLSL twin; -fp-mode precise / `precise`).
set(_fuse_frame_gen "${CMAKE_CURRENT_BINARY_DIR}/frame_gen")
set(_fuse_frame_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/frame")
file(MAKE_DIRECTORY "${_fuse_frame_gen}" "${_fuse_frame_spv}")
set(_fuse_frame_header "${_fuse_frame_gen}/frame_spv.h")
add_custom_target(fuse_frame_kernels)
set(_fuse_frame_embed_args "")
set(_fuse_frame_embed_deps "")
file(GLOB _fuse_frame_glsl_includes "${_fuse_frame_shd}/*.glsl" "${_fuse_frame_shd_root}/atmosphere/at_sample.glsl")

foreach(_row IN LISTS _fuse_frame_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_frame_kernels
            SOURCES "${_fuse_frame_shd}/${_slang}"
            STAGE compute
            SUFFIX ".fc_${_suffix}"
            INCLUDE_DIRS "${_fuse_frame_shd}" "${_fuse_frame_shd_root}"
            # 39001: the bindless arrays alias one binding on purpose.
            FLAGS -warnings-disable 39001 -fp-mode precise
            OUTPUT_DIR "${_fuse_frame_spv}"
            OUTPUT_VAR _fuse_frame_out)
        if(_fuse_frame_out)
            list(APPEND _fuse_frame_embed_args "-D${_key}_SLANG=${_fuse_frame_out}")
            list(APPEND _fuse_frame_embed_deps "${_fuse_frame_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_frame_spv}/fc_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_frame_common_inc}"
                          "-I${_fuse_frame_shd_root}" "-I${_fuse_frame_shd}" "${_fuse_frame_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_frame_shd}/${_glsl}" ${_fuse_frame_glsl_includes} "${_fuse_frame_common_inc}/bindless.glsl"
            COMMENT "glslangValidator ${_glsl} (fc_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_frame_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_frame_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_frame_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_frame_header}" ${_fuse_frame_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_frame_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the frame composer kernel's SPIR-V"
    VERBATIM)
add_custom_target(fuse_frame_header DEPENDS "${_fuse_frame_header}")
add_dependencies(fuse_frame_header fuse_frame_kernels)
add_dependencies(fuse_frame fuse_frame_header)
target_include_directories(fuse_frame PRIVATE "${_fuse_frame_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_frame_tests_dir "${_fuse_frame_root}/tests")

# --- CPU gates (layouts vs the kernel sources, the CPU reference, settings / API; also in the stub tree) --------
add_executable(fuse_rp_frame_cpu ${_fuse_frame_tests_dir}/test_rp_frame_cpu.cpp)
target_link_libraries(fuse_rp_frame_cpu PRIVATE fuse_frame)
target_compile_definitions(fuse_rp_frame_cpu PRIVATE FUSE_RP_FRAME_SHADER_DIR="${_fuse_frame_shd}")
fuse_apply_cxx23(fuse_rp_frame_cpu)
foreach(_suite layout reference api)
    add_test(NAME fuse_rp_frame_${_suite} COMMAND fuse_rp_frame_cpu ${_suite})
    set_tests_properties(fuse_rp_frame_${_suite} PROPERTIES LABELS "gate;renderer;frame" TIMEOUT 300)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------------------
# Goldens: Tests/golden/renderer/frame_composer_t0.png / _t2.png (the WP-0.7 GoldenStore, FUSE_UPDATE_GOLDENS=1
# rewrites them). Tolerance: see test_rp_frame.cpp (kGoldenSpec).
add_executable(fuse_rp_frame ${_fuse_frame_tests_dir}/test_rp_frame.cpp)
target_link_libraries(fuse_rp_frame PRIVATE fuse_frame fuse_rp_harness)
target_compile_definitions(fuse_rp_frame PRIVATE
    FUSE_RP_GOLDEN_DIR="${FUSE_RP_GOLDEN_DIR}"
    FUSE_RP_HARNESS_ARTIFACT_DIR="${FUSE_RP_HARNESS_ARTIFACT_DIR}")
fuse_apply_cxx23(fuse_rp_frame)

set(_fuse_frame_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_frame_vk_tests "")
foreach(_case "full;t0;auto" "full;t2;auto" "toggles;t0;auto" "toggles;t2;auto" "determinism;t0;auto"
              "determinism;t2;auto" "zero_alloc;t0;auto" "zero_alloc;t2;auto" "golden;t0;auto" "golden;t2;auto"
              "parity;t0;slang" "parity;t2;slang" "parity;t0;glsl" "parity;t2;glsl" "full;t2;glsl")
    list(GET _case 0 _mode)
    list(GET _case 1 _tier)
    list(GET _case 2 _lang)
    set(_name "fuse_rp_frame_vk_${_mode}_${_tier}")
    if(NOT _lang STREQUAL "auto")
        set(_name "${_name}_${_lang}")
    endif()
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name} COMMAND "${_fuse_frame_lock}" "$<TARGET_FILE:fuse_rp_frame>" --mode ${_mode} --tier ${_tier}
                                       --language ${_lang})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_frame --mode ${_mode} --tier ${_tier} --language ${_lang})
    endif()
    list(APPEND _fuse_frame_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_frame_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 1800
    LABELS "gate;vulkan;renderer;frame")
