# RL-5.5 (docs/plans/FUSE_REMIX_PORT_PLAN.md §5.5, RL-5.5 row): the in-tree radiance denoiser, extending WP-6.4
# additively (rp_wp64.cmake / fuse_denoise are untouched). Owned by RL-5.5.
#
#   fuse_radiance_denoise  STATIC  RadianceDenoiser (rdn.* passes on render graph v2), the single-source core
#                                  (shaders/denoise/rdn_core.h; C++ dialect rdn_kernel.hpp) and the CPU reference chain
#                                  RdnReference (include/fuse/renderer/denoise/radiance_denois*.hpp, rdn_kernel.hpp,
#                                  src/denoise/radiance_*.cpp)
#   rdn kernel             SPIR-V  Slang (primary, -fp-mode precise) + GLSL twin of shaders/denoise/rdn.{slang,comp},
#                                  embedded (rdn_spv.h)
#   fuse_rp_rdn_*          ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Script mode (build step): embed the kernel's SPIR-V.
#   cmake -DOUT=<header> [-DSLANG_SPV=<spv>] [-DGLSL_SPV=<spv>] -P rp_rl55.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_rl55.cmake from shaders/denoise/rdn.*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_spv "${${_lang}_SPV}")
        if(_spv AND EXISTS "${_spv}")
            string(APPEND _text "#define FUSE_RDN_${_lang} 1\n")
            file(READ "${_spv}" _hex HEX)
            string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
            string(APPEND _text "alignas(4) static const std::uint32_t kRdn${_suffix}Spv[] = {${_words}};\n")
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_rl55_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_rl55_inc "${_fuse_rl55_root}/include/fuse/renderer/denoise")
set(_fuse_rl55_src "${_fuse_rl55_root}/src/denoise")
set(_fuse_rl55_shd "${_fuse_rl55_root}/shaders/denoise")

set(_fuse_rl55_shader_files "${_fuse_rl55_shd}/rdn_core.h" "${_fuse_rl55_shd}/rdn.comp" "${_fuse_rl55_shd}/rdn.slang")
add_library(fuse_radiance_denoise STATIC
    ${_fuse_rl55_src}/radiance_reference.cpp
    ${_fuse_rl55_src}/radiance_denoiser.cpp
    ${_fuse_rl55_src}/rdn_synthetic.cpp
    ${_fuse_rl55_inc}/rdn_synthetic.hpp
    ${_fuse_rl55_inc}/rdn_kernel.hpp
    ${_fuse_rl55_inc}/radiance_denoise.hpp
    ${_fuse_rl55_inc}/radiance_denoiser.hpp
    ${_fuse_rl55_shader_files})
set_source_files_properties(${_fuse_rl55_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_radiance_denoise PUBLIC fuse_rhi)
# rdn_kernel.hpp includes the single-source core from the shader directory.
target_include_directories(fuse_radiance_denoise PUBLIC "${_fuse_rl55_shd}")
fuse_apply_cxx23(fuse_radiance_denoise)

set(_fuse_rl55_gen "${CMAKE_CURRENT_BINARY_DIR}/rdn_gen")
set(_fuse_rl55_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/rdn")
file(MAKE_DIRECTORY "${_fuse_rl55_gen}" "${_fuse_rl55_spv}")
set(_fuse_rl55_header "${_fuse_rl55_gen}/rdn_spv.h")
add_custom_target(fuse_radiance_denoise_kernels)
set(_fuse_rl55_args "")
set(_fuse_rl55_deps "")
if(COMMAND fuse_add_slang_shaders)
    fuse_add_slang_shaders(fuse_radiance_denoise_kernels
        SOURCES "${_fuse_rl55_shd}/rdn.slang"
        STAGE compute
        SUFFIX ".rdn"
        INCLUDE_DIRS "${_fuse_rl55_shd}"
        FLAGS -fp-mode precise
        OUTPUT_DIR "${_fuse_rl55_spv}"
        OUTPUT_VAR _fuse_rl55_slang_out)
    if(_fuse_rl55_slang_out)
        list(APPEND _fuse_rl55_args "-DSLANG_SPV=${_fuse_rl55_slang_out}")
        list(APPEND _fuse_rl55_deps "${_fuse_rl55_slang_out}")
    endif()
endif()
if(FUSE_GLSLANG_VALIDATOR)
    set(_out "${_fuse_rl55_spv}/rdn.glsl.spv")
    set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_rl55_shd}"
                      "${_fuse_rl55_shd}/rdn.comp" -o "${_out}")
    if(FUSE_SPIRV_VAL)
        list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
    endif()
    add_custom_command(OUTPUT "${_out}" ${_cmds}
        DEPENDS "${_fuse_rl55_shd}/rdn.comp" "${_fuse_rl55_shd}/rdn_core.h"
        COMMENT "glslangValidator rdn.comp (RL-5.5 radiance denoiser, GLSL twin)"
        VERBATIM)
    list(APPEND _fuse_rl55_args "-DGLSL_SPV=${_out}")
    list(APPEND _fuse_rl55_deps "${_out}")
endif()
add_custom_command(OUTPUT "${_fuse_rl55_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_rl55_header}" ${_fuse_rl55_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_rl55_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the RL-5.5 radiance denoiser's SPIR-V"
    VERBATIM)
add_custom_target(fuse_radiance_denoise_header DEPENDS "${_fuse_rl55_header}")
add_dependencies(fuse_radiance_denoise_header fuse_radiance_denoise_kernels)
add_dependencies(fuse_radiance_denoise fuse_radiance_denoise_header)
target_include_directories(fuse_radiance_denoise PRIVATE "${_fuse_rl55_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_rl55_tests_dir "${_fuse_rl55_root}/tests")

# --- CPU gates (also in the stub tree) -----------------------------------------------------------------------------
add_executable(fuse_rp_rdn_cpu ${_fuse_rl55_tests_dir}/test_rp_rdn_cpu.cpp)
target_link_libraries(fuse_rp_rdn_cpu PRIVATE fuse_radiance_denoise)
target_compile_definitions(fuse_rp_rdn_cpu PRIVATE FUSE_RP_RDN_SHADER_DIR="${_fuse_rl55_shd}")
fuse_apply_cxx23(fuse_rp_rdn_cpu)
foreach(_suite layout backends quality ghosting disocclusion asvgf firefly determinism zero_alloc)
    add_test(NAME fuse_rp_rdn_${_suite} COMMAND fuse_rp_rdn_cpu ${_suite})
    set_tests_properties(fuse_rp_rdn_${_suite} PROPERTIES LABELS "gate;renderer;denoise" TIMEOUT 900)
endforeach()

# --- Lavapipe gates --------------------------------------------------------------------------------------------------
add_executable(fuse_rp_rdn ${_fuse_rl55_tests_dir}/test_rp_rdn.cpp)
target_link_libraries(fuse_rp_rdn PRIVATE fuse_radiance_denoise)
fuse_apply_cxx23(fuse_rp_rdn)
set(_fuse_rl55_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_rl55_vk_tests "")
foreach(_case "passes;set;slang" "passes;set;glsl" "passes;buffer;slang" "zero_alloc;set;slang")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    list(GET _case 2 _lang)
    set(_name "fuse_rp_rdn_vk_${_mode}_${_backend}_${_lang}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name} COMMAND "${_fuse_rl55_lock}" "$<TARGET_FILE:fuse_rp_rdn>" --mode ${_mode}
                                       --backend ${_backend} --language ${_lang})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_rdn --mode ${_mode} --backend ${_backend} --language ${_lang})
    endif()
    list(APPEND _fuse_rl55_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_rl55_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;denoise")
