# WP-2.1 (docs/unification/RENDERER-EXECUTION.md): GPU clustered light assignment + deferred shading.
# Owned by WP-2.1; other packages must not edit this file.
#
#   fuse_lighting_gpu   STATIC  ClusteredLighting (light.bounds / bin / cull / scan / compact into GPU
#                               buffers from the GPU scene's light table, light.shade over the WP-1.5
#                               G-buffer) + CPU references (clustered_gpu_kernel.hpp shade kernel, oracle
#                               adapters) (include/fuse/renderer/lighting/gpu/**, src/lighting/gpu/**)
#   lc_* kernels        SPIR-V  Slang (primary) + GLSL twins, embedded in fuse_lighting_gpu
#   fuse_rp_clustered_gpu_*  ctest  CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source
set(_fuse_wp21_kernels
    "BOUNDS|Bounds|lc_bounds.comp|lc_bounds.slang"
    "BIN|Bin|lc_bin.comp|lc_bin.slang"
    "CULL|Cull|lc_cull.comp|lc_cull.slang"
    "SCAN|Scan|lc_scan.comp|lc_scan.slang"
    "COMPACT|Compact|lc_compact.comp|lc_compact.slang"
    "SHADE|Shade|lc_shade.comp|lc_shade.slang")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp21.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp21.cmake from shaders/lighting/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp21_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_LIGHTING_GPU_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp21_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kLc${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp21_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp21_inc "${_fuse_wp21_root}/include/fuse/renderer/lighting/gpu")
set(_fuse_wp21_src "${_fuse_wp21_root}/src/lighting/gpu")
set(_fuse_wp21_shd "${_fuse_wp21_root}/shaders/lighting")
set(_fuse_wp21_scene_inc "${_fuse_wp21_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp21_common_inc "${_fuse_wp21_root}/shaders/common")

file(GLOB _fuse_wp21_shader_files CONFIGURE_DEPENDS "${_fuse_wp21_shd}/*")
add_library(fuse_lighting_gpu STATIC
    ${_fuse_wp21_src}/clustered_lighting.cpp
    ${_fuse_wp21_src}/clustered_gpu_reference.cpp
    ${_fuse_wp21_inc}/clustered_gpu_types.hpp
    ${_fuse_wp21_inc}/clustered_gpu_kernel.hpp
    ${_fuse_wp21_inc}/clustered_gpu_reference.hpp
    ${_fuse_wp21_inc}/clustered_lighting.hpp
    ${_fuse_wp21_shader_files}
)
set_source_files_properties(${_fuse_wp21_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_lighting_gpu PUBLIC fuse_material_resolve fuse_gpu_scene)
fuse_apply_cxx23(fuse_lighting_gpu)

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the
# GLSL twins keep the lighting available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
# Slang: -fp-mode precise; GLSL: `precise` (the cluster AABBs / light spheres must be the oracle's bits).
set(_fuse_wp21_gen "${CMAKE_CURRENT_BINARY_DIR}/lighting_gpu_gen")
set(_fuse_wp21_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/lighting")
file(MAKE_DIRECTORY "${_fuse_wp21_gen}" "${_fuse_wp21_spv}")
set(_fuse_wp21_header "${_fuse_wp21_gen}/lighting_gpu_spv.h")
add_custom_target(fuse_lighting_gpu_kernels)
set(_fuse_wp21_embed_args "")
set(_fuse_wp21_embed_deps "")
file(GLOB _fuse_wp21_glsl_includes "${_fuse_wp21_shd}/*.glsl")

foreach(_row IN LISTS _fuse_wp21_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_lighting_gpu_kernels
            SOURCES "${_fuse_wp21_shd}/${_slang}"
            STAGE compute
            SUFFIX ".lc_${_suffix}"
            INCLUDE_DIRS "${_fuse_wp21_scene_inc}" "${_fuse_wp21_shd}"
            # 39001: the bindless arrays alias one binding on purpose.
            FLAGS -warnings-disable 39001 -fp-mode precise
            OUTPUT_DIR "${_fuse_wp21_spv}"
            OUTPUT_VAR _fuse_wp21_out)
        if(_fuse_wp21_out)
            list(APPEND _fuse_wp21_embed_args "-D${_key}_SLANG=${_fuse_wp21_out}")
            list(APPEND _fuse_wp21_embed_deps "${_fuse_wp21_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp21_spv}/lc_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp21_common_inc}"
                          "-I${_fuse_wp21_scene_inc}" "-I${_fuse_wp21_shd}" "${_fuse_wp21_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp21_shd}/${_glsl}" ${_fuse_wp21_glsl_includes} "${_fuse_wp21_scene_inc}/gpu_scene.glsl"
                    "${_fuse_wp21_common_inc}/bindless.glsl"
            COMMENT "glslangValidator ${_glsl} (lc_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp21_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp21_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp21_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp21_header}" ${_fuse_wp21_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp21_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the clustered-lighting kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_lighting_gpu_header DEPENDS "${_fuse_wp21_header}")
add_dependencies(fuse_lighting_gpu_header fuse_lighting_gpu_kernels)
add_dependencies(fuse_lighting_gpu fuse_lighting_gpu_header)
target_include_directories(fuse_lighting_gpu PRIVATE "${_fuse_wp21_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp21_tests_dir "${_fuse_wp21_root}/tests")

# --- CPU gates (reference kernels and oracle adapters; also run in the stub tree) -----------------
add_executable(fuse_rp_clustered_gpu_cpu ${_fuse_wp21_tests_dir}/test_rp_clustered_gpu_cpu.cpp)
target_link_libraries(fuse_rp_clustered_gpu_cpu PRIVATE fuse_lighting_gpu)
fuse_apply_cxx23(fuse_rp_clustered_gpu_cpu)
foreach(_suite layout oracle brdf shade api)
    add_test(NAME fuse_rp_clustered_gpu_${_suite} COMMAND fuse_rp_clustered_gpu_cpu ${_suite})
    set_tests_properties(fuse_rp_clustered_gpu_${_suite} PROPERTIES LABELS "gate;renderer;lighting" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_clustered_gpu ${_fuse_wp21_tests_dir}/test_rp_clustered_gpu.cpp)
target_link_libraries(fuse_rp_clustered_gpu PRIVATE fuse_lighting_gpu)
fuse_apply_cxx23(fuse_rp_clustered_gpu)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp21_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp21_vk_tests "")
foreach(_case "parity_4096;set" "parity_4096;buffer" "overflow;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_clustered_gpu_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp21_lock}" "$<TARGET_FILE:fuse_rp_clustered_gpu>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_clustered_gpu --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp21_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp21_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;lighting")
