# WP-1.1 (docs/unification/RENDERER-EXECUTION.md): GPU scene.
# Owned by WP-1.1; other packages must not edit this file.
#
#   fuse_gpu_scene        STATIC  persistent BDA scene tables + CPU mirror + dirty-range delta upload
#                                 through UploadQueue, bindless handles, render-graph import
#                                 (include/fuse/renderer/gpu_scene/**, src/gpu_scene/**)
#   fuse_gpu_scene_ecs    STATIC  read-only ECS extraction adapter (gpu_scene_extract kernel)
#   gpu_scene_scatter     SPIR-V  scatter-upload kernel (Slang + GLSL twin), embedded in fuse_gpu_scene
#   gpu_scene_readback    SPIR-V  exit-test kernel, Slang (primary) + GLSL twin
#   fuse_rp_gpu_scene_*   ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Script mode (build step): embed the scatter kernel SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-DSLANG_SPV=<spv>] [-DGLSL_SPV=<spv>] -P rp_wp11.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp11.cmake from gpu_scene_scatter.{slang,comp}.\n")
    string(APPEND _text "// Do not edit.\n#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        set(_spv "${${_lang}_SPV}")
        if(_spv AND EXISTS "${_spv}")
            file(READ "${_spv}" _hex HEX)
            string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
            if(_lang STREQUAL "SLANG")
                set(_name kGpuSceneScatterSlangSpv)
            else()
                set(_name kGpuSceneScatterGlslSpv)
            endif()
            string(APPEND _text "#define FUSE_GPU_SCENE_SCATTER_${_lang} 1\n")
            string(APPEND _text "alignas(4) static const std::uint32_t ${_name}[] = {${_words}};\n")
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

set(_fuse_wp11_inc "${CMAKE_CURRENT_LIST_DIR}/../include/fuse/renderer/gpu_scene")
set(_fuse_wp11_src "${CMAKE_CURRENT_LIST_DIR}/../src/gpu_scene")
get_filename_component(_fuse_wp11_inc "${_fuse_wp11_inc}" ABSOLUTE)
get_filename_component(_fuse_wp11_src "${_fuse_wp11_src}" ABSOLUTE)

add_library(fuse_gpu_scene STATIC
    ${_fuse_wp11_src}/scene_table.cpp
    ${_fuse_wp11_src}/gpu_scene.cpp
    ${_fuse_wp11_src}/gpu_scene_meshlets.cpp
    ${_fuse_wp11_inc}/gpu_scene_types.hpp
    ${_fuse_wp11_inc}/scene_table.hpp
    ${_fuse_wp11_inc}/gpu_scene.hpp
    ${_fuse_wp11_inc}/gpu_scene_meshlets.hpp
    ${_fuse_wp11_inc}/gpu_scene.glsl
    ${_fuse_wp11_inc}/gpu_scene.slang
)
target_link_libraries(fuse_gpu_scene PUBLIC fuse_rhi fuse_geometry)
fuse_apply_cxx23(fuse_gpu_scene)

# Scatter-upload kernel, embedded into the library. Slang is the primary source (renderer plan §4,
# execution doc §8 decision 1a); the GLSL twin keeps scatter available when slangc is not
# (FUSE_SLANG=AUTO) and lets the tests check both. Neither toolchain: direct copies only.
set(_fuse_wp11_gen "${CMAKE_CURRENT_BINARY_DIR}/gpu_scene_gen")
set(_fuse_wp11_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/gpu_scene")
file(MAKE_DIRECTORY "${_fuse_wp11_gen}" "${_fuse_wp11_spv}")
set(_fuse_wp11_scatter_header "${_fuse_wp11_gen}/gpu_scene_scatter_spv.h")
add_custom_target(fuse_gpu_scene_kernels)
set(_fuse_wp11_embed_args "")
set(_fuse_wp11_embed_deps "")
if(COMMAND fuse_add_slang_shaders)
    fuse_add_slang_shaders(fuse_gpu_scene_kernels
        SOURCES "${_fuse_wp11_src}/shaders/gpu_scene_scatter.slang"
        STAGE compute
        OUTPUT_DIR "${_fuse_wp11_spv}"
        OUTPUT_VAR _fuse_wp11_scatter_slang)
    if(_fuse_wp11_scatter_slang)
        list(APPEND _fuse_wp11_embed_args "-DSLANG_SPV=${_fuse_wp11_scatter_slang}")
        list(APPEND _fuse_wp11_embed_deps "${_fuse_wp11_scatter_slang}")
    endif()
endif()
if(FUSE_GLSLANG_VALIDATOR)
    set(_src "${_fuse_wp11_src}/shaders/gpu_scene_scatter.comp")
    set(_out "${_fuse_wp11_spv}/gpu_scene_scatter.comp.spv")
    set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "${_src}" -o "${_out}")
    if(FUSE_SPIRV_VAL)
        list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
    endif()
    add_custom_command(OUTPUT "${_out}" ${_cmds} DEPENDS "${_src}"
        COMMENT "glslangValidator gpu_scene_scatter.comp -> SPIR-V (GLSL twin)" VERBATIM)
    list(APPEND _fuse_wp11_embed_args "-DGLSL_SPV=${_out}")
    list(APPEND _fuse_wp11_embed_deps "${_out}")
endif()
add_custom_command(OUTPUT "${_fuse_wp11_scatter_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp11_scatter_header}" ${_fuse_wp11_embed_args}
            -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp11_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the GPU scene scatter kernel SPIR-V"
    VERBATIM)
add_custom_target(fuse_gpu_scene_scatter_header DEPENDS "${_fuse_wp11_scatter_header}")
add_dependencies(fuse_gpu_scene_scatter_header fuse_gpu_scene_kernels)
add_dependencies(fuse_gpu_scene fuse_gpu_scene_scatter_header)
target_include_directories(fuse_gpu_scene PRIVATE "${_fuse_wp11_gen}")

add_library(fuse_gpu_scene_ecs STATIC
    ${_fuse_wp11_src}/gpu_scene_ecs.cpp
    ${_fuse_wp11_inc}/gpu_scene_ecs.hpp
    ${_fuse_wp11_inc}/gpu_scene_extract_kernel.hpp
)
target_link_libraries(fuse_gpu_scene_ecs PUBLIC fuse_gpu_scene fuse_ecs)
fuse_apply_cxx23(fuse_gpu_scene_ecs)

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

# --- CPU gates (CPU-only GpuScene mode; also run in the stub tree) ---------------------------------
set(_fuse_wp11_tests_dir "${CMAKE_CURRENT_LIST_DIR}/../tests")
add_executable(fuse_rp_gpu_scene_cpu ${_fuse_wp11_tests_dir}/test_rp_gpu_scene_cpu.cpp)
target_link_libraries(fuse_rp_gpu_scene_cpu PRIVATE fuse_gpu_scene_ecs)
fuse_apply_cxx23(fuse_rp_gpu_scene_cpu)
foreach(_suite table delta_scaling extract churn meshlets zero_alloc)
    add_test(NAME fuse_rp_gpu_scene_${_suite} COMMAND fuse_rp_gpu_scene_cpu ${_suite})
    set_tests_properties(fuse_rp_gpu_scene_${_suite} PROPERTIES LABELS "gate;renderer;gpu_scene" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_gpu_scene ${_fuse_wp11_tests_dir}/test_rp_gpu_scene.cpp)
target_link_libraries(fuse_rp_gpu_scene PRIVATE fuse_gpu_scene_ecs)
fuse_apply_cxx23(fuse_rp_gpu_scene)

# Readback kernel. Slang is the primary source (renderer plan §4, execution doc §8 decision 1a);
# the GLSL twin keeps the gate runnable when slangc is unavailable (FUSE_SLANG=AUTO) and, when both
# exist, the test runs both and requires identical output.
set(_fuse_wp11_out "${_fuse_wp11_spv}")
add_custom_target(fuse_rp_gpu_scene_shaders)
set(_fuse_wp11_defs "")
if(COMMAND fuse_add_slang_shaders)
    fuse_add_slang_shaders(fuse_rp_gpu_scene_shaders
        SOURCES "${_fuse_wp11_src}/shaders/gpu_scene_readback.slang"
        STAGE compute
        INCLUDE_DIRS "${_fuse_wp11_inc}"
        OUTPUT_DIR "${_fuse_wp11_out}"
        OUTPUT_VAR _fuse_wp11_slang_spv)
    if(_fuse_wp11_slang_spv)
        list(APPEND _fuse_wp11_defs FUSE_RP_GPU_SCENE_SLANG_SPV="${_fuse_wp11_slang_spv}")
    endif()
endif()
if(FUSE_GLSLANG_VALIDATOR)
    set(_glsl_src "${_fuse_wp11_src}/shaders/gpu_scene_readback.comp")
    set(_glsl_spv "${_fuse_wp11_out}/gpu_scene_readback.comp.spv")
    set(_bindless_inc "${CMAKE_CURRENT_LIST_DIR}/../shaders/common")
    get_filename_component(_bindless_inc "${_bindless_inc}" ABSOLUTE)
    set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_bindless_inc}" "-I${_fuse_wp11_inc}"
                      "${_glsl_src}" -o "${_glsl_spv}")
    if(FUSE_SPIRV_VAL)
        list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_glsl_spv}")
    endif()
    add_custom_command(OUTPUT "${_glsl_spv}" ${_cmds}
        DEPENDS "${_glsl_src}" "${_fuse_wp11_inc}/gpu_scene.glsl" "${_bindless_inc}/bindless.glsl"
        COMMENT "glslangValidator gpu_scene_readback.comp -> SPIR-V (GLSL twin)"
        VERBATIM)
    add_custom_target(fuse_rp_gpu_scene_glsl DEPENDS "${_glsl_spv}")
    add_dependencies(fuse_rp_gpu_scene_shaders fuse_rp_gpu_scene_glsl)
    list(APPEND _fuse_wp11_defs FUSE_RP_GPU_SCENE_GLSL_SPV="${_glsl_spv}")
endif()
add_dependencies(fuse_rp_gpu_scene fuse_rp_gpu_scene_shaders)
target_compile_definitions(fuse_rp_gpu_scene PRIVATE ${_fuse_wp11_defs})

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp11_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp11_vk_tests "")
foreach(_mode readback churn delta zero_alloc)
    foreach(_backend set buffer)
        set(_name "fuse_rp_gpu_scene_vk_${_mode}_${_backend}")
        if(FUSE_VULKAN_BACKEND)
            add_test(NAME ${_name}
                     COMMAND "${_fuse_wp11_lock}" "$<TARGET_FILE:fuse_rp_gpu_scene>" --mode ${_mode} --backend ${_backend})
        else()
            add_test(NAME ${_name} COMMAND fuse_rp_gpu_scene --mode ${_mode} --backend ${_backend})
        endif()
        list(APPEND _fuse_wp11_vk_tests ${_name})
    endforeach()
endforeach()
set_tests_properties(${_fuse_wp11_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;gpu_scene")
