# WP-3.1 (docs/unification/RENDERER-EXECUTION.md): virtual shadow map core.
# Owned by WP-3.1; other packages must not edit this file.
#
#   fuse_vsm            STATIC  VirtualShadowMap (vsm.reset / init / mark / bounds_clear / invalidate / update /
#                               alloc / render / clear as RG v2 compute passes), VsmClipmap placement and the CPU
#                               references (include/fuse/renderer/shadow/vsm/**, src/shadow/vsm/**)
#   vsm_* kernels       SPIR-V  Slang (primary) + GLSL twins (src/shadow/vsm/shaders/*), embedded in fuse_vsm
#   core_logic/vsm_pages        page model (VsmPagePool): header-only, CBMC dialect; property tests, lint, BMC
#   fuse_core_logic_vsm_pages_* / fuse_core_logic_bmc_native_vsm_pages / fuse_core_logic_cbmc_vsm_pages
#   fuse_rp_vsm_*       ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source
set(_fuse_wp31_kernels
    "MARK|Mark|vsm_mark.comp|vsm_mark.slang"
    "INVALIDATE|Invalidate|vsm_invalidate.comp|vsm_invalidate.slang"
    "UPDATE|Update|vsm_update.comp|vsm_update.slang"
    "ALLOC|Alloc|vsm_alloc.comp|vsm_alloc.slang"
    "RENDER|Render|vsm_render.comp|vsm_render.slang"
    "CLEAR|Clear|vsm_clear.comp|vsm_clear.slang")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp31.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp31.cmake from src/shadow/vsm/shaders/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp31_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_VSM_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp31_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kVsm${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp31_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp31_inc "${_fuse_wp31_root}/include/fuse/renderer/shadow/vsm")
set(_fuse_wp31_src "${_fuse_wp31_root}/src/shadow/vsm")
set(_fuse_wp31_shd "${_fuse_wp31_src}/shaders")
set(_fuse_wp31_scene_inc "${_fuse_wp31_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp31_common_inc "${_fuse_wp31_root}/shaders/common")
set(_fuse_wp31_cl "${_fuse_wp31_root}/core_logic")
set(_fuse_wp31_cl_vsm "${_fuse_wp31_cl}/vsm_pages")

file(GLOB _fuse_wp31_shader_files CONFIGURE_DEPENDS "${_fuse_wp31_shd}/*" "${_fuse_wp31_inc}/*.glsl" "${_fuse_wp31_inc}/*.slang")
add_library(fuse_vsm STATIC
    ${_fuse_wp31_src}/vsm_clipmap.cpp
    ${_fuse_wp31_src}/virtual_shadow_map.cpp
    ${_fuse_wp31_inc}/vsm_types.hpp
    ${_fuse_wp31_inc}/vsm_kernel.hpp
    ${_fuse_wp31_inc}/vsm_clipmap.hpp
    ${_fuse_wp31_inc}/virtual_shadow_map.hpp
    ${_fuse_wp31_cl_vsm}/include/fuse/core_logic/vsm_pages.hpp
    ${_fuse_wp31_shader_files}
)
set_source_files_properties(${_fuse_wp31_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_include_directories(fuse_vsm PUBLIC "${_fuse_wp31_cl_vsm}/include")
target_link_libraries(fuse_vsm PUBLIC fuse_gpu_scene fuse_core_logic)
fuse_apply_cxx23(fuse_vsm)
# The CPU reference must round like the kernels (no multiply-add contraction).
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(fuse_vsm PUBLIC -ffp-contract=off)
endif()

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the
# GLSL twins keep the VSM available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
# Slang: -fp-mode precise; GLSL: `precise` (the request bits must be the CPU reference's bits).
set(_fuse_wp31_gen "${CMAKE_CURRENT_BINARY_DIR}/vsm_gen")
set(_fuse_wp31_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/shadow_vsm_core")
file(MAKE_DIRECTORY "${_fuse_wp31_gen}" "${_fuse_wp31_spv}")
set(_fuse_wp31_header "${_fuse_wp31_gen}/vsm_spv.h")
add_custom_target(fuse_vsm_kernels)
set(_fuse_wp31_embed_args "")
set(_fuse_wp31_embed_deps "")
file(GLOB _fuse_wp31_includes "${_fuse_wp31_shd}/*.glsl" "${_fuse_wp31_inc}/*.glsl")

foreach(_row IN LISTS _fuse_wp31_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_vsm_kernels
            SOURCES "${_fuse_wp31_shd}/${_slang}"
            STAGE compute
            SUFFIX ".vsm_${_suffix}"
            INCLUDE_DIRS "${_fuse_wp31_scene_inc}" "${_fuse_wp31_inc}" "${_fuse_wp31_shd}"
            # 39001: the bindless arrays alias one binding on purpose.
            FLAGS -warnings-disable 39001 -fp-mode precise
            OUTPUT_DIR "${_fuse_wp31_spv}"
            OUTPUT_VAR _fuse_wp31_out)
        if(_fuse_wp31_out)
            list(APPEND _fuse_wp31_embed_args "-D${_key}_SLANG=${_fuse_wp31_out}")
            list(APPEND _fuse_wp31_embed_deps "${_fuse_wp31_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp31_spv}/vsm_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp31_common_inc}"
                          "-I${_fuse_wp31_scene_inc}" "-I${_fuse_wp31_inc}" "-I${_fuse_wp31_shd}" "${_fuse_wp31_shd}/${_glsl}"
                          -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp31_shd}/${_glsl}" ${_fuse_wp31_includes} "${_fuse_wp31_scene_inc}/gpu_scene.glsl"
                    "${_fuse_wp31_common_inc}/bindless.glsl"
            COMMENT "glslangValidator ${_glsl} (vsm_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp31_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp31_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp31_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp31_header}" ${_fuse_wp31_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp31_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the VSM kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_vsm_header DEPENDS "${_fuse_wp31_header}")
add_dependencies(fuse_vsm_header fuse_vsm_kernels)
add_dependencies(fuse_vsm fuse_vsm_header)
target_include_directories(fuse_vsm PRIVATE "${_fuse_wp31_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

# --- core_logic/vsm_pages: the page model (same gates as the WP-0.8 cores) ---------------------------
set(_fuse_wp31_cl_warn "")
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
    set(_fuse_wp31_cl_warn -Wall -Wextra -Wshadow -Wconversion -Wsign-conversion)
endif()
set(_fuse_wp31_cl_test_src "${_fuse_wp31_cl_vsm}/tests/test_core_logic_vsm_pages.cpp")
add_executable(fuse_core_logic_vsm_pages_tests ${_fuse_wp31_cl_test_src})
target_include_directories(fuse_core_logic_vsm_pages_tests PRIVATE "${_fuse_wp31_cl_vsm}/include" "${_fuse_wp31_cl}/include")
target_compile_features(fuse_core_logic_vsm_pages_tests PRIVATE cxx_std_17)
target_compile_options(fuse_core_logic_vsm_pages_tests PRIVATE ${_fuse_wp31_cl_warn})
foreach(_suite slots model props big errors)
    add_test(NAME fuse_core_logic_vsm_pages_${_suite} COMMAND fuse_core_logic_vsm_pages_tests ${_suite})
    set_tests_properties(fuse_core_logic_vsm_pages_${_suite} PROPERTIES LABELS "gate;core_logic;prism;renderer;vsm" TIMEOUT 300)
endforeach()

# Lint: the page model and its harness include only <stdint.h>/<stddef.h>/core_logic headers.
add_test(NAME fuse_core_logic_vsm_pages_no_vulkan
    COMMAND ${CMAKE_COMMAND} -DCL_DIR=${_fuse_wp31_cl_vsm} -P ${_fuse_wp31_cl}/tools/check_includes.cmake)
set_tests_properties(fuse_core_logic_vsm_pages_no_vulkan PROPERTIES LABELS "gate;core_logic;prism;lint;vsm")

# BMC harness, native smoke (PRNG-driven nondet, same assertions).
add_executable(fuse_core_logic_bmc_vsm_pages "${_fuse_wp31_cl_vsm}/bmc/bmc_vsm_pages.cpp")
target_include_directories(fuse_core_logic_bmc_vsm_pages PRIVATE "${_fuse_wp31_cl_vsm}/include" "${_fuse_wp31_cl}/include"
                                                                 "${_fuse_wp31_cl}/bmc")
target_compile_options(fuse_core_logic_bmc_vsm_pages PRIVATE ${_fuse_wp31_cl_warn})
add_test(NAME fuse_core_logic_bmc_native_vsm_pages COMMAND fuse_core_logic_bmc_vsm_pages 20000)
set_tests_properties(fuse_core_logic_bmc_native_vsm_pages PROPERTIES LABELS "gate;core_logic;prism;bmc;vsm" TIMEOUT 300)

# CBMC (registered with the WP-0.8 switch: DISABLED unless -DFUSE_CORE_LOGIC_CBMC=ON).
if(FUSE_CBMC_EXECUTABLE)
    add_test(NAME fuse_core_logic_cbmc_vsm_pages
        COMMAND ${FUSE_CBMC_EXECUTABLE} --cpp11 -I${_fuse_wp31_cl_vsm}/include -I${_fuse_wp31_cl}/include -I${_fuse_wp31_cl}/bmc
                --unwinding-assertions --bounds-check --pointer-check --div-by-zero-check --signed-overflow-check
                --undefined-shift-check -DBMC_STEPS=2 --unwind 20 ${_fuse_wp31_cl_vsm}/bmc/bmc_vsm_pages.cpp)
    set_tests_properties(fuse_core_logic_cbmc_vsm_pages PROPERTIES LABELS "core_logic;prism;bmc;slow;vsm" TIMEOUT 3600)
    if(NOT FUSE_CORE_LOGIC_CBMC)
        set_tests_properties(fuse_core_logic_cbmc_vsm_pages PROPERTIES DISABLED TRUE)
    endif()
endif()

# ASan + UBSan build of the property tests (WP-0.8 probe result; skipped under the fuse-asan preset,
# where every target is instrumented anyway).
if(FUSE_CORE_LOGIC_SAN_OK AND "${FUSE_SANITIZE}" STREQUAL "")
    set(_san -fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer)
    add_executable(fuse_core_logic_vsm_pages_tests_san ${_fuse_wp31_cl_test_src})
    target_include_directories(fuse_core_logic_vsm_pages_tests_san PRIVATE "${_fuse_wp31_cl_vsm}/include" "${_fuse_wp31_cl}/include")
    target_compile_features(fuse_core_logic_vsm_pages_tests_san PRIVATE cxx_std_17)
    target_compile_options(fuse_core_logic_vsm_pages_tests_san PRIVATE ${_san} -O1 -g)
    target_link_options(fuse_core_logic_vsm_pages_tests_san PRIVATE ${_san})
    add_test(NAME fuse_core_logic_vsm_pages_sanitize COMMAND fuse_core_logic_vsm_pages_tests_san all)
    set_tests_properties(fuse_core_logic_vsm_pages_sanitize PROPERTIES LABELS "gate;core_logic;prism;sanitize;vsm"
        TIMEOUT 600 ENVIRONMENT "ASAN_OPTIONS=detect_leaks=1:abort_on_error=1;UBSAN_OPTIONS=print_stacktrace=1")
endif()

set(_fuse_wp31_tests_dir "${_fuse_wp31_root}/tests")

# --- CPU gates (clipmap placement, reference kernels vs brute force, model wiring; stub-safe) ------
add_executable(fuse_rp_vsm_cpu ${_fuse_wp31_tests_dir}/test_rp_vsm_cpu.cpp)
target_link_libraries(fuse_rp_vsm_cpu PRIVATE fuse_vsm)
target_compile_definitions(fuse_rp_vsm_cpu PRIVATE FUSE_VSM_INCLUDE_DIR="${_fuse_wp31_inc}")
fuse_apply_cxx23(fuse_rp_vsm_cpu)
foreach(_suite layout clipmap mark invalidate frame api)
    add_test(NAME fuse_rp_vsm_${_suite} COMMAND fuse_rp_vsm_cpu ${_suite})
    set_tests_properties(fuse_rp_vsm_${_suite} PROPERTIES LABELS "gate;renderer;shadow;vsm" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_vsm ${_fuse_wp31_tests_dir}/test_rp_vsm.cpp)
target_link_libraries(fuse_rp_vsm PRIVATE fuse_vsm fuse_visbuffer)
fuse_apply_cxx23(fuse_rp_vsm)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp31_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp31_vk_tests "")
foreach(_case "parity;set" "parity;buffer" "cache;set" "evict;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_vsm_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name} COMMAND "${_fuse_wp31_lock}" "$<TARGET_FILE:fuse_rp_vsm>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_vsm --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp31_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp31_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;shadow;vsm")
