# WP-7.3 (docs/unification/RENDERER-EXECUTION.md): path-tracing mode (tier T3 ray-tracing pipeline, T2 ray-query
# variant). Owned by WP-7.3; other packages must not edit this file.
#
#   fuse_pathtrace         STATIC  settings / frame constants / emitter map / SBT layout / capability gate /
#                                  reconstruction choice (pathtrace.hpp), the BSDF (pt_bsdf.hpp), the CPU reference
#                                  path tracer (pt_reference.hpp) and PathTracerGpu (pt_gpu.hpp: "pathtrace.trace" on
#                                  render graph v2, RT pipeline + SBT or ray-query compute)
#                                  (include/fuse/renderer/pathtrace/**, src/pathtrace/**)
#   pathtrace kernels      SPIR-V  Slang (primary) + GLSL twins (shaders/pathtrace/**): ray-query compute, raygen,
#                                  miss, closest hit, any hit; embedded in fuse_pathtrace
#   fuse_rp_pathtrace_*    ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source | Slang stage.
set(_fuse_wp73_kernels
    "TRACE|Trace|pt_trace.comp|pt_trace.slang|compute"
    "RAYGEN|Raygen|pt_raygen.rgen|pt_raygen.slang|raygeneration"
    "MISS|Miss|pt_miss.rmiss|pt_miss.slang|miss"
    "CLOSEST_HIT|ClosestHit|pt_closest_hit.rchit|pt_closest_hit.slang|closesthit"
    "ANY_HIT|AnyHit|pt_any_hit.rahit|pt_any_hit.slang|anyhit")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp73.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp73.cmake from shaders/pathtrace/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp73_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_PT_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp73_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kPt${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp73_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp73_inc "${_fuse_wp73_root}/include/fuse/renderer/pathtrace")
set(_fuse_wp73_src "${_fuse_wp73_root}/src/pathtrace")
set(_fuse_wp73_shd "${_fuse_wp73_root}/shaders/pathtrace")
set(_fuse_wp73_lt_shd "${_fuse_wp73_root}/shaders/light_tree")
set(_fuse_wp73_scene_inc "${_fuse_wp73_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp73_tests_dir "${_fuse_wp73_root}/tests")

set(_fuse_wp73_warn "")
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
    set(_fuse_wp73_warn -Wall -Wextra -Werror)
endif()

find_package(Threads REQUIRED)
file(GLOB _fuse_wp73_shader_files CONFIGURE_DEPENDS "${_fuse_wp73_shd}/*")
add_library(fuse_pathtrace STATIC
    ${_fuse_wp73_src}/pathtrace.cpp
    ${_fuse_wp73_src}/pt_reference.cpp
    ${_fuse_wp73_src}/pt_gpu.cpp
    ${_fuse_wp73_inc}/pt_types.hpp
    ${_fuse_wp73_inc}/pt_bsdf.hpp
    ${_fuse_wp73_inc}/pathtrace.hpp
    ${_fuse_wp73_inc}/pt_reference.hpp
    ${_fuse_wp73_inc}/pt_gpu.hpp
    ${_fuse_wp73_shader_files}
)
set_source_files_properties(${_fuse_wp73_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
# fuse_rt: the T2 gate + instance masks; fuse_light_tree: emitters / GPU ring refs; fuse_denoiser: the IDenoiser
# registry (NRD / SVGF); the upscaler registry (DLSS RR) lives in fuse_rhi; fuse_restir: the shared RGB light table.
target_link_libraries(fuse_pathtrace PUBLIC fuse_light_tree fuse_rt fuse_gpu_scene fuse_denoiser fuse_restir PRIVATE Threads::Threads)
target_compile_options(fuse_pathtrace PRIVATE ${_fuse_wp73_warn})
fuse_apply_cxx23(fuse_pathtrace)

# Kernels, embedded into fuse_pathtrace: Slang primary, GLSL twins (the gates run both).
set(_fuse_wp73_gen "${CMAKE_CURRENT_BINARY_DIR}/pathtrace_gen")
set(_fuse_wp73_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/pathtrace")
file(MAKE_DIRECTORY "${_fuse_wp73_gen}" "${_fuse_wp73_spv}")
set(_fuse_wp73_header "${_fuse_wp73_gen}/pathtrace_spv.h")
add_custom_target(fuse_pathtrace_kernels)
set(_fuse_wp73_embed_args "")
set(_fuse_wp73_embed_deps "")
set(_fuse_wp73_glsl_deps "${_fuse_wp73_shd}/pt_common.glsl" "${_fuse_wp73_shd}/pt_integrator.glsl" "${_fuse_wp73_shd}/pt_payload.glsl"
                         "${_fuse_wp73_lt_shd}/lt_common.glsl" "${_fuse_wp73_scene_inc}/gpu_scene.glsl")
foreach(_row IN LISTS _fuse_wp73_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    list(GET _entry 4 _stage)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        set(_caps "")
        if(_stage STREQUAL "compute")
            set(_caps -capability spvRayQueryKHR)
        endif()
        fuse_add_slang_shaders(fuse_pathtrace_kernels
            SOURCES "${_fuse_wp73_shd}/${_slang}"
            STAGE ${_stage}
            SUFFIX ".pt_${_suffix}"
            INCLUDE_DIRS "${_fuse_wp73_scene_inc}" "${_fuse_wp73_lt_shd}" "${_fuse_wp73_shd}"
            FLAGS ${_caps}
            OUTPUT_DIR "${_fuse_wp73_spv}"
            OUTPUT_VAR _fuse_wp73_out)
        if(_fuse_wp73_out)
            list(APPEND _fuse_wp73_embed_args "-D${_key}_SLANG=${_fuse_wp73_out}")
            list(APPEND _fuse_wp73_embed_deps "${_fuse_wp73_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp73_spv}/pt_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp73_scene_inc}" "-I${_fuse_wp73_lt_shd}"
                          "-I${_fuse_wp73_shd}" "${_fuse_wp73_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp73_shd}/${_glsl}" ${_fuse_wp73_glsl_deps}
            COMMENT "glslangValidator ${_glsl} (pt_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp73_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp73_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp73_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp73_header}" ${_fuse_wp73_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp73_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the path-tracing kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_pathtrace_header DEPENDS "${_fuse_wp73_header}")
add_dependencies(fuse_pathtrace_header fuse_pathtrace_kernels)
add_dependencies(fuse_pathtrace fuse_pathtrace_header)
target_include_directories(fuse_pathtrace PRIVATE "${_fuse_wp73_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

# --- CPU gates (layouts, BSDF, reference estimators, API, reconstruction choice; also run in the stub tree) --------
add_executable(fuse_rp_pathtrace_cpu ${_fuse_wp73_tests_dir}/test_rp_pathtrace_cpu.cpp)
target_link_libraries(fuse_rp_pathtrace_cpu PRIVATE fuse_pathtrace fuse_geometry)
target_compile_definitions(fuse_rp_pathtrace_cpu PRIVATE "FUSE_RP_PATHTRACE_SHADER_DIR=\"${_fuse_wp73_shd}\"")
target_compile_options(fuse_rp_pathtrace_cpu PRIVATE ${_fuse_wp73_warn})
fuse_apply_cxx23(fuse_rp_pathtrace_cpu)
foreach(_suite layout bsdf furnace analytic strategies determinism api reconstruction zero_alloc)
    add_test(NAME fuse_rp_pathtrace_${_suite} COMMAND fuse_rp_pathtrace_cpu ${_suite})
    set_tests_properties(fuse_rp_pathtrace_${_suite} PROPERTIES LABELS "gate;renderer;pathtrace" TIMEOUT 1800)
endforeach()

# --- Lavapipe gates --------------------------------------------------------------------------------------------
add_executable(fuse_rp_pathtrace ${_fuse_wp73_tests_dir}/test_rp_pathtrace.cpp)
target_link_libraries(fuse_rp_pathtrace PRIVATE fuse_pathtrace fuse_geometry)
target_compile_options(fuse_rp_pathtrace PRIVATE ${_fuse_wp73_warn})
fuse_apply_cxx23(fuse_rp_pathtrace)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp73_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp73_vk_tests "")
foreach(_case "converge;set" "converge;buffer" "furnace;set" "determinism;set" "denoise;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_pathtrace_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp73_lock}" "$<TARGET_FILE:fuse_rp_pathtrace>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_pathtrace --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp73_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp73_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 1800
    LABELS "gate;vulkan;renderer;pathtrace")
