# WP-1.4 (docs/unification/RENDERER-EXECUTION.md): visibility buffer.
# Owned by WP-1.4; other packages must not edit this file.
#
#   fuse_visbuffer         STATIC  VisBuffer (R32G32_UINT + D32 raster target, 64-bit atomic target with
#                                  export, full-frame decode, all as render-graph v2 passes fed by the
#                                  WP-1.3 culler) + CPU references (vis_decode_kernel.hpp, vis_reference)
#                                  (include/fuse/renderer/visbuffer/**, src/visbuffer/**)
#   vis_* kernels          SPIR-V  Slang (primary) + GLSL twins, embedded in fuse_visbuffer
#   fuse_rp_visbuffer_*    ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | (unused) | Slang source | Slang stage | define
set(_fuse_wp14_kernels
    "RASTER_VS|RasterVs|vis_raster.vert||vis_raster_vs.slang|vertex|"
    "RASTER_FS|RasterFs|vis_raster.frag||vis_raster_fs.slang|fragment|"
    "ATOMIC_FS_IMAGE|AtomicFsImage|vis_atomic.frag||vis_atomic_fs.slang|fragment|FUSE_VIS64_IMAGE"
    "ATOMIC_FS_BUFFER|AtomicFsBuffer|vis_atomic.frag||vis_atomic_fs.slang|fragment|"
    "VIS64_IMAGE|Vis64Image|vis64.comp||vis64.slang|compute|FUSE_VIS64_IMAGE"
    "VIS64_BUFFER|Vis64Buffer|vis64.comp||vis64.slang|compute|"
    "DECODE|Decode|vis_decode.comp||vis_decode.slang|compute|")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp14.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW) # list(GET) keeps the empty fields of the kernel table
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp14.cmake from shaders/visbuffer/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp14_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_VISBUFFER_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp14_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kVis${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp14_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp14_inc "${_fuse_wp14_root}/include/fuse/renderer/visbuffer")
set(_fuse_wp14_src "${_fuse_wp14_root}/src/visbuffer")
set(_fuse_wp14_shd "${_fuse_wp14_root}/shaders/visbuffer")
set(_fuse_wp14_scene_inc "${_fuse_wp14_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp14_common_inc "${_fuse_wp14_root}/shaders/common")

file(GLOB _fuse_wp14_shader_files CONFIGURE_DEPENDS "${_fuse_wp14_shd}/*")
add_library(fuse_visbuffer STATIC
    ${_fuse_wp14_src}/visbuffer.cpp
    ${_fuse_wp14_src}/vis_reference.cpp
    ${_fuse_wp14_inc}/vis_format.hpp
    ${_fuse_wp14_inc}/vis_types.hpp
    ${_fuse_wp14_inc}/vis_decode_kernel.hpp
    ${_fuse_wp14_inc}/vis_reference.hpp
    ${_fuse_wp14_inc}/visbuffer.hpp
    ${_fuse_wp14_shader_files}
)
set_source_files_properties(${_fuse_wp14_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_visbuffer PUBLIC fuse_culling fuse_gpu_scene fuse_geometry)
fuse_apply_cxx23(fuse_visbuffer)

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the
# GLSL twins keep the visibility buffer available where slangc is not (FUSE_SLANG=AUTO), and the gates
# run both. Vertex + decode are compiled with -fp-mode precise (twins of vis_decode_kernel.hpp).
set(_fuse_wp14_gen "${CMAKE_CURRENT_BINARY_DIR}/visbuffer_gen")
set(_fuse_wp14_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/visbuffer")
file(MAKE_DIRECTORY "${_fuse_wp14_gen}" "${_fuse_wp14_spv}")
set(_fuse_wp14_header "${_fuse_wp14_gen}/visbuffer_spv.h")
add_custom_target(fuse_visbuffer_kernels)
set(_fuse_wp14_embed_args "")
set(_fuse_wp14_embed_deps "")
file(GLOB _fuse_wp14_glsl_includes "${_fuse_wp14_shd}/*.glsl")

foreach(_row IN LISTS _fuse_wp14_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 1 _stem)
    list(GET _entry 2 _glsl)
    list(GET _entry 4 _slang)
    list(GET _entry 5 _stage)
    list(GET _entry 6 _define)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        set(_defines "")
        if(_define)
            set(_defines DEFINES ${_define})
        endif()
        set(_flags -warnings-disable 39001) # the bindless arrays alias one binding on purpose
        if(_stage STREQUAL "vertex" OR _key STREQUAL "DECODE")
            list(APPEND _flags -fp-mode precise)
        endif()
        fuse_add_slang_shaders(fuse_visbuffer_kernels
            SOURCES "${_fuse_wp14_shd}/${_slang}"
            STAGE ${_stage}
            SUFFIX ".${_suffix}"
            ${_defines}
            INCLUDE_DIRS "${_fuse_wp14_scene_inc}" "${_fuse_wp14_shd}"
            FLAGS ${_flags}
            OUTPUT_DIR "${_fuse_wp14_spv}"
            OUTPUT_VAR _fuse_wp14_out)
        if(_fuse_wp14_out)
            list(APPEND _fuse_wp14_embed_args "-D${_key}_SLANG=${_fuse_wp14_out}")
            list(APPEND _fuse_wp14_embed_deps "${_fuse_wp14_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp14_spv}/${_suffix}.glsl.spv")
        set(_dflag "")
        if(_define)
            set(_dflag "-D${_define}")
        endif()
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 ${_dflag} "-I${_fuse_wp14_common_inc}"
                          "-I${_fuse_wp14_scene_inc}" "-I${_fuse_wp14_shd}" "${_fuse_wp14_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp14_shd}/${_glsl}" ${_fuse_wp14_glsl_includes} "${_fuse_wp14_scene_inc}/gpu_scene.glsl"
                    "${_fuse_wp14_common_inc}/bindless.glsl"
            COMMENT "glslangValidator ${_glsl} (${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp14_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp14_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp14_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp14_header}" ${_fuse_wp14_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp14_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the visibility-buffer kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_visbuffer_header DEPENDS "${_fuse_wp14_header}")
add_dependencies(fuse_visbuffer_header fuse_visbuffer_kernels)
add_dependencies(fuse_visbuffer fuse_visbuffer_header)
target_include_directories(fuse_visbuffer PRIVATE "${_fuse_wp14_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp14_tests_dir "${_fuse_wp14_root}/tests")

# --- CPU gates (reference kernels; also run in the stub tree) --------------------------------------
add_executable(fuse_rp_visbuffer_cpu ${_fuse_wp14_tests_dir}/test_rp_visbuffer_cpu.cpp)
target_link_libraries(fuse_rp_visbuffer_cpu PRIVATE fuse_visbuffer)
fuse_apply_cxx23(fuse_rp_visbuffer_cpu)
foreach(_suite format indices decode reference api)
    add_test(NAME fuse_rp_visbuffer_${_suite} COMMAND fuse_rp_visbuffer_cpu ${_suite})
    set_tests_properties(fuse_rp_visbuffer_${_suite} PROPERTIES LABELS "gate;renderer;visbuffer" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_visbuffer ${_fuse_wp14_tests_dir}/test_rp_visbuffer.cpp)
target_link_libraries(fuse_rp_visbuffer PRIVATE fuse_visbuffer)
fuse_apply_cxx23(fuse_rp_visbuffer)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp14_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp14_vk_tests "")
foreach(_case "raster;set" "raster;buffer" "atomic_image;set" "atomic_buffer;set" "atomic_buffer;buffer" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_visbuffer_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp14_lock}" "$<TARGET_FILE:fuse_rp_visbuffer>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_visbuffer --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp14_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp14_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;visbuffer")
