# WP-0.6: verify Engine/lib/renderdoc against its VERSION pin (cmake -DPIN_DIR=<dir> -P this file).
# Checks the required fields, every sha256:<file>=<hex> line (CRLF normalized to LF) and that the
# newest eRENDERDOC_API_Version_X_Y_Z the header declares equals api_version.
if(NOT PIN_DIR OR NOT EXISTS "${PIN_DIR}/VERSION")
    message(FATAL_ERROR "missing pin file: ${PIN_DIR}/VERSION")
endif()
file(STRINGS "${PIN_DIR}/VERSION" _lines)
set(_hashes 0)
foreach(_line IN LISTS _lines)
    if(_line MATCHES "^#" OR _line STREQUAL "")
        continue()
    endif()
    if(_line MATCHES "^sha256:([^=]+)=([0-9a-f]+)$")
        set(_file "${PIN_DIR}/${CMAKE_MATCH_1}")
        set(_want "${CMAKE_MATCH_2}")
        if(NOT EXISTS "${_file}")
            message(SEND_ERROR "${_file}: pinned file missing")
            continue()
        endif()
        file(READ "${_file}" _text)
        string(REPLACE "\r\n" "\n" _text "${_text}")
        string(SHA256 _got "${_text}")
        if(NOT _got STREQUAL _want)
            message(SEND_ERROR "${_file}: sha256 ${_got} != pinned ${_want}")
        endif()
        math(EXPR _hashes "${_hashes} + 1")
    elseif(_line MATCHES "^([a-z_]+)=(.*)$")
        set(_pin_${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
    else()
        message(SEND_ERROR "VERSION: malformed line '${_line}'")
    endif()
endforeach()
foreach(_key name upstream version tag commit license license_file version_header api_version)
    if("${_pin_${_key}}" STREQUAL "")
        message(SEND_ERROR "VERSION: required field '${_key}' missing")
    endif()
endforeach()
string(LENGTH "${_pin_commit}" _commit_length)
if(NOT _pin_commit MATCHES "^[0-9a-f]+$" OR NOT _commit_length EQUAL 40)
    message(SEND_ERROR "VERSION: commit '${_pin_commit}' is not a 40-hex hash")
endif()
if(NOT _pin_tag STREQUAL "v${_pin_version}")
    message(SEND_ERROR "VERSION: tag '${_pin_tag}' does not name version ${_pin_version}")
endif()
if(_hashes EQUAL 0)
    message(SEND_ERROR "VERSION: no sha256 lines")
endif()
file(READ "${PIN_DIR}/${_pin_version_header}" _header)
string(REGEX MATCHALL "eRENDERDOC_API_Version_([0-9]+)_([0-9]+)_([0-9]+)" _declared "${_header}")
set(_newest "0.0.0")
foreach(_d IN LISTS _declared)
    string(REGEX REPLACE "eRENDERDOC_API_Version_([0-9]+)_([0-9]+)_([0-9]+)" "\\1.\\2.\\3" _v "${_d}")
    if(_v VERSION_GREATER _newest)
        set(_newest "${_v}")
    endif()
endforeach()
if(NOT _newest STREQUAL _pin_api_version)
    message(SEND_ERROR "${_pin_version_header}: newest API version ${_newest}, pin says ${_pin_api_version}")
endif()
file(READ "${PIN_DIR}/${_pin_license_file}" _license)
if(NOT _license MATCHES "Copyright" OR NOT _license MATCHES "MIT License")
    message(SEND_ERROR "${_pin_license_file}: no MIT copyright notice")
endif()
message(STATUS "renderdoc pin ok: ${_pin_name} ${_pin_version} (${_pin_commit}), API ${_newest}, ${_hashes} file(s)")
