# WP-1.5 (docs/unification/RENDERER-EXECUTION.md): material resolve from the visibility buffer.
# Owned by WP-1.5; other packages must not edit this file.
#
#   fuse_material_resolve  STATIC  MaterialResolve (tile classification + per-bin indirect resolve and
#                                  the uber fallback into the deferred G-buffer layout, attribute dump,
#                                  forward G-buffer reference) + CPU references (resolve_kernel.hpp,
#                                  resolve_reference) (include/fuse/renderer/material_resolve/**,
#                                  src/material_resolve/**)
#   mr_* kernels           SPIR-V  Slang (primary) + GLSL twins, embedded in fuse_material_resolve; the
#                                  forward reference shaders are GLSL only
#   fuse_rp_material_resolve_*  ctest  CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source (empty: GLSL only) | stage
set(_fuse_wp15_kernels
    "CLASSIFY|Classify|mr_classify.comp|mr_classify.slang|compute"
    "ATTRIBUTES|Attributes|mr_attributes.comp|mr_attributes.slang|compute"
    "RESOLVE_VS|ResolveVs|mr_resolve.vert|mr_resolve_vs.slang|vertex"
    "RESOLVE_FS|ResolveFs|mr_resolve.frag|mr_resolve_fs.slang|fragment"
    "FORWARD_VS|ForwardVs|mr_forward.vert||vertex"
    "FORWARD_FS|ForwardFs|mr_forward.frag||fragment")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp15.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW) # list(GET) keeps the empty fields of the kernel table
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp15.cmake from shaders/material_resolve/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp15_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            list(GET _entry 3 _slang)
            if(_lang STREQUAL "SLANG" AND NOT _slang)
                continue()
            endif()
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_MATERIAL_RESOLVE_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp15_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                list(GET _entry 3 _slang)
                if(_lang STREQUAL "SLANG" AND NOT _slang)
                    continue()
                endif()
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kMr${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp15_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp15_inc "${_fuse_wp15_root}/include/fuse/renderer/material_resolve")
set(_fuse_wp15_src "${_fuse_wp15_root}/src/material_resolve")
set(_fuse_wp15_shd "${_fuse_wp15_root}/shaders/material_resolve")
set(_fuse_wp15_vis_shd "${_fuse_wp15_root}/shaders/visbuffer")
set(_fuse_wp15_scene_inc "${_fuse_wp15_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp15_common_inc "${_fuse_wp15_root}/shaders/common")
# Asset W0.7 layered bin: mr_layered.{glsl,slang} include shaders/material_layers/ml_common.{glsl,slang}.
set(_fuse_wp15_ml_shd "${_fuse_wp15_root}/shaders/material_layers")

file(GLOB _fuse_wp15_shader_files CONFIGURE_DEPENDS "${_fuse_wp15_shd}/*")
add_library(fuse_material_resolve STATIC
    ${_fuse_wp15_src}/material_resolve.cpp
    ${_fuse_wp15_src}/resolve_reference.cpp
    ${_fuse_wp15_inc}/resolve_types.hpp
    ${_fuse_wp15_inc}/resolve_kernel.hpp
    ${_fuse_wp15_inc}/resolve_reference.hpp
    ${_fuse_wp15_inc}/material_resolve.hpp
    ${_fuse_wp15_shader_files}
)
set_source_files_properties(${_fuse_wp15_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_material_resolve PUBLIC fuse_visbuffer)
fuse_apply_cxx23(fuse_material_resolve)

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the
# GLSL twins keep the resolve available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
# Everything is compiled with -fp-mode precise (twins of resolve_kernel.hpp).
set(_fuse_wp15_gen "${CMAKE_CURRENT_BINARY_DIR}/material_resolve_gen")
set(_fuse_wp15_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/material_resolve")
file(MAKE_DIRECTORY "${_fuse_wp15_gen}" "${_fuse_wp15_spv}")
set(_fuse_wp15_header "${_fuse_wp15_gen}/material_resolve_spv.h")
add_custom_target(fuse_material_resolve_kernels)
set(_fuse_wp15_embed_args "")
set(_fuse_wp15_embed_deps "")
file(GLOB _fuse_wp15_glsl_includes "${_fuse_wp15_shd}/*.glsl" "${_fuse_wp15_vis_shd}/*.glsl" "${_fuse_wp15_ml_shd}/*.glsl")

foreach(_row IN LISTS _fuse_wp15_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    list(GET _entry 4 _stage)
    string(TOLOWER "${_key}" _suffix)
    if(_slang AND COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_material_resolve_kernels
            SOURCES "${_fuse_wp15_shd}/${_slang}"
            STAGE ${_stage}
            SUFFIX ".${_suffix}"
            INCLUDE_DIRS "${_fuse_wp15_scene_inc}" "${_fuse_wp15_vis_shd}" "${_fuse_wp15_shd}" "${_fuse_wp15_ml_shd}"
            # 39001: the bindless arrays alias one binding on purpose; 41012: the fragment stage's
            # implicit capability upgrade (derivative control etc. are declared, not used).
            FLAGS -warnings-disable 39001 -warnings-disable 41012 -fp-mode precise
            OUTPUT_DIR "${_fuse_wp15_spv}"
            OUTPUT_VAR _fuse_wp15_out)
        if(_fuse_wp15_out)
            list(APPEND _fuse_wp15_embed_args "-D${_key}_SLANG=${_fuse_wp15_out}")
            list(APPEND _fuse_wp15_embed_deps "${_fuse_wp15_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp15_spv}/${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp15_common_inc}"
                          "-I${_fuse_wp15_scene_inc}" "-I${_fuse_wp15_vis_shd}" "-I${_fuse_wp15_shd}" "-I${_fuse_wp15_ml_shd}"
                          "${_fuse_wp15_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp15_shd}/${_glsl}" ${_fuse_wp15_glsl_includes} "${_fuse_wp15_scene_inc}/gpu_scene.glsl"
                    "${_fuse_wp15_common_inc}/bindless.glsl" "${_fuse_wp15_common_inc}/gbuffer.glsl"
                    "${_fuse_wp15_common_inc}/material.glsl"
            COMMENT "glslangValidator ${_glsl} (${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp15_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp15_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp15_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp15_header}" ${_fuse_wp15_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp15_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the material-resolve kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_material_resolve_header DEPENDS "${_fuse_wp15_header}")
add_dependencies(fuse_material_resolve_header fuse_material_resolve_kernels)
add_dependencies(fuse_material_resolve fuse_material_resolve_header)
target_include_directories(fuse_material_resolve PRIVATE "${_fuse_wp15_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp15_tests_dir "${_fuse_wp15_root}/tests")

# --- CPU gates (reference kernels; also run in the stub tree) --------------------------------------
add_executable(fuse_rp_material_resolve_cpu ${_fuse_wp15_tests_dir}/test_rp_material_resolve_cpu.cpp)
target_link_libraries(fuse_rp_material_resolve_cpu PRIVATE fuse_material_resolve)
fuse_apply_cxx23(fuse_rp_material_resolve_cpu)
foreach(_suite layout bary attributes classify api)
    add_test(NAME fuse_rp_material_resolve_${_suite} COMMAND fuse_rp_material_resolve_cpu ${_suite})
    set_tests_properties(fuse_rp_material_resolve_${_suite} PROPERTIES LABELS "gate;renderer;material_resolve" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_material_resolve ${_fuse_wp15_tests_dir}/test_rp_material_resolve.cpp)
target_link_libraries(fuse_rp_material_resolve PRIVATE fuse_material_resolve)
fuse_apply_cxx23(fuse_rp_material_resolve)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp15_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp15_vk_tests "")
foreach(_case "parity;set" "parity;buffer" "parity_atomic;set" "multiframe;set" "multiframe;buffer" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_material_resolve_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp15_lock}" "$<TARGET_FILE:fuse_rp_material_resolve>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_material_resolve --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp15_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp15_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;material_resolve")

# --- Asset W0.7 integration: the layered-material bin (material_layers/ x material_resolve/) --------------------
# CPU gates (stub tree too) and Lavapipe gates of the layered bin; the golden G-buffer image lives next to the W0.7
# fixtures (tests/material_layers/resolve_layered_gbuffer.png).
set(_fuse_wp15_ml_fixtures "${_fuse_wp15_tests_dir}/material_layers")
add_executable(fuse_rp_material_resolve_layered_cpu ${_fuse_wp15_tests_dir}/test_rp_material_resolve_layered_cpu.cpp)
target_link_libraries(fuse_rp_material_resolve_layered_cpu PRIVATE fuse_material_resolve fuse_material_layers)
target_compile_definitions(fuse_rp_material_resolve_layered_cpu PRIVATE
    FUSE_RP_MR_SHADER_DIR="${_fuse_wp15_shd}" FUSE_RP_ML_SHADER_DIR="${_fuse_wp15_ml_shd}"
    FUSE_RP_SCENE_SHADER_DIR="${_fuse_wp15_scene_inc}" FUSE_RP_ML_FIXTURE_DIR="${_fuse_wp15_ml_fixtures}")
fuse_apply_cxx23(fuse_rp_material_resolve_layered_cpu)
foreach(_suite layout mips surface classify api)
    add_test(NAME fuse_rp_material_resolve_layered_${_suite} COMMAND fuse_rp_material_resolve_layered_cpu ${_suite})
    set_tests_properties(fuse_rp_material_resolve_layered_${_suite} PROPERTIES
        LABELS "gate;renderer;material_resolve;material_layers" TIMEOUT 600)
endforeach()

add_executable(fuse_rp_material_resolve_layered ${_fuse_wp15_tests_dir}/test_rp_material_resolve_layered.cpp)
target_link_libraries(fuse_rp_material_resolve_layered PRIVATE fuse_material_resolve fuse_material_layers)
target_compile_definitions(fuse_rp_material_resolve_layered PRIVATE FUSE_RP_ML_FIXTURE_DIR="${_fuse_wp15_ml_fixtures}"
                                                                    FUSE_RP_MRL_OUTPUT_DIR="${CMAKE_CURRENT_BINARY_DIR}")
fuse_apply_cxx23(fuse_rp_material_resolve_layered)
set(_fuse_wp15_layered_tests "")
foreach(_case "parity;set" "parity;buffer" "golden;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_material_resolve_layered_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp15_lock}" "$<TARGET_FILE:fuse_rp_material_resolve_layered>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_material_resolve_layered --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp15_layered_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp15_layered_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;material_resolve;material_layers")
