# Asset plan W0.7 (docs/plans/FUSE_ASSET_PLAN.md §1.5, §5.1, §6 Wave 0): the .fusemat format and layered materials
# (height-blended layer stack, detail maps, triplanar projection, stochastic tiling) in the renderer.
# Owned by W0.7; other packages must not edit this file.
#
#   fuse_material_layers   STATIC  .fusemat JSON / binary (fusemat.hpp), the material library + CPU reference
#                                  (ml_kernel.hpp, ml_reference.hpp) and MaterialLayers (materials.eval,
#                                  materials.balls, materials.copy on render graph v2)
#                                  (include/fuse/renderer/material_layers/**, src/material_layers/**)
#   ml_* kernels           SPIR-V  Slang (primary, -fp-mode precise) + GLSL twins, embedded in fuse_material_layers
#   fuse_rp_material_layers_*  ctest  CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source
set(_fuse_w07_kernels
    "EVAL|Eval|ml_eval.comp|ml_eval.slang"
    "BALLS|Balls|ml_balls.comp|ml_balls.slang")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_w07.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_w07.cmake from shaders/material_layers/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_w07_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_MATERIAL_LAYERS_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_w07_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kMl${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_w07_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_w07_inc "${_fuse_w07_root}/include/fuse/renderer/material_layers")
set(_fuse_w07_src "${_fuse_w07_root}/src/material_layers")
set(_fuse_w07_shd "${_fuse_w07_root}/shaders/material_layers")

file(GLOB _fuse_w07_shader_files CONFIGURE_DEPENDS "${_fuse_w07_shd}/*")
add_library(fuse_material_layers STATIC
    ${_fuse_w07_src}/fusemat.cpp
    ${_fuse_w07_src}/ml_reference.cpp
    ${_fuse_w07_src}/material_layers.cpp
    ${_fuse_w07_inc}/ml_types.hpp
    ${_fuse_w07_inc}/ml_kernel.hpp
    ${_fuse_w07_inc}/ml_reference.hpp
    ${_fuse_w07_inc}/fusemat.hpp
    ${_fuse_w07_inc}/material_layers.hpp
    ${_fuse_w07_shader_files}
)
set_source_files_properties(${_fuse_w07_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_material_layers PUBLIC fuse_rhi)
fuse_apply_cxx23(fuse_material_layers)

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the GLSL
# twins keep the layered materials available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
set(_fuse_w07_gen "${CMAKE_CURRENT_BINARY_DIR}/material_layers_gen")
set(_fuse_w07_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/material_layers")
file(MAKE_DIRECTORY "${_fuse_w07_gen}" "${_fuse_w07_spv}")
set(_fuse_w07_header "${_fuse_w07_gen}/material_layers_spv.h")
add_custom_target(fuse_material_layers_kernels)
set(_fuse_w07_embed_args "")
set(_fuse_w07_embed_deps "")
file(GLOB _fuse_w07_glsl_includes "${_fuse_w07_shd}/*.glsl")

foreach(_row IN LISTS _fuse_w07_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_material_layers_kernels
            SOURCES "${_fuse_w07_shd}/${_slang}"
            STAGE compute
            SUFFIX ".ml_${_suffix}"
            INCLUDE_DIRS "${_fuse_w07_shd}"
            FLAGS -fp-mode precise
            OUTPUT_DIR "${_fuse_w07_spv}"
            OUTPUT_VAR _fuse_w07_out)
        if(_fuse_w07_out)
            list(APPEND _fuse_w07_embed_args "-D${_key}_SLANG=${_fuse_w07_out}")
            list(APPEND _fuse_w07_embed_deps "${_fuse_w07_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_w07_spv}/ml_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_w07_shd}"
                          "${_fuse_w07_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_w07_shd}/${_glsl}" ${_fuse_w07_glsl_includes}
            COMMENT "glslangValidator ${_glsl} (ml_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_w07_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_w07_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_w07_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_w07_header}" ${_fuse_w07_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_w07_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the layered-material kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_material_layers_header DEPENDS "${_fuse_w07_header}")
add_dependencies(fuse_material_layers_header fuse_material_layers_kernels)
add_dependencies(fuse_material_layers fuse_material_layers_header)
target_include_directories(fuse_material_layers PRIVATE "${_fuse_w07_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_w07_tests_dir "${_fuse_w07_root}/tests")
set(_fuse_w07_fixtures "${_fuse_w07_tests_dir}/material_layers")

# --- CPU gates (layouts, .fusemat round trip + validation errors, reference properties; stub tree too) ----------
add_executable(fuse_rp_material_layers_cpu ${_fuse_w07_tests_dir}/test_rp_material_layers_cpu.cpp)
target_link_libraries(fuse_rp_material_layers_cpu PRIVATE fuse_material_layers)
target_compile_definitions(fuse_rp_material_layers_cpu PRIVATE FUSE_RP_ML_SHADER_DIR="${_fuse_w07_shd}"
                                                                FUSE_RP_ML_FIXTURE_DIR="${_fuse_w07_fixtures}")
fuse_apply_cxx23(fuse_rp_material_layers_cpu)
foreach(_suite layout fusemat reference golden_cpu api)
    add_test(NAME fuse_rp_material_layers_${_suite} COMMAND fuse_rp_material_layers_cpu ${_suite})
    set_tests_properties(fuse_rp_material_layers_${_suite} PROPERTIES LABELS "gate;renderer;material_layers" TIMEOUT 900)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_material_layers ${_fuse_w07_tests_dir}/test_rp_material_layers.cpp)
target_link_libraries(fuse_rp_material_layers PRIVATE fuse_material_layers)
target_compile_definitions(fuse_rp_material_layers PRIVATE FUSE_RP_ML_FIXTURE_DIR="${_fuse_w07_fixtures}"
                                                            FUSE_RP_ML_OUTPUT_DIR="${CMAKE_CURRENT_BINARY_DIR}")
fuse_apply_cxx23(fuse_rp_material_layers)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_w07_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_w07_vk_tests "")
foreach(_case "parity;set" "parity;buffer" "stochastic;set" "triplanar;set" "golden;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_material_layers_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_w07_lock}" "$<TARGET_FILE:fuse_rp_material_layers>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_material_layers --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_w07_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_w07_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;material_layers")
