# WP-8.3 (docs/unification/RENDERER-EXECUTION.md): volumetric clouds on Vulkan (GPU-baked tileable noise volumes
# and weather map, raymarched cloud layer lit by the WP-8.2 atmosphere, 1/16-per-frame temporal amortisation with
# reprojection and history rejection, aerial-perspective composite). Owned by WP-8.3; other packages must not edit
# this file.
#
#   fuse_clouds_gpu        STATIC  VolumetricClouds (clouds.noise.shape, clouds.noise.detail, clouds.weather,
#                                  clouds.march, clouds.reconstruct, clouds.composite, clouds.probe on render
#                                  graph v2) + the CPU reference of every kernel (cloud_reference.*)
#   cl_* kernels           SPIR-V  Slang (primary, -fp-mode precise) + GLSL twins, embedded in fuse_clouds_gpu;
#                                  they include shaders/atmosphere/at_sample.{glsl,slang}
#   fuse_rp_clouds_*       ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source
set(_fuse_wp83_kernels
    "SHAPE|NoiseShape|cl_noise_shape.comp|cl_noise_shape.slang"
    "DETAIL|NoiseDetail|cl_noise_detail.comp|cl_noise_detail.slang"
    "WEATHER|Weather|cl_weather.comp|cl_weather.slang"
    "MARCH|March|cl_march.comp|cl_march.slang"
    "RECONSTRUCT|Reconstruct|cl_reconstruct.comp|cl_reconstruct.slang"
    "COMPOSITE|Composite|cl_composite.comp|cl_composite.slang"
    "PROBE|Probe|cl_probe.comp|cl_probe.slang")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp83.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp83.cmake from shaders/clouds/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp83_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_CLOUDS_GPU_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp83_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kCl${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp83_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp83_inc "${_fuse_wp83_root}/include/fuse/renderer/clouds")
set(_fuse_wp83_src "${_fuse_wp83_root}/src/clouds")
set(_fuse_wp83_shd "${_fuse_wp83_root}/shaders/clouds")

file(GLOB _fuse_wp83_shader_files CONFIGURE_DEPENDS "${_fuse_wp83_shd}/*")
add_library(fuse_clouds_gpu STATIC
    ${_fuse_wp83_src}/cloud_reference.cpp
    ${_fuse_wp83_src}/volumetric_clouds.cpp
    ${_fuse_wp83_inc}/cloud_types.hpp
    ${_fuse_wp83_inc}/cloud_reference.hpp
    ${_fuse_wp83_inc}/volumetric_clouds.hpp
    ${_fuse_wp83_shader_files}
)
set_source_files_properties(${_fuse_wp83_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
# fuse_atmosphere_gpu: AtParams and the CPU sampling helpers (at_sun_illuminance_at, at_sky_radiance, at_aerial).
target_link_libraries(fuse_clouds_gpu PUBLIC fuse_atmosphere_gpu)
fuse_apply_cxx23(fuse_clouds_gpu)

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the GLSL
# twins keep the clouds available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
set(_fuse_wp83_gen "${CMAKE_CURRENT_BINARY_DIR}/clouds_gpu_gen")
set(_fuse_wp83_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/clouds")
set(_fuse_wp83_shd_root "${_fuse_wp83_root}/shaders")
file(MAKE_DIRECTORY "${_fuse_wp83_gen}" "${_fuse_wp83_spv}")
set(_fuse_wp83_header "${_fuse_wp83_gen}/clouds_gpu_spv.h")
add_custom_target(fuse_clouds_gpu_kernels)
set(_fuse_wp83_embed_args "")
set(_fuse_wp83_embed_deps "")
file(GLOB _fuse_wp83_glsl_includes "${_fuse_wp83_shd}/*.glsl" "${_fuse_wp83_shd_root}/atmosphere/at_sample.glsl")

foreach(_row IN LISTS _fuse_wp83_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_clouds_gpu_kernels
            SOURCES "${_fuse_wp83_shd}/${_slang}"
            STAGE compute
            SUFFIX ".cl_${_suffix}"
            INCLUDE_DIRS "${_fuse_wp83_shd}" "${_fuse_wp83_shd_root}"
            FLAGS -fp-mode precise
            OUTPUT_DIR "${_fuse_wp83_spv}"
            OUTPUT_VAR _fuse_wp83_out)
        if(_fuse_wp83_out)
            list(APPEND _fuse_wp83_embed_args "-D${_key}_SLANG=${_fuse_wp83_out}")
            list(APPEND _fuse_wp83_embed_deps "${_fuse_wp83_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp83_spv}/cl_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp83_shd}" "-I${_fuse_wp83_shd_root}"
                          "${_fuse_wp83_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp83_shd}/${_glsl}" ${_fuse_wp83_glsl_includes}
            COMMENT "glslangValidator ${_glsl} (cl_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp83_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp83_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp83_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp83_header}" ${_fuse_wp83_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp83_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the cloud kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_clouds_gpu_header DEPENDS "${_fuse_wp83_header}")
add_dependencies(fuse_clouds_gpu_header fuse_clouds_gpu_kernels)
add_dependencies(fuse_clouds_gpu fuse_clouds_gpu_header)
target_include_directories(fuse_clouds_gpu PRIVATE "${_fuse_wp83_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp83_tests_dir "${_fuse_wp83_root}/tests")

# --- CPU gates (noise, density, single-ray integration, analytic slab, temporal logic, layouts; stub tree too) ---
add_executable(fuse_rp_clouds_cpu ${_fuse_wp83_tests_dir}/test_rp_clouds_cpu.cpp)
target_link_libraries(fuse_rp_clouds_cpu PRIVATE fuse_clouds_gpu)
target_compile_definitions(fuse_rp_clouds_cpu PRIVATE FUSE_RP_CLOUDS_SHADER_DIR="${_fuse_wp83_shd}")
fuse_apply_cxx23(fuse_rp_clouds_cpu)
foreach(_suite layout noise density analytic temporal composite api)
    add_test(NAME fuse_rp_clouds_${_suite} COMMAND fuse_rp_clouds_cpu ${_suite})
    set_tests_properties(fuse_rp_clouds_${_suite} PROPERTIES LABELS "gate;renderer;clouds" TIMEOUT 900)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_clouds ${_fuse_wp83_tests_dir}/test_rp_clouds.cpp)
target_link_libraries(fuse_rp_clouds PRIVATE fuse_clouds_gpu)
fuse_apply_cxx23(fuse_rp_clouds)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp83_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp83_vk_tests "")
foreach(_case "noise;set" "ray;set" "ray;buffer" "analytic;set" "converge;set" "ghosting;set" "composite;set"
              "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_clouds_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp83_lock}" "$<TARGET_FILE:fuse_rp_clouds>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_clouds --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp83_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp83_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;clouds")
