# WP-4.2 (docs/unification/RENDERER-EXECUTION.md): FSR 3.1 temporal upscaler backend on Vulkan.
# Owned by WP-4.2; other packages must not edit this file.
#
#   fuse_fsr3            STATIC  Fsr3Gpu (fsr3.clear / fsr3.convert + the eight FidelityFX FSR 3.1 passes on render
#                                graph v2), the clean-room host (constants, ping-pong, clears, reflection-driven
#                                descriptor binding) and the "fsr3" ITemporalUpscaler adapter
#                                (include/fuse/renderer/upscale_backends/fsr3/**, src/upscale_backends/fsr3/**)
#   FSR 3.1 passes       SPIR-V  the vendored AMD FidelityFX SDK v1.1.4 Vulkan GLSL (Engine/lib/fidelityfx, MIT),
#                                compiled verbatim with glslangValidator -Os (the SDK's FidelityFX-SC glslang flags)
#                                for FUSE's permutation, embedded in fuse_fsr3
#   fsr3.convert         SPIR-V  FUSE input adapter, Slang (primary) + GLSL twin
#   fuse_rp_fsr3_*       ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded vendored pass, '|'-separated: KEY | C++ name stem | pass file stem | APPLY_SHARPENING
set(_fuse_wp42_passes
    "PREPARE_INPUTS|PrepareInputs|prepare_inputs|0"
    "LUMA_PYRAMID|LumaPyramid|luma_pyramid|0"
    "SHADING_CHANGE_PYRAMID|ShadingChangePyramid|shading_change_pyramid|0"
    "SHADING_CHANGE|ShadingChange|shading_change|0"
    "PREPARE_REACTIVITY|PrepareReactivity|prepare_reactivity|0"
    "LUMA_INSTABILITY|LumaInstability|luma_instability|0"
    "ACCUMULATE|Accumulate|accumulate|0"
    "ACCUMULATE_SHARPEN|AccumulateSharpen|accumulate|1"
    "RCAS|Rcas|rcas|0")

# Script mode (build step): embed the SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>=<spv> ...] [-DCONVERT_SLANG=<spv>] [-DCONVERT_GLSL=<spv>] -P rp_wp42.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp42.cmake. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    set(_complete TRUE)
    foreach(_row IN LISTS _fuse_wp42_passes)
        string(REPLACE "|" ";" _entry "${_row}")
        list(GET _entry 0 _key)
        if(NOT ${_key} OR NOT EXISTS "${${_key}}")
            set(_complete FALSE)
        endif()
    endforeach()
    if(_complete)
        string(APPEND _text "#define FUSE_FSR3_PASSES 1\n")
        foreach(_row IN LISTS _fuse_wp42_passes)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            list(GET _entry 1 _stem)
            file(READ "${${_key}}" _hex HEX)
            string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
            string(APPEND _text "alignas(4) static const std::uint32_t kFsr3${_stem}Spv[] = {${_words}};\n")
        endforeach()
    endif()
    foreach(_lang SLANG GLSL)
        if(CONVERT_${_lang} AND EXISTS "${CONVERT_${_lang}}")
            if(_lang STREQUAL "SLANG")
                set(_suffix Slang)
            else()
                set(_suffix Glsl)
            endif()
            string(APPEND _text "#define FUSE_FSR3_CONVERT_${_lang} 1\n")
            file(READ "${CONVERT_${_lang}}" _hex HEX)
            string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
            string(APPEND _text "alignas(4) static const std::uint32_t kFsr3Convert${_suffix}Spv[] = {${_words}};\n")
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp42_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp42_inc "${_fuse_wp42_root}/include/fuse/renderer/upscale_backends/fsr3")
set(_fuse_wp42_src "${_fuse_wp42_root}/src/upscale_backends/fsr3")
set(_fuse_wp42_shd "${_fuse_wp42_src}/shaders")
set(_fuse_wp42_ffx "${CMAKE_SOURCE_DIR}/Engine/lib/fidelityfx")
set(_fuse_wp42_ffx_gpu "${_fuse_wp42_ffx}/include/FidelityFX/gpu")
set(_fuse_wp42_ffx_vk "${_fuse_wp42_ffx}/shaders/vk/fsr3upscaler")

file(GLOB _fuse_wp42_shader_files CONFIGURE_DEPENDS "${_fuse_wp42_shd}/*")
add_library(fuse_fsr3 STATIC
    ${_fuse_wp42_src}/fsr3_host.cpp
    ${_fuse_wp42_src}/fsr3_reflect.cpp
    ${_fuse_wp42_src}/fsr3_gpu.cpp
    ${_fuse_wp42_src}/fsr3_upscaler.cpp
    ${_fuse_wp42_inc}/fsr3_types.hpp
    ${_fuse_wp42_inc}/fsr3_reflect.hpp
    ${_fuse_wp42_inc}/fsr3_gpu.hpp
    ${_fuse_wp42_inc}/fsr3_upscaler.hpp
    ${_fuse_wp42_shader_files}
)
set_source_files_properties(${_fuse_wp42_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_fsr3 PUBLIC fuse_rhi)
# FUSE_UPSCALER_FSR3 (option in cmake/upscale.cmake, default ON with Vulkan): register_fsr3_backend() registers
# "fsr3" only when set (PUBLIC so consumers can test it too).
if(FUSE_UPSCALER_FSR3 AND FUSE_VULKAN_BACKEND)
    target_compile_definitions(fuse_fsr3 PUBLIC FUSE_UPSCALER_FSR3=1)
endif()
# The FFX_CPU host helpers (FsrRcasCon, ffxSpdSetup) of the vendored headers; SYSTEM: third-party code.
target_include_directories(fuse_fsr3 SYSTEM PRIVATE "${_fuse_wp42_ffx}/include")
fuse_apply_cxx23(fuse_fsr3)

# Kernels, embedded into the library.
set(_fuse_wp42_gen "${CMAKE_CURRENT_BINARY_DIR}/fsr3_gen")
set(_fuse_wp42_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/fsr3")
file(MAKE_DIRECTORY "${_fuse_wp42_gen}" "${_fuse_wp42_spv}")
set(_fuse_wp42_header "${_fuse_wp42_gen}/fsr3_spv.h")
add_custom_target(fuse_fsr3_kernels)
set(_fuse_wp42_embed_args "")
set(_fuse_wp42_embed_deps "")

if(FUSE_GLSLANG_VALIDATOR)
    # The SDK's FidelityFX-SC glslang invocation (CMakeCompileFSR3UpscalerShaders.txt + the Vulkan
    # CMakeShadersFSR3Upscaler.txt: -Os, FFX_GLSL, the base options) with FUSE's one permutation per pass:
    # reference Lanczos reprojection (the LUT variant is the SDK's choice for wave32/64 AMD parts only), HDR colour,
    # render-resolution motion vectors without jitter, inverted (reverse-Z) depth, no FP16 (FFX_HALF=0).
    file(GLOB _fuse_wp42_ffx_deps "${_fuse_wp42_ffx_gpu}/*.h" "${_fuse_wp42_ffx_gpu}/fsr3upscaler/*.h"
                                  "${_fuse_wp42_ffx_gpu}/spd/*.h" "${_fuse_wp42_ffx_gpu}/fsr1/*.h")
    set(_fuse_wp42_ffx_defines
        -DFFX_GPU=1 -DFFX_GLSL=1 -DFFX_HALF=0
        -DFFX_FSR3UPSCALER_OPTION_UPSAMPLE_SAMPLERS_USE_DATA_HALF=0
        -DFFX_FSR3UPSCALER_OPTION_ACCUMULATE_SAMPLERS_USE_DATA_HALF=0
        -DFFX_FSR3UPSCALER_OPTION_REPROJECT_SAMPLERS_USE_DATA_HALF=1
        -DFFX_FSR3UPSCALER_OPTION_POSTPROCESSLOCKSTATUS_SAMPLERS_USE_DATA_HALF=0
        -DFFX_FSR3UPSCALER_OPTION_UPSAMPLE_USE_LANCZOS_TYPE=2
        -DFFX_FSR3UPSCALER_OPTION_REPROJECT_USE_LANCZOS_TYPE=0
        -DFFX_FSR3UPSCALER_OPTION_HDR_COLOR_INPUT=1
        -DFFX_FSR3UPSCALER_OPTION_LOW_RESOLUTION_MOTION_VECTORS=1
        -DFFX_FSR3UPSCALER_OPTION_JITTERED_MOTION_VECTORS=0
        -DFFX_FSR3UPSCALER_OPTION_INVERTED_DEPTH=1)
    foreach(_row IN LISTS _fuse_wp42_passes)
        string(REPLACE "|" ";" _entry "${_row}")
        list(GET _entry 0 _key)
        list(GET _entry 2 _file)
        list(GET _entry 3 _sharpen)
        string(TOLOWER "${_key}" _suffix)
        set(_out "${_fuse_wp42_spv}/fsr3_${_suffix}.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" -V -Os --target-env vulkan1.3 -S comp ${_fuse_wp42_ffx_defines}
                          -DFFX_FSR3UPSCALER_OPTION_APPLY_SHARPENING=${_sharpen}
                          "-I${_fuse_wp42_ffx_gpu}" "-I${_fuse_wp42_ffx_gpu}/fsr3upscaler"
                          "${_fuse_wp42_ffx_vk}/ffx_fsr3upscaler_${_file}_pass.glsl" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp42_ffx_vk}/ffx_fsr3upscaler_${_file}_pass.glsl" ${_fuse_wp42_ffx_deps}
            COMMENT "glslangValidator FidelityFX FSR 3.1 ${_file} (vendored, sharpen=${_sharpen})"
            VERBATIM)
        list(APPEND _fuse_wp42_embed_args "-D${_key}=${_out}")
        list(APPEND _fuse_wp42_embed_deps "${_out}")
    endforeach()

    set(_out "${_fuse_wp42_spv}/fsr3_convert.glsl.spv")
    set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "${_fuse_wp42_shd}/fsr3_convert.comp" -o "${_out}")
    if(FUSE_SPIRV_VAL)
        list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
    endif()
    add_custom_command(OUTPUT "${_out}" ${_cmds}
        DEPENDS "${_fuse_wp42_shd}/fsr3_convert.comp"
        COMMENT "glslangValidator fsr3_convert.comp (GLSL twin)"
        VERBATIM)
    list(APPEND _fuse_wp42_embed_args "-DCONVERT_GLSL=${_out}")
    list(APPEND _fuse_wp42_embed_deps "${_out}")
endif()
if(COMMAND fuse_add_slang_shaders)
    fuse_add_slang_shaders(fuse_fsr3_kernels
        SOURCES "${_fuse_wp42_shd}/fsr3_convert.slang"
        STAGE compute
        SUFFIX ".fsr3_convert"
        FLAGS -fp-mode precise
        OUTPUT_DIR "${_fuse_wp42_spv}"
        OUTPUT_VAR _fuse_wp42_out)
    if(_fuse_wp42_out)
        list(APPEND _fuse_wp42_embed_args "-DCONVERT_SLANG=${_fuse_wp42_out}")
        list(APPEND _fuse_wp42_embed_deps "${_fuse_wp42_out}")
    endif()
endif()
add_custom_command(OUTPUT "${_fuse_wp42_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp42_header}" ${_fuse_wp42_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp42_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the FSR 3.1 passes' SPIR-V"
    VERBATIM)
add_custom_target(fuse_fsr3_header DEPENDS "${_fuse_wp42_header}")
add_dependencies(fuse_fsr3_header fuse_fsr3_kernels)
add_dependencies(fuse_fsr3 fuse_fsr3_header)
target_include_directories(fuse_fsr3 PRIVATE "${_fuse_wp42_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp42_tests_dir "${_fuse_wp42_root}/tests")

# --- CPU gates (host port, reflection vs C++ layouts, conventions; also run in the stub tree) ------------------
add_executable(fuse_rp_fsr3_cpu ${_fuse_wp42_tests_dir}/test_rp_fsr3_cpu.cpp)
target_link_libraries(fuse_rp_fsr3_cpu PRIVATE fuse_fsr3)
target_include_directories(fuse_rp_fsr3_cpu SYSTEM PRIVATE "${_fuse_wp42_ffx}/include")
fuse_apply_cxx23(fuse_rp_fsr3_cpu)
foreach(_suite layout bindings host jitter convert)
    add_test(NAME fuse_rp_fsr3_${_suite} COMMAND fuse_rp_fsr3_cpu ${_suite})
    set_tests_properties(fuse_rp_fsr3_${_suite} PROPERTIES LABELS "gate;renderer;fsr3" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------------
if(TARGET fuse_upscale_refscenes AND TARGET fuse_temporal)
    add_executable(fuse_rp_fsr3 ${_fuse_wp42_tests_dir}/test_rp_fsr3.cpp)
    target_link_libraries(fuse_rp_fsr3 PRIVATE fuse_fsr3 fuse_temporal fuse_upscale_refscenes)
    fuse_apply_cxx23(fuse_rp_fsr3)
    target_compile_definitions(fuse_rp_fsr3 PRIVATE
        FUSE_FSR3_REPORT_PATH="${CMAKE_CURRENT_BINARY_DIR}/fsr3_quality_report.json")

    # tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
    set(_fuse_wp42_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
    set(_fuse_wp42_vk_tests "")
    foreach(_case "quality;set" "determinism;set" "reset;set" "switch;set" "zero_alloc;set" "zero_alloc;buffer")
        list(GET _case 0 _mode)
        list(GET _case 1 _backend)
        set(_name "fuse_rp_fsr3_vk_${_mode}_${_backend}")
        if(FUSE_VULKAN_BACKEND)
            add_test(NAME ${_name}
                     COMMAND "${_fuse_wp42_lock}" "$<TARGET_FILE:fuse_rp_fsr3>" --mode ${_mode} --backend ${_backend})
        else()
            add_test(NAME ${_name} COMMAND fuse_rp_fsr3 --mode ${_mode} --backend ${_backend})
        endif()
        list(APPEND _fuse_wp42_vk_tests ${_name})
    endforeach()
    set_tests_properties(${_fuse_wp42_vk_tests} PROPERTIES
        ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
        RUN_SERIAL TRUE
        SKIP_RETURN_CODE 77
        TIMEOUT 1500
        LABELS "gate;vulkan;renderer;fsr3")
endif()
