# WP-7.1 (docs/unification/RENDERER-EXECUTION.md): light tree (light BVH with orientation bounds).
# Owned by WP-7.1; other packages must not edit this file.
#
#   fuse_light_tree       STATIC  LightTree (CPU build / refit / single-source sampler, light_tree_kernel.hpp),
#                                 the WP-1.1 GpuScene adapter, LightTreeGpu (ring-slot upload + the
#                                 "light_tree.sample" pass on render graph v2)
#                                 (include/fuse/renderer/light_tree/**, src/light_tree/**)
#   lt_sample             SPIR-V  Slang (primary) + GLSL twin, embedded in fuse_light_tree; the sampler library
#                                 shaders/light_tree/lt_common.{slang,glsl} is what consumers include
#   fuse_rp_light_tree_*  ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Script mode (build step): embed the kernel SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-DSLANG_SPV=<spv>] [-DGLSL_SPV=<spv>] -P rp_wp71.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp71.cmake from shaders/light_tree/lt_sample.*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        set(_spv "${${_lang}_SPV}")
        if(_spv AND EXISTS "${_spv}")
            file(READ "${_spv}" _hex HEX)
            string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
            if(_lang STREQUAL "SLANG")
                set(_name kLtSampleSlangSpv)
            else()
                set(_name kLtSampleGlslSpv)
            endif()
            string(APPEND _text "#define FUSE_LIGHT_TREE_${_lang} 1\n")
            string(APPEND _text "alignas(4) static const std::uint32_t ${_name}[] = {${_words}};\n")
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp71_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp71_inc "${_fuse_wp71_root}/include/fuse/renderer/light_tree")
set(_fuse_wp71_src "${_fuse_wp71_root}/src/light_tree")
set(_fuse_wp71_shd "${_fuse_wp71_root}/shaders/light_tree")

file(GLOB _fuse_wp71_shader_files CONFIGURE_DEPENDS "${_fuse_wp71_shd}/*")
add_library(fuse_light_tree STATIC
    ${_fuse_wp71_src}/light_tree.cpp
    ${_fuse_wp71_src}/light_tree_gpu.cpp
    ${_fuse_wp71_inc}/light_tree_types.hpp
    ${_fuse_wp71_inc}/light_tree_kernel.hpp
    ${_fuse_wp71_inc}/light_tree.hpp
    ${_fuse_wp71_inc}/light_tree_gpu.hpp
    ${_fuse_wp71_shader_files}
)
set_source_files_properties(${_fuse_wp71_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_light_tree PUBLIC fuse_rhi PRIVATE fuse_gpu_scene fuse_ltc fuse_geometry)
fuse_apply_cxx23(fuse_light_tree)
# The CPU sampler must round like the kernels (no multiply-add contraction): PUBLIC, so every user of
# light_tree_kernel.hpp (tests, WP-7.2 references) compiles it the same way.
if(MSVC AND CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    target_compile_options(fuse_light_tree PUBLIC /fp:precise /clang:-ffp-contract=off) # clang-cl
elseif(MSVC)
    target_compile_options(fuse_light_tree PUBLIC /fp:precise) # no /fp:contract: MSVC does not contract then
elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(fuse_light_tree PUBLIC -ffp-contract=off)
endif()

# Kernel, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the GLSL twin
# keeps the pass available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
# Slang: -fp-mode precise; GLSL: `precise` (the samples must be the CPU sampler's bits).
set(_fuse_wp71_gen "${CMAKE_CURRENT_BINARY_DIR}/light_tree_gen")
set(_fuse_wp71_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/light_tree")
file(MAKE_DIRECTORY "${_fuse_wp71_gen}" "${_fuse_wp71_spv}")
set(_fuse_wp71_header "${_fuse_wp71_gen}/light_tree_spv.h")
add_custom_target(fuse_light_tree_kernels)
set(_fuse_wp71_embed_args "")
set(_fuse_wp71_embed_deps "")
if(COMMAND fuse_add_slang_shaders)
    fuse_add_slang_shaders(fuse_light_tree_kernels
        SOURCES "${_fuse_wp71_shd}/lt_sample.slang"
        STAGE compute
        SUFFIX ".lt_sample"
        INCLUDE_DIRS "${_fuse_wp71_shd}"
        FLAGS -fp-mode precise
        OUTPUT_DIR "${_fuse_wp71_spv}"
        OUTPUT_VAR _fuse_wp71_slang_out)
    if(_fuse_wp71_slang_out)
        list(APPEND _fuse_wp71_embed_args "-DSLANG_SPV=${_fuse_wp71_slang_out}")
        list(APPEND _fuse_wp71_embed_deps "${_fuse_wp71_slang_out}")
    endif()
endif()
if(FUSE_GLSLANG_VALIDATOR)
    set(_out "${_fuse_wp71_spv}/lt_sample.glsl.spv")
    set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp71_shd}"
                      "${_fuse_wp71_shd}/lt_sample.comp" -o "${_out}")
    if(FUSE_SPIRV_VAL)
        list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
    endif()
    add_custom_command(OUTPUT "${_out}" ${_cmds}
        DEPENDS "${_fuse_wp71_shd}/lt_sample.comp" "${_fuse_wp71_shd}/lt_common.glsl"
        COMMENT "glslangValidator lt_sample.comp (GLSL twin)"
        VERBATIM)
    list(APPEND _fuse_wp71_embed_args "-DGLSL_SPV=${_out}")
    list(APPEND _fuse_wp71_embed_deps "${_out}")
endif()
add_custom_command(OUTPUT "${_fuse_wp71_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp71_header}" ${_fuse_wp71_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp71_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the light tree kernel's SPIR-V"
    VERBATIM)
add_custom_target(fuse_light_tree_header DEPENDS "${_fuse_wp71_header}")
add_dependencies(fuse_light_tree_header fuse_light_tree_kernels)
add_dependencies(fuse_light_tree fuse_light_tree_header)
target_include_directories(fuse_light_tree PRIVATE "${_fuse_wp71_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp71_tests_dir "${_fuse_wp71_root}/tests")

# --- CPU gates (stub-safe) -----------------------------------------------------------------------
add_executable(fuse_rp_light_tree_cpu ${_fuse_wp71_tests_dir}/test_rp_light_tree_cpu.cpp)
target_link_libraries(fuse_rp_light_tree_cpu PRIVATE fuse_light_tree fuse_gpu_scene fuse_ltc fuse_geometry)
target_compile_definitions(fuse_rp_light_tree_cpu PRIVATE FUSE_RP_LIGHT_TREE_SHADER_DIR="${_fuse_wp71_shd}")
fuse_apply_cxx23(fuse_rp_light_tree_cpu)
foreach(_suite layout pmf_sum area_pdf histogram refit adapter zero_alloc)
    add_test(NAME fuse_rp_light_tree_${_suite} COMMAND fuse_rp_light_tree_cpu ${_suite})
    set_tests_properties(fuse_rp_light_tree_${_suite} PROPERTIES LABELS "gate;renderer;light_tree" TIMEOUT 900)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_light_tree ${_fuse_wp71_tests_dir}/test_rp_light_tree.cpp)
target_link_libraries(fuse_rp_light_tree PRIVATE fuse_light_tree)
fuse_apply_cxx23(fuse_rp_light_tree)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp71_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp71_vk_tests "")
foreach(_case "sample;set" "sample;buffer" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_light_tree_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp71_lock}" "$<TARGET_FILE:fuse_rp_light_tree>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_light_tree --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp71_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp71_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;light_tree")
