# WP-2.3 (docs/unification/RENDERER-EXECUTION.md): forward transparency.
# Owned by WP-2.3; other packages must not edit this file.
#
#   fuse_forward        STATIC  ForwardTransparency (CPU collection + back-to-front sort of the GpuScene's
#                               kInstanceTransparent instances, forward.copy of the lit image, forward.draw
#                               blending over it with the WP-2.1 cluster lists and shade functions, depth
#                               test against the visibility buffer's depth) + the CPU references
#                               (forward_reference.hpp) (include/fuse/renderer/forward/**, src/forward/**)
#   fw_* shaders        SPIR-V  Slang (primary) + GLSL twins, embedded in fuse_forward
#   fuse_rp_forward_*   ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded shader, '|'-separated: KEY | C++ name stem | GLSL source | Slang source | stage
set(_fuse_wp23_kernels
    "VS|Vs|fw_forward.vert|fw_forward_vs.slang|vertex"
    "FS|Fs|fw_forward.frag|fw_forward_fs.slang|fragment")

# Script mode (build step): embed the shaders' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp23.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp23.cmake from shaders/forward/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp23_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_FORWARD_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp23_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kFw${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp23_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp23_inc "${_fuse_wp23_root}/include/fuse/renderer/forward")
set(_fuse_wp23_src "${_fuse_wp23_root}/src/forward")
set(_fuse_wp23_shd "${_fuse_wp23_root}/shaders/forward")
set(_fuse_wp23_scene_inc "${_fuse_wp23_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp23_common_inc "${_fuse_wp23_root}/shaders/common")
set(_fuse_wp23_vis_shd "${_fuse_wp23_root}/shaders/visbuffer")
set(_fuse_wp23_mr_shd "${_fuse_wp23_root}/shaders/material_resolve")
set(_fuse_wp23_lc_shd "${_fuse_wp23_root}/shaders/lighting")

file(GLOB _fuse_wp23_shader_files CONFIGURE_DEPENDS "${_fuse_wp23_shd}/*")
add_library(fuse_forward STATIC
    ${_fuse_wp23_src}/forward_transparency.cpp
    ${_fuse_wp23_inc}/forward_types.hpp
    ${_fuse_wp23_inc}/forward_reference.hpp
    ${_fuse_wp23_inc}/forward_transparency.hpp
    ${_fuse_wp23_shader_files}
)
set_source_files_properties(${_fuse_wp23_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_forward PUBLIC fuse_lighting_gpu)
fuse_apply_cxx23(fuse_forward)

# Shaders, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the
# GLSL twins keep the pass available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
# They include the WP-1.5 material evaluation (shaders/material_resolve/mr_common) and the WP-2.1
# shading (shaders/lighting/lc_common) unchanged, so any change there reaches the forward pass.
set(_fuse_wp23_gen "${CMAKE_CURRENT_BINARY_DIR}/forward_gen")
set(_fuse_wp23_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/forward")
file(MAKE_DIRECTORY "${_fuse_wp23_gen}" "${_fuse_wp23_spv}")
set(_fuse_wp23_header "${_fuse_wp23_gen}/forward_spv.h")
add_custom_target(fuse_forward_kernels)
set(_fuse_wp23_embed_args "")
set(_fuse_wp23_embed_deps "")
file(GLOB _fuse_wp23_glsl_includes "${_fuse_wp23_shd}/*.glsl" "${_fuse_wp23_vis_shd}/*.glsl" "${_fuse_wp23_mr_shd}/*.glsl"
     "${_fuse_wp23_lc_shd}/*.glsl" "${_fuse_wp23_common_inc}/*.glsl")

foreach(_row IN LISTS _fuse_wp23_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    list(GET _entry 4 _stage)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_forward_kernels
            SOURCES "${_fuse_wp23_shd}/${_slang}"
            STAGE ${_stage}
            SUFFIX ".fw_${_suffix}"
            INCLUDE_DIRS "${_fuse_wp23_scene_inc}" "${_fuse_wp23_vis_shd}" "${_fuse_wp23_mr_shd}" "${_fuse_wp23_lc_shd}"
                         "${_fuse_wp23_shd}"
            # 39001: the bindless arrays alias one binding on purpose; 41012: the fragment stage's
            # implicit capability upgrade.
            FLAGS -warnings-disable 39001 -warnings-disable 41012 -fp-mode precise
            OUTPUT_DIR "${_fuse_wp23_spv}"
            OUTPUT_VAR _fuse_wp23_out)
        if(_fuse_wp23_out)
            list(APPEND _fuse_wp23_embed_args "-D${_key}_SLANG=${_fuse_wp23_out}")
            list(APPEND _fuse_wp23_embed_deps "${_fuse_wp23_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp23_spv}/fw_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp23_common_inc}"
                          "-I${_fuse_wp23_scene_inc}" "-I${_fuse_wp23_vis_shd}" "-I${_fuse_wp23_mr_shd}" "-I${_fuse_wp23_lc_shd}"
                          "-I${_fuse_wp23_shd}" "${_fuse_wp23_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp23_shd}/${_glsl}" ${_fuse_wp23_glsl_includes} "${_fuse_wp23_scene_inc}/gpu_scene.glsl"
            COMMENT "glslangValidator ${_glsl} (fw_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp23_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp23_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp23_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp23_header}" ${_fuse_wp23_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp23_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the forward-transparency shaders' SPIR-V"
    VERBATIM)
add_custom_target(fuse_forward_header DEPENDS "${_fuse_wp23_header}")
add_dependencies(fuse_forward_header fuse_forward_kernels)
add_dependencies(fuse_forward fuse_forward_header)
target_include_directories(fuse_forward PRIVATE "${_fuse_wp23_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp23_tests_dir "${_fuse_wp23_root}/tests")

# --- CPU gates (collection / sort / blend references; also run in the stub tree) -----------------
add_executable(fuse_rp_forward_cpu ${_fuse_wp23_tests_dir}/test_rp_forward_cpu.cpp)
target_link_libraries(fuse_rp_forward_cpu PRIVATE fuse_forward)
fuse_apply_cxx23(fuse_rp_forward_cpu)
foreach(_suite layout collect sort blend api)
    add_test(NAME fuse_rp_forward_${_suite} COMMAND fuse_rp_forward_cpu ${_suite})
    set_tests_properties(fuse_rp_forward_${_suite} PROPERTIES LABELS "gate;renderer;forward" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_forward ${_fuse_wp23_tests_dir}/test_rp_forward.cpp)
target_link_libraries(fuse_rp_forward PRIVATE fuse_forward)
fuse_apply_cxx23(fuse_rp_forward)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp23_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp23_vk_tests "")
foreach(_case "twin;set" "twin;buffer" "blend;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_forward_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp23_lock}" "$<TARGET_FILE:fuse_rp_forward>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_forward --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp23_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp23_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;forward")
