# WP-1.3 (docs/unification/RENDERER-EXECUTION.md): instance cull + Hi-Z + indirect-count.
# Owned by WP-1.3; other packages must not edit this file.
#
#   fuse_culling          STATIC  InstanceCuller (two-phase occlusion, single-pass Hi-Z, draw-indirect-count
#                                 args, all as render-graph v2 passes) + CPU reference helpers
#                                 (include/fuse/renderer/culling/**, src/culling/**)
#   instance_cull         SPIR-V  both cull phases, Slang (primary) + GLSL twin, embedded in fuse_culling
#   hiz_build             SPIR-V  SPD-style single-pass Hi-Z, Slang + GLSL twin, embedded in fuse_culling
#   cull_draw             SPIR-V  test raster (vertex + fragment), Slang + GLSL twin, files for the gate
#   fuse_rp_culling_*     ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Script mode (build step): embed the kernel SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-DCULL_SLANG=<spv> -DHIZ_SLANG=<spv>] [-DCULL_GLSL=<spv> -DHIZ_GLSL=<spv>] -P rp_wp13.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp13.cmake from shaders/culling/{instance_cull,hiz_build}.{slang,comp}.\n")
    string(APPEND _text "// Do not edit.\n#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(CULL_${_lang} AND HIZ_${_lang} AND EXISTS "${CULL_${_lang}}" AND EXISTS "${HIZ_${_lang}}")
            if(_lang STREQUAL "SLANG")
                set(_suffix Slang)
            else()
                set(_suffix Glsl)
            endif()
            string(APPEND _text "#define FUSE_CULLING_${_lang} 1\n")
            foreach(_kernel CULL HIZ)
                file(READ "${${_kernel}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                if(_kernel STREQUAL "CULL")
                    set(_name kCullingCull${_suffix}Spv)
                else()
                    set(_name kCullingHiz${_suffix}Spv)
                endif()
                string(APPEND _text "alignas(4) static const std::uint32_t ${_name}[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp13_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp13_inc "${_fuse_wp13_root}/include/fuse/renderer/culling")
set(_fuse_wp13_src "${_fuse_wp13_root}/src/culling")
set(_fuse_wp13_shd "${_fuse_wp13_root}/shaders/culling")
set(_fuse_wp13_scene_inc "${_fuse_wp13_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp13_common_inc "${_fuse_wp13_root}/shaders/common")

add_library(fuse_culling STATIC
    ${_fuse_wp13_src}/instance_culler.cpp
    ${_fuse_wp13_src}/cull_reference.cpp
    ${_fuse_wp13_inc}/cull_types.hpp
    ${_fuse_wp13_inc}/hiz_build_kernel.hpp
    ${_fuse_wp13_inc}/instance_cull_kernel.hpp
    ${_fuse_wp13_inc}/cull_reference.hpp
    ${_fuse_wp13_inc}/instance_culler.hpp
    ${_fuse_wp13_shd}/cull_common.glsl
    ${_fuse_wp13_shd}/cull_common.slang
    ${_fuse_wp13_shd}/instance_cull.comp
    ${_fuse_wp13_shd}/instance_cull.slang
    ${_fuse_wp13_shd}/hiz_build.comp
    ${_fuse_wp13_shd}/hiz_build.slang
)
target_link_libraries(fuse_culling PUBLIC fuse_gpu_scene fuse_geometry)
fuse_apply_cxx23(fuse_culling)

# Kernels, embedded into the library. Slang is the primary source (renderer plan §4, execution doc §8
# decision 1a); the GLSL twins keep culling available where slangc is not (FUSE_SLANG=AUTO), and the
# gates run both and require identical results. instance_cull.slang is compiled with
# -fp-mode precise (Slang does not honour `precise` per variable), so neither twin contracts FMAs.
set(_fuse_wp13_gen "${CMAKE_CURRENT_BINARY_DIR}/culling_gen")
set(_fuse_wp13_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/culling")
file(MAKE_DIRECTORY "${_fuse_wp13_gen}" "${_fuse_wp13_spv}")
set(_fuse_wp13_header "${_fuse_wp13_gen}/culling_spv.h")
add_custom_target(fuse_culling_kernels)
set(_fuse_wp13_embed_args "")
set(_fuse_wp13_embed_deps "")
if(COMMAND fuse_add_slang_shaders)
    fuse_add_slang_shaders(fuse_culling_kernels
        SOURCES "${_fuse_wp13_shd}/instance_cull.slang"
        STAGE compute
        INCLUDE_DIRS "${_fuse_wp13_scene_inc}" "${_fuse_wp13_shd}"
        FLAGS -fp-mode precise
        OUTPUT_DIR "${_fuse_wp13_spv}"
        OUTPUT_VAR _fuse_wp13_cull_slang)
    fuse_add_slang_shaders(fuse_culling_kernels
        SOURCES "${_fuse_wp13_shd}/hiz_build.slang"
        STAGE compute
        INCLUDE_DIRS "${_fuse_wp13_scene_inc}" "${_fuse_wp13_shd}"
        OUTPUT_DIR "${_fuse_wp13_spv}"
        OUTPUT_VAR _fuse_wp13_hiz_slang)
    if(_fuse_wp13_cull_slang AND _fuse_wp13_hiz_slang)
        list(APPEND _fuse_wp13_embed_args "-DCULL_SLANG=${_fuse_wp13_cull_slang}" "-DHIZ_SLANG=${_fuse_wp13_hiz_slang}")
        list(APPEND _fuse_wp13_embed_deps "${_fuse_wp13_cull_slang}" "${_fuse_wp13_hiz_slang}")
    endif()
endif()

# glslangValidator -> SPIR-V (+ spirv-val) for one GLSL source; sets <out_var> to the .spv path.
function(_fuse_wp13_glsl src out_name out_var)
    set(_out "${_fuse_wp13_spv}/${out_name}")
    set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp13_common_inc}"
                      "-I${_fuse_wp13_scene_inc}" "-I${_fuse_wp13_shd}" "${src}" -o "${_out}")
    if(FUSE_SPIRV_VAL)
        list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
    endif()
    add_custom_command(OUTPUT "${_out}" ${_cmds}
        DEPENDS "${src}" "${_fuse_wp13_shd}/cull_common.glsl" "${_fuse_wp13_scene_inc}/gpu_scene.glsl"
                "${_fuse_wp13_common_inc}/bindless.glsl"
        COMMENT "glslangValidator ${out_name} (GLSL twin)"
        VERBATIM)
    set(${out_var} "${_out}" PARENT_SCOPE)
endfunction()

if(FUSE_GLSLANG_VALIDATOR)
    _fuse_wp13_glsl("${_fuse_wp13_shd}/instance_cull.comp" instance_cull.comp.spv _fuse_wp13_cull_glsl)
    _fuse_wp13_glsl("${_fuse_wp13_shd}/hiz_build.comp" hiz_build.comp.spv _fuse_wp13_hiz_glsl)
    list(APPEND _fuse_wp13_embed_args "-DCULL_GLSL=${_fuse_wp13_cull_glsl}" "-DHIZ_GLSL=${_fuse_wp13_hiz_glsl}")
    list(APPEND _fuse_wp13_embed_deps "${_fuse_wp13_cull_glsl}" "${_fuse_wp13_hiz_glsl}")
endif()
add_custom_command(OUTPUT "${_fuse_wp13_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp13_header}" ${_fuse_wp13_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp13_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the culling kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_culling_header DEPENDS "${_fuse_wp13_header}")
add_dependencies(fuse_culling_header fuse_culling_kernels)
add_dependencies(fuse_culling fuse_culling_header)
target_include_directories(fuse_culling PRIVATE "${_fuse_wp13_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

# --- CPU gates (reference kernels; also run in the stub tree) --------------------------------------
set(_fuse_wp13_tests_dir "${_fuse_wp13_root}/tests")
add_executable(fuse_rp_culling_cpu ${_fuse_wp13_tests_dir}/test_rp_culling_cpu.cpp)
target_link_libraries(fuse_rp_culling_cpu PRIVATE fuse_culling)
fuse_apply_cxx23(fuse_rp_culling_cpu)
foreach(_suite hiz frustum occlusion phases parity api)
    add_test(NAME fuse_rp_culling_${_suite} COMMAND fuse_rp_culling_cpu ${_suite})
    set_tests_properties(fuse_rp_culling_${_suite} PROPERTIES LABELS "gate;renderer;culling" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_culling ${_fuse_wp13_tests_dir}/test_rp_culling.cpp)
target_link_libraries(fuse_rp_culling PRIVATE fuse_culling)
fuse_apply_cxx23(fuse_rp_culling)

# Test raster shaders (vertex pulls the instance transform from the scene by gl_InstanceIndex).
add_custom_target(fuse_rp_culling_shaders)
set(_fuse_wp13_defs "")
if(COMMAND fuse_add_slang_shaders)
    fuse_add_slang_shaders(fuse_rp_culling_shaders
        SOURCES "${_fuse_wp13_shd}/test/cull_draw_vs.slang"
        STAGE vertex
        INCLUDE_DIRS "${_fuse_wp13_scene_inc}"
        OUTPUT_DIR "${_fuse_wp13_spv}"
        OUTPUT_VAR _fuse_wp13_vs_slang)
    fuse_add_slang_shaders(fuse_rp_culling_shaders
        SOURCES "${_fuse_wp13_shd}/test/cull_draw_fs.slang"
        STAGE fragment
        OUTPUT_DIR "${_fuse_wp13_spv}"
        OUTPUT_VAR _fuse_wp13_fs_slang)
    if(_fuse_wp13_vs_slang AND _fuse_wp13_fs_slang)
        list(APPEND _fuse_wp13_defs FUSE_RP_CULLING_SLANG_VS="${_fuse_wp13_vs_slang}"
                                    FUSE_RP_CULLING_SLANG_FS="${_fuse_wp13_fs_slang}")
    endif()
endif()
if(FUSE_GLSLANG_VALIDATOR)
    _fuse_wp13_glsl("${_fuse_wp13_shd}/test/cull_draw.vert" cull_draw.vert.spv _fuse_wp13_vs_glsl)
    _fuse_wp13_glsl("${_fuse_wp13_shd}/test/cull_draw.frag" cull_draw.frag.spv _fuse_wp13_fs_glsl)
    add_custom_target(fuse_rp_culling_glsl DEPENDS "${_fuse_wp13_vs_glsl}" "${_fuse_wp13_fs_glsl}")
    add_dependencies(fuse_rp_culling_shaders fuse_rp_culling_glsl)
    list(APPEND _fuse_wp13_defs FUSE_RP_CULLING_GLSL_VS="${_fuse_wp13_vs_glsl}"
                                FUSE_RP_CULLING_GLSL_FS="${_fuse_wp13_fs_glsl}")
endif()
add_dependencies(fuse_rp_culling fuse_rp_culling_shaders)
target_compile_definitions(fuse_rp_culling PRIVATE ${_fuse_wp13_defs})

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp13_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp13_vk_tests "")
foreach(_case "parity;set" "parity;buffer" "camera_cut;set" "camera_cut;buffer" "submit_flat;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_culling_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp13_lock}" "$<TARGET_FILE:fuse_rp_culling>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_culling --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp13_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp13_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;culling")
