# WP-7.2 (docs/unification/RENDERER-EXECUTION.md): ReSTIR DI and GI (tier T2, ray queries).
# Owned by WP-7.2; other packages must not edit this file.
#
#   fuse_restir          STATIC  settings / frame constants / light table (restir.hpp), the single-source kernel
#                                (restir_kernel.hpp), the CPU runner + f64 reference (restir_reference.hpp) and
#                                RestirGpu (restir_gpu.hpp: restir.* passes on render graph v2)
#                                (include/fuse/renderer/restir/**, src/restir/**)
#   restir kernels       SPIR-V  Slang (primary) + GLSL twins (shaders/restir/**), embedded in fuse_restir
#   fuse_rp_restir_*     ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source (shaders/restir/).
set(_fuse_wp72_kernels
    "PREPARE|Prepare|restir_prepare.comp|restir_prepare.slang"
    "DI_INITIAL|DiInitial|restir_di_initial.comp|restir_di_initial.slang"
    "DI_REUSE|DiReuse|restir_di_reuse.comp|restir_di_reuse.slang"
    "GI_INITIAL|GiInitial|restir_gi_initial.comp|restir_gi_initial.slang"
    "GI_REUSE|GiReuse|restir_gi_reuse.comp|restir_gi_reuse.slang"
    "SHADE|Shade|restir_shade.comp|restir_shade.slang")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp72.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp72.cmake from shaders/restir/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp72_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_RESTIR_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp72_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kRestir${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp72_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp72_inc "${_fuse_wp72_root}/include/fuse/renderer/restir")
set(_fuse_wp72_src "${_fuse_wp72_root}/src/restir")
set(_fuse_wp72_shd "${_fuse_wp72_root}/shaders/restir")
set(_fuse_wp72_lt_shd "${_fuse_wp72_root}/shaders/light_tree")
set(_fuse_wp72_scene_inc "${_fuse_wp72_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp72_common_inc "${_fuse_wp72_root}/shaders/common")
set(_fuse_wp72_tests_dir "${_fuse_wp72_root}/tests")

set(_fuse_wp72_warn "")
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
    set(_fuse_wp72_warn -Wall -Wextra -Werror)
endif()

file(GLOB _fuse_wp72_shader_files CONFIGURE_DEPENDS "${_fuse_wp72_shd}/*")
add_library(fuse_restir STATIC
    ${_fuse_wp72_src}/restir.cpp
    ${_fuse_wp72_src}/restir_reference.cpp
    ${_fuse_wp72_src}/restir_gpu.cpp
    ${_fuse_wp72_inc}/restir_types.hpp
    ${_fuse_wp72_inc}/restir_kernel.hpp
    ${_fuse_wp72_inc}/restir.hpp
    ${_fuse_wp72_inc}/restir_reference.hpp
    ${_fuse_wp72_inc}/restir_gpu.hpp
    ${_fuse_wp72_shader_files}
)
set_source_files_properties(${_fuse_wp72_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
# fuse_light_tree is PUBLIC: it carries -ffp-contract=off (the kernel must round like the GPU twins) to every
# user of restir_kernel.hpp. fuse_rt: the T2 capability gate. fuse_material_resolve / fuse_gpu_scene: the inputs.
target_link_libraries(fuse_restir PUBLIC fuse_light_tree fuse_rt fuse_material_resolve fuse_gpu_scene)
target_compile_options(fuse_restir PRIVATE ${_fuse_wp72_warn})
fuse_apply_cxx23(fuse_restir)

# Kernels, embedded into fuse_restir: Slang primary, GLSL twins (the gates run both).
set(_fuse_wp72_gen "${CMAKE_CURRENT_BINARY_DIR}/restir_gen")
set(_fuse_wp72_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/restir")
file(MAKE_DIRECTORY "${_fuse_wp72_gen}" "${_fuse_wp72_spv}")
set(_fuse_wp72_header "${_fuse_wp72_gen}/restir_spv.h")
add_custom_target(fuse_restir_kernels)
set(_fuse_wp72_embed_args "")
set(_fuse_wp72_embed_deps "")
set(_fuse_wp72_glsl_deps "${_fuse_wp72_shd}/restir_common.glsl" "${_fuse_wp72_lt_shd}/lt_common.glsl"
                         "${_fuse_wp72_scene_inc}/gpu_scene.glsl" "${_fuse_wp72_common_inc}/bindless.glsl")
foreach(_row IN LISTS _fuse_wp72_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_restir_kernels
            SOURCES "${_fuse_wp72_shd}/${_slang}"
            STAGE compute
            SUFFIX ".restir_${_suffix}"
            INCLUDE_DIRS "${_fuse_wp72_scene_inc}" "${_fuse_wp72_lt_shd}" "${_fuse_wp72_shd}"
            # 39001: the bindless arrays alias one binding on purpose.
            FLAGS -warnings-disable 39001 -fp-mode precise -capability spvRayQueryKHR
            OUTPUT_DIR "${_fuse_wp72_spv}"
            OUTPUT_VAR _fuse_wp72_out)
        if(_fuse_wp72_out)
            list(APPEND _fuse_wp72_embed_args "-D${_key}_SLANG=${_fuse_wp72_out}")
            list(APPEND _fuse_wp72_embed_deps "${_fuse_wp72_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp72_spv}/restir_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp72_common_inc}" "-I${_fuse_wp72_scene_inc}"
                          "-I${_fuse_wp72_lt_shd}" "-I${_fuse_wp72_shd}" "${_fuse_wp72_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp72_shd}/${_glsl}" ${_fuse_wp72_glsl_deps}
            COMMENT "glslangValidator ${_glsl} (restir_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp72_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp72_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp72_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp72_header}" ${_fuse_wp72_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp72_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the ReSTIR kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_restir_header DEPENDS "${_fuse_wp72_header}")
add_dependencies(fuse_restir_header fuse_restir_kernels)
add_dependencies(fuse_restir fuse_restir_header)
target_include_directories(fuse_restir PRIVATE "${_fuse_wp72_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

# --- CPU gates (layouts, API, unbiasedness, variance, bias, allocations; also run in the stub tree) ----------
add_executable(fuse_rp_restir_cpu ${_fuse_wp72_tests_dir}/test_rp_restir_cpu.cpp)
target_link_libraries(fuse_rp_restir_cpu PRIVATE fuse_restir fuse_geometry)
target_compile_definitions(fuse_rp_restir_cpu PRIVATE "FUSE_RP_RESTIR_SHADER_DIR=\"${_fuse_wp72_shd}\"")
target_compile_options(fuse_rp_restir_cpu PRIVATE ${_fuse_wp72_warn})
fuse_apply_cxx23(fuse_rp_restir_cpu)
foreach(_suite layout api unbiased variance biased reuse zero_alloc)
    add_test(NAME fuse_rp_restir_${_suite} COMMAND fuse_rp_restir_cpu ${_suite})
    set_tests_properties(fuse_rp_restir_${_suite} PROPERTIES LABELS "gate;renderer;restir" TIMEOUT 1800)
endforeach()

# --- Lavapipe gates --------------------------------------------------------------------------------------------
add_executable(fuse_rp_restir ${_fuse_wp72_tests_dir}/test_rp_restir.cpp)
target_link_libraries(fuse_rp_restir PRIVATE fuse_restir fuse_rt_reference fuse_denoise fuse_geometry)
target_compile_options(fuse_rp_restir PRIVATE ${_fuse_wp72_warn})
fuse_apply_cxx23(fuse_rp_restir)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp72_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp72_vk_tests "")
foreach(_case "passes;set" "passes;buffer" "denoise;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_restir_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp72_lock}" "$<TARGET_FILE:fuse_rp_restir>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_restir --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp72_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp72_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 1800
    LABELS "gate;vulkan;renderer;restir")
