# WP-6.0 (docs/unification/RENDERER-EXECUTION.md): acceleration structures (tier T2).
# Owned by WP-6.0; other packages must not edit this file.
#
#   fuse_rt            STATIC  BLAS per GPU-scene mesh (scene index buffer + ranges), TLAS from the GPU
#                              scene's instance slots (GPU instance packing, CPU fallback), compaction,
#                              refit (moving instances, deforming meshes), T2 caps gate, ray-query probe
#                              (include/fuse/renderer/rt/**, src/rt/**)
#   fuse_rt_reference  STATIC  CPU reference: two-level fuse::spatial::BVH (ECS/Spatial CPU BVH)
#   rt kernels         SPIR-V  Slang (primary) + GLSL twins (shaders/rt/**), embedded in fuse_rt
#   fuse_rp_rt_*       ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source | extra slangc flags
# (space-separated; sources relative to shaders/rt/).
set(_fuse_wp60_kernels
    "DECODE|Decode|rt_decode.comp|rt_decode.slang|"
    "INSTANCES|Instances|rt_instances.comp|rt_instances.slang|"
    "PROBE|Probe|rt_probe.comp|rt_probe.slang|-capability spvRayQueryKHR")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp60.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp60.cmake from shaders/rt/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp60_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_RT_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp60_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kRt${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp60_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp60_inc "${_fuse_wp60_root}/include/fuse/renderer/rt")
set(_fuse_wp60_src "${_fuse_wp60_root}/src/rt")
set(_fuse_wp60_shd "${_fuse_wp60_root}/shaders/rt")
set(_fuse_wp60_tests_dir "${_fuse_wp60_root}/tests")

set(_fuse_wp60_warn "")
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
    set(_fuse_wp60_warn -Wall -Wextra -Werror)
endif()

file(GLOB _fuse_wp60_shader_files CONFIGURE_DEPENDS "${_fuse_wp60_shd}/*")
add_library(fuse_rt STATIC
    ${_fuse_wp60_src}/rt_caps.cpp
    ${_fuse_wp60_src}/acceleration_structures.cpp
    ${_fuse_wp60_src}/rt_probe.cpp
    ${_fuse_wp60_inc}/rt_types.hpp
    ${_fuse_wp60_inc}/rt_caps.hpp
    ${_fuse_wp60_inc}/acceleration_structures.hpp
    ${_fuse_wp60_inc}/rt_probe.hpp
    ${_fuse_wp60_shader_files}
)
set_source_files_properties(${_fuse_wp60_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_rt PUBLIC fuse_gpu_scene)
target_compile_options(fuse_rt PRIVATE ${_fuse_wp60_warn})
fuse_apply_cxx23(fuse_rt)

add_library(fuse_rt_reference STATIC
    ${_fuse_wp60_src}/rt_reference.cpp
    ${_fuse_wp60_inc}/rt_reference.hpp
)
target_link_libraries(fuse_rt_reference PUBLIC fuse_rt fuse_ecs)
target_compile_options(fuse_rt_reference PRIVATE ${_fuse_wp60_warn})
fuse_apply_cxx23(fuse_rt_reference)

# Kernels, embedded into fuse_rt. Slang is the primary source (execution doc §8 decision 1a); the GLSL
# twins keep the path available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
set(_fuse_wp60_gen "${CMAKE_CURRENT_BINARY_DIR}/rt_gen")
set(_fuse_wp60_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/rt")
file(MAKE_DIRECTORY "${_fuse_wp60_gen}" "${_fuse_wp60_spv}")
set(_fuse_wp60_header "${_fuse_wp60_gen}/rt_spv.h")
add_custom_target(fuse_rt_kernels)
set(_fuse_wp60_embed_args "")
set(_fuse_wp60_embed_deps "")
cmake_policy(PUSH)
cmake_policy(SET CMP0007 NEW) # list(GET) keeps the empty flags field
foreach(_row IN LISTS _fuse_wp60_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    list(GET _entry 4 _flags)
    separate_arguments(_flags UNIX_COMMAND "${_flags}")
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_rt_kernels
            SOURCES "${_fuse_wp60_shd}/${_slang}"
            STAGE compute
            SUFFIX ".${_suffix}"
            INCLUDE_DIRS "${_fuse_wp60_shd}"
            FLAGS -fp-mode precise ${_flags}
            OUTPUT_DIR "${_fuse_wp60_spv}"
            OUTPUT_VAR _fuse_wp60_out)
        if(_fuse_wp60_out)
            list(APPEND _fuse_wp60_embed_args "-D${_key}_SLANG=${_fuse_wp60_out}")
            list(APPEND _fuse_wp60_embed_deps "${_fuse_wp60_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp60_spv}/${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp60_shd}" "${_fuse_wp60_shd}/${_glsl}"
                          -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp60_shd}/${_glsl}" "${_fuse_wp60_shd}/rt_common.glsl"
            COMMENT "glslangValidator ${_glsl} (rt ${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp60_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp60_embed_deps "${_out}")
    endif()
endforeach()
cmake_policy(POP)
add_custom_command(OUTPUT "${_fuse_wp60_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp60_header}" ${_fuse_wp60_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp60_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the acceleration-structure kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_rt_header DEPENDS "${_fuse_wp60_header}")
add_dependencies(fuse_rt_header fuse_rt_kernels)
add_dependencies(fuse_rt fuse_rt_header)
target_include_directories(fuse_rt PRIVATE "${_fuse_wp60_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

# --- CPU gates (layouts, packing, T2 rule, CPU reference; also run in the stub tree) ----------------
add_executable(fuse_rp_rt_cpu ${_fuse_wp60_tests_dir}/test_rp_rt_cpu.cpp)
target_link_libraries(fuse_rp_rt_cpu PRIVATE fuse_rt_reference)
target_compile_definitions(fuse_rp_rt_cpu PRIVATE "FUSE_RT_SHADER_DIR=\"${_fuse_wp60_shd}\"")
target_compile_options(fuse_rp_rt_cpu PRIVATE ${_fuse_wp60_warn})
fuse_apply_cxx23(fuse_rp_rt_cpu)
foreach(_suite layout pack caps reference refit)
    add_test(NAME fuse_rp_rt_${_suite} COMMAND fuse_rp_rt_cpu ${_suite})
    set_tests_properties(fuse_rp_rt_${_suite} PROPERTIES LABELS "gate;renderer;rt" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------------
add_executable(fuse_rp_rt ${_fuse_wp60_tests_dir}/test_rp_rt.cpp)
target_link_libraries(fuse_rp_rt PRIVATE fuse_rt_reference fuse_geometry)
target_compile_options(fuse_rp_rt PRIVATE ${_fuse_wp60_warn})
fuse_apply_cxx23(fuse_rp_rt)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp60_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp60_vk_tests "")
foreach(_mode parity cpu_packing refit compaction zero_alloc caps_gate bindless_order)
    set(_name "fuse_rp_rt_vk_${_mode}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name} COMMAND "${_fuse_wp60_lock}" "$<TARGET_FILE:fuse_rp_rt>" --mode ${_mode})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_rt --mode ${_mode})
    endif()
    list(APPEND _fuse_wp60_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp60_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 1200
    LABELS "gate;vulkan;renderer;rt")
