# WP-0.2 link gate (ctest fuse_rp_volk_no_loader_imports), run with cmake -P:
#   -DNM=<nm> -DREADELF=<readelf> -DEXE=<test executable> -DARCHIVE=<libfuse_rhi.a>
# 1. EXE (links fuse_rhi) imports no vk* symbol dynamically: volk opens the loader at run time.
#    vkGetInstanceProcAddr is tolerated, and so are the platform surface constructors
#    (vkCreate{Xlib,Xcb,Wayland,Win32}SurfaceKHR) that fuse_core's WSI (x11_window.cpp, window_wsi.cpp)
#    still calls through the linked loader. libvulkan may be DT_NEEDED only for those.
# 2. ARCHIVE (fuse_rhi) defines volk's pointer globals, every vk* symbol its objects reference is
#    one of them, and no object *calls* a vk* symbol (no call/jump relocation such as
#    R_X86_64_PLT32 or R_AARCH64_CALL26 against a vk* name): all calls go through volk's pointers,
#    none to a loader export.
cmake_minimum_required(VERSION 3.20)
if(NOT NM OR NOT READELF OR NOT EXISTS "${EXE}" OR NOT EXISTS "${ARCHIVE}")
    message("SKIP: nm/readelf or the binaries are unavailable (EXE=${EXE} ARCHIVE=${ARCHIVE})")
    cmake_language(EXIT 77)
endif()
set(_fail 0)

execute_process(COMMAND "${READELF}" -d -W "${EXE}" OUTPUT_VARIABLE _dyn RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "readelf -d failed on ${EXE}")
endif()
set(_needs_loader FALSE)
if(_dyn MATCHES "NEEDED[^\n]*libvulkan")
    set(_needs_loader TRUE)
endif()

execute_process(COMMAND "${NM}" -D --undefined-only "${EXE}" OUTPUT_VARIABLE _undef RESULT_VARIABLE _rc)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "nm -D failed on ${EXE}")
endif()
string(REGEX MATCHALL "[ \t]vk[A-Za-z0-9_]+" _imports "${_undef}")
set(_bad "")
set(_wsi "")
foreach(_s IN LISTS _imports)
    string(STRIP "${_s}" _s)
    if(_s MATCHES "^vkCreate(Xlib|Xcb|Wayland|Win32)SurfaceKHR$")
        list(APPEND _wsi "${_s}")
    elseif(NOT _s STREQUAL "vkGetInstanceProcAddr")
        list(APPEND _bad "${_s}")
    endif()
endforeach()
if(_bad)
    message("FAIL: ${EXE} imports vk* symbols: ${_bad}")
    set(_fail 1)
endif()
if(_needs_loader AND NOT _wsi)
    message("FAIL: ${EXE} has libvulkan as DT_NEEDED but imports nothing that needs it")
    set(_fail 1)
endif()
if(_wsi)
    message("note: fuse_core platform WSI imports ${_wsi} from the linked loader (not fuse_rhi)")
endif()

execute_process(COMMAND "${NM}" -A "${ARCHIVE}" OUTPUT_VARIABLE _syms RESULT_VARIABLE _rc ERROR_QUIET)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "nm failed on ${ARCHIVE}")
endif()
string(REGEX MATCHALL "[ \t]U vk[A-Za-z0-9_]+" _refs "${_syms}")
string(REGEX MATCHALL "[ \t][BbDdCc] vk[A-Za-z0-9_]+" _defs "${_syms}")
set(_defined "")
foreach(_d IN LISTS _defs)
    string(REGEX REPLACE "^[ \t][BbDdCc] " "" _d "${_d}")
    list(APPEND _defined "${_d}")
endforeach()
list(LENGTH _defined _ndef)
set(_direct "")
set(_nrefs 0)
foreach(_r IN LISTS _refs)
    string(REGEX REPLACE "^[ \t]U " "" _r "${_r}")
    math(EXPR _nrefs "${_nrefs} + 1")
    if(NOT _r IN_LIST _defined AND NOT _r STREQUAL "vkGetInstanceProcAddr")
        list(APPEND _direct "${_r}")
    endif()
endforeach()
list(REMOVE_DUPLICATES _direct)

execute_process(COMMAND "${READELF}" -rW "${ARCHIVE}" OUTPUT_VARIABLE _relocs RESULT_VARIABLE _rc ERROR_QUIET)
if(NOT _rc EQUAL 0)
    message(FATAL_ERROR "readelf -r failed on ${ARCHIVE}")
endif()
string(REGEX MATCHALL "R_[A-Z0-9_]*(PLT32|PLT|CALL26|JUMP26|CALL)[ \t]+[0-9a-f]+[ \t]+vk[A-Za-z0-9_]+" _calls "${_relocs}")
set(_called "")
foreach(_c IN LISTS _calls)
    string(REGEX REPLACE ".*[ \t](vk[A-Za-z0-9_]+)$" "\\1" _c "${_c}")
    list(APPEND _called "${_c}")
endforeach()
list(REMOVE_DUPLICATES _called)
if(_called)
    message("FAIL: ${ARCHIVE} calls vk* symbols directly (prototype calls, not volk pointers): ${_called}")
    set(_fail 1)
endif()
if(_ndef LESS 100)
    message("FAIL: ${ARCHIVE} defines only ${_ndef} vk* data symbols; volk's table is missing")
    set(_fail 1)
endif()
if(_direct)
    message("FAIL: ${ARCHIVE} references vk* symbols it does not define (direct loader imports): ${_direct}")
    set(_fail 1)
endif()
message("fuse_rp_volk_no_loader_imports: ${_ndef} volk pointer globals, ${_nrefs} vk* references in fuse_rhi, "
        "0 resolved outside it; test executable imports no fuse_rhi vk* symbol")
if(_fail)
    message(FATAL_ERROR "fuse_rp_volk_no_loader_imports failed")
endif()
