# WP-5.4 (docs/unification/RENDERER-EXECUTION.md): compute software rasteriser for micro-triangle clusters.
# Owned by WP-5.4; other packages must not edit this file.
#
#   fuse_swraster          STATIC  SwRasterizer (cluster classifier SW / HW by screen-space triangle size,
#                                  compute rasteriser with 64-bit atomicMin into the WP-1.4 Atomic64 target,
#                                  HW cluster path into the same target) + CPU references (swraster_kernel.hpp,
#                                  swraster_reference) (include/fuse/renderer/swraster/**, src/swraster/**)
#   swraster kernels       SPIR-V  Slang (primary) + GLSL twins, embedded in fuse_swraster
#   fuse_rp_swraster_*     ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source | Slang stage | define
# (sources relative to shaders/swraster/).
set(_fuse_wp54_kernels
    "EXPAND|Expand|swraster_expand.comp|swraster_expand.slang|compute|"
    "CLASSIFY|Classify|swraster_classify.comp|swraster_classify.slang|compute|"
    "RASTER_IMAGE|RasterImage|swraster_raster.comp|swraster_raster.slang|compute|FUSE_VIS64_IMAGE"
    "RASTER_BUFFER|RasterBuffer|swraster_raster.comp|swraster_raster.slang|compute|"
    "HW_VS|HwVs|swraster_hw.vert|swraster_hw_vs.slang|vertex|"
    "HW_FS_IMAGE|HwFsImage|swraster_hw.frag|swraster_hw_fs.slang|fragment|FUSE_VIS64_IMAGE"
    "HW_FS_BUFFER|HwFsBuffer|swraster_hw.frag|swraster_hw_fs.slang|fragment|")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp54.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW) # list(GET) keeps the empty fields of the kernel table
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp54.cmake from shaders/swraster/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp54_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_SWRASTER_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp54_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kSwRaster${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp54_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp54_inc "${_fuse_wp54_root}/include/fuse/renderer/swraster")
set(_fuse_wp54_src "${_fuse_wp54_root}/src/swraster")
set(_fuse_wp54_shaders "${_fuse_wp54_root}/shaders")
set(_fuse_wp54_shd "${_fuse_wp54_shaders}/swraster")
set(_fuse_wp54_scene_inc "${_fuse_wp54_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp54_common_inc "${_fuse_wp54_shaders}/common")
set(_fuse_wp54_include_dirs "${_fuse_wp54_scene_inc}" "${_fuse_wp54_shaders}/visbuffer" "${_fuse_wp54_shd}")

file(GLOB _fuse_wp54_shader_files CONFIGURE_DEPENDS "${_fuse_wp54_shd}/*")
add_library(fuse_swraster STATIC
    ${_fuse_wp54_src}/swraster.cpp
    ${_fuse_wp54_src}/swraster_reference.cpp
    ${_fuse_wp54_inc}/swraster_types.hpp
    ${_fuse_wp54_inc}/swraster_kernel.hpp
    ${_fuse_wp54_inc}/swraster_reference.hpp
    ${_fuse_wp54_inc}/swraster.hpp
    ${_fuse_wp54_shader_files}
)
set_source_files_properties(${_fuse_wp54_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_swraster PUBLIC fuse_visbuffer fuse_culling fuse_gpu_scene fuse_geometry)
fuse_apply_cxx23(fuse_swraster)

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the
# GLSL twins keep the rasteriser available where slangc is not (FUSE_SLANG=AUTO), and the gates run
# both. Everything is compiled with -fp-mode precise (the vertex transform is the WP-1.4 one and must
# not be contracted: the SW kernel is checked against the CPU reference bit for bit).
set(_fuse_wp54_gen "${CMAKE_CURRENT_BINARY_DIR}/swraster_gen")
set(_fuse_wp54_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/swraster")
file(MAKE_DIRECTORY "${_fuse_wp54_gen}" "${_fuse_wp54_spv}")
set(_fuse_wp54_header "${_fuse_wp54_gen}/swraster_spv.h")
add_custom_target(fuse_swraster_kernels)
set(_fuse_wp54_embed_args "")
set(_fuse_wp54_embed_deps "")
file(GLOB _fuse_wp54_glsl_includes "${_fuse_wp54_shd}/*.glsl" "${_fuse_wp54_shaders}/visbuffer/*.glsl")

foreach(_row IN LISTS _fuse_wp54_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 1 _stem)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    list(GET _entry 4 _stage)
    list(GET _entry 5 _define)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        set(_defines "")
        if(_define)
            set(_defines DEFINES ${_define})
        endif()
        fuse_add_slang_shaders(fuse_swraster_kernels
            SOURCES "${_fuse_wp54_shd}/${_slang}"
            STAGE ${_stage}
            SUFFIX ".${_suffix}"
            ${_defines}
            INCLUDE_DIRS ${_fuse_wp54_include_dirs}
            FLAGS -warnings-disable 39001 -fp-mode precise # the bindless arrays alias one binding on purpose
            OUTPUT_DIR "${_fuse_wp54_spv}"
            OUTPUT_VAR _fuse_wp54_out)
        if(_fuse_wp54_out)
            list(APPEND _fuse_wp54_embed_args "-D${_key}_SLANG=${_fuse_wp54_out}")
            list(APPEND _fuse_wp54_embed_deps "${_fuse_wp54_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp54_spv}/${_suffix}.glsl.spv")
        set(_dflag "")
        if(_define)
            set(_dflag "-D${_define}")
        endif()
        set(_iflags "-I${_fuse_wp54_common_inc}")
        foreach(_dir IN LISTS _fuse_wp54_include_dirs)
            list(APPEND _iflags "-I${_dir}")
        endforeach()
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 ${_dflag} ${_iflags} "${_fuse_wp54_shd}/${_glsl}"
                          -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp54_shd}/${_glsl}" ${_fuse_wp54_glsl_includes} "${_fuse_wp54_scene_inc}/gpu_scene.glsl"
                    "${_fuse_wp54_common_inc}/bindless.glsl"
            COMMENT "glslangValidator ${_glsl} (swraster ${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp54_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp54_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp54_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp54_header}" ${_fuse_wp54_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp54_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the software rasteriser kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_swraster_header DEPENDS "${_fuse_wp54_header}")
add_dependencies(fuse_swraster_header fuse_swraster_kernels)
add_dependencies(fuse_swraster fuse_swraster_header)
target_include_directories(fuse_swraster PRIVATE "${_fuse_wp54_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp54_tests_dir "${_fuse_wp54_root}/tests")

# --- CPU gates (reference kernels, fill rule, classifier; also run in the stub tree) --------------
add_executable(fuse_rp_swraster_cpu ${_fuse_wp54_tests_dir}/test_rp_swraster_cpu.cpp)
target_link_libraries(fuse_rp_swraster_cpu PRIVATE fuse_swraster)
target_compile_definitions(fuse_rp_swraster_cpu PRIVATE "FUSE_SWRASTER_SHADER_DIR=\"${_fuse_wp54_shd}\"")
fuse_apply_cxx23(fuse_rp_swraster_cpu)
foreach(_suite layout fixed fill raster classify api)
    add_test(NAME fuse_rp_swraster_${_suite} COMMAND fuse_rp_swraster_cpu ${_suite})
    set_tests_properties(fuse_rp_swraster_${_suite} PROPERTIES LABELS "gate;renderer;swraster" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_swraster ${_fuse_wp54_tests_dir}/test_rp_swraster.cpp)
target_link_libraries(fuse_rp_swraster PRIVATE fuse_swraster)
fuse_apply_cxx23(fuse_rp_swraster)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp54_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp54_vk_tests "")
foreach(_case "atomic_image;set" "atomic_buffer;set" "atomic_image;buffer" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_swraster_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp54_lock}" "$<TARGET_FILE:fuse_rp_swraster>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_swraster --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp54_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp54_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 1200
    LABELS "gate;vulkan;renderer;swraster")
