# WP-6.1 (docs/unification/RENDERER-EXECUTION.md): DDGI on Vulkan, T0 global-SDF and T2 ray-query paths.
# Owned by WP-6.1; other packages must not edit this file.
#
#   fuse_ddgi_gpu     STATIC  DdgiGpu: ddgi.reset / raygen / trace (T2 ray query or T0 SDF) / blend / probe
#                             render-graph compute passes, the volume view the WP-2.1 shade samples, CPU
#                             references (include/fuse/renderer/gi/gpu/**, src/gi/gpu/**)
#   ddgi kernels      SPIR-V  Slang (primary) + GLSL twins (shaders/ddgi/**), embedded in fuse_ddgi_gpu
#   fuse_rp_ddgi_gpu_*  ctest CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source | defines | extra
# slangc flags (space-separated; sources relative to shaders/ddgi/).
set(_fuse_wp61_kernels
    "RESET|Reset|ddgi_reset.comp|ddgi_reset.slang||"
    "RAYGEN|Raygen|ddgi_raygen.comp|ddgi_raygen.slang||"
    "TRACE_SDF|TraceSdf|ddgi_trace.comp|ddgi_trace.slang||"
    "TRACE_RQ|TraceRq|ddgi_trace.comp|ddgi_trace.slang|FUSE_DDGI_RAY_QUERY=1|-capability spvRayQueryKHR"
    "BLEND|Blend|ddgi_blend.comp|ddgi_blend.slang||"
    "PROBE|Probe|ddgi_probe.comp|ddgi_probe.slang||"
    "STATE|State|ddgi_state.comp|ddgi_state.slang||")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp61.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp61.cmake from shaders/ddgi/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp61_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_DDGI_GPU_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp61_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kDdgi${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp61_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp61_inc "${_fuse_wp61_root}/include/fuse/renderer/gi/gpu")
set(_fuse_wp61_src "${_fuse_wp61_root}/src/gi/gpu")
set(_fuse_wp61_shd "${_fuse_wp61_root}/shaders/ddgi")
set(_fuse_wp61_tests_dir "${_fuse_wp61_root}/tests")
# The global SDF (T0) is the Compute agent's analytic scene: header-only use of
# compute::SdfObject / ray_march_kernel (no link dependency on fuse_compute).
set(_fuse_wp61_compute_inc "${_fuse_wp61_root}/../Compute/include")

set(_fuse_wp61_warn "")
if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
    set(_fuse_wp61_warn -Wall -Wextra -Werror)
endif()

file(GLOB _fuse_wp61_shader_files CONFIGURE_DEPENDS "${_fuse_wp61_shd}/*")
add_library(fuse_ddgi_gpu STATIC
    ${_fuse_wp61_src}/ddgi_gpu.cpp
    ${_fuse_wp61_src}/ddgi_gpu_reference.cpp
    ${_fuse_wp61_inc}/ddgi_gpu_types.hpp
    ${_fuse_wp61_inc}/ddgi_gpu.hpp
    ${_fuse_wp61_inc}/ddgi_gpu_reference.hpp
    ${_fuse_wp61_shader_files}
)
set_source_files_properties(${_fuse_wp61_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_ddgi_gpu PUBLIC fuse_rt)
target_include_directories(fuse_ddgi_gpu PUBLIC "${_fuse_wp61_compute_inc}")
target_compile_options(fuse_ddgi_gpu PRIVATE ${_fuse_wp61_warn})
fuse_apply_cxx23(fuse_ddgi_gpu)

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the GLSL
# twins keep DDGI available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
# Slang: -fp-mode precise; GLSL: `precise` (the oracle's operation order, no contraction).
set(_fuse_wp61_gen "${CMAKE_CURRENT_BINARY_DIR}/ddgi_gpu_gen")
set(_fuse_wp61_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/ddgi")
file(MAKE_DIRECTORY "${_fuse_wp61_gen}" "${_fuse_wp61_spv}")
set(_fuse_wp61_header "${_fuse_wp61_gen}/ddgi_gpu_spv.h")
add_custom_target(fuse_ddgi_gpu_kernels)
set(_fuse_wp61_embed_args "")
set(_fuse_wp61_embed_deps "")
file(GLOB _fuse_wp61_glsl_includes "${_fuse_wp61_shd}/*.glsl")
cmake_policy(PUSH)
cmake_policy(SET CMP0007 NEW) # list(GET) keeps the empty fields
foreach(_row IN LISTS _fuse_wp61_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    list(GET _entry 4 _defines)
    list(GET _entry 5 _flags)
    separate_arguments(_flags UNIX_COMMAND "${_flags}")
    string(TOLOWER "${_key}" _suffix)
    set(_glsl_defines "")
    foreach(_d IN LISTS _defines)
        list(APPEND _glsl_defines "-D${_d}")
    endforeach()
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_ddgi_gpu_kernels
            SOURCES "${_fuse_wp61_shd}/${_slang}"
            STAGE compute
            SUFFIX ".dg_${_suffix}"
            DEFINES ${_defines}
            INCLUDE_DIRS "${_fuse_wp61_shd}"
            FLAGS -fp-mode precise ${_flags}
            OUTPUT_DIR "${_fuse_wp61_spv}"
            OUTPUT_VAR _fuse_wp61_out)
        if(_fuse_wp61_out)
            list(APPEND _fuse_wp61_embed_args "-D${_key}_SLANG=${_fuse_wp61_out}")
            list(APPEND _fuse_wp61_embed_deps "${_fuse_wp61_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp61_spv}/dg_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 ${_glsl_defines} "-I${_fuse_wp61_shd}"
                          "${_fuse_wp61_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp61_shd}/${_glsl}" ${_fuse_wp61_glsl_includes}
            COMMENT "glslangValidator ${_glsl} (dg_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp61_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp61_embed_deps "${_out}")
    endif()
endforeach()
cmake_policy(POP)
add_custom_command(OUTPUT "${_fuse_wp61_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp61_header}" ${_fuse_wp61_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp61_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the DDGI kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_ddgi_gpu_header DEPENDS "${_fuse_wp61_header}")
add_dependencies(fuse_ddgi_gpu_header fuse_ddgi_gpu_kernels)
add_dependencies(fuse_ddgi_gpu fuse_ddgi_gpu_header)
target_include_directories(fuse_ddgi_gpu PRIVATE "${_fuse_wp61_gen}")

# The WP-2.1 light.shade GLSL twin includes shaders/ddgi/ddgi_sample.glsl (by relative path, the indirect
# diffuse hook): rebuild it when that changes. (Its Slang twin tracks it by depfile.)
if(FUSE_GLSLANG_VALIDATOR)
    add_custom_command(OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/shaders/lighting/lc_shade.glsl.spv" APPEND
                       DEPENDS "${_fuse_wp61_shd}/ddgi_sample.glsl")
endif()

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

# --- CPU gates (layouts, references, constants; also run in the stub tree) ----------------------------
add_executable(fuse_rp_ddgi_gpu_cpu ${_fuse_wp61_tests_dir}/test_rp_ddgi_gpu_cpu.cpp)
target_link_libraries(fuse_rp_ddgi_gpu_cpu PRIVATE fuse_ddgi_gpu)
target_compile_definitions(fuse_rp_ddgi_gpu_cpu PRIVATE "FUSE_DDGI_SHADER_DIR=\"${_fuse_wp61_shd}\"")
target_compile_options(fuse_rp_ddgi_gpu_cpu PRIVATE ${_fuse_wp61_warn})
fuse_apply_cxx23(fuse_rp_ddgi_gpu_cpu)
foreach(_suite layout constants sdf blend api state leak)
    add_test(NAME fuse_rp_ddgi_gpu_${_suite} COMMAND fuse_rp_ddgi_gpu_cpu ${_suite})
    set_tests_properties(fuse_rp_ddgi_gpu_${_suite} PROPERTIES LABELS "gate;renderer;ddgi" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------------
add_executable(fuse_rp_ddgi_gpu ${_fuse_wp61_tests_dir}/test_rp_ddgi_gpu.cpp)
target_link_libraries(fuse_rp_ddgi_gpu PRIVATE fuse_ddgi_gpu fuse_geometry fuse_lighting_gpu fuse_visbuffer fuse_culling fuse_material_resolve)
target_compile_options(fuse_rp_ddgi_gpu PRIVATE ${_fuse_wp61_warn})
fuse_apply_cxx23(fuse_rp_ddgi_gpu)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp61_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp61_vk_tests "")
foreach(_mode parity_rq parity_sdf parity_rq_states parity_sdf_states converge leak tod shade zero_alloc)
    set(_name "fuse_rp_ddgi_gpu_vk_${_mode}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name} COMMAND "${_fuse_wp61_lock}" "$<TARGET_FILE:fuse_rp_ddgi_gpu>" --mode ${_mode})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_ddgi_gpu --mode ${_mode})
    endif()
    list(APPEND _fuse_wp61_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp61_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 1500
    LABELS "gate;vulkan;renderer;ddgi")
