# WP-8.1 (docs/unification/RENDERER-EXECUTION.md): froxel volumetric fog on Vulkan (inject, temporal
# reprojection, integration, apply). Owned by WP-8.1; other packages must not edit this file.
#
#   fuse_volumetric_gpu       STATIC  FroxelFog (fog.inject, fog.temporal, fog.integrate, fog.apply on render
#                                     graph v2) + settings / constant resolution and the CPU reference
#                                     (include/fuse/renderer/volumetric/gpu/**, src/volumetric/gpu/**); the
#                                     oracles are the B5 volumetric_fog.hpp medium / slice layout and the WP-2.1
#                                     light records and lists
#   fog_* kernels             SPIR-V  Slang (primary) + GLSL twins (shaders/volumetric/**), embedded
#   fuse_rp_volumetric_gpu_*  ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source
set(_fuse_wp81_kernels
    "INJECT|Inject|fog_inject.comp|fog_inject.slang"
    "TEMPORAL|Temporal|fog_temporal.comp|fog_temporal.slang"
    "INTEGRATE|Integrate|fog_integrate.comp|fog_integrate.slang"
    "APPLY|Apply|fog_apply.comp|fog_apply.slang")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp81.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp81.cmake from shaders/volumetric/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp81_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_FOG_GPU_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp81_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kFog${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp81_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp81_inc "${_fuse_wp81_root}/include/fuse/renderer/volumetric/gpu")
set(_fuse_wp81_src "${_fuse_wp81_root}/src/volumetric/gpu")
set(_fuse_wp81_shd "${_fuse_wp81_root}/shaders/volumetric")
set(_fuse_wp81_common_inc "${_fuse_wp81_root}/shaders/common")
set(_fuse_wp81_scene_inc "${_fuse_wp81_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp81_lc_shd "${_fuse_wp81_root}/shaders/lighting")
set(_fuse_wp81_vsm_shd "${_fuse_wp81_root}/shaders/shadow_vsm")
set(_fuse_wp81_vsm_inc "${_fuse_wp81_root}/include/fuse/renderer/shadow/vsm")

file(GLOB _fuse_wp81_shader_files CONFIGURE_DEPENDS "${_fuse_wp81_shd}/*")
add_library(fuse_volumetric_gpu STATIC
    ${_fuse_wp81_src}/froxel_fog.cpp
    ${_fuse_wp81_src}/froxel_fog_reference.cpp
    ${_fuse_wp81_inc}/froxel_fog_types.hpp
    ${_fuse_wp81_inc}/froxel_fog_kernel.hpp
    ${_fuse_wp81_inc}/froxel_fog_reference.hpp
    ${_fuse_wp81_inc}/froxel_fog.hpp
    ${_fuse_wp81_shader_files}
)
set_source_files_properties(${_fuse_wp81_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
# fuse_lighting_gpu: the WP-2.1 records (LightingFrameConstants), the oracle light lists
# (clustered_gpu_reference) and, through it, the GPU scene (light table).
target_link_libraries(fuse_volumetric_gpu PUBLIC fuse_lighting_gpu)
fuse_apply_cxx23(fuse_volumetric_gpu)

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the GLSL
# twins keep the fog available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
# Slang: -fp-mode precise; GLSL: `precise` (the CPU reference's operation order, no contraction).
set(_fuse_wp81_gen "${CMAKE_CURRENT_BINARY_DIR}/volumetric_gpu_gen")
set(_fuse_wp81_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/volumetric")
file(MAKE_DIRECTORY "${_fuse_wp81_gen}" "${_fuse_wp81_spv}")
set(_fuse_wp81_header "${_fuse_wp81_gen}/froxel_fog_spv.h")
add_custom_target(fuse_volumetric_gpu_kernels)
set(_fuse_wp81_embed_args "")
set(_fuse_wp81_embed_deps "")
file(GLOB _fuse_wp81_glsl_includes "${_fuse_wp81_shd}/*.glsl" "${_fuse_wp81_lc_shd}/lc_common.glsl"
     "${_fuse_wp81_vsm_shd}/vsm_shadow.glsl" "${_fuse_wp81_vsm_inc}/vsm_common.glsl" "${_fuse_wp81_common_inc}/bindless.glsl"
     "${_fuse_wp81_scene_inc}/gpu_scene.glsl")

foreach(_row IN LISTS _fuse_wp81_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_volumetric_gpu_kernels
            SOURCES "${_fuse_wp81_shd}/${_slang}"
            STAGE compute
            SUFFIX ".fog_${_suffix}"
            INCLUDE_DIRS "${_fuse_wp81_scene_inc}" "${_fuse_wp81_lc_shd}" "${_fuse_wp81_shd}"
            # 39001: the bindless arrays alias one binding on purpose.
            FLAGS -warnings-disable 39001 -fp-mode precise
            OUTPUT_DIR "${_fuse_wp81_spv}"
            OUTPUT_VAR _fuse_wp81_out)
        if(_fuse_wp81_out)
            list(APPEND _fuse_wp81_embed_args "-D${_key}_SLANG=${_fuse_wp81_out}")
            list(APPEND _fuse_wp81_embed_deps "${_fuse_wp81_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp81_spv}/fog_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp81_common_inc}"
                          "-I${_fuse_wp81_scene_inc}" "-I${_fuse_wp81_lc_shd}" "-I${_fuse_wp81_shd}"
                          "${_fuse_wp81_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp81_shd}/${_glsl}" ${_fuse_wp81_glsl_includes}
            COMMENT "glslangValidator ${_glsl} (fog_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp81_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp81_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp81_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp81_header}" ${_fuse_wp81_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp81_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the froxel fog kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_volumetric_gpu_header DEPENDS "${_fuse_wp81_header}")
add_dependencies(fuse_volumetric_gpu_header fuse_volumetric_gpu_kernels)
add_dependencies(fuse_volumetric_gpu fuse_volumetric_gpu_header)
target_include_directories(fuse_volumetric_gpu PRIVATE "${_fuse_wp81_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp81_tests_dir "${_fuse_wp81_root}/tests")

# --- CPU gates (layouts, oracle alignment, per-pass references, analytic medium, temporal metrics; also in
# the stub tree) ---------------------------------------------------------------------------------------------
add_executable(fuse_rp_volumetric_gpu_cpu ${_fuse_wp81_tests_dir}/test_rp_volumetric_gpu_cpu.cpp)
target_link_libraries(fuse_rp_volumetric_gpu_cpu PRIVATE fuse_volumetric_gpu)
target_compile_definitions(fuse_rp_volumetric_gpu_cpu PRIVATE FUSE_RP_FOG_SHADER_DIR="${_fuse_wp81_shd}")
fuse_apply_cxx23(fuse_rp_volumetric_gpu_cpu)
foreach(_suite layout oracle lights analytic temporal api)
    add_test(NAME fuse_rp_volumetric_gpu_${_suite} COMMAND fuse_rp_volumetric_gpu_cpu ${_suite})
    set_tests_properties(fuse_rp_volumetric_gpu_${_suite} PROPERTIES LABELS "gate;renderer;volumetric" TIMEOUT 900)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_volumetric_gpu ${_fuse_wp81_tests_dir}/test_rp_volumetric_gpu.cpp)
# fuse_vsm_raster (tests only): the shadow gate renders a WP-3.2 local shadow page and probes it.
target_link_libraries(fuse_rp_volumetric_gpu PRIVATE fuse_volumetric_gpu fuse_vsm_raster)
fuse_apply_cxx23(fuse_rp_volumetric_gpu)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp81_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp81_vk_tests "")
foreach(_case "passes;set" "passes;buffer" "analytic;set" "converge;set" "ghosting;set" "shadow;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_volumetric_gpu_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp81_lock}" "$<TARGET_FILE:fuse_rp_volumetric_gpu>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_volumetric_gpu --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp81_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp81_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;volumetric")
