# WP-8.2 (docs/unification/RENDERER-EXECUTION.md): Hillaire atmosphere on Vulkan (transmittance, multi-scattering,
# sky-view LUTs, aerial-perspective froxels, bilinear sampling helpers).
# Owned by WP-8.2; other packages must not edit this file.
#
#   fuse_atmosphere_gpu       STATIC  AtmosphereGpu (atmos.transmittance, atmos.multiscatter, atmos.skyview,
#                                     atmos.aerial, atmos.probe on render graph v2) + the CPU reference of every
#                                     LUT and sampling helper (atmosphere_luts.*) + the brute-force single-scatter
#                                     oracle (atmosphere_brute_force.hpp); the pre-existing CPU sky stays in fuse_rhi
#   at_* kernels              SPIR-V  Slang (primary) + GLSL twins, embedded in fuse_atmosphere_gpu;
#                                     shaders/atmosphere/at_sample.{glsl,slang} are the includable consumer helpers
#   fuse_rp_atmosphere_gpu_*  ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source
set(_fuse_wp82_kernels
    "TRANSMITTANCE|Transmittance|at_transmittance.comp|at_transmittance.slang"
    "MULTISCATTER|Multiscatter|at_multiscatter.comp|at_multiscatter.slang"
    "SKYVIEW|Skyview|at_skyview.comp|at_skyview.slang"
    "AERIAL|Aerial|at_aerial.comp|at_aerial.slang"
    "PROBE|Probe|at_probe.comp|at_probe.slang")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp82.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp82.cmake from shaders/atmosphere/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp82_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_ATMOSPHERE_GPU_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp82_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kAt${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp82_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp82_inc "${_fuse_wp82_root}/include/fuse/renderer/atmosphere")
set(_fuse_wp82_src "${_fuse_wp82_root}/src/atmosphere")
set(_fuse_wp82_shd "${_fuse_wp82_root}/shaders/atmosphere")

file(GLOB _fuse_wp82_shader_files CONFIGURE_DEPENDS "${_fuse_wp82_shd}/*")
add_library(fuse_atmosphere_gpu STATIC
    ${_fuse_wp82_src}/atmosphere_luts.cpp
    ${_fuse_wp82_src}/atmosphere_gpu.cpp
    ${_fuse_wp82_inc}/atmosphere_lut_types.hpp
    ${_fuse_wp82_inc}/atmosphere_luts.hpp
    ${_fuse_wp82_inc}/atmosphere_brute_force.hpp
    ${_fuse_wp82_inc}/atmosphere_gpu.hpp
    ${_fuse_wp82_shader_files}
)
set_source_files_properties(${_fuse_wp82_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_atmosphere_gpu PUBLIC fuse_rhi)
fuse_apply_cxx23(fuse_atmosphere_gpu)

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the GLSL
# twins keep the atmosphere available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
set(_fuse_wp82_gen "${CMAKE_CURRENT_BINARY_DIR}/atmosphere_gpu_gen")
set(_fuse_wp82_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/atmosphere")
file(MAKE_DIRECTORY "${_fuse_wp82_gen}" "${_fuse_wp82_spv}")
set(_fuse_wp82_header "${_fuse_wp82_gen}/atmosphere_gpu_spv.h")
add_custom_target(fuse_atmosphere_gpu_kernels)
set(_fuse_wp82_embed_args "")
set(_fuse_wp82_embed_deps "")
file(GLOB _fuse_wp82_glsl_includes "${_fuse_wp82_shd}/*.glsl")

foreach(_row IN LISTS _fuse_wp82_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_atmosphere_gpu_kernels
            SOURCES "${_fuse_wp82_shd}/${_slang}"
            STAGE compute
            SUFFIX ".at_${_suffix}"
            INCLUDE_DIRS "${_fuse_wp82_shd}"
            OUTPUT_DIR "${_fuse_wp82_spv}"
            OUTPUT_VAR _fuse_wp82_out)
        if(_fuse_wp82_out)
            list(APPEND _fuse_wp82_embed_args "-D${_key}_SLANG=${_fuse_wp82_out}")
            list(APPEND _fuse_wp82_embed_deps "${_fuse_wp82_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp82_spv}/at_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp82_shd}" "${_fuse_wp82_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp82_shd}/${_glsl}" ${_fuse_wp82_glsl_includes}
            COMMENT "glslangValidator ${_glsl} (at_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp82_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp82_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp82_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp82_header}" ${_fuse_wp82_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp82_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the atmosphere kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_atmosphere_gpu_header DEPENDS "${_fuse_wp82_header}")
add_dependencies(fuse_atmosphere_gpu_header fuse_atmosphere_gpu_kernels)
add_dependencies(fuse_atmosphere_gpu fuse_atmosphere_gpu_header)
target_include_directories(fuse_atmosphere_gpu PRIVATE "${_fuse_wp82_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp82_tests_dir "${_fuse_wp82_root}/tests")

# --- CPU gates (CPU references, brute-force comparison, energy, sweep, layouts; also in the stub tree) --------
add_executable(fuse_rp_atmosphere_gpu_cpu ${_fuse_wp82_tests_dir}/test_rp_atmosphere_gpu_cpu.cpp)
target_link_libraries(fuse_rp_atmosphere_gpu_cpu PRIVATE fuse_atmosphere_gpu)
target_compile_definitions(fuse_rp_atmosphere_gpu_cpu PRIVATE FUSE_RP_ATMOSPHERE_SHADER_DIR="${_fuse_wp82_shd}")
fuse_apply_cxx23(fuse_rp_atmosphere_gpu_cpu)
foreach(_suite layout luts reference energy sweep legacy api)
    add_test(NAME fuse_rp_atmosphere_gpu_${_suite} COMMAND fuse_rp_atmosphere_gpu_cpu ${_suite})
    set_tests_properties(fuse_rp_atmosphere_gpu_${_suite} PROPERTIES LABELS "gate;renderer;atmosphere" TIMEOUT 900)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_atmosphere_gpu ${_fuse_wp82_tests_dir}/test_rp_atmosphere_gpu.cpp)
target_link_libraries(fuse_rp_atmosphere_gpu PRIVATE fuse_atmosphere_gpu)
fuse_apply_cxx23(fuse_rp_atmosphere_gpu)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp82_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp82_vk_tests "")
foreach(_case "luts;set" "luts;buffer" "reference;set" "energy;set" "sweep;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_atmosphere_gpu_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp82_lock}" "$<TARGET_FILE:fuse_rp_atmosphere_gpu>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_atmosphere_gpu --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp82_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp82_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;atmosphere")
