# WP-4.1 (docs/unification/RENDERER-EXECUTION.md): GPU motion vectors + the TAAU Vulkan dispatch.
# Owned by WP-4.1; other packages must not edit this file.
#
#   fuse_temporal        STATIC  TemporalMotion ("temporal.motion": camera + per-object motion vectors and linear
#                                depth from the WP-1.4 visibility buffer and the WP-1.1 previous transforms, jitter
#                                handled explicitly) and TaauGpu ("taau.resolve" + "taau.keep": the Batch 9 TAAU
#                                kernel on the GPU) + the CPU reference motion kernel
#                                (include/fuse/renderer/temporal/**, src/temporal/**)
#   tm_* kernels         SPIR-V  Slang (primary) + GLSL twins, embedded in fuse_temporal
#   fuse_rp_temporal_*   ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source
set(_fuse_wp41_kernels
    "MOTION|Motion|tm_motion.comp|tm_motion.slang"
    "TAAU|Taau|tm_taau.comp|tm_taau.slang")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp41.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp41.cmake from shaders/temporal/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp41_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_TEMPORAL_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp41_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kTm${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp41_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp41_inc "${_fuse_wp41_root}/include/fuse/renderer/temporal")
set(_fuse_wp41_src "${_fuse_wp41_root}/src/temporal")
set(_fuse_wp41_shd "${_fuse_wp41_root}/shaders/temporal")
set(_fuse_wp41_scene_inc "${_fuse_wp41_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp41_vis_shd "${_fuse_wp41_root}/shaders/visbuffer")
set(_fuse_wp41_common_inc "${_fuse_wp41_root}/shaders/common")

file(GLOB _fuse_wp41_shader_files CONFIGURE_DEPENDS "${_fuse_wp41_shd}/*")
add_library(fuse_temporal STATIC
    ${_fuse_wp41_src}/temporal_motion.cpp
    ${_fuse_wp41_src}/taau_gpu.cpp
    ${_fuse_wp41_src}/temporal_pipeline.cpp
    ${_fuse_wp41_src}/temporal_pipeline.hpp
    ${_fuse_wp41_inc}/temporal_types.hpp
    ${_fuse_wp41_inc}/motion_kernel.hpp
    ${_fuse_wp41_inc}/temporal_motion.hpp
    ${_fuse_wp41_inc}/taau_gpu.hpp
    ${_fuse_wp41_shader_files}
)
set_source_files_properties(${_fuse_wp41_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_temporal PUBLIC fuse_visbuffer fuse_gpu_scene)
fuse_apply_cxx23(fuse_temporal)

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the GLSL
# twins keep the temporal passes available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
# Slang: -fp-mode precise; GLSL: `precise` (the kernels are twins of the CPU references, no contraction).
set(_fuse_wp41_gen "${CMAKE_CURRENT_BINARY_DIR}/temporal_gen")
set(_fuse_wp41_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/temporal")
file(MAKE_DIRECTORY "${_fuse_wp41_gen}" "${_fuse_wp41_spv}")
set(_fuse_wp41_header "${_fuse_wp41_gen}/temporal_spv.h")
add_custom_target(fuse_temporal_kernels)
set(_fuse_wp41_embed_args "")
set(_fuse_wp41_embed_deps "")
file(GLOB _fuse_wp41_glsl_includes "${_fuse_wp41_shd}/*.glsl" "${_fuse_wp41_vis_shd}/*.glsl")

foreach(_row IN LISTS _fuse_wp41_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_temporal_kernels
            SOURCES "${_fuse_wp41_shd}/${_slang}"
            STAGE compute
            SUFFIX ".tm_${_suffix}"
            INCLUDE_DIRS "${_fuse_wp41_scene_inc}" "${_fuse_wp41_vis_shd}" "${_fuse_wp41_shd}"
            # 39001: the bindless arrays alias one binding on purpose.
            FLAGS -warnings-disable 39001 -fp-mode precise
            OUTPUT_DIR "${_fuse_wp41_spv}"
            OUTPUT_VAR _fuse_wp41_out)
        if(_fuse_wp41_out)
            list(APPEND _fuse_wp41_embed_args "-D${_key}_SLANG=${_fuse_wp41_out}")
            list(APPEND _fuse_wp41_embed_deps "${_fuse_wp41_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp41_spv}/tm_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp41_common_inc}"
                          "-I${_fuse_wp41_scene_inc}" "-I${_fuse_wp41_vis_shd}" "-I${_fuse_wp41_shd}"
                          "${_fuse_wp41_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp41_shd}/${_glsl}" ${_fuse_wp41_glsl_includes} "${_fuse_wp41_scene_inc}/gpu_scene.glsl"
                    "${_fuse_wp41_common_inc}/bindless.glsl"
            COMMENT "glslangValidator ${_glsl} (tm_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp41_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp41_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp41_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp41_header}" ${_fuse_wp41_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp41_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the temporal kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_temporal_header DEPENDS "${_fuse_wp41_header}")
add_dependencies(fuse_temporal_header fuse_temporal_kernels)
add_dependencies(fuse_temporal fuse_temporal_header)
target_include_directories(fuse_temporal PRIVATE "${_fuse_wp41_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp41_tests_dir "${_fuse_wp41_root}/tests")

# --- CPU gates (reference kernels, host packing; also run in the stub tree) ----------------------------
add_executable(fuse_rp_temporal_cpu ${_fuse_wp41_tests_dir}/test_rp_temporal_cpu.cpp)
target_link_libraries(fuse_rp_temporal_cpu PRIVATE fuse_temporal)
fuse_apply_cxx23(fuse_rp_temporal_cpu)
foreach(_suite layout jitter motion sky taau_params)
    add_test(NAME fuse_rp_temporal_${_suite} COMMAND fuse_rp_temporal_cpu ${_suite})
    set_tests_properties(fuse_rp_temporal_${_suite} PROPERTIES LABELS "gate;renderer;temporal" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------------
add_executable(fuse_rp_temporal ${_fuse_wp41_tests_dir}/test_rp_temporal.cpp)
target_link_libraries(fuse_rp_temporal PRIVATE fuse_temporal fuse_material_resolve)
fuse_apply_cxx23(fuse_rp_temporal)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp41_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp41_vk_tests "")
foreach(_case "motion;set" "motion;buffer" "taau;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_temporal_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp41_lock}" "$<TARGET_FILE:fuse_rp_temporal>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_temporal --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp41_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp41_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;temporal")
