# WP-3.2 (docs/unification/RENDERER-EXECUTION.md): virtual shadow map page rendering, filtering and
# local lights. Owned by WP-3.2; other packages must not edit this file.
#
#   fuse_vsm_raster     STATIC  VsmShadows (vsm.raster_reset / raster / local_dirty / local_list /
#                               local_clear / local_raster / probe as RG v2 compute passes) and the CPU
#                               references (include/fuse/renderer/shadow/vsm_raster/**, src/shadow/vsm_raster/**)
#   vsmr_* kernels      SPIR-V  Slang (primary) + GLSL twins (shaders/shadow_vsm/*), embedded in fuse_vsm_raster
#   shadow lookup               shaders/shadow_vsm/vsm_shadow.{glsl,slang}, included by the WP-2.1 lighting
#                               (lc_ltc) and so by light.shade and the WP-2.3 forward pass
#   fuse_rp_vsm_raster_*        CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source
set(_fuse_wp32_kernels
    "RASTER|Raster|vsm_raster.comp|vsm_raster.slang"
    "LOCAL_DIRTY|LocalDirty|vsm_local_dirty.comp|vsm_local_dirty.slang"
    "LOCAL_LIST|LocalList|vsm_local_list.comp|vsm_local_list.slang"
    "LOCAL_CLEAR|LocalClear|vsm_local_clear.comp|vsm_local_clear.slang"
    "LOCAL_RASTER|LocalRaster|vsm_local_raster.comp|vsm_local_raster.slang"
    "PROBE|Probe|vsm_probe.comp|vsm_probe.slang")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp32.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp32.cmake from shaders/shadow_vsm/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp32_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_VSMR_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp32_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kVsmr${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp32_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp32_inc "${_fuse_wp32_root}/include/fuse/renderer/shadow/vsm_raster")
set(_fuse_wp32_src "${_fuse_wp32_root}/src/shadow/vsm_raster")
set(_fuse_wp32_shd "${_fuse_wp32_root}/shaders/shadow_vsm")
set(_fuse_wp32_vsm_inc "${_fuse_wp32_root}/include/fuse/renderer/shadow/vsm")
set(_fuse_wp32_scene_inc "${_fuse_wp32_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp32_common_inc "${_fuse_wp32_root}/shaders/common")

file(GLOB _fuse_wp32_shader_files CONFIGURE_DEPENDS "${_fuse_wp32_shd}/*")
add_library(fuse_vsm_raster STATIC
    ${_fuse_wp32_src}/vsm_shadows.cpp
    ${_fuse_wp32_src}/vsm_raster_reference.cpp
    ${_fuse_wp32_inc}/vsm_raster_types.hpp
    ${_fuse_wp32_inc}/vsm_raster_kernel.hpp
    ${_fuse_wp32_inc}/vsm_raster_reference.hpp
    ${_fuse_wp32_inc}/vsm_shadows.hpp
    ${_fuse_wp32_shader_files}
)
set_source_files_properties(${_fuse_wp32_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_vsm_raster PUBLIC fuse_vsm fuse_visbuffer fuse_lighting_gpu)
fuse_apply_cxx23(fuse_vsm_raster)

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the
# GLSL twins keep the passes available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
set(_fuse_wp32_gen "${CMAKE_CURRENT_BINARY_DIR}/vsm_raster_gen")
set(_fuse_wp32_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/shadow_vsm")
file(MAKE_DIRECTORY "${_fuse_wp32_gen}" "${_fuse_wp32_spv}")
set(_fuse_wp32_header "${_fuse_wp32_gen}/vsm_raster_spv.h")
add_custom_target(fuse_vsm_raster_kernels)
set(_fuse_wp32_embed_args "")
set(_fuse_wp32_embed_deps "")
file(GLOB _fuse_wp32_includes "${_fuse_wp32_shd}/*.glsl" "${_fuse_wp32_vsm_inc}/*.glsl")

foreach(_row IN LISTS _fuse_wp32_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_vsm_raster_kernels
            SOURCES "${_fuse_wp32_shd}/${_slang}"
            STAGE compute
            SUFFIX ".vsmr_${_suffix}"
            INCLUDE_DIRS "${_fuse_wp32_scene_inc}" "${_fuse_wp32_shd}"
            # 39001: the bindless arrays alias one binding on purpose.
            FLAGS -warnings-disable 39001 -fp-mode precise
            OUTPUT_DIR "${_fuse_wp32_spv}"
            OUTPUT_VAR _fuse_wp32_out)
        if(_fuse_wp32_out)
            list(APPEND _fuse_wp32_embed_args "-D${_key}_SLANG=${_fuse_wp32_out}")
            list(APPEND _fuse_wp32_embed_deps "${_fuse_wp32_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp32_spv}/vsmr_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp32_common_inc}"
                          "-I${_fuse_wp32_scene_inc}" "-I${_fuse_wp32_shd}" "${_fuse_wp32_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp32_shd}/${_glsl}" ${_fuse_wp32_includes} "${_fuse_wp32_scene_inc}/gpu_scene.glsl"
                    "${_fuse_wp32_common_inc}/bindless.glsl"
            COMMENT "glslangValidator ${_glsl} (vsmr_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp32_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp32_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp32_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp32_header}" ${_fuse_wp32_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp32_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the VSM raster kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_vsm_raster_header DEPENDS "${_fuse_wp32_header}")
add_dependencies(fuse_vsm_raster_header fuse_vsm_raster_kernels)
add_dependencies(fuse_vsm_raster fuse_vsm_raster_header)
target_include_directories(fuse_vsm_raster PRIVATE "${_fuse_wp32_gen}")

# The WP-2.1 lighting and WP-2.3 forward GLSL twins include shaders/shadow_vsm/vsm_shadow.glsl (through
# lc_ltc.glsl, by relative path): rebuild them when it changes. (Their Slang twins track it by depfile.)
if(FUSE_GLSLANG_VALIDATOR)
    set(_fuse_wp32_lookup "${_fuse_wp32_shd}/vsm_shadow.glsl" "${_fuse_wp32_vsm_inc}/vsm_common.glsl")
    foreach(_suffix bounds bin cull scan compact shade)
        add_custom_command(OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/shaders/lighting/lc_${_suffix}.glsl.spv" APPEND
                           DEPENDS ${_fuse_wp32_lookup})
    endforeach()
    foreach(_suffix vs fs)
        add_custom_command(OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/shaders/forward/fw_${_suffix}.glsl.spv" APPEND
                           DEPENDS ${_fuse_wp32_lookup})
    endforeach()
endif()

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp32_tests_dir "${_fuse_wp32_root}/tests")

# --- CPU gates (raster / filter references against brute force, the ported seam test; stub-safe) ----
add_executable(fuse_rp_vsm_raster_cpu ${_fuse_wp32_tests_dir}/test_rp_vsm_raster_cpu.cpp)
target_link_libraries(fuse_rp_vsm_raster_cpu PRIVATE fuse_vsm_raster)
target_compile_definitions(fuse_rp_vsm_raster_cpu PRIVATE FUSE_VSMR_SHADER_DIR="${_fuse_wp32_shd}")
fuse_apply_cxx23(fuse_rp_vsm_raster_cpu)
foreach(_suite layout raster local filter seam cache api)
    add_test(NAME fuse_rp_vsm_raster_${_suite} COMMAND fuse_rp_vsm_raster_cpu ${_suite})
    set_tests_properties(fuse_rp_vsm_raster_${_suite} PROPERTIES LABELS "gate;renderer;shadow;vsm" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_vsm_raster ${_fuse_wp32_tests_dir}/test_rp_vsm_raster.cpp)
target_link_libraries(fuse_rp_vsm_raster PRIVATE fuse_vsm_raster fuse_forward)
fuse_apply_cxx23(fuse_rp_vsm_raster)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp32_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp32_vk_tests "")
foreach(_case "seam;set" "shade;set" "shade;buffer" "local;set" "cache;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_vsm_raster_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name} COMMAND "${_fuse_wp32_lock}" "$<TARGET_FILE:fuse_rp_vsm_raster>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_vsm_raster --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp32_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp32_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;shadow;vsm")
