# WP-4.4 (docs/unification/RENDERER-EXECUTION.md): frame generation plus latency.
# Owned by WP-4.4; other packages must not edit this file.
#
#   fuse_present_latency  STATIC  ILatencyProvider (none; Reflex through the NVIDIA runtime provider's latency
#                                 extension; VK_NV_low_latency2; AMD Anti-Lag 2 = VK_AMD_anti_lag) and the present-timing
#                                 model (include/fuse/renderer/present/latency/**, src/present/latency/**). CPU, stub-safe.
#   fuse_framegen         STATIC  FrameGenGpu: FSR 3.1 frame generation on render graph v2 (optical flow + frame
#                                 interpolation of the vendored AMD FidelityFX SDK v1.1.4, clean-room host, FUSE convert /
#                                 UI composite / portable search passes) (include/fuse/renderer/framegen/**, src/framegen/**)
#   FSR 3.1 FG passes     SPIR-V  the vendored Vulkan GLSL (Engine/lib/fidelityfx, MIT) compiled verbatim with
#                                 glslangValidator -Os (the SDK's FidelityFX-SC glslang flags), embedded in fuse_framegen
#   fuse_rp_latency_*, fuse_rp_framegen_*   ctest   CPU gates (stub-safe) and Lavapipe gates

# Every embedded vendored pass, '|'-separated: KEY | C++ name stem | effect dir | pass file stem
set(_fuse_wp44_passes
    "OF_PREPARE_LUMA|OfPrepareLuma|opticalflow|ffx_opticalflow_prepare_luma_pass"
    "OF_LUMINANCE_PYRAMID|OfLuminancePyramid|opticalflow|ffx_opticalflow_compute_luminance_pyramid_pass"
    "OF_SCD_HISTOGRAM|OfScdHistogram|opticalflow|ffx_opticalflow_generate_scd_histogram_pass"
    "OF_SCD_DIVERGENCE|OfScdDivergence|opticalflow|ffx_opticalflow_compute_scd_divergence_pass"
    "OF_SEARCH|OfSearch|opticalflow|ffx_opticalflow_compute_optical_flow_advanced_pass_v5"
    "OF_FILTER|OfFilter|opticalflow|ffx_opticalflow_filter_optical_flow_pass_v5"
    "OF_SCALE|OfScale|opticalflow|ffx_opticalflow_scale_optical_flow_advanced_pass_v5"
    "FI_RECONSTRUCT_AND_DILATE|FiReconstructAndDilate|frameinterpolation|ffx_frameinterpolation_reconstruct_and_dilate_pass"
    "FI_SETUP|FiSetup|frameinterpolation|ffx_frameinterpolation_setup_pass"
    "FI_RECONSTRUCT_PREV_DEPTH|FiReconstructPrevDepth|frameinterpolation|ffx_frameinterpolation_reconstruct_previous_depth_pass"
    "FI_GAME_MV_FIELD|FiGameMotionVectorField|frameinterpolation|ffx_frameinterpolation_game_motion_vector_field_pass"
    "FI_GAME_VF_PYRAMID|FiGameVectorFieldInpaintingPyramid|frameinterpolation|ffx_frameinterpolation_compute_game_vector_field_inpainting_pyramid_pass"
    "FI_OF_VECTOR_FIELD|FiOpticalFlowVectorField|frameinterpolation|ffx_frameinterpolation_optical_flow_vector_field_pass"
    "FI_DISOCCLUSION|FiDisocclusionMask|frameinterpolation|ffx_frameinterpolation_disocclusion_mask_pass"
    "FI_INTERPOLATION|FiInterpolation|frameinterpolation|ffx_frameinterpolation_pass"
    "FI_INPAINTING_PYRAMID|FiInpaintingPyramid|frameinterpolation|ffx_frameinterpolation_compute_inpainting_pyramid_pass"
    "FI_INPAINTING|FiInpainting|frameinterpolation|ffx_frameinterpolation_inpainting_pass")
# FUSE passes: KEY | C++ name stem
set(_fuse_wp44_fuse_passes
    "CONVERT_SLANG|ConvertSlang"
    "CONVERT_GLSL|ConvertGlsl"
    "COMPOSITE_SLANG|CompositeSlang"
    "COMPOSITE_GLSL|CompositeGlsl"
    "SEARCH_PORTABLE|OfSearchPortable")

# Script mode (build step): embed the SPIR-V into a C++ header.
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp44.cmake. Do not edit.\n#pragma once\n#include <cstdint>\n")
    set(_complete TRUE)
    foreach(_row IN LISTS _fuse_wp44_passes)
        string(REPLACE "|" ";" _entry "${_row}")
        list(GET _entry 0 _key)
        if(NOT ${_key} OR NOT EXISTS "${${_key}}")
            set(_complete FALSE)
        endif()
    endforeach()
    if(_complete)
        string(APPEND _text "#define FUSE_FG_PASSES 1\n")
        foreach(_row IN LISTS _fuse_wp44_passes)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            list(GET _entry 1 _stem)
            file(READ "${${_key}}" _hex HEX)
            string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
            string(APPEND _text "alignas(4) static const std::uint32_t kFg${_stem}Spv[] = {${_words}};\n")
        endforeach()
    endif()
    foreach(_row IN LISTS _fuse_wp44_fuse_passes)
        string(REPLACE "|" ";" _entry "${_row}")
        list(GET _entry 0 _key)
        list(GET _entry 1 _stem)
        if(${_key} AND EXISTS "${${_key}}")
            string(APPEND _text "#define FUSE_FG_${_key} 1\n")
            file(READ "${${_key}}" _hex HEX)
            string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
            string(APPEND _text "alignas(4) static const std::uint32_t kFg${_stem}Spv[] = {${_words}};\n")
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp44_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp44_ffx "${FUSE_VENDOR_DIR}/fidelityfx")
set(_fuse_wp44_ffx_gpu "${_fuse_wp44_ffx}/include/FidelityFX/gpu")
set(_fuse_wp44_ffx_vk "${_fuse_wp44_ffx}/shaders/vk")

# ---- fuse_present_latency (CPU) ----------------------------------------------------------------------------------
set(_fuse_wp44_lat_inc "${_fuse_wp44_root}/include/fuse/renderer/present/latency")
set(_fuse_wp44_lat_src "${_fuse_wp44_root}/src/present/latency")
add_library(fuse_present_latency STATIC
    ${_fuse_wp44_lat_src}/latency_provider.cpp
    ${_fuse_wp44_lat_src}/present_timing.cpp
    ${_fuse_wp44_lat_src}/vk_latency_bindings.cpp
    ${_fuse_wp44_lat_inc}/latency_provider.hpp
    ${_fuse_wp44_lat_inc}/present_timing.hpp
    ${_fuse_wp44_lat_inc}/fuse_nv_latency_abi.h)
target_link_libraries(fuse_present_latency PUBLIC fuse_rhi fuse_nvidia_plugin)
fuse_apply_cxx23(fuse_present_latency)

# ---- fuse_framegen ---------------------------------------------------------------------------------------------------
set(_fuse_wp44_fg_inc "${_fuse_wp44_root}/include/fuse/renderer/framegen")
set(_fuse_wp44_fg_src "${_fuse_wp44_root}/src/framegen")
set(_fuse_wp44_shd "${_fuse_wp44_fg_src}/shaders")
file(GLOB _fuse_wp44_shader_files CONFIGURE_DEPENDS "${_fuse_wp44_shd}/*")
add_library(fuse_framegen STATIC
    ${_fuse_wp44_fg_src}/fg_host.cpp
    ${_fuse_wp44_fg_src}/fg_gpu.cpp
    ${_fuse_wp44_fg_inc}/fg_types.hpp
    ${_fuse_wp44_fg_inc}/fg_gpu.hpp
    ${_fuse_wp44_shader_files})
set_source_files_properties(${_fuse_wp44_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
# fsr3::reflect_spirv (WP-4.2) drives the by-name descriptor binding; fuse_present_latency for the pacing model.
target_link_libraries(fuse_framegen PUBLIC fuse_rhi fuse_fsr3 fuse_present_latency)
# The FFX_CPU host helper ffxSpdSetup of the vendored headers; SYSTEM: third-party code.
target_include_directories(fuse_framegen SYSTEM PRIVATE "${_fuse_wp44_ffx}/include")
fuse_apply_cxx23(fuse_framegen)

set(_fuse_wp44_gen "${CMAKE_CURRENT_BINARY_DIR}/framegen_gen")
set(_fuse_wp44_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/framegen")
file(MAKE_DIRECTORY "${_fuse_wp44_gen}" "${_fuse_wp44_spv}")
set(_fuse_wp44_header "${_fuse_wp44_gen}/fg_spv.h")
add_custom_target(fuse_framegen_kernels)
set(_fuse_wp44_embed_args "")
set(_fuse_wp44_embed_deps "")

if(FUSE_GLSLANG_VALIDATOR)
    # The SDK's FidelityFX-SC glslang invocation (CMakeShaders{Opticalflow,Frameinterpolation}.txt of the Vulkan
    # backend: -Os, FFX_GLSL, FFX_GPU) with the provider's permutation: optical flow without the HDR option (the
    # frame-generation provider creates its OF context with no flags); frame interpolation with render-resolution
    # unjittered motion vectors and inverted (reverse-Z) depth; FP32 (FFX_HALF=0).
    file(GLOB _fuse_wp44_ffx_deps "${_fuse_wp44_ffx_gpu}/*.h" "${_fuse_wp44_ffx_gpu}/opticalflow/*.h"
                                  "${_fuse_wp44_ffx_gpu}/frameinterpolation/*.h" "${_fuse_wp44_ffx_gpu}/spd/*.h")
    set(_fuse_wp44_defines_of -DFFX_GPU=1 -DFFX_GLSL=1 -DFFX_HALF=0 -DFFX_OPTICALFLOW_OPTION_HDR_COLOR_INPUT=0)
    set(_fuse_wp44_defines_fi -DFFX_GPU=1 -DFFX_GLSL=1 -DFFX_HALF=0
        -DFFX_FRAMEINTERPOLATION_OPTION_UPSAMPLE_SAMPLERS_USE_DATA_HALF=0
        -DFFX_FRAMEINTERPOLATION_OPTION_ACCUMULATE_SAMPLERS_USE_DATA_HALF=0
        -DFFX_FRAMEINTERPOLATION_OPTION_REPROJECT_SAMPLERS_USE_DATA_HALF=1
        -DFFX_FRAMEINTERPOLATION_OPTION_POSTPROCESSLOCKSTATUS_SAMPLERS_USE_DATA_HALF=0
        -DFFX_FRAMEINTERPOLATION_OPTION_UPSAMPLE_USE_LANCZOS_TYPE=2
        -DFFX_FRAMEINTERPOLATION_OPTION_LOW_RES_MOTION_VECTORS=1
        -DFFX_FRAMEINTERPOLATION_OPTION_JITTER_MOTION_VECTORS=0
        -DFFX_FRAMEINTERPOLATION_OPTION_INVERTED_DEPTH=1)
    foreach(_row IN LISTS _fuse_wp44_passes)
        string(REPLACE "|" ";" _entry "${_row}")
        list(GET _entry 0 _key)
        list(GET _entry 2 _dir)
        list(GET _entry 3 _file)
        string(TOLOWER "${_key}" _suffix)
        set(_out "${_fuse_wp44_spv}/fg_${_suffix}.spv")
        if(_dir STREQUAL "opticalflow")
            set(_defs ${_fuse_wp44_defines_of})
        else()
            set(_defs ${_fuse_wp44_defines_fi})
        endif()
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" -V -Os --target-env vulkan1.3 -S comp ${_defs}
                          "-I${_fuse_wp44_ffx_gpu}" "-I${_fuse_wp44_ffx_gpu}/${_dir}"
                          "${_fuse_wp44_ffx_vk}/${_dir}/${_file}.glsl" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp44_ffx_vk}/${_dir}/${_file}.glsl" ${_fuse_wp44_ffx_deps}
            COMMENT "glslangValidator FidelityFX FSR 3.1 FG ${_file} (vendored)"
            VERBATIM)
        list(APPEND _fuse_wp44_embed_args "-D${_key}=${_out}")
        list(APPEND _fuse_wp44_embed_deps "${_out}")
    endforeach()

    # FUSE-derived portable search (includes the vendored optical-flow headers).
    set(_out "${_fuse_wp44_spv}/fg_of_search_portable.spv")
    set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" -V -Os --target-env vulkan1.3 -S comp ${_fuse_wp44_defines_of}
                      "-I${_fuse_wp44_ffx_gpu}" "-I${_fuse_wp44_ffx_gpu}/opticalflow"
                      "${_fuse_wp44_shd}/fg_of_search_portable.comp" -o "${_out}")
    if(FUSE_SPIRV_VAL)
        list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
    endif()
    add_custom_command(OUTPUT "${_out}" ${_cmds}
        DEPENDS "${_fuse_wp44_shd}/fg_of_search_portable.comp" ${_fuse_wp44_ffx_deps}
        COMMENT "glslangValidator fg_of_search_portable.comp (FUSE, derived from the SDK search v5)"
        VERBATIM)
    list(APPEND _fuse_wp44_embed_args "-DSEARCH_PORTABLE=${_out}")
    list(APPEND _fuse_wp44_embed_deps "${_out}")

    foreach(_pair "convert|CONVERT_GLSL" "ui_composite|COMPOSITE_GLSL")
        string(REPLACE "|" ";" _p "${_pair}")
        list(GET _p 0 _stem)
        list(GET _p 1 _key)
        set(_out "${_fuse_wp44_spv}/fg_${_stem}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "${_fuse_wp44_shd}/fg_${_stem}.comp" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp44_shd}/fg_${_stem}.comp"
            COMMENT "glslangValidator fg_${_stem}.comp (GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp44_embed_args "-D${_key}=${_out}")
        list(APPEND _fuse_wp44_embed_deps "${_out}")
    endforeach()
endif()
if(COMMAND fuse_add_slang_shaders)
    foreach(_pair "convert|CONVERT_SLANG" "ui_composite|COMPOSITE_SLANG")
        string(REPLACE "|" ";" _p "${_pair}")
        list(GET _p 0 _stem)
        list(GET _p 1 _key)
        fuse_add_slang_shaders(fuse_framegen_kernels
            SOURCES "${_fuse_wp44_shd}/fg_${_stem}.slang"
            STAGE compute
            SUFFIX ".fg"
            FLAGS -fp-mode precise
            OUTPUT_DIR "${_fuse_wp44_spv}"
            OUTPUT_VAR _fuse_wp44_out)
        if(_fuse_wp44_out)
            list(APPEND _fuse_wp44_embed_args "-D${_key}=${_fuse_wp44_out}")
            list(APPEND _fuse_wp44_embed_deps "${_fuse_wp44_out}")
        endif()
    endforeach()
endif()
add_custom_command(OUTPUT "${_fuse_wp44_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp44_header}" ${_fuse_wp44_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp44_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the FSR 3.1 frame-generation passes' SPIR-V"
    VERBATIM)
add_custom_target(fuse_framegen_header DEPENDS "${_fuse_wp44_header}")
add_dependencies(fuse_framegen_header fuse_framegen_kernels)
add_dependencies(fuse_framegen fuse_framegen_header)
target_include_directories(fuse_framegen PRIVATE "${_fuse_wp44_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp44_tests_dir "${_fuse_wp44_root}/tests")

# --- CPU gates (stub tree too) ---------------------------------------------------------------------------------------
add_executable(fuse_rp_latency_cpu ${_fuse_wp44_tests_dir}/test_rp_latency_cpu.cpp)
target_link_libraries(fuse_rp_latency_cpu PRIVATE fuse_present_latency)
fuse_apply_cxx23(fuse_rp_latency_cpu)
foreach(_suite pacing latency markers reflex low_latency2 anti_lag selection)
    add_test(NAME fuse_rp_latency_${_suite} COMMAND fuse_rp_latency_cpu ${_suite})
    set_tests_properties(fuse_rp_latency_${_suite} PROPERTIES LABELS "gate;renderer;latency" TIMEOUT 300)
endforeach()

add_executable(fuse_rp_framegen_cpu ${_fuse_wp44_tests_dir}/test_rp_framegen_cpu.cpp)
target_link_libraries(fuse_rp_framegen_cpu PRIVATE fuse_framegen)
target_include_directories(fuse_rp_framegen_cpu SYSTEM PRIVATE "${_fuse_wp44_ffx}/include")
fuse_apply_cxx23(fuse_rp_framegen_cpu)
foreach(_suite layout bindings host plan composite of_search)
    add_test(NAME fuse_rp_framegen_${_suite} COMMAND fuse_rp_framegen_cpu ${_suite})
    set_tests_properties(fuse_rp_framegen_${_suite} PROPERTIES LABELS "gate;renderer;framegen" TIMEOUT 300)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------------------------------
add_executable(fuse_rp_framegen ${_fuse_wp44_tests_dir}/test_rp_framegen.cpp)
target_link_libraries(fuse_rp_framegen PRIVATE fuse_framegen fuse_present_latency)
fuse_apply_cxx23(fuse_rp_framegen)
# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp44_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp44_vk_tests "")
foreach(_mode midpoint ui reset determinism optical_flow scene_cut zero_alloc latency_probe)
    set(_name "fuse_rp_framegen_vk_${_mode}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name} COMMAND "${_fuse_wp44_lock}" "$<TARGET_FILE:fuse_rp_framegen>" --mode ${_mode})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_framegen --mode ${_mode})
    endif()
    list(APPEND _fuse_wp44_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp44_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 1500
    LABELS "gate;vulkan;renderer;framegen")
