# WP-6.3 (docs/unification/RENDERER-EXECUTION.md): screen-space fallback on Vulkan (SSR, GTAO, SSGI).
# Owned by WP-6.3; other packages must not edit this file.
#
#   fuse_ssfx_gpu       STATIC  SsfxGpu (ssfx.prepare, ssfx.gtao, ssfx.ssr, ssfx.ssgi, ssfx.compose on render
#                               graph v2) + settings / constant resolution and the CPU references
#                               (include/fuse/renderer/ssfx_gpu/**, src/ssfx_gpu/**); the oracles are the
#                               single-source fuse_ssfx kernels (ScreenSpace/include/fuse/ssfx/*_kernel.hpp,
#                               incl. the new gtao_kernel.hpp)
#   sx_* kernels        SPIR-V  Slang (primary) + GLSL twins, embedded in fuse_ssfx_gpu
#   fuse_rp_ssfx_gpu_*  ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source
set(_fuse_wp63_kernels
    "PREPARE|Prepare|sx_prepare.comp|sx_prepare.slang"
    "GTAO|Gtao|sx_gtao.comp|sx_gtao.slang"
    "SSR|Ssr|sx_ssr.comp|sx_ssr.slang"
    "SSGI|Ssgi|sx_ssgi.comp|sx_ssgi.slang"
    "COMPOSE|Compose|sx_compose.comp|sx_compose.slang")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp63.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp63.cmake from shaders/ssfx/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp63_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_SSFX_GPU_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp63_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kSx${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp63_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp63_inc "${_fuse_wp63_root}/include/fuse/renderer/ssfx_gpu")
set(_fuse_wp63_src "${_fuse_wp63_root}/src/ssfx_gpu")
set(_fuse_wp63_shd "${_fuse_wp63_root}/shaders/ssfx")
set(_fuse_wp63_common_inc "${_fuse_wp63_root}/shaders/common")

file(GLOB _fuse_wp63_shader_files CONFIGURE_DEPENDS "${_fuse_wp63_shd}/*")
add_library(fuse_ssfx_gpu STATIC
    ${_fuse_wp63_src}/ssfx_gpu.cpp
    ${_fuse_wp63_src}/ssfx_gpu_reference.cpp
    ${_fuse_wp63_inc}/ssfx_gpu_types.hpp
    ${_fuse_wp63_inc}/ssfx_gpu_reference.hpp
    ${_fuse_wp63_inc}/ssfx_gpu.hpp
    ${_fuse_wp63_root}/../ScreenSpace/include/fuse/ssfx/gtao_kernel.hpp
    ${_fuse_wp63_shader_files}
)
set_source_files_properties(${_fuse_wp63_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_ssfx_gpu PUBLIC fuse_rhi)
fuse_apply_cxx23(fuse_ssfx_gpu)

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the
# GLSL twins keep the screen-space passes available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
# Slang: -fp-mode precise; GLSL: `precise` (the oracle's operation order, no contraction).
set(_fuse_wp63_gen "${CMAKE_CURRENT_BINARY_DIR}/ssfx_gpu_gen")
set(_fuse_wp63_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/ssfx")
file(MAKE_DIRECTORY "${_fuse_wp63_gen}" "${_fuse_wp63_spv}")
set(_fuse_wp63_header "${_fuse_wp63_gen}/ssfx_gpu_spv.h")
add_custom_target(fuse_ssfx_gpu_kernels)
set(_fuse_wp63_embed_args "")
set(_fuse_wp63_embed_deps "")
file(GLOB _fuse_wp63_glsl_includes "${_fuse_wp63_shd}/*.glsl")

foreach(_row IN LISTS _fuse_wp63_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        fuse_add_slang_shaders(fuse_ssfx_gpu_kernels
            SOURCES "${_fuse_wp63_shd}/${_slang}"
            STAGE compute
            SUFFIX ".sx_${_suffix}"
            INCLUDE_DIRS "${_fuse_wp63_shd}"
            # 39001: the bindless arrays alias one binding on purpose.
            FLAGS -warnings-disable 39001 -fp-mode precise
            OUTPUT_DIR "${_fuse_wp63_spv}"
            OUTPUT_VAR _fuse_wp63_out)
        if(_fuse_wp63_out)
            list(APPEND _fuse_wp63_embed_args "-D${_key}_SLANG=${_fuse_wp63_out}")
            list(APPEND _fuse_wp63_embed_deps "${_fuse_wp63_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp63_spv}/sx_${_suffix}.glsl.spv")
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp63_common_inc}"
                          "-I${_fuse_wp63_shd}" "${_fuse_wp63_shd}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp63_shd}/${_glsl}" ${_fuse_wp63_glsl_includes} "${_fuse_wp63_common_inc}/bindless.glsl"
            COMMENT "glslangValidator ${_glsl} (sx_${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp63_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp63_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp63_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp63_header}" ${_fuse_wp63_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp63_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the screen-space fallback kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_ssfx_gpu_header DEPENDS "${_fuse_wp63_header}")
add_dependencies(fuse_ssfx_gpu_header fuse_ssfx_gpu_kernels)
add_dependencies(fuse_ssfx_gpu fuse_ssfx_gpu_header)
target_include_directories(fuse_ssfx_gpu PRIVATE "${_fuse_wp63_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp63_tests_dir "${_fuse_wp63_root}/tests")

# --- CPU gates (GTAO analytic references + CPU backend parity, layouts, references; also in the stub tree) -
add_executable(fuse_rp_ssfx_gpu_cpu ${_fuse_wp63_tests_dir}/test_rp_ssfx_gpu_cpu.cpp)
target_link_libraries(fuse_rp_ssfx_gpu_cpu PRIVATE fuse_ssfx_gpu)
target_compile_definitions(fuse_rp_ssfx_gpu_cpu PRIVATE FUSE_RP_SSFX_SHADER_DIR="${_fuse_wp63_shd}")
fuse_apply_cxx23(fuse_rp_ssfx_gpu_cpu)
foreach(_suite layout gtao_analytic gtao_parity reference api)
    add_test(NAME fuse_rp_ssfx_gpu_${_suite} COMMAND fuse_rp_ssfx_gpu_cpu ${_suite})
    set_tests_properties(fuse_rp_ssfx_gpu_${_suite} PROPERTIES LABELS "gate;renderer;ssfx" TIMEOUT 900)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_ssfx_gpu ${_fuse_wp63_tests_dir}/test_rp_ssfx_gpu.cpp)
target_link_libraries(fuse_rp_ssfx_gpu PRIVATE fuse_ssfx_gpu)
fuse_apply_cxx23(fuse_rp_ssfx_gpu)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp63_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp63_vk_tests "")
foreach(_case "passes;set" "passes;buffer" "analytic;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_ssfx_gpu_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp63_lock}" "$<TARGET_FILE:fuse_rp_ssfx_gpu>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_ssfx_gpu --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp63_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp63_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;ssfx")
