# WP-9.3 (docs/unification/RENDERER-EXECUTION.md): device-generated commands (VK_EXT_device_generated_commands)
# pipeline selection for the WP-1.3 culling output, with the indirect-count fallback.
# Owned by WP-9.3; other packages must not edit this file.
#
#   fuse_dgc          STATIC  DgcPipelineSelector (dgc.reset + dgc.generate on render graph v2, DGC execute or
#                             per-bucket vkCmdDrawIndexedIndirectCount), capability gate, CPU reference +
#                             indirect-commands layout emulation (include/fuse/renderer/vk/dgc/**, src/vk/dgc/**)
#   dgc_generate      SPIR-V  Slang (primary) + GLSL twin, embedded in fuse_dgc
#   dgc_draw          SPIR-V  test raster (vertex + fragment, bucket = specialization constant), files for the gate
#   fuse_rp_dgc_*     ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Script mode (build step): embed the kernel SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-DGEN_SLANG=<spv>] [-DGEN_GLSL=<spv>] -P rp_wp93.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp93.cmake from shaders/dgc/dgc_generate.{slang,comp}.\n")
    string(APPEND _text "// Do not edit.\n#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(GEN_${_lang} AND EXISTS "${GEN_${_lang}}")
            if(_lang STREQUAL "SLANG")
                set(_suffix Slang)
            else()
                set(_suffix Glsl)
            endif()
            string(APPEND _text "#define FUSE_DGC_${_lang} 1\n")
            file(READ "${GEN_${_lang}}" _hex HEX)
            string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
            string(APPEND _text "alignas(4) static const std::uint32_t kDgcGenerate${_suffix}Spv[] = {${_words}};\n")
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp93_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp93_inc "${_fuse_wp93_root}/include/fuse/renderer/vk/dgc")
set(_fuse_wp93_src "${_fuse_wp93_root}/src/vk/dgc")
set(_fuse_wp93_shd "${_fuse_wp93_root}/shaders/dgc")
set(_fuse_wp93_scene_inc "${_fuse_wp93_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp93_common_inc "${_fuse_wp93_root}/shaders/common")

add_library(fuse_dgc STATIC
    ${_fuse_wp93_src}/dgc_pipeline_selector.cpp
    ${_fuse_wp93_src}/dgc_reference.cpp
    ${_fuse_wp93_src}/dgc_vk_ext.hpp
    ${_fuse_wp93_inc}/dgc_types.hpp
    ${_fuse_wp93_inc}/dgc_reference.hpp
    ${_fuse_wp93_inc}/dgc_pipeline_selector.hpp
    ${_fuse_wp93_shd}/dgc_generate.comp
    ${_fuse_wp93_shd}/dgc_generate.slang
)
target_link_libraries(fuse_dgc PUBLIC fuse_culling)
fuse_apply_cxx23(fuse_dgc)

set(_fuse_wp93_gen "${CMAKE_CURRENT_BINARY_DIR}/dgc_gen")
set(_fuse_wp93_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/dgc")
file(MAKE_DIRECTORY "${_fuse_wp93_gen}" "${_fuse_wp93_spv}")
set(_fuse_wp93_header "${_fuse_wp93_gen}/dgc_spv.h")
add_custom_target(fuse_dgc_kernels)
set(_fuse_wp93_embed_args "")
set(_fuse_wp93_embed_deps "")
if(COMMAND fuse_add_slang_shaders)
    fuse_add_slang_shaders(fuse_dgc_kernels
        SOURCES "${_fuse_wp93_shd}/dgc_generate.slang"
        STAGE compute
        OUTPUT_DIR "${_fuse_wp93_spv}"
        OUTPUT_VAR _fuse_wp93_gen_slang)
    if(_fuse_wp93_gen_slang)
        list(APPEND _fuse_wp93_embed_args "-DGEN_SLANG=${_fuse_wp93_gen_slang}")
        list(APPEND _fuse_wp93_embed_deps "${_fuse_wp93_gen_slang}")
    endif()
endif()

# glslangValidator -> SPIR-V (+ spirv-val) for one GLSL source; sets <out_var> to the .spv path.
function(_fuse_wp93_glsl src out_name out_var)
    set(_out "${_fuse_wp93_spv}/${out_name}")
    set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 "-I${_fuse_wp93_common_inc}"
                      "-I${_fuse_wp93_scene_inc}" "${src}" -o "${_out}")
    if(FUSE_SPIRV_VAL)
        list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
    endif()
    add_custom_command(OUTPUT "${_out}" ${_cmds}
        DEPENDS "${src}" "${_fuse_wp93_scene_inc}/gpu_scene.glsl" "${_fuse_wp93_common_inc}/bindless.glsl"
        COMMENT "glslangValidator ${out_name} (GLSL twin)"
        VERBATIM)
    set(${out_var} "${_out}" PARENT_SCOPE)
endfunction()

if(FUSE_GLSLANG_VALIDATOR)
    _fuse_wp93_glsl("${_fuse_wp93_shd}/dgc_generate.comp" dgc_generate.comp.spv _fuse_wp93_gen_glsl)
    list(APPEND _fuse_wp93_embed_args "-DGEN_GLSL=${_fuse_wp93_gen_glsl}")
    list(APPEND _fuse_wp93_embed_deps "${_fuse_wp93_gen_glsl}")
endif()
add_custom_command(OUTPUT "${_fuse_wp93_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp93_header}" ${_fuse_wp93_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp93_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the DGC generate kernel's SPIR-V"
    VERBATIM)
add_custom_target(fuse_dgc_header DEPENDS "${_fuse_wp93_header}")
add_dependencies(fuse_dgc_header fuse_dgc_kernels)
add_dependencies(fuse_dgc fuse_dgc_header)
target_include_directories(fuse_dgc PRIVATE "${_fuse_wp93_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp93_tests_dir "${_fuse_wp93_root}/tests")

# --- CPU gates (reference, emulation, capability gate, command model, layouts; also in the stub tree) -----
add_executable(fuse_rp_dgc_cpu ${_fuse_wp93_tests_dir}/test_rp_dgc_cpu.cpp)
target_link_libraries(fuse_rp_dgc_cpu PRIVATE fuse_dgc)
target_compile_definitions(fuse_rp_dgc_cpu PRIVATE FUSE_RP_DGC_SHADER_DIR="${_fuse_wp93_shd}")
fuse_apply_cxx23(fuse_rp_dgc_cpu)
foreach(_suite layout reference emulation capability commands api)
    add_test(NAME fuse_rp_dgc_${_suite} COMMAND fuse_rp_dgc_cpu ${_suite})
    set_tests_properties(fuse_rp_dgc_${_suite} PROPERTIES LABELS "gate;renderer;dgc" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_dgc ${_fuse_wp93_tests_dir}/test_rp_dgc.cpp)
target_link_libraries(fuse_rp_dgc PRIVATE fuse_dgc)
fuse_apply_cxx23(fuse_rp_dgc)

add_custom_target(fuse_rp_dgc_shaders)
set(_fuse_wp93_defs "")
if(COMMAND fuse_add_slang_shaders)
    fuse_add_slang_shaders(fuse_rp_dgc_shaders
        SOURCES "${_fuse_wp93_shd}/test/dgc_draw_vs.slang"
        STAGE vertex
        INCLUDE_DIRS "${_fuse_wp93_scene_inc}"
        OUTPUT_DIR "${_fuse_wp93_spv}"
        OUTPUT_VAR _fuse_wp93_vs_slang)
    fuse_add_slang_shaders(fuse_rp_dgc_shaders
        SOURCES "${_fuse_wp93_shd}/test/dgc_draw_fs.slang"
        STAGE fragment
        OUTPUT_DIR "${_fuse_wp93_spv}"
        OUTPUT_VAR _fuse_wp93_fs_slang)
    if(_fuse_wp93_vs_slang AND _fuse_wp93_fs_slang)
        list(APPEND _fuse_wp93_defs FUSE_RP_DGC_SLANG_VS="${_fuse_wp93_vs_slang}"
                                    FUSE_RP_DGC_SLANG_FS="${_fuse_wp93_fs_slang}")
    endif()
endif()
if(FUSE_GLSLANG_VALIDATOR)
    _fuse_wp93_glsl("${_fuse_wp93_shd}/test/dgc_draw.vert" dgc_draw.vert.spv _fuse_wp93_vs_glsl)
    _fuse_wp93_glsl("${_fuse_wp93_shd}/test/dgc_draw.frag" dgc_draw.frag.spv _fuse_wp93_fs_glsl)
    add_custom_target(fuse_rp_dgc_glsl DEPENDS "${_fuse_wp93_vs_glsl}" "${_fuse_wp93_fs_glsl}")
    add_dependencies(fuse_rp_dgc_shaders fuse_rp_dgc_glsl)
    list(APPEND _fuse_wp93_defs FUSE_RP_DGC_GLSL_VS="${_fuse_wp93_vs_glsl}"
                                FUSE_RP_DGC_GLSL_FS="${_fuse_wp93_fs_glsl}")
endif()
add_dependencies(fuse_rp_dgc fuse_rp_dgc_shaders)
target_compile_definitions(fuse_rp_dgc PRIVATE ${_fuse_wp93_defs})

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp93_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp93_vk_tests "")
foreach(_case "parity;set" "parity;buffer" "dgc;set" "dgc;buffer" "fallback;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_dgc_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp93_lock}" "$<TARGET_FILE:fuse_rp_dgc>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_dgc --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp93_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp93_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;dgc")
