# WP-5.1 (docs/unification/RENDERER-EXECUTION.md): mesh-shader visibility path (tier T1).
# Owned by WP-5.1; other packages must not edit this file.
#
#   fuse_meshlet            STATIC  MeshletPath (task / mesh pipeline with per-meshlet frustum, cone and
#                                   Hi-Z culling writing the WP-1.4 visibility buffer, T0 fallback to the
#                                   WP-1.4 indirect path) + CPU reference (meshlet_cull_kernel.hpp,
#                                   meshlet_reference) (include/fuse/renderer/meshlet/**, src/meshlet/**)
#   meshlet kernels         SPIR-V  Slang (primary) + GLSL twins, embedded in fuse_meshlet; the fragment
#                                   stage is WP-1.4's (shaders/visbuffer/vis_{raster,atomic}*) compiled here
#   fuse_rp_meshlet_path_*  ctest   CPU gates (stub-safe) and Lavapipe gates (validation + sync validation)

# Every embedded kernel, '|'-separated: KEY | C++ name stem | GLSL source | Slang source | Slang stage | define
# (sources relative to shaders/).
set(_fuse_wp51_kernels
    "EXPAND|Expand|meshlet/meshlet_expand.comp|meshlet/meshlet_expand.slang|compute|"
    "TASK|Task|meshlet/meshlet.task|meshlet/meshlet_task.slang|amplification|"
    "MESH|Mesh|meshlet/meshlet.mesh|meshlet/meshlet_mesh.slang|mesh|"
    "RASTER_FS|RasterFs|visbuffer/vis_raster.frag|visbuffer/vis_raster_fs.slang|fragment|"
    "ATOMIC_FS_IMAGE|AtomicFsImage|visbuffer/vis_atomic.frag|visbuffer/vis_atomic_fs.slang|fragment|FUSE_VIS64_IMAGE"
    "ATOMIC_FS_BUFFER|AtomicFsBuffer|visbuffer/vis_atomic.frag|visbuffer/vis_atomic_fs.slang|fragment|")

# Script mode (build step): embed the kernels' SPIR-V into a C++ header.
#   cmake -DOUT=<header> [-D<KEY>_SLANG=<spv> ...] [-D<KEY>_GLSL=<spv> ...] -P rp_wp51.cmake
if(CMAKE_SCRIPT_MODE_FILE)
    cmake_policy(SET CMP0007 NEW) # list(GET) keeps the empty fields of the kernel table
    set(_text "// Generated by Source/FUSE/Renderer/cmake/rp_wp51.cmake from shaders/{meshlet,visbuffer}/*. Do not edit.\n")
    string(APPEND _text "#pragma once\n#include <cstdint>\n")
    foreach(_lang SLANG GLSL)
        if(_lang STREQUAL "SLANG")
            set(_suffix Slang)
        else()
            set(_suffix Glsl)
        endif()
        set(_complete TRUE)
        foreach(_row IN LISTS _fuse_wp51_kernels)
            string(REPLACE "|" ";" _entry "${_row}")
            list(GET _entry 0 _key)
            if(NOT ${_key}_${_lang} OR NOT EXISTS "${${_key}_${_lang}}")
                set(_complete FALSE)
            endif()
        endforeach()
        if(_complete)
            string(APPEND _text "#define FUSE_MESHLET_${_lang} 1\n")
            foreach(_row IN LISTS _fuse_wp51_kernels)
                string(REPLACE "|" ";" _entry "${_row}")
                list(GET _entry 0 _key)
                list(GET _entry 1 _stem)
                file(READ "${${_key}_${_lang}}" _hex HEX)
                string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1u," _words "${_hex}")
                string(APPEND _text "alignas(4) static const std::uint32_t kMeshlet${_stem}${_suffix}Spv[] = {${_words}};\n")
            endforeach()
        endif()
    endforeach()
    file(WRITE "${OUT}" "${_text}")
    return()
endif()

get_filename_component(_fuse_wp51_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_fuse_wp51_inc "${_fuse_wp51_root}/include/fuse/renderer/meshlet")
set(_fuse_wp51_src "${_fuse_wp51_root}/src/meshlet")
set(_fuse_wp51_shaders "${_fuse_wp51_root}/shaders")
set(_fuse_wp51_shd "${_fuse_wp51_shaders}/meshlet")
set(_fuse_wp51_scene_inc "${_fuse_wp51_root}/include/fuse/renderer/gpu_scene")
set(_fuse_wp51_common_inc "${_fuse_wp51_shaders}/common")
set(_fuse_wp51_include_dirs "${_fuse_wp51_scene_inc}" "${_fuse_wp51_shaders}/culling" "${_fuse_wp51_shaders}/visbuffer"
                            "${_fuse_wp51_shd}")

file(GLOB _fuse_wp51_shader_files CONFIGURE_DEPENDS "${_fuse_wp51_shd}/*")
add_library(fuse_meshlet STATIC
    ${_fuse_wp51_src}/meshlet_path.cpp
    ${_fuse_wp51_src}/meshlet_reference.cpp
    ${_fuse_wp51_inc}/meshlet_types.hpp
    ${_fuse_wp51_inc}/meshlet_cull_kernel.hpp
    ${_fuse_wp51_inc}/meshlet_reference.hpp
    ${_fuse_wp51_inc}/meshlet_path.hpp
    ${_fuse_wp51_shader_files}
)
set_source_files_properties(${_fuse_wp51_shader_files} PROPERTIES HEADER_FILE_ONLY TRUE)
target_link_libraries(fuse_meshlet PUBLIC fuse_visbuffer fuse_culling fuse_gpu_scene fuse_geometry)
fuse_apply_cxx23(fuse_meshlet)

# Kernels, embedded into the library. Slang is the primary source (execution doc §8 decision 1a); the
# GLSL twins keep the path available where slangc is not (FUSE_SLANG=AUTO), and the gates run both.
# Task and mesh are compiled with -fp-mode precise (twins of meshlet_cull_kernel.hpp / the WP-1.4
# vertex transform).
set(_fuse_wp51_gen "${CMAKE_CURRENT_BINARY_DIR}/meshlet_gen")
set(_fuse_wp51_spv "${CMAKE_CURRENT_BINARY_DIR}/shaders/meshlet")
file(MAKE_DIRECTORY "${_fuse_wp51_gen}" "${_fuse_wp51_spv}")
set(_fuse_wp51_header "${_fuse_wp51_gen}/meshlet_spv.h")
add_custom_target(fuse_meshlet_kernels)
set(_fuse_wp51_embed_args "")
set(_fuse_wp51_embed_deps "")
file(GLOB _fuse_wp51_glsl_includes "${_fuse_wp51_shd}/*.glsl" "${_fuse_wp51_shaders}/culling/*.glsl"
     "${_fuse_wp51_shaders}/visbuffer/*.glsl")

foreach(_row IN LISTS _fuse_wp51_kernels)
    string(REPLACE "|" ";" _entry "${_row}")
    list(GET _entry 0 _key)
    list(GET _entry 1 _stem)
    list(GET _entry 2 _glsl)
    list(GET _entry 3 _slang)
    list(GET _entry 4 _stage)
    list(GET _entry 5 _define)
    string(TOLOWER "${_key}" _suffix)
    if(COMMAND fuse_add_slang_shaders)
        set(_defines "")
        if(_define)
            set(_defines DEFINES ${_define})
        endif()
        set(_flags -warnings-disable 39001) # the bindless arrays alias one binding on purpose
        if(NOT _stage STREQUAL "fragment")
            list(APPEND _flags -fp-mode precise)
        endif()
        fuse_add_slang_shaders(fuse_meshlet_kernels
            SOURCES "${_fuse_wp51_shaders}/${_slang}"
            STAGE ${_stage}
            SUFFIX ".${_suffix}"
            ${_defines}
            INCLUDE_DIRS ${_fuse_wp51_include_dirs}
            FLAGS ${_flags}
            OUTPUT_DIR "${_fuse_wp51_spv}"
            OUTPUT_VAR _fuse_wp51_out)
        if(_fuse_wp51_out)
            list(APPEND _fuse_wp51_embed_args "-D${_key}_SLANG=${_fuse_wp51_out}")
            list(APPEND _fuse_wp51_embed_deps "${_fuse_wp51_out}")
        endif()
    endif()
    if(FUSE_GLSLANG_VALIDATOR)
        set(_out "${_fuse_wp51_spv}/${_suffix}.glsl.spv")
        set(_dflag "")
        if(_define)
            set(_dflag "-D${_define}")
        endif()
        set(_iflags "-I${_fuse_wp51_common_inc}")
        foreach(_dir IN LISTS _fuse_wp51_include_dirs)
            list(APPEND _iflags "-I${_dir}")
        endforeach()
        set(_cmds COMMAND "${FUSE_GLSLANG_VALIDATOR}" --target-env vulkan1.3 ${_dflag} ${_iflags}
                          "${_fuse_wp51_shaders}/${_glsl}" -o "${_out}")
        if(FUSE_SPIRV_VAL)
            list(APPEND _cmds COMMAND "${FUSE_SPIRV_VAL}" --target-env vulkan1.3 "${_out}")
        endif()
        add_custom_command(OUTPUT "${_out}" ${_cmds}
            DEPENDS "${_fuse_wp51_shaders}/${_glsl}" ${_fuse_wp51_glsl_includes} "${_fuse_wp51_scene_inc}/gpu_scene.glsl"
                    "${_fuse_wp51_common_inc}/bindless.glsl"
            COMMENT "glslangValidator ${_glsl} (meshlet ${_suffix}, GLSL twin)"
            VERBATIM)
        list(APPEND _fuse_wp51_embed_args "-D${_key}_GLSL=${_out}")
        list(APPEND _fuse_wp51_embed_deps "${_out}")
    endif()
endforeach()
add_custom_command(OUTPUT "${_fuse_wp51_header}"
    COMMAND "${CMAKE_COMMAND}" "-DOUT=${_fuse_wp51_header}" ${_fuse_wp51_embed_args} -P "${CMAKE_CURRENT_LIST_FILE}"
    DEPENDS ${_fuse_wp51_embed_deps} "${CMAKE_CURRENT_LIST_FILE}"
    COMMENT "Embedding the mesh-shader path kernels' SPIR-V"
    VERBATIM)
add_custom_target(fuse_meshlet_header DEPENDS "${_fuse_wp51_header}")
add_dependencies(fuse_meshlet_header fuse_meshlet_kernels)
add_dependencies(fuse_meshlet fuse_meshlet_header)
target_include_directories(fuse_meshlet PRIVATE "${_fuse_wp51_gen}")

if(NOT FUSE_BUILD_CORE_TESTS)
    return()
endif()

set(_fuse_wp51_tests_dir "${_fuse_wp51_root}/tests")

# --- CPU gates (reference kernel, selection rule; also run in the stub tree) ----------------------
add_executable(fuse_rp_meshlet_path_cpu ${_fuse_wp51_tests_dir}/test_rp_meshlet_path_cpu.cpp)
target_link_libraries(fuse_rp_meshlet_path_cpu PRIVATE fuse_meshlet)
fuse_apply_cxx23(fuse_rp_meshlet_path_cpu)
foreach(_suite layout kernel parity select api)
    add_test(NAME fuse_rp_meshlet_path_${_suite} COMMAND fuse_rp_meshlet_path_cpu ${_suite})
    set_tests_properties(fuse_rp_meshlet_path_${_suite} PROPERTIES LABELS "gate;renderer;meshlet" TIMEOUT 600)
endforeach()

# --- Lavapipe gates ------------------------------------------------------------------------------
add_executable(fuse_rp_meshlet_path ${_fuse_wp51_tests_dir}/test_rp_meshlet_path.cpp)
target_link_libraries(fuse_rp_meshlet_path PRIVATE fuse_meshlet)
fuse_apply_cxx23(fuse_rp_meshlet_path)

# tests/CMakeLists.txt writes the ICD lock wrapper; its variable is scoped to that directory.
set(_fuse_wp51_lock "${CMAKE_CURRENT_BINARY_DIR}/tests/run_vulkan_icd_locked.sh")
set(_fuse_wp51_vk_tests "")
foreach(_case "raster;set" "raster;buffer" "atomic_image;set" "atomic_buffer;set" "masked_t0;set" "zero_alloc;set")
    list(GET _case 0 _mode)
    list(GET _case 1 _backend)
    set(_name "fuse_rp_meshlet_path_vk_${_mode}_${_backend}")
    if(FUSE_VULKAN_BACKEND)
        add_test(NAME ${_name}
                 COMMAND "${_fuse_wp51_lock}" "$<TARGET_FILE:fuse_rp_meshlet_path>" --mode ${_mode} --backend ${_backend})
    else()
        add_test(NAME ${_name} COMMAND fuse_rp_meshlet_path --mode ${_mode} --backend ${_backend})
    endif()
    list(APPEND _fuse_wp51_vk_tests ${_name})
endforeach()
set_tests_properties(${_fuse_wp51_vk_tests} PROPERTIES
    ENVIRONMENT "VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.json"
    RUN_SERIAL TRUE
    SKIP_RETURN_CODE 77
    TIMEOUT 900
    LABELS "gate;vulkan;renderer;meshlet")
