# FUSE Relight RL-6.4: package gates (cmake -P).
#
#   MODE=layout    PKG=<package dir> REPO=<repo root> [REQUIRE_X86=ON] [CHECK_PE=ON]
#       expected files present (x64 set, host payload, text files, every licence of the notices table);
#       x86 bridge set all-or-nothing (and required with REQUIRE_X86); no forbidden file (the RL-0.1 binary
#       patterns plus debug symbols, import libraries, test helpers and binaries in plugin folders);
#       with CHECK_PE the PE machine of every binary (x64 files AMD64, x86 bridge files i386); licence texts
#       verbatim from the repository, THIRD_PARTY_NOTICES.txt holding every title and licence phrase, every
#       Relight entry named in THIRD_PARTY.md; MANIFEST.sha256 and manifest.json listing exactly the package
#       files with matching sha256 and sizes.
#   MODE=licence   PKG=<package dir> [REPO=<repo root>]
#       RL-0.1's scanner over the package: text mode (proprietary licence titles / header phrases /
#       clean-room names / MDL / (L)GPL) and binary mode (NVIDIA / Intel runtime names) on every file.
#   MODE=selftest  SCRATCH=<dir> REPO=<repo root>
#       builds a package from placeholder binaries with relight_package_build.cmake, requires both modes
#       to pass on it, then seeds one violation per copy (missing binary, forbidden runtime, plugin DLL in
#       the plugin folder, debug symbols, tampered file, unlisted file, missing licence, notice without its
#       licence phrase, partial x86 set, proprietary header phrase) and requires the matching finding.
#
# Findings print as "RL_PKG_FINDING <kind> <path>" (stable; the self-test greps them).

cmake_minimum_required(VERSION 3.21)
include("${CMAKE_CURRENT_LIST_DIR}/relight_package_spec.cmake")
get_filename_component(_rl_scan "${CMAKE_CURRENT_LIST_DIR}/../cmake/relight_proprietary_scan.cmake" ABSOLUTE)

set(_findings 0)
macro(_finding kind path msg)
    message("RL_PKG_FINDING ${kind} ${path}")
    message(SEND_ERROR "${msg}")
    math(EXPR _findings "${_findings} + 1")
endmacro()

# PE machine of a file ("" when it is not a PE image).
function(_rl_pe_machine path out)
    set(${out} "" PARENT_SCOPE)
    file(READ "${path}" _hdr LIMIT 64 HEX)
    if(NOT _hdr MATCHES "^4d5a")
        return()
    endif()
    string(SUBSTRING "${_hdr}" 120 8 _lfa) # e_lfanew at 0x3C, little endian
    string(SUBSTRING "${_lfa}" 6 2 _b3)
    string(SUBSTRING "${_lfa}" 4 2 _b2)
    string(SUBSTRING "${_lfa}" 2 2 _b1)
    string(SUBSTRING "${_lfa}" 0 2 _b0)
    math(EXPR _off "0x${_b3}${_b2}${_b1}${_b0}")
    file(READ "${path}" _pe OFFSET ${_off} LIMIT 6 HEX)
    if(NOT _pe MATCHES "^50450000")
        return()
    endif()
    string(SUBSTRING "${_pe}" 8 4 _m)
    set(${out} "${_m}" PARENT_SCOPE)
endfunction()

function(_rl_pkg_files pkg out)
    file(GLOB_RECURSE _all LIST_DIRECTORIES false RELATIVE "${pkg}" "${pkg}/*")
    list(SORT _all)
    set(${out} "${_all}" PARENT_SCOPE)
endfunction()

# ================================================================================================
if(MODE STREQUAL "layout")
    foreach(_v PKG REPO)
        if(NOT DEFINED ${_v})
            message(FATAL_ERROR "relight_package_check(layout): pass -D${_v}=...")
        endif()
    endforeach()
    if(NOT IS_DIRECTORY "${PKG}")
        message(FATAL_ERROR "relight_package_check: no package at ${PKG} (build the relight_package target)")
    endif()
    set(RL_SCAN_LIBRARY_ONLY ON) # tables and rl_binary_match only
    include("${_rl_scan}")
    _rl_pkg_files("${PKG}" _files)

    # ---- expected files ----
    set(_expected ${RL_PKG_TEXT_FILES} ${RL_PKG_MANIFESTS})
    set(_x64_bins "")
    foreach(_e IN LISTS RL_PKG_X64_BINARIES)
        string(REPLACE "|" ";" _e "${_e}")
        list(GET _e 0 _dst)
        list(APPEND _expected "${_dst}")
        list(APPEND _x64_bins "${_dst}")
    endforeach()
    set(_licences "")
    foreach(_id IN LISTS RL_NOTICE_IDS)
        rl_notice_package_names(${_id} _names)
        list(APPEND _expected ${_names})
        list(APPEND _licences ${_names})
    endforeach()
    set(_x86_bins "")
    set(_x86_present 0)
    foreach(_e IN LISTS RL_PKG_X86_BINARIES)
        string(REPLACE "|" ";" _e "${_e}")
        list(GET _e 0 _dst)
        list(APPEND _x86_bins "${_dst}")
        if(EXISTS "${PKG}/${_dst}")
            math(EXPR _x86_present "${_x86_present} + 1")
        endif()
    endforeach()
    list(LENGTH _x86_bins _x86_n)
    if(REQUIRE_X86 OR _x86_present GREATER 0)
        list(APPEND _expected ${_x86_bins})
        if(_x86_present GREATER 0 AND _x86_present LESS _x86_n)
            _finding(x86_partial "x86" "x86 bridge set is partial (${_x86_present} of ${_x86_n} files): ship all or none")
        endif()
    endif()
    foreach(_f IN LISTS _expected)
        if(NOT EXISTS "${PKG}/${_f}")
            _finding(missing "${_f}" "package file missing: ${_f}")
        endif()
    endforeach()
    foreach(_f IN LISTS _files)
        if(NOT _f IN_LIST _expected)
            _finding(unlisted "${_f}" "unexpected file in the package (not in relight_package_spec.cmake): ${_f}")
        endif()
    endforeach()

    # ---- forbidden files ----
    foreach(_f IN LISTS _files)
        string(TOLOWER "${_f}" _lf)
        set(_why "")
        rl_binary_match("${_f}" _why)
        if(NOT _why)
            foreach(_re IN LISTS RL_PKG_FORBIDDEN_RE)
                if(_lf MATCHES "${_re}")
                    set(_why "${_re}")
                    break()
                endif()
            endforeach()
        endif()
        if(_why)
            _finding(forbidden "${_f}" "forbidden file in the package (${_why}): ${_f}")
        endif()
    endforeach()

    # ---- PE machines ----
    if(CHECK_PE)
        foreach(_f IN LISTS _x64_bins _x86_bins)
            if(NOT EXISTS "${PKG}/${_f}")
                continue()
            endif()
            _rl_pe_machine("${PKG}/${_f}" _m)
            if(_f IN_LIST _x86_bins)
                set(_want "4c01") # i386 (bridge client, launcher and passthrough DXVK from the i686 tree)
            else()
                set(_want "6486") # AMD64
            endif()
            if(NOT _m STREQUAL _want)
                _finding(pe_machine "${_f}" "${_f}: PE machine '${_m}', expected '${_want}'")
            endif()
        endforeach()
    endif()

    # ---- licences and notices ----
    set(_tp "")
    if(EXISTS "${REPO}/Source/FUSE/Relight/THIRD_PARTY.md")
        file(READ "${REPO}/Source/FUSE/Relight/THIRD_PARTY.md" _tp)
    endif()
    set(_notices "")
    if(EXISTS "${PKG}/THIRD_PARTY_NOTICES.txt")
        file(READ "${PKG}/THIRD_PARTY_NOTICES.txt" _notices)
    endif()
    foreach(_id IN LISTS RL_NOTICE_IDS)
        rl_notice_package_names(${_id} _names)
        set(_i 0)
        foreach(_src IN LISTS RL_NOTICE_FILES_${_id})
            list(GET _names ${_i} _dst)
            math(EXPR _i "${_i} + 1")
            if(EXISTS "${PKG}/${_dst}" AND EXISTS "${REPO}/${_src}")
                file(SHA256 "${PKG}/${_dst}" _a)
                file(SHA256 "${REPO}/${_src}" _b)
                if(NOT _a STREQUAL _b)
                    _finding(licence_text "${_dst}" "${_dst} is not the verbatim licence text of ${_src}")
                endif()
            endif()
        endforeach()
        string(FIND "${_notices}" "${RL_NOTICE_TITLE_${_id}}" _p1)
        string(FIND "${_notices}" "${RL_NOTICE_PHRASE_${_id}}" _p2)
        if(_p1 LESS 0 OR _p2 LESS 0)
            _finding(notice "THIRD_PARTY_NOTICES.txt" "THIRD_PARTY_NOTICES.txt lacks '${_id}' (title or '${RL_NOTICE_PHRASE_${_id}}')")
        endif()
        if(NOT RL_NOTICE_TP_KEY_${_id} STREQUAL "")
            string(FIND "${_tp}" "${RL_NOTICE_TP_KEY_${_id}}" _p3)
            if(_p3 LESS 0)
                _finding(third_party_md "${_id}" "THIRD_PARTY.md has no entry '${RL_NOTICE_TP_KEY_${_id}}' for shipped component ${_id}")
            endif()
        endif()
    endforeach()
    # Each licence phrase is checked per component text as well (a truncated copy fails here).
    foreach(_id IN LISTS RL_NOTICE_IDS)
        rl_notice_package_names(${_id} _names)
        set(_all "")
        foreach(_dst IN LISTS _names)
            if(EXISTS "${PKG}/${_dst}")
                file(READ "${PKG}/${_dst}" _t)
                string(APPEND _all "${_t}")
            endif()
        endforeach()
        string(FIND "${_all}" "${RL_NOTICE_PHRASE_${_id}}" _p)
        if(_p LESS 0)
            _finding(licence_text "licenses/${_id}" "licence texts of ${_id} lack '${RL_NOTICE_PHRASE_${_id}}'")
        endif()
    endforeach()

    # ---- manifests ----
    set(_listed "")
    if(EXISTS "${PKG}/MANIFEST.sha256")
        file(STRINGS "${PKG}/MANIFEST.sha256" _lines)
        foreach(_l IN LISTS _lines)
            if(NOT _l MATCHES "^([0-9a-f]+)  (.+)$")
                _finding(manifest "MANIFEST.sha256" "malformed MANIFEST.sha256 line: ${_l}")
                continue()
            endif()
            set(_h "${CMAKE_MATCH_1}")
            set(_p "${CMAKE_MATCH_2}")
            list(APPEND _listed "${_p}")
            if(NOT EXISTS "${PKG}/${_p}")
                _finding(manifest "${_p}" "MANIFEST.sha256 lists a missing file: ${_p}")
                continue()
            endif()
            file(SHA256 "${PKG}/${_p}" _a)
            if(NOT _a STREQUAL _h)
                _finding(hash "${_p}" "sha256 mismatch for ${_p} (manifest ${_h}, file ${_a})")
            endif()
        endforeach()
        set(_want "${_files}")
        list(REMOVE_ITEM _want "MANIFEST.sha256")
        foreach(_f IN LISTS _want)
            if(NOT _f IN_LIST _listed)
                _finding(manifest "${_f}" "MANIFEST.sha256 does not list ${_f}")
            endif()
        endforeach()
    endif()
    if(EXISTS "${PKG}/manifest.json")
        file(READ "${PKG}/manifest.json" _j)
        string(JSON _n ERROR_VARIABLE _jerr LENGTH "${_j}" files)
        if(_jerr)
            _finding(manifest "manifest.json" "manifest.json: ${_jerr}")
        else()
            set(_jlisted "")
            math(EXPR _last "${_n} - 1")
            foreach(_i RANGE 0 ${_last})
                string(JSON _p GET "${_j}" files ${_i} path)
                string(JSON _h GET "${_j}" files ${_i} sha256)
                string(JSON _s GET "${_j}" files ${_i} size)
                list(APPEND _jlisted "${_p}")
                if(NOT EXISTS "${PKG}/${_p}")
                    _finding(manifest "${_p}" "manifest.json lists a missing file: ${_p}")
                    continue()
                endif()
                file(SHA256 "${PKG}/${_p}" _a)
                file(SIZE "${PKG}/${_p}" _sz)
                if(NOT _a STREQUAL _h OR NOT _sz EQUAL _s)
                    _finding(hash "${_p}" "manifest.json entry for ${_p} does not match the file")
                endif()
            endforeach()
            set(_want "${_files}")
            list(REMOVE_ITEM _want "MANIFEST.sha256" "manifest.json")
            foreach(_f IN LISTS _want)
                if(NOT _f IN_LIST _jlisted)
                    _finding(manifest "${_f}" "manifest.json does not list ${_f}")
                endif()
            endforeach()
            string(JSON _x GET "${_j}" x86_bridge)
            if((_x STREQUAL "ON" OR _x STREQUAL "true") AND _x86_present EQUAL 0)
                _finding(manifest "manifest.json" "manifest.json claims the x86 bridge but it is absent")
            endif()
        endif()
    endif()

    list(LENGTH _files _nf)
    if(_findings GREATER 0)
        message(FATAL_ERROR "relight_package_check(layout): ${_findings} finding(s) in ${PKG}")
    endif()
    if(_x86_present EQUAL 0)
        message(STATUS "relight_package_check(layout): note: x86 bridge client not packaged (no i686 tree)")
    endif()
    message(STATUS "relight_package_check(layout): ${_nf} files, layout / licences / manifests OK")

# ================================================================================================
elseif(MODE STREQUAL "licence")
    if(NOT DEFINED PKG OR NOT IS_DIRECTORY "${PKG}")
        message(FATAL_ERROR "relight_package_check(licence): no package at '${PKG}'")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" -DMODE=text "-DREPO=${PKG}" "-DROOTS=${PKG}" -P "${_rl_scan}"
        RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _out)
    message("${_out}")
    if(NOT _rc EQUAL 0)
        _finding(licence_scan "${PKG}" "RL-0.1 text scan fails on the package")
    endif()
    _rl_pkg_files("${PKG}" _files)
    string(REPLACE ";" "\n" _list "${_files}")
    set(_fl "${PKG}.files.txt")
    file(WRITE "${_fl}" "${_list}\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -DMODE=binary "-DREPO=${PKG}" "-DFILE_LIST=${_fl}" -P "${_rl_scan}"
        RESULT_VARIABLE _rc OUTPUT_VARIABLE _out ERROR_VARIABLE _out)
    file(REMOVE "${_fl}")
    message("${_out}")
    if(NOT _rc EQUAL 0)
        _finding(binary_scan "${PKG}" "RL-0.1 binary gate fails on the package")
    endif()
    if(_findings GREATER 0)
        message(FATAL_ERROR "relight_package_check(licence): the package fails the licence gates")
    endif()
    message(STATUS "relight_package_check(licence): text and binary gates clean on ${PKG}")

# ================================================================================================
elseif(MODE STREQUAL "selftest")
    foreach(_v SCRATCH REPO)
        if(NOT DEFINED ${_v})
            message(FATAL_ERROR "relight_package_check(selftest): pass -D${_v}=...")
        endif()
    endforeach()
    file(REMOVE_RECURSE "${SCRATCH}")
    set(_bin "${SCRATCH}/bin")
    foreach(_n d3d9.dll d3d8.dll host.exe launcher.exe plugins.exe)
        file(WRITE "${_bin}/${_n}" "MZ placeholder ${_n}\n")
    endforeach()
    foreach(_p relight/bridge/client/d3d9.dll relight/bridge/client/d3d8.dll relight/bin/fuse_relight_launcher.exe relight/bin/d3d9.dll)
        file(WRITE "${SCRATCH}/x86tree/${_p}" "MZ placeholder x86 ${_p}\n")
    endforeach()
    set(_build_args -DREPO=${REPO} -DVERSION=0.0.0-selftest -DBUILD_ID=selftest
        -DX64_D3D9=${_bin}/d3d9.dll -DX64_D3D8=${_bin}/d3d8.dll -DHOST=${_bin}/host.exe
        -DLAUNCHER=${_bin}/launcher.exe -DPLUGINS_TOOL=${_bin}/plugins.exe)
    set(_errors 0)
    macro(_st_fail msg)
        message(SEND_ERROR "${msg}")
        math(EXPR _errors "${_errors} + 1")
    endmacro()
    function(_st_check mode pkg out_rc out_findings)
        execute_process(COMMAND "${CMAKE_COMMAND}" -DMODE=${mode} "-DPKG=${pkg}" "-DREPO=${REPO}" ${ARGN}
            -P "${CMAKE_CURRENT_LIST_FILE}" RESULT_VARIABLE _r OUTPUT_VARIABLE _o ERROR_VARIABLE _o)
        string(REGEX MATCHALL "RL_PKG_FINDING [^\n]*" _l "${_o}")
        string(REGEX MATCHALL "RL_FINDING [^\n]*" _l2 "${_o}")
        set(${out_rc} "${_r}" PARENT_SCOPE)
        set(${out_findings} "${_l};${_l2}" PARENT_SCOPE)
        if(NOT _r EQUAL 0)
            set(_st_last_output "${_o}" PARENT_SCOPE)
        endif()
    endfunction()

    # Good packages: x64 only, and with the x86 bridge.
    foreach(_variant x64only withx86)
        set(_pkg "${SCRATCH}/${_variant}/FUSE-Relight")
        set(_extra "")
        if(_variant STREQUAL "withx86")
            set(_extra "-DX86_DIR=${SCRATCH}/x86tree")
        endif()
        execute_process(COMMAND "${CMAKE_COMMAND}" ${_build_args} "-DOUT=${_pkg}" ${_extra}
            -P "${CMAKE_CURRENT_LIST_DIR}/relight_package_build.cmake" RESULT_VARIABLE _r OUTPUT_VARIABLE _o ERROR_VARIABLE _o)
        if(NOT _r EQUAL 0)
            _st_fail("building the ${_variant} placeholder package failed:\n${_o}")
            continue()
        endif()
        _st_check(layout "${_pkg}" _rc _f)
        if(NOT _rc EQUAL 0)
            _st_fail("good ${_variant} package fails the layout gate:\n${_st_last_output}")
        endif()
        _st_check(licence "${_pkg}" _rc _f)
        if(NOT _rc EQUAL 0)
            _st_fail("good ${_variant} package fails the licence gates:\n${_st_last_output}")
        endif()
    endforeach()
    # REQUIRE_X86 on the x64-only package must fail with the x86 files missing.
    _st_check(layout "${SCRATCH}/x64only/FUSE-Relight" _rc _f -DREQUIRE_X86=ON)
    if(_rc EQUAL 0 OR NOT "RL_PKG_FINDING missing x86/d3d9.dll" IN_LIST _f)
        _st_fail("REQUIRE_X86 on an x64-only package: expected 'missing x86/d3d9.dll' (got: ${_f})")
    endif()

    # Seeded violations: <name>|<mode>|<expected finding>; each gets its own copy of the x86 package.
    set(_cases
        "missing_bin|layout|RL_PKG_FINDING missing x64/d3d9.dll"
        "dlss_runtime|layout|RL_PKG_FINDING forbidden x64/nvngx_dlss.dll"
        "plugin_dir_dll|layout|RL_PKG_FINDING forbidden x64/fuse_relight_plugins/nvidia/sl.interposer.dll"
        "pdb|layout|RL_PKG_FINDING forbidden x64/d3d9.pdb"
        "stub_host|layout|RL_PKG_FINDING forbidden x86/fuse_relight/fuse_relight_bridge_stub_host.exe"
        "tampered|layout|RL_PKG_FINDING hash README.txt"
        "unlisted|layout|RL_PKG_FINDING unlisted x64/extra.txt"
        "no_licence|layout|RL_PKG_FINDING missing licenses/dxvk.txt"
        "notice_phrase|layout|RL_PKG_FINDING notice THIRD_PARTY_NOTICES.txt"
        "x86_partial|layout|RL_PKG_FINDING x86_partial x86"
        "xess_runtime|licence|RL_FINDING binary x86/fuse_relight/libxess.dll"
        "proprietary_text|licence|RL_FINDING hdr_licensors_retain")
    set(RL_SCAN_LIBRARY_ONLY ON) # marker samples for the seeded proprietary text
    include("${_rl_scan}")
    foreach(_c IN LISTS _cases)
        string(REPLACE "|" ";" _c "${_c}")
        list(GET _c 0 _name)
        list(GET _c 1 _mode)
        list(GET _c 2 _want)
        set(_pkg "${SCRATCH}/case_${_name}/FUSE-Relight")
        file(COPY "${SCRATCH}/withx86/FUSE-Relight" DESTINATION "${SCRATCH}/case_${_name}")
        if(_name STREQUAL "missing_bin")
            file(REMOVE "${_pkg}/x64/d3d9.dll")
        elseif(_name STREQUAL "dlss_runtime")
            file(WRITE "${_pkg}/x64/nvngx_dlss.dll" "MZ fake\n")
        elseif(_name STREQUAL "plugin_dir_dll")
            file(WRITE "${_pkg}/x64/fuse_relight_plugins/nvidia/sl.interposer.dll" "MZ fake\n")
        elseif(_name STREQUAL "pdb")
            file(WRITE "${_pkg}/x64/d3d9.pdb" "symbols\n")
        elseif(_name STREQUAL "stub_host")
            file(WRITE "${_pkg}/x86/fuse_relight/fuse_relight_bridge_stub_host.exe" "MZ fake\n")
        elseif(_name STREQUAL "tampered")
            file(APPEND "${_pkg}/README.txt" "tampered\n")
        elseif(_name STREQUAL "unlisted")
            file(WRITE "${_pkg}/x64/extra.txt" "extra\n")
        elseif(_name STREQUAL "no_licence")
            file(REMOVE "${_pkg}/licenses/dxvk.txt")
        elseif(_name STREQUAL "notice_phrase")
            file(READ "${_pkg}/THIRD_PARTY_NOTICES.txt" _t)
            string(REPLACE "${RL_NOTICE_PHRASE_dxvk}" "altered versions" _t "${_t}")
            file(WRITE "${_pkg}/THIRD_PARTY_NOTICES.txt" "${_t}")
        elseif(_name STREQUAL "x86_partial")
            file(REMOVE "${_pkg}/x86/d3d8.dll")
        elseif(_name STREQUAL "xess_runtime")
            file(WRITE "${_pkg}/x86/fuse_relight/libxess.dll" "MZ fake\n")
        elseif(_name STREQUAL "proprietary_text")
            file(APPEND "${_pkg}/docs/relight.md" "\n${RL_MARKER_SAMPLE_hdr_licensors_retain}\n")
        endif()
        _st_check(${_mode} "${_pkg}" _rc _f)
        set(_hit FALSE)
        foreach(_l IN LISTS _f)
            string(FIND "${_l}" "${_want}" _p)
            if(_p EQUAL 0)
                set(_hit TRUE)
            endif()
        endforeach()
        if(_rc EQUAL 0 OR NOT _hit)
            _st_fail("seeded case ${_name}: expected '${_want}' (rc ${_rc}, findings: ${_f})")
        endif()
    endforeach()
    list(LENGTH _cases _nc)
    if(_errors GREATER 0)
        message(FATAL_ERROR "relight_package_check(selftest): FAILED (${_errors})")
    endif()
    file(REMOVE_RECURSE "${SCRATCH}")
    message(STATUS "relight_package_check(selftest): 2 good packages pass; ${_nc} seeded violations and REQUIRE_X86 caught")
else()
    message(FATAL_ERROR "relight_package_check: MODE must be layout, licence or selftest")
endif()
